### ISSUE TITLE
媒体服务器添加扫描库可选功能

### ISSUE THREAD

**Issue by boeto** [NAStool/nas-tools#1969]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x

v2.4.1

> 环境: docker or windows or synology

docker 

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？

`媒体服务器` 添加`扫描库可选` 功能

媒体服务器存在多个库，且与nastool rss订阅等功能无关，则会扫描过多非必需的媒体库（nastool应该是扫描媒体服务器中所有的库，如果不是请告知）。例如电影库和电视剧库有20000个媒体，其它非必需的媒体库有80000个媒体，那么扫描那80000个媒体的操作则可以说是对服务器添加了非必要的运算负荷和时间。

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

例如下图中的nas库在nastool中可以作为非必需的媒体库，可以选择关闭对这个库的扫描，这样可以优化扫描的效率：

![](https://raw.githubusercontent.com/boeto/image/main/uploads/20221109171352.png)

**Comment by jxxghp** [comment]
不是这样的，按下面的优先级递减：
已经存在的电影或者电视剧集的不会扫描。
如果是在已有的电视剧里面增加了新的集只会扫这个电视剧的文件夹。
如果开了二级分类，并且在媒体服务器里面的媒体库设置的路径跟二级分类一致，只会扫描这个二级分类对应的库。
以上条件都不满足时扫整个库，这个情况下扫多少这个工具是没办法决定的是美体服器软件决定的。
以上说的指的是emby和jellyfin，plex只支持扫整库。
你有具体的例子把两边的目录跟两边的日志贴出来分析吧。

**Comment by boeto** [comment]
1. 已经存在的电影或者电视剧的媒体会被扫描，例如下图的'Movies Other'和'TV Shows Other'，它们不是使用TMDB的媒体刮刮库，不需要被扫描识别；
2. 如果没设置二级分类，会额外扫描媒体库设置的路径之外的文件夹

---

emby媒体服务器库与路径：

![](https://raw.githubusercontent.com/boeto/image/main/uploads/20221109205418.png)

nastools媒体库路径：

![](https://raw.githubusercontent.com/boeto/image/main/uploads/20221109204345.png)

nastools扫描过程：（注意这里识别了Movies Other 和 TV Shows Other）
![](https://raw.githubusercontent.com/boeto/image/main/uploads/20221109212635.png)
![](https://raw.githubusercontent.com/boeto/image/main/uploads/20221109212713.png)

nastools日志
```log
20:40:45 INFO - 【MEDIASERVER】开始同步媒体库数据...
20:41:24 INFO - 【MEDIASERVER】媒体库数据同步完成，同步数量：2848
```

nastools媒体库同步扫描公耗时时间：39s 

Ps: 之前因为耗时太久，所以之前测试已经移除了大部分媒体库，
不在TMDB上的电影电视剧媒体（例如某些小电影），下次依然会被扫描

![](https://raw.githubusercontent.com/boeto/image/main/uploads/20221109204245.png)

---

功能举例：

选择需要扫描的库：

![](https://raw.githubusercontent.com/boeto/image/main/uploads/20221109212539.png)

扫描日志与时间：

![](https://raw.githubusercontent.com/boeto/image/main/uploads/20221109203545.png)

功能优化列举：
选择需要扫描的某些库
![](https://raw.githubusercontent.com/boeto/image/main/uploads/20221109210712.png)

扫描日志与时间：
![](https://raw.githubusercontent.com/boeto/image/main/uploads/20221109212859.png)

媒体库同步扫描公耗时时间：16s

---

两千多的媒体扫描时间相差 ：39s - 16s = 23s

如果这媒体数量 x10 ，x100 呢，那么这扫描效率的差距就明显了

---

上述只是简单地说明一下，如果有说的不清楚或者不对的地方还望大大海涵～

**Comment by jxxghp** [comment]
你是说的同步啊。。我一直以分你说的是转移后自动刷新媒体库。。

**Comment by boeto** [comment]
嗯嗯，是的呢，还是带上图来说明比较清楚～NasTools肯定会越来越棒！
