### ISSUE TITLE
自定义订阅支持使用代理

### ISSUE THREAD

**Issue by amtoaer** [NAStool/nas-tools#2039]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.4.2
>
> 环境: docker

## 你想要新增或者改进什么功能？

自定义订阅支持使用代理（北京联通直连 mikanani 经常出现 RSS 未下载到数据，添加下载任务失败的错误）

## 这个功能有什么可以参考的资料吗？

可以像站点维护里一样，加一个“使用代理服务器”的开关？

**Comment by zouhy2001** [comment]
支持
