### ISSUE TITLE
刷流任务一键停止或开启

### ISSUE THREAD

**Issue by roadinger** [NAStool/nas-tools#2100]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>
> 环境: docker or windows or synology

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by roadinger** [comment]
刷流任务能搞个一键停止或开启的功能吗

**Comment by yjdandwzd** [comment]
支持

**Comment by Yinghai75** [comment]
支持

**Comment by sjtuross** [comment]
最好再加上禁用某个刷流任务，以及克隆某个刷流任务方便新建

**Comment by A-S-76** [comment]
支持

**Comment by ghost1nx** [comment]
同求

**Comment by KKFantasy** [comment]
同求，或者增加**定时开启关闭**的功能也行，感谢。

> 需要这个功能是因为固态硬盘不够大，rss下来的种子可能还要手动调整，所以晚上睡觉时希望关闭rss，以免硬盘被塞满而出错。
