### ISSUE TITLE
求解决：2.6.0 目录同步选择“复制”模式的时候，文件权限丢失

### ISSUE THREAD

**Issue by yangdejun029** [NAStool/nas-tools#2261]
NASTool 版本: v2.6.0 b00e4220

环境:群晖 6.2.4-25556  Docker安装

在群晖上用DOCKER版更新到2.6.0版本之后发现，如果目录同步功能中使用“复制”方式到其它文件夹的时候，该文件的权限会全部丢失，仅“admin”有权限，造成其它用户及应用都无法打开使用，比如EMBY，JF，Drive ShareSync等都无法使用，需要手动在上一级目录重新给一次权限才能打开，求解决！

![image](https://user-images.githubusercontent.com/119518709/204845358-68387b3f-8175-4830-b5d7-c3759d2d0cae.png)

EMBY 可以识别到，但是无法播放，一播放就显示没有可用的流
Drive ShareSync就根本无法识别到有新文件，不会同步该文件

**Comment by sanchidr** [comment]
群晖下面无论docker还是套件安装复制文件后权限丢失了。

**Comment by yangdejun029** [comment]
> 

那看来是整个版本的问题，还望大佬 解决，我昨天又测试了下，是从2.4.0版本起就出问题了，2.3.2都没问题

**Comment by jxxghp** [comment]
不理解问题在哪，中间有个版本docker丢失了mask，但最新的版本程序已经加上了。

**Comment by yangdejun029** [comment]
> 不理解问题在哪，中间有个版本docker丢失了mask，但最新的版本程序已经加上了。

就是如果我设置了文件转移是“复制”转移模式，那么转移之后的文件上原来的权限就丢失了，只有admin这个帐户有权限，其它的什么emby，guest，或者system等都没有权限了，就会转成EMBY打不开，windows下共享进去也打不开文件

![image](https://user-images.githubusercontent.com/119518709/205242507-4b4a3c18-4f64-474b-b493-c7c83bfbcf62.png)

**Comment by jxxghp** [comment]
估计是 shutil.copy2 的锅

**Comment by yangdejun029** [comment]
> 估计是 shutil.copy2 的锅

这个就不懂了，感谢大佬跟进

**Comment by Shurelol** [comment]
nastool和uid和pid改成和下载器的一样再试试吧

**Comment by yangdejun029** [comment]
> nastool和uid和pid改成和下载器的一样再试试吧

试过也没用，我下载的用的是套件里的QB，关键是2.4之前版本没问题的

**Comment by ntsugar** [comment]
> 

同样的问题，搞了两天一直没搞定，目录同步复制后变成admin权限，哪怕给整个媒体目录everyone权限，新copy的媒体EMBY都是无权限。

**Comment by KITblue** [comment]
我qb和nas-tool都设的一样的权限，正常的 puid：1000   PGID：100，还有jellyfin也要设一样的，这三个程序都会动文件

**Comment by lightolly** [comment]
复制之前的文件所有者是什么？

**Comment by yangdejun029** [comment]
> 复制之前的文件所有者是什么？

system administrs emby everyone 都有

**Comment by imyuqi1982** [comment]
不一定是权限问题（换方案同步之前这问题我也碰到过）把复制的文件权限还原后有些文件播到一半时间就会出现暂停现像，剩的一半硬是播不了，确定是复制的文件数据出了问题（qbit里的原文件播完没问题）。

**Comment by yhslln** [comment]
同样遇到了这个问题，采用复制的方式进行目录同步时，同步后的文件仅有admin权限
