### ISSUE TITLE
Chrome 优化安装方式

### ISSUE THREAD

**Issue by DDSDerek** [NAStool/nas-tools#2381]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.3
>
> 环境: docker

## 你想要新增或者改进什么功能？

- 目前nas-tools配合的Chrome都是从软件库安装的，但是这样会出现一些问题：
1. Windows 不支持
2. 会出现兼容性问题，类似于https://github.com/jxxghp/nas-tools/issues/1430

- 所以我觉得Chrome不应该从软件包里面安装，而是应该像ChineseSubFinder一样通过程序控制下载Chrome程序，这样才可以做到完美的兼容。并且通过这种方法下载的Chrome可以做到支持全平台，包括Windows和群晖

- 并且我这边ChineseSubFinder通过程序下载的Chrome是可以正常在非root用户下运行的，而nas-tools目前通过alpine软件库安装的Chromedrive却不行，这也验证了上面我说的，程序控制下载的Chrome就很少会出现兼容性问题

- 但是我个人不是很懂代码，所以具体是如何通过程序控制Chrome的下载这方面问题大佬可以与ChineseSubFinder作者交流一下

## 这个功能有什么可以参考的资料吗？

> ChineseSubFinder

**Comment by jxxghp** [comment]
windows下是故意不支持的，因为有bug还未解决，会导致重启很多份进程。
docker下alpine自动下载的有问题无法使用（原因不明），所以才默认指定版本内置的。
其他环境都可以自己手工安装到指定路径就会调起（以下是各个环境的路径），群晖套件的裙下大佬的套件已经支持。
目前的处理方式是经过实践后比较稳定和试用大多数人的，当然也可以帮忙验证其他方案。

# WebDriver路径
WEBDRIVER_PATH = {
    "Windows": None,
    "Linux": "/usr/lib/chromium/chromedriver",
    "Synology": "/var/packages/NASTool/target/bin/chromedriver",
    "MACOS": "/Users/nastool/chromedriver",
}

**Comment by DDS-ALL** [comment]
我这边用同一个版本的镜像在不同机器上测试，j1900的蜗牛星际就会出现在非root用户下启动Chrome会被系统不正常关闭，最终导致nastools无法连接到chrome，也就是https://github.com/jxxghp/nas-tools/issues/1430 这个老问题了，而在e3和e5的机器上就不会出现这种问题。我排查了系统版本，Docker版本，最终都没有发现问题，所以周末我准备用Ubuntu做为基础镜像再尝试一下，排除一下Alpine的问题。争取解决https://github.com/jxxghp/nas-tools/issues/1430 这个问题

**Comment by DDS-ALL** [comment]
我这边测试了一下，问题依旧，说明可以排除系统问题了

**Comment by DDS-ALL** [comment]
我这边给到一个解决办法，如果有相同问题 https://github.com/jxxghp/nas-tools/issues/1430 的朋友，可以参考参考

- nastools通过root用户启动

在这种情况下，只有nastools刮削转移后的文件需要重新设置权限，因为下载的文件的权限是由下载器决定的

- https://github.com/DDS-Derek/nas-tools-all-in-one/blob/master/scripts/File_Permission_Changes.sh 定时运行这个脚本

通过这个脚本，可以定期检测新产生的媒体文件，并给新媒体文件设置权限，而不是全部媒体文件都重设一遍

**Comment by hongshaoyi** [comment]
我也遇到这个问题了，基本就是上面说的问题
这里补充一点，如果你们担心权限问题，可以了解下docker的namespace用法(好像现在还有更新的技术)，大概就是用户映射，容器内的root在宿主机上只是一个普通用户，这样就没权限问题了
但是映射范围要写大一点，不然拉取镜像会报错，我有提过bug单#2312，现在镜像里有个非常大的containerid，不知道啥原因，从某个版本开始的
所以我现在容器就是root启动，但是不用担心权限问题
![image](https://user-images.githubusercontent.com/8248135/210221955-2bd88277-dda8-4820-828e-175315fdfecf.png)
![image](https://user-images.githubusercontent.com/8248135/210222313-bda0f280-2635-4c41-9048-431273a74a81.png)

**Comment by DDS-ALL** [comment]
> 我也遇到这个问题了，基本就是上面说的问题
> 这里补充一点，如果你们担心权限问题，可以了解下docker的namespace用法(好像现在还有更新的技术)，大概就是用户映射，容器内的root在宿主机上只是一个普通用户，这样就没权限问题了
> 但是映射范围要写大一点，不然拉取镜像会报错，我有提过bug单#2312，现在镜像里有个非常大的containerid，不知道啥原因，从某个版本开始的
> 所以我现在容器就是root启动，但是不用担心权限问题
> ![image](https://user-images.githubusercontent.com/8248135/210221955-2bd88277-dda8-4820-828e-175315fdfecf.png)
> ![image](https://user-images.githubusercontent.com/8248135/210222313-bda0f280-2635-4c41-9048-431273a74a81.png)

多谢大佬给出解决方案，我研究一下
