### ISSUE TITLE
关于更好的对媒体文件进行管理的一些想法和建议

### ISSUE THREAD

**Issue by zjgithub413** [NAStool/nas-tools#2405]
> NAStool 版本: v2.6.3 f7aec36e
> 环境: docker
NT的功能越来越强大，现在有了文件管理功能，可以对原文件、硬链接后的文件、字幕文件进行管理。本人不懂代码、不会设计、不会PS，拿PPT随便画了点图，展示自己的一些想法：如何可以更好的对媒体文件进行管理，包括：原文件、硬链接后的文件、字幕文件、图片文件等。个人画的感觉可以更加直观的管理每部电影，供开发者参考，也不知道这些乱七八糟的想法在技术上能否实现，如有任何不妥之处，请指正。
![新建 Microsoft PowerPoint 演示文稿 (2)_页面_1](https://user-images.githubusercontent.com/106440008/206406809-1e2e8a3f-8206-4834-9e6f-48c39141117a.jpg)
![新建 Microsoft PowerPoint 演示文稿 (2)_页面_2](https://user-images.githubusercontent.com/106440008/206406815-5406f680-3e9d-4d5f-a8b3-688529a035a3.jpg)
![新建 Microsoft PowerPoint 演示文稿 (2)_页面_4](https://user-images.githubusercontent.com/106440008/206406822-87713790-47e6-45ab-912d-28315666f8e8.jpg)
![新建 Microsoft PowerPoint 演示文稿 (2)_页面_5](https://user-images.githubusercontent.com/106440008/206406833-3ab918fe-50cb-400e-8d22-ab89fd13afaf.jpg)
![新建 Microsoft PowerPoint 演示文稿 (2)_页面_6](https://user-images.githubusercontent.com/106440008/206406843-659f2b11-3f7b-40c9-a64f-1a032fe6ba1b.jpg)
![新建 Microsoft PowerPoint 演示文稿 (2)_页面_7](https://user-images.githubusercontent.com/106440008/206406870-3b751447-d20c-486b-900e-9df734fe4fac.jpg)

**Comment by Shurelol** [comment]
下载的电影最终都要通过emby，plex等播放，媒体软件能展示这些，nastool没必要做

**Comment by zjgithub413** [comment]
> 下载的电影最终都要通过emby，plex等播放，媒体软件能展示这些，nastool没必要做

其实这些功能中最希望能拥有的就是第三张图，可以直观的展现原文件和硬链接后的文件，看看哪些电影硬链接后原文件丢了，或者哪些文件没有成功的硬链接，再或者是某部电影不想保种了，直接可以通过第三张图删了

**Comment by serenity666** [comment]
我觉得第一张图可以点击后跳转到媒体服务器地址。这个应该很简单，也挺实用的。至于展示所有电影确实有些多此一举，nastools开发初衷是自动化下载和整理，展示还是交给其他媒体服务器吧。硬链接在历史记录里好像都有，也可以删除媒体文件，不过仅展示了媒体文件和字幕文件，图片和INFO文件没有展示，也没办法直接删除。要是可以删除该电影的目录就好了。个人愚见。

**Comment by Shurelol** [comment]
用文件管理删除视频文件后，如果删除视频文件后，所在文件夹没有视频文件，会删除该文件夹，并且会向上查询一级

这都是已经实现的功能

**Comment by xhrzg2017** [comment]
可以参考tmm

**Comment by serenity666** [comment]
> 用文件管理删除视频文件后，如果删除视频文件后，所在文件夹没有视频文件，会删除该文件夹，并且会向上查询一级
> 
> 这都是已经实现的功能

原来如此

**Comment by zjgithub413** [comment]
感谢以上的各位愿意对个人的这些想法进行谈论

**Comment by zjgithub413** [comment]
您好，您的邮件我已收到，我会尽快回复Hello, I have received your mail, and I will reply as soon as possible
