### ISSUE TITLE
Transmission重启后会重设种子ID导致刷流任务认为种子不存在

### ISSUE THREAD

**Issue by SilenceEagle** [NAStool/nas-tools#2506]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.4
>
> 环境: docker on qnap NAS

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？
不使用种子'ID'作为种子的哈希值，因为`Transmission`重启后`ID`会被按照顺序重置为连续序号，这样就会存在几个问题：
1. 当删除了`id`较小的种子后再重启'Transmission'，`id`被顺位补进，这样`nas-tools`刷流任务监控的种子`id`可能就因被重置而不存在，会导致从数据库中删除做种记录，重新按照做种体积要求来下载新种子；
2. 如果有种子的`id`被重置后刚好变成了`nas-tools`监控的种子`id`，而刚好又开启了刷流任务的自动删种规则且这个错误的种子阴差阳错的满足了做种时间之类的规则，就会被误删，我遇到过几次，之前一直以为是删种规则有误，就不敢再开启自动删种了。

## 这个功能有什么可以参考的资料吗？
有一个老帖子：
[Torrent ids change upon restart](https://trac.transmissionbt.com/ticket/3063)
里面提到了`hashString`是不会因重启而变化的。

大佬可否改进一下，万分感谢！！！

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by jxxghp** [comment]
TR竞然有这个问题。。。。

**Comment by devocyACT** [comment]
目前我使用的 `v3.0.1 0ec1160` 版本，我也出现的了这个问题，

#### 日志显示：
![SCR-20230327-119](https://user-images.githubusercontent.com/128909113/227792423-880afa40-9caf-4a48-96be-2b76dc0d36ef.png)

#### 后台列表显示：
![SCR-20230327-zq](https://user-images.githubusercontent.com/128909113/227793923-2b89da56-0b99-4fd7-8fd4-0dd53bd1b766.png)

#### 但是这个问题看上去是Transmission的bug，以 `id` 为 169 为例， 在不指定 `ids` 的情况下获取到列表是包含这条数据的
![SCR-20230327-1vn](https://user-images.githubusercontent.com/128909113/227792947-dd5279b7-40a4-4875-8cfb-b47df617064d.png)

#### 但在我指定了 `id` 以后，169 这条数据就获取不到了

![image](https://user-images.githubusercontent.com/128909113/227793225-76b2acea-448a-42d3-93f3-bbd0db24dd08.png)
![image](https://user-images.githubusercontent.com/128909113/227793248-85d0bfc2-0fb1-44db-bbac-b1c7380b29ec.png)

#### 我试了用 `hashString` 查询，这条数据是可以找到的
![image](https://user-images.githubusercontent.com/128909113/227793499-6b7c2e8a-7d14-409a-a9fb-f0ef1306f088.png)
![image](https://user-images.githubusercontent.com/128909113/227793543-ec4ea69f-a008-4f3f-98a1-553c8a5e373f.png)
![image](https://user-images.githubusercontent.com/128909113/227793608-44f86ab3-4767-4ab4-b59e-decc7824428c.png)

#### 所以使用 `hashString` 应该可以解决这个问题

**Comment by jxxghp** [comment]
v3.1.4 终于下决心改了这个问题。
