### ISSUE TITLE
消息推送已入库链接到next=history能不能添加个临时token，这样点进去之后不用登录就可以看

### ISSUE THREAD

**Issue by youyifentian** [NAStool/nas-tools#2554]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.7.1
>
> 环境: docker and synology

## 你想要新增或者改进什么功能？

> 消息推送已入库链接到next=history，直接点击会要求登录，在微信里面也不能记住密码，每次都得登录才能查看，就比较麻烦，能不能在连接上面添加个临时token，这样点进去之后不用登录就可以查看，有token也可以防止别人访问，token过期后才要求登录，感觉体验会好些，非常感谢

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by youyifentian** [comment]
并且这个token只有查看history的权限，可以保证安全

**Comment by Shurelol** [comment]
这个建议不错，特别微信还不能自动跳转到外部浏览器

tg关了内部浏览器，倒是问题不大

**Comment by jxxghp** [comment]
貌似会有安全问题，知道Key了就相当于有管理权限了，而且这个Key还发送到了消息客户端，有的消息是接收方可能是群组。
