### ISSUE TITLE
刷流任务一些功能建议

### ISSUE THREAD

**Issue by c939984606** [NAStool/nas-tools#2587]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>v2.7.1 28b4b420
> 环境: docker or windows or synology
docker 
## 你想要新增或者改进什么功能？

> 1. 种子发布时间增加介于判断，很多站点种子发布前1-3小时对于盒子不免费比如某空
> 2. 定时功能添加cron支持，比如只是周末刷，每周1,3，5刷
> 3. tabler有个开关样式可以加到刷流页面快速开关
![image](https://user-images.githubusercontent.com/34211368/208361963-3017b807-d1ae-4b52-9a9e-1cb29ba246e1.png)

**Comment by Mikcoono1** [comment]
请问楼主刷流会自动删种+数据吗？ 我用了好几个版本压根不删种跟数据

**Comment by c939984606** [comment]
> 请问楼主刷流会自动删种+数据吗？ 我用了好几个版本压根不删种跟数据

会的，这个是正常的，你会不会文件权限有问题

**Comment by Mikcoono1** [comment]
> > 请问楼主刷流会自动删种+数据吗？ 我用了好几个版本压根不删种跟数据
> 
> 会的，这个是正常的，你会不会文件权限有问题

谢谢 这就去看看
