### ISSUE TITLE
建议增加字幕下载插件多目录支持

### ISSUE THREAD

**Issue by zraxx** [NAStool/nas-tools#2624]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.2
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？
因下载影视存储在2个硬盘不同目录，目前字幕功能中的chineseSubFInder，只能支持一组目录字幕下载，能否增加到两组目录电影和电视字幕下载。如，目前是本地路程：/downloads/media 远程路径： /media；增加一组 如 本地路径：/downloads2/media 远程路径： /media1
## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by zraxx** [comment]
![Screenshot_2022-12-22-09-31-23-052_com.android.browser.png](https://user-images.githubusercontent.com/25578054/209035270-66b692a5-b0ec-4591-acf7-38285fa614d1.png)

**Comment by jxxghp** [comment]
应该给csf提？
