### ISSUE TITLE
为站点增加搜索频率限制

### ISSUE THREAD

**Issue by acemby** [NAStool/nas-tools#2667]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.1
>
> 环境: docker on linux

## 你想要新增或者改进什么功能？

> 可否为站点设置搜索频率限制, 比如为mteam设置120秒内只能搜索1次, 以避免搜索功能被站点禁用

## 这个功能有什么可以参考的资料吗？

> 暂无

**Comment by luoxiao-xy** [comment]
确实，有些网站限流
