### ISSUE TITLE
同一类型下载器添加多个

### ISSUE THREAD

**Issue by GyanRoe** [NAStool/nas-tools#2715]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.3
>
> 环境: docker

## 你想要新增或者改进什么功能？

我下载BT/PT都是习惯使用qb(BT和PT分开，BT使用qb增强版，PT使用普通版，避免pt站点封号）。但目前同一类型的下载器只能添加一个

> 1、希望下载器同一类型的下载器可以任意添加，而不是同一个类型的下载器只能添加一个，添加时选择好下载器类型即可
> 2、希望下载器页面不显示没添加的下载器类型，只显示添加好的（如下载器1，下载器2），下载设置中的下载器对象为添加好的下载器（如下载器1，下载器2）。这样可以根据不同站点的资源选择下载器
。

**Comment by MickMo** [comment]
我有类似的需求，我是有多个下载机器，但是只能添加一个下载器，剩余的机器无法纳入到nastool的管理下。
