### ISSUE TITLE
刷流对不同的站点添加分类或者标签

### ISSUE THREAD

**Issue by youyifentian** [NAStool/nas-tools#2722]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.7.3
>
> 环境: docker 

## 有很多站点需要刷流的时候，用的是同一个qb下载器，这样所有的下载和做种都在一起了，不进行分类或者标签标记的话就分不清哪个种子是哪个站的了

下面是我自己添加的分类，可以很容易分清种子和站点
![QQ截图20221230121324](https://user-images.githubusercontent.com/5012570/210033826-22a81c7f-b4f1-4191-bb32-0f88e37c1d85.jpg)

**Comment by Shurelol** [comment]
Tracker不就能区分么

除了极个别站点，tracker就能看出是哪个站的吧

**Comment by Mrxlei** [comment]
这个其实挺实用，建议大佬考虑

**Comment by haoshaoyang** [comment]
> Tracker不就能区分么
> 
> 除了极个别站点，tracker就能看出是哪个站的吧

有些站不同种子的tracker不一样，最后tracker列表里同一个站的tracker可能有几百个，不太容易区分

**Comment by haoshaoyang** [comment]
我目前的临时解决方案是区分了不同目录，keep保种，refresh刷流，日常观影就正常的movie和tv。
