### ISSUE TITLE
希望增加延迟刷新媒体库

### ISSUE THREAD

**Issue by Tasle** [NAStool/nas-tools#2910]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.5 5d24c31
>
> 环境: docker

## 你想要新增或者改进什么功能？

>用的网盘挂载，经常入库刷新后没有反应，经过一段时间观察发现可能是因为转移后rclone挂载的网盘没有实时刷新导致的，经常会有以下情况：
`电影A`- 入库时间14.11 - Nastool 实时刷新后没有反应
`电影B`- 入库时间14.33 - Nastool 实时刷新后出现了`电影A`
`电影C`- 入库时间14.53 - Nastool 实时刷新后出现了`电影B`
...

## 这个功能有什么可以参考的资料吗？

> 每个人缓存更新时间可能不一样，建议增加可以自定义`sleep`的时间后再刷新媒体库。比如我可以设定`3min`，然后在nastool转移入库后等待3min后再刷新媒体库并发送通知。

**Comment by XINGYUZHMM** [comment]
为什么不直接在emby/jellyfin里创建计划任务扫描媒体库呢。
