### ISSUE TITLE
开始页电视剧数据错误

### ISSUE THREAD

**Issue by linyuan0213** [NAStool/nas-tools#2990]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.6
>
> 环境: docker
>

## 你遇到什么问题了？

> 下载了五季的绝命毒师电视剧展示展示变成了动漫的数据

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 正确显示结果

## 给出程序界面截图、后台运行日志或配置文件

![4312C9D1-496D-4F8A-99FB-4B1AD33984DA](https://user-images.githubusercontent.com/26356991/212324010-d0b879d6-b207-4948-baa9-4f4eb9dd97de.jpeg)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
历史记录界面截个图

**Comment by linyuan0213** [comment]
> 历史记录界面截个图

<img width="1917" alt="image" src="https://user-images.githubusercontent.com/26356991/213067133-48569efd-6c12-4f4d-a478-43cacf949257.png">

**Comment by WLYseven** [comment]
> 我也是，所有的电视剧都识别成电影，首页电视剧那栏从来都没有过数据

是不是jellyfin的分类名字一定要设置成电视剧不能是国产剧欧美剧这样
