### ISSUE TITLE
转移目录时希望能排除某些特定的子目录

### ISSUE THREAD

**Issue by dongshimou** [NAStool/nas-tools#3092]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.0
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 转移目录时希望能排除某些特定的子目录

## 这个功能有什么可以参考的资料吗？

> 应该是加一个选项,可以排除某些子目录.

比如一个 番剧的目录下,有 番剧的.mkv,还有`SPs`,`CDs`,`PVs`等目录,这些在tmdb没有对应的资料.
nas-tools在转移目录的似乎没有按照字典序,有时候会转移成功某些集,然后就去扫描子目录,转移失败,并导致后续其他集无法继续.
这时候要么删除掉这些额外的目录(会导致做种问题),要么就一个个手动转移具体的集,非常繁琐.
希望在转移目录的时候有一个排除某些特定的文件或者文件目录的选项.

**Comment by Shurelol** [comment]
![image](https://user-images.githubusercontent.com/16237201/213871979-fbf4ae43-d0db-4cb4-b7e3-c33eae8dbce8.png)
![image](https://user-images.githubusercontent.com/16237201/213871984-5f5bdd15-f17e-4b25-b202-e128c2428968.png)

或许该看看到底有什么功能？

**Comment by dongshimou** [comment]
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/9100799/213872099-e8c5aa38-49bd-4921-8971-d5a76b6f9131.png">
抱歉,我一直以为转移目录相关的东西在这里设置...
基础设置里面没有详细看过.

**Comment by dongshimou** [comment]
能在这里添加一个 选项吗?
基础设置里是通用配置,能像这个`最小文件大小`一样有一个覆盖配置码?
