### ISSUE TITLE
win版无法运行

### ISSUE THREAD

**Issue by Kevinhongmr** [NAStool/nas-tools#3116]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.1
>
> 环境: windows
>
## 你遇到什么问题了？

>exe文件无法运行，弹出提示如图

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 可以正常运行

## 给出程序界面截图、后台运行日志或配置文件

> 
![微信截图_20230123181929](https://user-images.githubusercontent.com/48870975/214016342-27e427c0-efaa-4cdb-9d68-4c47d36e5932.png)

> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by yexiaozhulin** [comment]
下载sqlitestudio 打开user.db 复制一张表改名alembic_version 试试

**Comment by Shurelol** [comment]
先运行2.8.0，再同目录运行2.8.1

**Comment by zhaokun0721** [comment]
> 下载sqlitestudio 打开user.db 复制一张表改名alembic_version 试试

本来就有alembic_version呀

**Comment by zhaokun0721** [comment]
> 先运行2.8.0，再同目录运行2.8.1

2.8也运行不了  除非单独目录运行2.8 然后倒入备份 又打不开了

**Comment by makerdegit** [comment]
一样。。。

**Comment by makerdegit** [comment]
能保留大部分配置都行，所有东西重新配置太费劲了

**Comment by Dreamray** [comment]
这问题从274以后版本就有了，等了好几个版本一直到281还是不行，我是这样解决的：全新纯净目录运行281，生成db文件，对比此db与原来的274的db多了哪些字段，一个一个加上，全手动双眼对比，用时一个小时

**Comment by Shurelol** [comment]
> 这问题从274以后版本就有了，等了好几个版本一直到281还是不行，我是这样解决的：全新纯净目录运行281，生成db文件，对比此db与原来的274的db多了哪些字段，一个一个加上，全手动双眼对比，用时一个小时

要愿意这么干，要不了10分钟，因为这里面有些加了哪些
https://github.com/jxxghp/nas-tools/blob/master/db_scripts/versions/720a6289a697_1_1_0.py

**Comment by zhaokun0721** [comment]
> 这问题从274以后版本就有了，等了好几个版本一直到281还是不行，我是这样解决的：全新纯净目录运行281，生成db文件，对比此db与原来的274的db多了哪些字段，一个一个加上，全手动双眼对比，用时一个小时

问题是我全新的目录都运行不了 2.8.1    2.8.0 倒是可以  win10 64

**Comment by Kevinhongmr** [comment]
> 
这个文件怎么使用呢

**Comment by fishingxx** [comment]
我也是同样的问题  只能用2.7.4 之后的每个版本都报同样的问题  两台电脑都打不开

**Comment by gaoshouyu** [comment]
一样的问题，只能停留在2.7.4。

**Comment by zgmf-x-20a** [comment]
> 这问题从274以后版本就有了，等了好几个版本一直到281还是不行，我是这样解决的：全新纯净目录运行281，生成db文件，对比此db与原来的274的db多了哪些字段，一个一个加上，全手动双眼对比，用时一个小时

2.7.4 和 2.8.0 升级 2.8.1的问题还不一样。
2.7.4 是 CONFIG_USER_RSS 只有15个字段，280 改到 20 个字段，打开数据参考DDL看缺什么字段自己加。
2.8.1 则是上图的缺少 alembic 的问题。我也是醉了，看来win版本只是个养子。

**Comment by sakumakenshin** [comment]
同样问题，暂时坚持2.7.4了。懒得折腾

**Comment by wufloor** [comment]
同样的问题 全新安装无法打开使用

**Comment by k2y1982** [comment]
我把能正常用docker版2.7.6里的db和yaml都复制过来，然后win版的就能运行了。

**Comment by C3604** [comment]
我在全新目录运行2.8.1也报错，还是在用2.7.4，😔

**Comment by gaoshouyu** [comment]
> > 这问题从274以后版本就有了，等了好几个版本一直到281还是不行，我是这样解决的：全新纯净目录运行281，生成db文件，对比此db与原来的274的db多了哪些字段，一个一个加上，全手动双眼对比，用时一个小时
> 
> 2.7.4 和 2.8.0 升级 2.8.1的问题还不一样。 2.7.4 是 CONFIG_USER_RSS 只有15个字段，280 改到 20 个字段，打开数据参考DDL看缺什么字段自己加。 2.8.1 则是上图的缺少 alembic 的问题。我也是醉了，看来win版本只是个养子。

直接把个人数据挪到新版本可行？

**Comment by w-kun** [comment]
之前升2.8.0时尝试过删alembic表没成功。停在2.7.4 +1。

**Comment by sdepool** [comment]
2.7.9到2.8.2更新一直都有问题，每次升级都要重新配一遍，删表还会导致其他问题，如订阅界面打不开，不如全新安装。
从2.8.2升到2.8.3倒是挺顺利，没出现错误。

**Comment by jxxghp** [comment]
#3977
