### ISSUE TITLE
关于同步目录的小bug

### ISSUE THREAD

**Issue by 188334911** [NAStool/nas-tools#3283]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
> 2.83
> 环境: docker or windows or Synology
>AMD X64 ubuntu docker

## 你遇到什么问题了？

> 使用监控目录同步功能时,第一次移动或者创建文件(夹)均可以正常触发nas-tools的同步功能,但是将同步文件(夹)删除或者移出后,再次移动或者创建同名文件(夹)时,始终无法触发同步功能,从inotifywait -m /point里看到第二次移动文件是有事件发生的,但是nas-tools没有反应,不知道这是nas-tools为了防止反复同步特意设定的还是程序小bug?

* 已经清理过转移缓存试过了,还是不能再次识别同名文件(夹)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已搜索并讨论

## 你期望的结果

> 修复bug,有时候看过一部电影以后删除了,后面如果又想看的时候,再次下载就不能自动同步识别了.

## 给出程序界面截图、后台运行日志或配置文件
1.移动test.mp4到监控目录
![移动test mp4到监控目录](https://user-images.githubusercontent.com/54146909/215985440-bbd7e741-86a1-444d-a339-8357b9b4b039.png)
2.nas-tools正确触发同步
![nas-tools正确触发同步](https://user-images.githubusercontent.com/54146909/215985500-ffe6860a-2388-461a-b577-b774c4fecb6b.png)
3.删除test mp4
![删除test mp4](https://user-images.githubusercontent.com/54146909/215985576-7d3fefa3-56fe-4495-8442-dfe7507bc4e8.png)
4.再次移动test mp4到监控目录
![再次移动test mp4到监控目录](https://user-images.githubusercontent.com/54146909/215985638-5514bb60-4ca6-4fd2-b434-0b0f9fa3b06f.png)
5.nas-tools没有反应
![nas-tools没有反应](https://user-images.githubusercontent.com/54146909/215985687-edb1aa48-72f3-41d6-8c9e-0ccde9ba2cc5.png)
> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by link2fun** [comment]
![image](https://user-images.githubusercontent.com/19241982/216026419-845d9763-c82a-41a4-9a9e-c6b25cad1430.png)

**Comment by DDSDerek** [comment]
> ![image](https://user-images.githubusercontent.com/19241982/216026419-845d9763-c82a-41a4-9a9e-c6b25cad1430.png)

不是这个原因，清理了也会这样，Ubuntu22.04+NAStool2.8.3可以重现

**Comment by 188334911** [comment]
> * 已经清理过转移缓存试过了,还是不能再次识别同名文件(夹)

是的 ,我已经清理过缓存试过的,确定不能反复触发

**Comment by 188334911** [comment]
> ![image](https://user-images.githubusercontent.com/19241982/216026419-845d9763-c82a-41a4-9a9e-c6b25cad1430.png)

是的 ,我确定是清理过缓存试过的,确定不能反复触发同名文件(夹)的同步

**Comment by jxxghp** [comment]
清理完重启下看看
