### ISSUE TITLE
无法展开列表 电脑端Firefox可以复现

### ISSUE THREAD

**Issue by zsbai** [NAStool/nas-tools#3287]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.2
>
> 环境: docker or windows or Synology
> 环境: docker

## 你遇到什么问题了？

无法展开列表，如自定义识别词，刷流任务右边的三条杠，点击就跳转到[object Object]页面，电脑端Firefox浏览器可以重现问题
![](https://user-images.githubusercontent.com/62942942/215310193-acbbc522-b130-4a98-9aca-479e6dbf157d.png)
![](https://user-images.githubusercontent.com/62942942/215310230-f48834b5-1eb4-48f5-9aad-fcea78cddb43.png)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

还未解决

## 你期望的结果

正确展开列表

## 给出程序界面截图、后台运行日志或配置文件

![](https://user-images.githubusercontent.com/62942942/215310517-41f26bbd-997e-4e3b-9548-b5673a6a0f8d.png)

**Comment by DDSDerek** [comment]
同样遇到了，希望作者可以修复
