### ISSUE TITLE
不在订阅范围内

### ISSUE THREAD

**Issue by PoiYuudachi** [NAStool/nas-tools#3306]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>2.8.3 3ea1be2
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

> 描述一下你遇到的问题
过滤规则与识别都没有问题 但是日志却说不在订阅范围内
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
![photo_2023-02-03_02-02-31](https://user-images.githubusercontent.com/41389186/216410179-1a4c83cc-9f84-4ca9-9eb2-db1d9e72f47c.jpg)
![V5_M(`1DABHRSZIH6`3S `T](https://user-images.githubusercontent.com/41389186/216410190-a36e2cde-f0b9-49c6-aee2-e085439cfdf1.png)
![photo_2023-02-03_02-01-46](https://user-images.githubusercontent.com/41389186/216410196-f676c234-259b-489e-8273-0fb3961dc6af.jpg)
![8UL1G BEOCO4ZJ1NTX( 8ET](https://user-images.githubusercontent.com/41389186/216410618-e3e9353f-f98d-4b1e-b7f2-c8a537f8cb11.png)

**Comment by jxxghp** [comment]
你订阅了吗？乍不截一下你已订阅的内容截图？

**Comment by PoiYuudachi** [comment]
![0`3@`CCU3P_PLI{%QDRX8%F](https://user-images.githubusercontent.com/41389186/216571177-f1f8e540-8402-4d46-9937-466b04f92176.png)

>
