### ISSUE TITLE
【需求】增加利于站点唯一id更新cookie的API

### ISSUE THREAD

**Issue by Eao-Kind** [NAStool/nas-tools#3347]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.2
>
> 环境: docker 

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？

 利用唯一 ID 更新cookie， updateCookie(site_id，cookie)，方便油猴脚本更新cookie。

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by luoxiao-xy** [comment]
好想法，也不用去登录获取cookie了
