### ISSUE TITLE
请问nastool 榜单推荐打不开怎么办呢？

### ISSUE THREAD

**Issue by jeannu** [NAStool/nas-tools#3432]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本:2.9
>
> 环境: docker

请问nastool 榜单推荐打不开怎么办呢？日志截图如下：
![f4a129d79442f141da243e42d154aa6](https://user-images.githubusercontent.com/124561494/218047617-a4ce200f-e036-43f3-b681-a0af3b3ef16f.png)

其他功能没问题，打开榜单下所有内容一直转圈圈不显示——
![f4a129d79442f141da243e42d154aa6](https://user-images.githubusercontent.com/124561494/218047795-627eae97-023c-4835-9fd1-ffc7e326e05f.png)

谢谢谢谢

**Comment by jeannu** [comment]
![image](https://user-images.githubusercontent.com/124561494/218047936-cc1b347a-cdc7-4eeb-8416-b013ce084df4.png)

**Comment by jxxghp** [comment]
日志看不全

**Comment by jxxghp** [comment]
要不容器连不上tmdb要么是电脑连不上导致加载不了同图片。
