### ISSUE TITLE
2.9.0的手机UI是不是存在BUG？

### ISSUE THREAD

**Issue by j4i0n4** [NAStool/nas-tools#3457]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: [v2.9.0 226b07e]

> 环境: synology套件

ios 14.4.1系统，safari浏览器登录之后一直在转，无法进入到后台，尝试过chrome，也是存在该问题

**Comment by c939984606** [comment]
ios14系统都不正常，我试过8台手机

**Comment by c939984606** [comment]
测试  [v2.9.1 e3a43d4](https://github.com/jxxghp/nas-tools)问题依旧，无配置全新安装

**Comment by jxxghp** [comment]
ios16正常，ios14没测试过。
清除缓存试了吗？

**Comment by c939984606** [comment]
> ios16正常，ios14没测试过。 清除缓存试了吗？

iOS 16 15都正常，iOS14不正常，浏览器缓存清空，app删了重新下，Chrome  alook   Safari ，火狐，都不正常，测试了8台手机，3台iOS15以上正常，5台iOS14不正常，都卡在加载动画那个转圈圈那里，2.8版本全部8台没问题

**Comment by c939984606** [comment]
另外2.8.3版本iOS14系统 电影榜单那边打开是空白页面，iOS15正常，安卓正常，感谢像是某个引用的东西不支持iOS15以下

**Comment by jxxghp** [comment]
> > ios16正常，ios14没测试过。 清除缓存试了吗？
> 
> 
> 
> iOS 16 15都正常，iOS14不正常，浏览器缓存清空，app删了重新下，Chrome  alook   Safari ，火狐，都不正常，测试了8台手机，3台iOS15以上正常，5台iOS14不正常，都卡在加载动画那个转圈圈那里，2.8版本全部8台没问题
> 
> ![711675929531_ pic](https://user-images.githubusercontent.com/34211368/218299826-88a154a4-1f9b-4f03-9a14-7abf098f49bf.jpg)
> 
> 

感谢这么详细的测试，但没环境不太清楚哪的问题。

**Comment by c939984606** [comment]
继续测试iOS14.8正常，有一部Xr 14.3正常，这个问题暂时原因未知，变量太多，也可能跟手机有关

**Comment by Xscaperrr** [comment]
windows10的exe版本也有同样问题，2.83能进，2.9及以上都一直转圈
