### ISSUE TITLE
9.2索引器没啦

### ISSUE THREAD

**Issue by zuiyuemuai** [NAStool/nas-tools#3482]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>
> 环境: docker or windows or synology

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by l552121229** [comment]
我也遇到了这个问题
<img width="708" alt="image" src="https://user-images.githubusercontent.com/35548398/218325377-c19a20ac-ce6e-43fc-82f9-3643e085adff.png">

**Comment by Putarku** [comment]
同样遇到了这个问题

**Comment by tualatina** [comment]
同样遇到这个问题。。内建全空 jackett木有了

**Comment by 574408898** [comment]
我的jackett也没有了

**Comment by tualatina** [comment]
> 我的jackett也没有了

看来都是今天晚上更新的 我还琢磨呢 怎么什么都搜不到…😂😂😂

**Comment by Putarku** [comment]
不止jackett没了，emby貌似也连不上了QAQ

**Comment by flower-knight** [comment]
我还以为是我一个人的问题，重装了好多次

**Comment by tualatina** [comment]
我还想着镜像得有点延迟呢 又拉了几次镜像也还是没有 aria的选项也没了

**Comment by Lobeu-m** [comment]
群晖docker  v2.9.2 b308bb9 也没有了

**Comment by MURChen** [comment]
很怪，wiki删了，readme删了部分，docker的镜像只有2.9.0版本，2.9.0删了很多东西
现在用别人的docker回退先

**Comment by KevinZjYang** [comment]
我也是这样。公开站点也没了
![image](https://user-images.githubusercontent.com/31529584/218344834-e7c5f4e7-9267-4bee-abd5-8fe4d38db34c.png)

**Comment by lllrrr2** [comment]
昨晚上11点多新装的，也是这样

**Comment by zuiyuemuai** [comment]
我先保存配置后，再重装9.0就可以恢复了

**Comment by sgpublic** [comment]
我也遇到这个问题了，这种情况大概率是用的docker，解决方案如下：

1. cd 到你的配置目录下，备份一个 `config.yaml` 文件，比如 `mv config.yaml config.yaml.bak`。
2. 把 `https://github.com/jxxghp/nas-tools` 仓库内 `config` 文件夹里面的所有内容覆盖进你的配置目录，比如 `cp ./nas-tools/config/* /xxx/config/`
3. 将第一步备份的 `config.yaml.bak`  恢复到配置目录下。
4. 重新启动 nas-tools 即可。

**Comment by yyyyyyounger** [comment]
同问题，作者大大标了不打算解决。。可能是遇到了什么非技术问题吗

**Comment by sgpublic** [comment]
看样子是作者删除支持了，就很难受

**Comment by yyyyyyounger** [comment]
> 看样子是作者删除支持了，就很难受

这不就等于nastool寄了吗😭 一键订阅真的很方便

**Comment by 91270** [comment]
hub.docker.io 的镜像也删除了， 谁那还有镜像 ？导出一份呗

**Comment by sgpublic** [comment]
> hub.docker.io 的镜像也删除了， 谁那还有镜像 ？导出一份呗

我找的其他人上传的镜像，sungamma/nas-tools:2.9.1

**Comment by vuhe** [comment]
作者把外部的两个索引都删除了，留了一个内部的，默认的公开站点也删除了。可能是要加强内建索引器以支持很多格式的种子名称吧，毕竟外部搜索名称处理不是那么好弄。感觉不像是非技术问题，聚合搜索下载类工具挺多的，而且这些也都是公开站点。

**Comment by sgpublic** [comment]
> 作者把外部的两个索引都删除了，留了一个内部的，默认的公开站点也删除了。可能是要加强内建索引器以支持很多格式的种子名称吧，毕竟外部搜索名称处理不是那么好弄。感觉不像是非技术问题，聚合搜索下载类工具挺多的，而且这些也都是公开站点。

但是2.9.2内建索引器没私有pt就没法用，按理说新的可用之前不该删旧的

**Comment by vuhe** [comment]
这一点我也很疑惑，我翻看了一下近几次提交，基本都是删除支持和删除说明的提交，确实看不懂 feature 的方向是啥。

**Comment by yyyyyyounger** [comment]
所以观感上很像遇到了非技术问题😢 只能等听听作者的想法了

**Comment by vuhe** [comment]
> > 作者把外部的两个索引都删除了，留了一个内部的，默认的公开站点也删除了。可能是要加强内建索引器以支持很多格式的种子名称吧，毕竟外部搜索名称处理不是那么好弄。感觉不像是非技术问题，聚合搜索下载类工具挺多的，而且这些也都是公开站点。
> 
> 但是2.9.2内建索引器没私有pt就没法用，按理说新的可用之前不该删旧的

而且按语义化版本的规则来说，将外部站点删除这种不兼容性 API 改动应该是要翻大版本号的。

**Comment by 120318** [comment]
这样直接就把功能删了，对一些用户还是很伤的。等待作者的正式回复吧。也希望大家把删除之后带来的困扰和问题回复在这里，我们试试能不能说服作者回心转意吧。

**Comment by linyuan0213** [comment]
清空了索引器还怎么用？

**Comment by badboy-tian** [comment]
+1

**Comment by jxxghp** [comment]
目前这个软件被多个渠道大量宣传，风险很高，加上近期的侵权事件，经开发者内部讨论，适当提高门槛，仅围绕私有站点圈子开发，希望能活得久一点。
最新的提交已经删除了bt相关的索引器及下载器，且不提供历史版本。
没有私有站点的自己想办法用旧版本，或者其它fork出去的项目，或者其它同类软件吧。

**Comment by 120318** [comment]
> 目前这个软件被多个渠道大量宣传，风险很高，加上近期的侵权事件，经开发者内部讨论，适当提高门槛，仅围绕私有站点圈子开发，希望能活得久一点。 最新的提交已经删除了bt相关的索引器及下载器，且不提供历史版本。 没有私有站点的自己想办法用旧版本，或者其它fork出去的项目，或者其它同类软件吧。

BT的受众比PT广很多，所以对于BT的支持会导致门槛变低，项目变得大众化，风险较高，所以我很支持相关BT内容的移除。

但对于Jackett和Prowlarr，他们只是一个索引器，项目并不关注它们内部配置的是PT还是BT，即使我们支持这两个索引器，也不会直接和BT扯上关系。而且，Jackett和Prowlarr在国内本身也拥有较高的门槛。

所以我希望可以考虑恢复下Jackett和Prowlarr的支持呢。

**Comment by KevinZjYang** [comment]
> 目前这个软件被多个渠道大量宣传，风险很高，加上近期的侵权事件，经开发者内部讨论，适当提高门槛，仅围绕私有站点圈子开发，希望能活得久一点。 最新的提交已经删除了bt相关的索引器及下载器，且不提供历史版本。 没有私有站点的自己想办法用旧版本，或者其它fork出去的项目，或者其它同类软件吧。

如果是这个原因的话，我支持开发者的决定，缩小圈子才能更好的长久发展，我可不希望这个神器某一天没了。
再说了BT站资源本来就不行，有没有都行，唯一就是动漫资源，大不了搞一个动漫的PT站，问题不大。
支持开发者！！！

**Comment by 91270** [comment]
> 目前这个软件被多个渠道大量宣传，风险很高，加上近期的侵权事件，经开发者内部讨论，适当提高门槛，仅围绕私有站点圈子开发，希望能活得久一点。 最新的提交已经删除了bt相关的索引器及下载器，且不提供历史版本。 没有私有站点的自己想办法用旧版本，或者其它fork出去的项目，或者其它同类软件吧。

如果使用插件的形式，用户自己上传支持其他站点的搜索，是否可行

**Comment by lllrrr2** [comment]
> > 目前这个软件被多个渠道大量宣传，风险很高，加上近期的侵权事件，经开发者内部讨论，适当提高门槛，仅围绕私有站点圈子开发，希望能活得久一点。 最新的提交已经删除了bt相关的索引器及下载器，且不提供历史版本。 没有私有站点的自己想办法用旧版本，或者其它fork出去的项目，或者其它同类软件吧。
> 
> 如果使用插件的形式，用户自己上传支持其他站点的搜索，是否可行

这个建议不错

**Comment by wyxls** [comment]
我个人是觉得没必要连jackett和prowlarr也删除处理，这两个工具本身就有使用门槛，而且属于外部功能支持，相对应的风险没那么高

**Comment by KevinZjYang** [comment]
或者有没有可能开放自定义的RSS订阅功能，动漫花园这种就可以使用了。找了一圈发现动漫还是都BT才行。。。

**Comment by hongyunfei** [comment]
v2.9.2

考虑到目前项目面临的风险，本版本开始不再提供bt索引及下载相关功能，官方渠道历史版本也已删除。请自行决定是否升级。

**Comment by HBSpy** [comment]
> 我个人是觉得没必要连jackett和prowlarr也删除处理，这两个工具本身就有使用门槛，而且属于外部功能支持，相对应的风险没那么高

同意wyxls的观点，jackett已经做了相当多的统一工作，减少大量重复造轮子工作，软件本身也十分小众，相对花工夫去适配大量PT/BT站点，兼容此类工具的工作量少，风险也小

**Comment by mjilopk520** [comment]
如果都取消了，接来是不是只能PT了，没有其他的资源可以衔接上

**Comment by Earendil-C** [comment]
> 或者有没有可能开放自定义的RSS订阅功能，动漫花园这种就可以使用了。找了一圈发现动漫还是都BT才行。。。

这个一直都可以，在站点维护里面不填cookie，填网址+rss，站点用途选订阅即可

**Comment by XIAOvest** [comment]
以第三方形式不行？

**Comment by sgpublic** [comment]
> 以第三方形式不行？

我觉得开发大大们说的很明确了，官方渠道不会有这些功能了，所以答案显而易见了

**Comment by 91270** [comment]
> > 以第三方形式不行？
> 
> 我觉得开发大大们说的很明确了，官方渠道不会有这些功能了，所以答案显而易见了

所以不内置，以插件形式添加 站点、 或者 jackett 之类的，相对来说更加合理

**Comment by sgpublic** [comment]
> 所以不内置，以插件形式添加 站点、 或者 jackett 之类的，相对来说更加合理

开发大大们应该去意已决了吧，所以想用索引器只能靠第三方开发者了，就像qBittorrent和qBittorrent-Enhanced-Edition的关系那样

**Comment by KevinZjYang** [comment]
都自己去搞PT吧，别把这么好的工具搞没了。我建议后面都不要讨论了。 @zuiyuemuai 把帖子关了把

**Comment by ysrs1977** [comment]
还是用Jellyseerr吧，jackett还可以使用！

**Comment by XIAOvest** [comment]
> > 所以不内置，以插件形式添加 站点、 或者 jackett 之类的，相对来说更加合理
> 
> 开发大大们应该去意已决了吧，所以想用索引器只能靠第三方开发者了，就像qBittorrent和qBittorrent-Enhanced-Edition的关系那样

和开发者说说学习下隔壁啊

**Comment by moxiaoweng** [comment]
最近刚玩就是在纠结是否使用sonarr，没了jackett就麻烦了啊

**Comment by k2y1982** [comment]
只能暂时退回2.9.1了，上面说有些功能丢出来，以插件的方式也不失为一个办法。

**Comment by ysrs1977** [comment]
> 只能暂时退回2.9.1了，上面说有些功能丢出来，以插件的方式也不失为一个办法。

和Jellyseerr一样做个服务器添加模式。

**Comment by XIAOvest** [comment]
> 只能暂时退回2.9.1了，上面说有些功能丢出来，以插件的方式也不失为一个办法。

作者暂时不考虑阿！~

**Comment by XIAOvest** [comment]
![photo_2023-02-13_17-39-19](https://user-images.githubusercontent.com/103026030/218433643-1ea92dc2-f4a9-48f1-92e5-ac97f94011df.jpg)
这种形式也可以，比自己维护Bt站强多了

**Comment by sgpublic** [comment]
> 这种形式也可以，比自己维护Bt站强多了

我看过源码，以我的理解，以目前的架构似乎不太好写（当然开发大大们有更好的方法也是极好的

**Comment by QAQQL** [comment]
这么说吧，舍弃了大部分入门玩家的常用功能，直接投入PT怀抱
虽然看似缩圈合理。。。
在国内开源就没有前途
现在PT吃相也不好看，天天谈奉献，该搜的东西还是搜不到
倒不如直接开放插件生态，省得天天遭人喷
