### ISSUE TITLE
TMDB 搜刮英文支持

### ISSUE THREAD

**Issue by HarborYuan** [NAStool/nas-tools#3494]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.9.2
>
> 环境: docker (linux amd64)

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？

现在的文件转移和搜刮全部使用中文，但这对于英文系统不是特别友好，同时部分电影名不支持中文或中文海报较差。请问是否可以加入TMDB英文支持，对于文件名，nfo简介等全部使用英文。

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

一个可能的实现是把[这一行](https://github.com/NAStool/nas-tools/blob/a74ea574ee5e4c4b67092732b00a29571aba0b2c/app/media/media.py#L160)改成从环境变量中读取。环境变量可以从docker命令传入。

同时请问下[这一行](https://github.com/NAStool/nas-tools/blob/a74ea574ee5e4c4b67092732b00a29571aba0b2c/app/media/tmdbv3api/tmdb.py#L32)会有效果吗？

**Comment by jxxghp** [comment]
目前修改环境变量不会有效果，需要支持配置才行。

**Comment by HarborYuan** [comment]
感谢回复。请问这样修改代码可以实现修改语言的功能吗：

> 一个可能的实现是把[这一行](https://github.com/NAStool/nas-tools/blob/a74ea574ee5e4c4b67092732b00a29571aba0b2c/app/media/media.py#L160)改成从环境变量中读取。环境变量可以从docker命令传入。

**Comment by jxxghp** [comment]
#3494
