### ISSUE TITLE
演员搜刮问题

### ISSUE THREAD

**Issue by Sliversea** [NAStool/nas-tools#3497]
演员搜刮提示豆瓣没有信息，导致emby里面不显示演员的头像。请问有什么解决办法吗？ 没有添加豆瓣的api  用的是TMDB
![image](https://user-images.githubusercontent.com/72388397/218420636-b89e62e4-7aa7-4a7a-a415-e9872f6d3710.png)

**Comment by jxxghp** [comment]
刮削设置里关掉中文演员
