### ISSUE TITLE
NAStool 当前版本号：v2.9.2 索引器问题

### ISSUE THREAD

**Issue by xiaobao1980** [NAStool/nas-tools#3499]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.9.2
>
> 环境: docker 

内置索引器无索引，也不能没有原先的第三方索引器
![WX20230213-210720](https://user-images.githubusercontent.com/47268315/218466385-506291ab-ac1d-4eab-b0e1-386c49893566.png)

**Comment by sp960817** [comment]
手动回退到v2.9.1
