### ISSUE TITLE
只剩下内置索引器

### ISSUE THREAD

**Issue by xx569029747** [NAStool/nas-tools#3500]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.9.2 8c95b74
>
> 环境: docker 

## 你想要新增或者改进什么功能？

> 现在是不支持其他索引器了吗？
![image](https://user-images.githubusercontent.com/12130701/218467154-14ca89a8-302d-4329-82eb-17f949bd1944.png)
而且内建索引器站点是空的
![image](https://user-images.githubusercontent.com/12130701/218467322-f43e5884-6198-4535-9655-5fd7626cdb1f.png)

**Comment by sp960817** [comment]
手动回退到v2.9.1

**Comment by Cytuslcy** [comment]
我也是，希望修复
