### ISSUE TITLE
【BUG】2.9.1及之前版本刷流严重bug，会导致其他保种被删

### ISSUE THREAD

**Issue by Kuro96** [NAStool/nas-tools#3501]
请大家注意，该bug不仅会删除所有该站点（4天以上的）种子，还会同时删除其他站点的保种，关注下图中的【已下载种子数】和【已删除种子数】
![image](https://user-images.githubusercontent.com/2878001/218473439-b3394571-44c4-4945-a846-eab6002c0275.png)

如何复现：
自己手动下载其他所有种子，在刷流任务中如图配置，【使用同一下载器】，添加删种规则【保种时间大于96小时】，四天后自己的种子全部被删

**Comment by PickTimbersaw** [comment]
遇到同样的bug。。。
还好我刚入pt，只被删了transmission里的98个种子，不过也足够头疼了，主要是被nastools删掉的文件并不会进入群晖回收站。
心疼你这种被删1k+的。

**Comment by PickTimbersaw** [comment]
> > 遇到同样的bug。。。 还好我刚入pt，只被删了transmission里的98个种子，不过也足够头疼了，主要是被nastools删掉的文件并不会进入群晖回收站。 心疼你这种被删1k+的。 版本2.9.1
> 
> 还行，还能用iyuu救命，分享给（万一不幸）有需要的人（把iyuu的torrent目录下的cachehash（里面包含了辅种过的种子的下载信息）复制出来，在同级目录使用）：
> 
> ```python
> import os
> import time
> import random
> import requests
> 
> from loguru import logger
> from transmission_rpc import Client
> 
> logger.add('logs/{time}.log')
> # 这里填写自己的transmission相关信息
> client = Client(
>     host: str,
>     port: int,
>     username: str,
>     password: str,
> )
> logger.info('connected to transmission')
> 
> tasks = [x for x in os.listdir('cachehash')]
> random.shuffle(tasks)
> for i, task in enumerate(tasks):
>     print(f'{i}/{len(tasks)}: {task}')
>     if os.path.exists(f'successed/{task}'):
>         logger.info('task already processed, skip...')
>         continue
>     time.sleep(10)
>     print('slept for 10 seconds ...')
>     with open(os.path.join('cachehash', task)) as f:
>         lines = [x for x in f.readlines()]
>     dp = lines[1].strip()
>     url = lines[2].strip()
> 
>     torrent_fp = os.path.join('torrents', task.replace('txt', 'torrent'))
>     if not os.path.exists(torrent_fp):
>         try:
>             resp = requests.get(url)
>         except Exception as e:
>             logger.error(f'failed to add {task}: {e}')
>             continue
>         if resp.status_code != 200:
>             logger.error(f'failed to download {task}')
>             continue
>         torrent = resp.content
>         if len(torrent) < 100:
>             logger.error(f'failed to download {task}')
>             continue
>         with open(torrent_fp, 'wb') as f:
>             f.write(torrent)
>     else:
>         with open(torrent_fp, 'rb') as f:
>             torrent = f.read()
> 
>     try:
>         client.add_torrent(torrent, download_dir=dp, paused=True)
>     except Exception as e:
>         logger.error(f'failed to add {task}: {e}')
>     else:
>         logger.info(f'added {task}')
>         with open(f'successed/{task}', 'w') as f:
>             f.writelines(lines)
> ```
> 
> 不包跑通，需看情况自行修改脚本内容

我是用群晖的备份套件还原到前一天的transmission config，种子列表都回来了，不过大部分文件都懒得再重新下了，就这样吧

**Comment by jxxghp** [comment]
![image](https://user-images.githubusercontent.com/51039935/222872116-6642b8b8-fe9b-4c42-82bc-b51989af5458.jpeg)

**Comment by jxxghp** [comment]
![image](https://user-images.githubusercontent.com/51039935/222872322-1ed54579-c6e8-470f-8951-1f59b9ba2419.png)

**Comment by SilenceEagle** [comment]
https://github.com/NAStool/nas-tools/issues/2506 （`Transmission`重启后会重设种子ID导致刷流任务认为种子不存在）这个原因也会导致`Transmission`错误删种

**Comment by dajiangfu** [comment]
2.9.1的版本谁有吗，可不可以帮忙发一下，可以发到这个邮箱dajiangfu@qq.com,可以附上你的收款二维码，有偿，谢谢！

**Comment by dajiangfu** [comment]
2.9.1的windows版本谁有吗，可不可以帮忙发一下，可以发到这个邮箱[dajiangfu@qq.com](mailto:dajiangfu@qq.com),可以附上你的收款二维码，有偿，谢谢！
