### ISSUE TITLE
建议增加自定义通知模板

### ISSUE THREAD

**Issue by Ice-Cream-MY** [NAStool/nas-tools#3506]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>
> 环境: docker or windows or synology

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？
希望可以自定义通知模板，如自由增删内容介绍，站点信息，大小，tmdb评分等内容
家人使用的话很多电影没有看过并不清楚是什么电影，一下入库很多不知道看什么，希望隐去站点信息
## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by jxxghp** [comment]
感觉不是很有必要
