### ISSUE TITLE
用qb下载器的时候没下载完成nas会识别成一个完成的视频文件，然后会开始自动转移到媒体库，导致播放的时候都是不完整损坏的视频文件，有什么办法让qb下载器下载完成后才变成视频文件不让nastool误识别，或者nastool能不能监控到确定文件下载完成后在开始进行转移。

### ISSUE THREAD

**Issue by PWMFI** [NAStool/nas-tools#3507]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>2.9.0
> 环境: docker or windows or synology
Synology 7
## 你想要新增或者改进什么功能？
用qb下载器的时候没下载完成nas会识别成一个完成的视频文件，然后会开始自动转移到媒体库，导致播放的时候都是不完整损坏的视频文件，有什么办法让qb下载器下载完成后才变成视频文件不让nastool误识别，或者nastool能不能监控到确定文件下载完成后在开始进行转移。
> 你想要新增或者改进什么功能？

## 这个功能有什么可以参考的资料吗？
![FFC87969-5408-403E-AD7F-38163ADA4E02](https://user-images.githubusercontent.com/63692121/218536434-dfdf6730-db68-4c99-a091-9e123b10b549.jpeg)

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by KevinZjYang** [comment]
![image](https://user-images.githubusercontent.com/31529584/218576403-2f0397c7-cae5-4267-a221-f5b31228d72e.png)
