### ISSUE TITLE
plex获取播放历史功能问题

### ISSUE THREAD

**Issue by Sowevo** [NAStool/nas-tools#3509]
https://github.com/NAStool/nas-tools/blob/515d43fd0972c7360baaea4fbfb88469d0b4f2d8/app/mediaserver/client/plex.py#L75-L91
发现目前调用这个接口 `self._plex.library.history(num)` ,只能获得到播放完成的记录
翻了半天没找到Plex有开始播放历史记录的接口

是不是可以通过 webhook功能保存一部分事件到数据库,用于在首页显示

**Comment by jxxghp** [comment]
如果有接口就好了。
有的人很讨厌这个显示，搞太复杂意义不大。
