### ISSUE TITLE
探索相关问题

### ISSUE THREAD

**Issue by git-0101** [NAStool/nas-tools#3511]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.9.2
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 1.即将上映和豆瓣最新电影内容一样
![Screenshot_20230214_085431](https://user-images.githubusercontent.com/115487446/218614289-81307903-2986-4c32-8015-d22b73482ba5.jpg)
![Screenshot_20230214_085512](https://user-images.githubusercontent.com/115487446/218614302-7abaf622-f13d-4adb-bc96-18b2cb725d0f.jpg)
    2.华语口碑剧集榜和全球口碑剧集榜分别只能显示10个剧集。
    3.一个建议：探索下面主标题的电视剧改成剧集
榜单推荐
豆瓣电影
豆瓣剧集
TMDB电影
TMDB剧集
BANGUMI
榜单推荐里面的豆瓣热门电视剧改成豆瓣热门剧集，这样就和其它的几个榜单标题一致了。
    4.题外话：NASTools简单高效，保留最主要的功能挺好，并且已经很完善了。什么都加入显得太庞杂。通知其实几个主流的也够了。

**Comment by jxxghp** [comment]
1.去掉了豆瓣最新
2.豆瓣的api只返回10条。
4.通知消息模块现在基本是配置化的，维护成本倒也还好。

**Comment by git-0101** [comment]
> 1.去掉了豆瓣最新 2.豆瓣的api只返回10条。 4.通知消息模块现在基本是配置化的，维护成本倒也还好。

收到！
