### ISSUE TITLE
内建索引器站点没有了

### ISSUE THREAD

**Issue by kakamatong** [NAStool/nas-tools#3512]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本:  v2.9.2 8c95b74
>
> 环境: docker

## 你想要新增或者改进什么功能？

> bug修复

## 这个功能有什么可以参考的资料吗？

> 无

**Comment by zuoshiyue** [comment]
内建索引器站点没了，并且 没有了Jackett的索引器关联配置
发现Readme的项目说名也变了 似乎发生了什么问题 最后的release也变更成了 项目初始化

**Comment by yukiChow** [comment]
> 

电报群有解释，可以找历史版本

**Comment by zuoshiyue** [comment]
> > 
> 
> 电报群有解释，可以找历史版本

是的 之前没关注电报群信息
