### ISSUE TITLE
增加Plex播放时限速功能

### ISSUE THREAD

**Issue by ihnic** [NAStool/nas-tools#3523]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.9.2
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 望能增加Plex播放限速功能

## 这个功能有什么可以参考的资料吗？

> 参考Nastools的Emby限速

**Comment by jxxghp** [comment]
dev已支持
