### ISSUE TITLE
增加自定义消息推送

### ISSUE THREAD

**Issue by iamckun** [NAStool/nas-tools#3524]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: [v2.9.2 8c95b74](https://github.com/NAStool/nas-tools)
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 增加自定义消息推送的渠道

## 这个功能有什么可以参考的资料吗？

> 青龙消息推送

**Comment by jxxghp** [comment]
已经很多了
