### ISSUE TITLE
订阅集数bug

### ISSUE THREAD

**Issue by seanlees** [NAStool/nas-tools#3528]
版本： 2.9.2
现象：设置了“开始订阅集数”，当前版本会把订阅所有集数全部下载。 以前的版本是没有这个问题的。

![image](https://user-images.githubusercontent.com/2920470/218759795-e76df0fe-1721-4c15-83ab-acce03d9a4fc.png)
![image](https://user-images.githubusercontent.com/2920470/218759856-66654834-f824-4771-8b40-e5aa6a964a08.png)
一直在添加根本止不住， 删了下载器任务继续添加。。。

还有个问题：如何退回到老版本..   希望有知道问题的大佬解救【爱心】

**Comment by seanlees** [comment]
补充：实时日志信息如下：
![image](https://user-images.githubusercontent.com/2920470/218761068-0e37c471-9c42-448b-b10e-92f9d5143028.png)

**Comment by seanlees** [comment]
补充：并不是应该是从285集开始吗，怎么变成了总共285集 .. 
![image](https://user-images.githubusercontent.com/2920470/218763539-5883c088-0c29-4324-9c93-f7c969c8483e.png)

**Comment by thsrite** [comment]
…tmdb记录总共285集，肯定总集数285啊

**Comment by seanlees** [comment]
> …tmdb记录总共285集，肯定总集数285啊

其实总集数并不是285集，还在一直更新中。
![image](https://user-images.githubusercontent.com/2920470/219532612-9cc4f1dc-8886-495f-9251-2edd28c5c144.png)

看了下tmdb的信息，确实是285,但是状态还是回归状态并没有完结。 tmdb信息上传者上传的信息可能有误
![image](https://user-images.githubusercontent.com/2920470/219533155-0ea2a146-7003-4508-ae26-506c10036014.png)
是否可以根据tmdb状态判断订阅是否完成？ 订阅达到tmdb总集数，但是tmdb状态为未完结，向前再搜索几集？ （不知道之前的订阅逻辑哈）

**Comment by jxxghp** [comment]
这个应该修复了
