### ISSUE TITLE
更新v2.9.2 8c95b74后只剩下内建索引器

### ISSUE THREAD

**Issue by leonedit** [NAStool/nas-tools#3532]
v2.9.2 8c95b74只剩下内建索引器了，Jackett之类的都不见了

**Comment by SheepChao** [comment]
内建索引器还搜索不到资源。

**Comment by hahawolaile** [comment]
jaclett 赶快回来啊

**Comment by rabbitlhf** [comment]
我也是，能回退版本么？

**Comment by hahawolaile** [comment]
sungamma还有老版本可下，我去试试退回

**Comment by hahawolaile** [comment]
sungamma/nas-tools  去下载2.9.0  直接用之前的config文件  变量关闭更新，可以用索引，快冲

**Comment by seanshangwenguang** [comment]
> sungamma/nas-tools 去下载2.9.0 直接用之前的config文件 变量关闭更新，可以用索引，快冲

2.9.1版本不行吗？

**Comment by shan-guo** [comment]
> > sungamma/nas-tools 去下载2.9.0 直接用之前的config文件 变量关闭更新，可以用索引，快冲
> 
> 2.9.1版本不行吗？

可以的，我目前就是 2.9.1

**Comment by Passerby1011** [comment]
能给个文件吗？项目没了

**Comment by Passerby1011** [comment]
> > > sungamma/nas-tools 去下载2.9.0 直接用之前的config文件 变量关闭更新，可以用索引，快冲
> > 
> > 
> > 2.9.1版本不行吗？
> 
> 可以的，我目前就是 2.9.1

大哥知道docke怎么版吗？

**Comment by Passerby1011** [comment]
> > > sungamma/nas-tools 去下载2.9.0 直接用之前的config文件 变量关闭更新，可以用索引，快冲
> > 
> > 
> > 2.9.1版本不行吗？
> 
> 可以的，我目前就是 2.9.1
大哥知道docker怎么办吗？

**Comment by leonedit** [comment]
我就是手快重启了docker的镜像，然后就自动更新了，然后……就没有然后了

**Comment by HankunYu** [comment]
群辉矿神最新版本还是2.9.1

**Comment by netduke777** [comment]
才发现，为啥？我是自动更新的

**Comment by Passerby1011** [comment]
都是，能替换文件吗？有人知道吗？

**Comment by BOBO2456** [comment]
好惨，我也手贱升级了，然后索引器就报废了，哎！！！！！

**Comment by stevenjue** [comment]
我安装旧版本之后，打开依然是2.9.2，第1天尝试使用，就遇到了这个问题。

**Comment by Passerby1011** [comment]
把自动更新关了

**Comment by Diluka** [comment]
> 我就是手快重启了docker的镜像，然后就自动更新了，然后……就没有然后了

查看这个仓库的fork，有人专门fork了2.9.1，自己也去fork一份。后续操作就有点复杂了，解释起来太麻烦，自行领悟吧。提示一下，可以ash到容器里面操作，也可以改Dockerfile自己用actions构建一个镜像，或者还有其他的什么方法。

**Comment by ysrs1977** [comment]
我还好1月24日做了个备份

**Comment by hahawolaile** [comment]
> 才发现，为啥？我是自动更新的

变量里 两个 update 的 改成false

**Comment by ysrs1977** [comment]
-e NASTOOL_AUTO_UPDATE=false `# 如需在启动容器时自动升级程程序请设置为true` \

**Comment by ysrs1977** [comment]
NASTOOL_AUTO_UPDATE=false 我是都改成false 不改会升级到2.9.2

**Comment by Tardisyuan** [comment]
docker镜像没有更新的话 把容器删掉 同样配置创建一下就好了

**Comment by hzmabin** [comment]
那不是今后都不能更新了？ 失去了灵魂

**Comment by Diluka** [comment]
> 那不是今后都不能更新了？ 失去了灵魂

那不一定，我看现在的代码正在新增插件功能，目测是打算将风险功能从主项目中移除，将下载行为变为用户的个人行为

**Comment by hzmabin** [comment]
求windows版，hzmabin@qq.com，谢谢啦

**Comment by linjhon** [comment]
我看 docker 有个变量是 REPO_URL ，应该是可以改成其他fork 的仓库升级吧

**Comment by Passerby1011** [comment]
> 我看 docker 有个变量是 REPO_URL ，应该是可以改成其他fork 的仓库升级吧

其实重新添加一下就行了，有2.9.1的三方复制的镜像

**Comment by Passerby1011** [comment]
> > 那不是今后都不能更新了？ 失去了灵魂
> 
> 那不一定，我看现在的代码正在新增插件功能，目测是打算将风险功能从主项目中移除，将下载行为变为用户的个人行为

这个项目的灵魂就是自动下载刮削，下载时不能少的，主项目做不了，那只能是以插件形式“三方”来做，主项目提供接口，好多这类有风险的项目都是这么干的

**Comment by hzmabin** [comment]
。。。
