### ISSUE TITLE
请求支持站点海胆

### ISSUE THREAD

**Issue by lingyizhuzhu** [NAStool/nas-tools#3533]
## 你使用的 NAStool 是什么版本，什么环境？
NAStool 版本: v2.9.2
环境:  synology的docker

## 你想要新增或者改进什么功能？
请求增加对PT站点海胆的支持 地址为：https://www.haidan.video

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by jxxghp** [comment]
海胆被魔改了，这个真支持不了。
