### ISSUE TITLE
仓库的历史Actions没有清空，里面还是能下载到2.9.1 win的exe文件

### ISSUE THREAD

**Issue by AndyWangM** [NAStool/nas-tools#3536]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>
> 环境: docker or windows or synology

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.
https://github.com/NAStool/nas-tools/actions/workflows/build-windows.yml
![image](https://user-images.githubusercontent.com/22785822/218955015-617a2778-d40b-4be3-a13a-e55a17d2777b.png)

**Comment by wcyws** [comment]
感谢提醒，已备份

**Comment by jxxghp** [comment]
也感谢提醒，这就去删。。。

**Comment by mrwbbs** [comment]
> 感谢提醒，已备份

是否能提供一下备份
