### ISSUE TITLE
申请支持站点OshenPT

### ISSUE THREAD

**Issue by 507039975** [NAStool/nas-tools#3540]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.9.2
>
> 环境: docker

## 你想要新增或者改进什么功能？

申请支持站点OshenPT

> 你想要新增或者改进什么功能？

## 这个功能有什么可以参考的资料吗？

链接https://www.oshen.win/

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by wcc961129** [comment]
同请求支持站点

**Comment by jxxghp** [comment]
发现这个站公开注册了，已支持。
