### ISSUE TITLE
themoviedb在微信中被禁访问

### ISSUE THREAD

**Issue by pfqckl** [NAStool/nas-tools#3541]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>
> 环境: docker or windows or synology

## 你想要新增或者改进什么功能？

> themoviedb在微信中被禁访问，搜索结果出来后想点击进去看看是不是自己找的电影，结果被禁止了打不开，能不能换成豆瓣，用TG的应该是正常的，那么能在后台加一个自己选择的选项吗？

## 这个功能有什么可以参考的资料吗？

> 
![111](https://user-images.githubusercontent.com/45281646/219030834-1545cd82-5b0a-411f-a302-309f5c96ae9d.png)
![dddd](https://user-images.githubusercontent.com/45281646/219031028-2c1e7a1e-d6a6-4aa0-8b47-f1679702d541.png)

**Comment by jxxghp** [comment]
实验室选择使用豆瓣名字联想
