### ISSUE TITLE
Windows版本网络连接问题

### ISSUE THREAD

**Issue by JoyInk** [NAStool/nas-tools#3542]
启动服务后（使用最新版或上一版）
localhost:3000  可访问
127.0.0.1:3000  访问被拒绝
192.168.1.86:3000  访问被拒绝
通过ddns解析ipv6的域名:3000  可访问
查询Windows中的端口确实存在nas-tool

**Comment by AisukaYuki** [comment]
windows版本，做不到同时监听v4+v6.,配置默认监听 ipv6.
localhost本地是同时匹配了 v4 v6访问的，所以你能打开。
监听 :: 改 0.0.0.0. 这样就能ipv4访问了。但是如果你ipv4没有公网，建议你保持默认，从ipv6访问。

**Comment by jxxghp** [comment]
下个版本改成默认0.0.0.0
