### ISSUE TITLE
新增功能：电视剧单集洗版

### ISSUE THREAD

**Issue by 120318** [NAStool/nas-tools#3543]
## 你使用的 NAStool 是什么版本，什么环境？
 NAStool 版本: dev
 环境: docker 
## 你想要新增或者改进什么功能？
当前 RSS 订阅的电视剧的洗版选项只能洗版整季的剧集，但是实际上存在一种这样的场景：当追某部剧的时候，设定好按质量排序的过滤规则，进行 RSS 订阅，此时希望：在看最新的更新之前，能够尽可能下到最高质量的集。高质量 的集可以按集覆盖之前的版本。

## 这个功能有什么可以参考的资料吗？
暂无

**Comment by jxxghp** [comment]
按集洗版比较复杂，要记录每一集的洗版状态，而且可能会导致各集质量参差不齐。
