### ISSUE TITLE
自定义订阅-RSS订阅-海贼王反复报错

### ISSUE THREAD

**Issue by xnoods** [NAStool/nas-tools#3546]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.9.2 8c95b74
>
> 环境: synology下的docker

> 使用订阅管理-自定义订阅，我订阅了海贼王的动漫，发现订阅日志中反复报错，希望大佬能看下是什么问题，目前我看报错日志中的ip是我的plex的ip地址，测试媒体服务器联通性是可以连接的
![image](https://user-images.githubusercontent.com/18209713/219231524-b99eebc9-9371-47ef-b1f7-853082f5c2ac.png)
> 集数缺失也很奇怪，明明库里有很多集了，这里显示还是几乎没有
![image](https://user-images.githubusercontent.com/18209713/219232035-2de3fb05-e1b6-4b10-8626-97fc9c1b61e2.png)

![image](https://user-images.githubusercontent.com/18209713/219232423-53ecee82-2231-4fb4-83bf-a0757a00fd59.png)

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by jxxghp** [comment]
这个是plex返回了500报错页面

**Comment by fanszoro** [comment]
求教，你是怎么配的过滤规则啊？海贼王好难搞，啊啊啊啊
