### ISSUE TITLE
榜单时不时加载不出

### ISSUE THREAD

**Issue by aiwu12** [NAStool/nas-tools#3549]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.9.1
>
> 环境: docker synology

## 你想要新增或者改进什么功能？
新2.9.2也会出现，测试连通性OK
![image](https://user-images.githubusercontent.com/61082200/219273314-2d6993c2-fd4b-4e73-b252-ab86170b723e.png)

![image](https://user-images.githubusercontent.com/61082200/219273050-2ae6c10b-fc0d-4177-85bb-ff4036ba0819.png)
重启或者停止容器重置容器，就能加载出来
![image](https://user-images.githubusercontent.com/61082200/219273141-39afb6a3-699e-4531-bf95-e4385222e716.png)

> 你想要新增或者改进什么功能？

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by jxxghp** [comment]
图片是ie浏览器直连加载的，有可能是电脑与themoviedb的连接性不好
