### ISSUE TITLE
Nastools docker版 无法访问 占用极大   bug

### ISSUE THREAD

**Issue by Crazy-FuQing** [NAStool/nas-tools#3553]
最近nastools自动升级到v2.9.2 后就无法访问了   查看日志发现升级后的版本可能依赖pikpakapi模块，xvfb进程反复重启，占用极大，甚至docker进程都卡死掉了，无法停止或重启

https://www.cnblogs.com/yujin2020/p/17127001.html

**Comment by c939984606** [comment]
既然是docker删除重新拉镜像安装，配置也都在，就没问题了

**Comment by Crazy-FuQing** [comment]
> 

我用的是程序内的自动升级

**Comment by luoxiao-xy** [comment]
我这还好，占用很少。建议删除容器，重新部署

**Comment by jxxghp** [comment]
这个模块的引入导致依赖冲突。重新拉镜像就不会有这个问题。
