### ISSUE TITLE
套件版nastool卡死

### ISSUE THREAD

**Issue by Venompool888** [NAStool/nas-tools#3559]
https://wwxa.lanzouy.com/iSDUU0nsni1e
这里是我的nastool日志，因为lanzou的格式限制后缀改成了txt

不知为何nastool在启动了一段时间后会出现网页无法访问的情况，需要nastool重启过后才能再次正常使用
![Screenshot_20230216_232421.jpg](https://user-images.githubusercontent.com/94547252/219410320-6d1d7bda-20d6-4c40-99a9-88b4adc8e133.jpg)

根据日志最后将内容，是nastool在检索我的订阅剧集的时候出现了问题，前几次出现无法访问nastool的情况时日志也是止步于此

**Comment by jxxghp** [comment]
套件版无法分析。有可能是在偿试调起浏览器导致的。
不要选ext这个站，最新版也没这个了。
