### ISSUE TITLE
手动识别电视剧Bug

### ISSUE THREAD

**Issue by 15316559235** [NAStool/nas-tools#3560]
电视剧设置了多个同步目录，在手动识别时，可以正常识别电视剧，日志也会显示转移成功，但是所有电视剧同步目录下都没有文件。在手动指定目的目录后，视频文件顺利转移且被重命名，但是没有生成对应的nfo，图片等。目录同步不会出现此问题，电影和动漫的手动转移不会出现此问题。可能是因为电视剧设置了多个同步目录。

版本：2.9.2

**Comment by 15316559235** [comment]
环境：docker

**Comment by jxxghp** [comment]
跟你说的没关系的，你要看日志，贴日志，不然别人也帮不到你。
