### ISSUE TITLE
【bug】刷流设置总大小失效

### ISSUE THREAD

**Issue by seanlees** [NAStool/nas-tools#3565]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.9.2
>
> 环境: docker
>

## 你遇到什么问题了？

> 更新到2.9.2之后，发现刷流里设置的刷流总体积失效了。。 之前在2.8.2下测试过达到体积后就停止添加新任务了更新新版后一直下载，只要下载器不排队就一直添加，不会限制刷流总体积了。

## 你期望的结果

> 刷流体积达到预设附近左右时，停止添加新的刷流任务。

## 程序界面截图、后台运行日志或配置文件
设置如下：
![image](https://user-images.githubusercontent.com/2920470/219535184-5c0efa63-a002-4afe-9309-6ad95667905f.png)

下载器中任务如下图，已经超过了预设很多，个人理解最大下载体积应该是： 65+30 = 95G 左右：
（最近没有在该站手动下载，截图中都是刷流器下载的）
![image](https://user-images.githubusercontent.com/2920470/219535375-43c55f2c-e99a-4b23-b604-e30b847dd2a7.png)

**Comment by jxxghp** [comment]
3.0.0之前的版本不支持也没办法分析了，升级一下吧
