### ISSUE TITLE
为了养老金去异世界存八万金 这部动漫无法订阅 搜索不到

### ISSUE THREAD

**Issue by jxdqwer** [NAStool/nas-tools#3570]
这部动漫无法订阅，也搜索不到，实际猫和柠檬都是有的，第一次遇到这个情况。

**Comment by lucaszhang99** [comment]
自己检查一下Log以及版本

**Comment by misaka19002** [comment]
可能是关键词的匹配的问题，看下自己的log识别出的关键词是什么。配置一下就好了。可以参考一下我的配置
![image](https://user-images.githubusercontent.com/14154704/221728081-2e6ea405-d128-488e-b5c6-3ed0b6f25728.png)
