### ISSUE TITLE
升级v 3.0后碰到的bug

### ISSUE THREAD

**Issue by madswaord** [NAStool/nas-tools#3587]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.0
>
> 环境: docker
>

1. 每次docker重启进入nt必须再进行一次认证否则无法使用 
2. 重启docker后 基础设置-媒体-默认文件转移方式 会变成复制，需手动更改设置

**Comment by thsrite** [comment]
1.目前设计如此
2.删除镜像重新拉取

**Comment by madswaord** [comment]
> 1.目前设计如此
> 
> 2.删除镜像重新拉取

1 是否可以参考iyuu一次认证之后无需重复认证站点，考虑到有的nas有计划重启的习惯
