### ISSUE TITLE
3.0版本自定义订阅下载器有问题

### ISSUE THREAD

**Issue by edhnt455** [NAStool/nas-tools#3595]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.0
>
> 环境: docker or windows or Synology
>

## 你遇到什么问题了？

> 描述一下你遇到的问题

新增了一个qb下载器，目前是1个tr,2个qb，但是在自定义订阅中无法选择，下拉菜单还是上个版本的下载器选项

## 你期望的结果

> 描述以下你期望的结果
解决问题

> 如UI BUG请提供截图及配置文件截图
![image](https://user-images.githubusercontent.com/59108157/221889430-87f708a1-8444-4698-8205-bdb4addf1257.png)
![image](https://user-images.githubusercontent.com/59108157/221889457-5a561d81-9f22-4d10-bbd1-dbdb7d8c8a69.png)

**Comment by Juhraya** [comment]
我升级完以后连订阅的功能都没了

**Comment by Shurelol** [comment]
这是下载设置，不是下载器
