### ISSUE TITLE
功能缺失

### ISSUE THREAD

**Issue by DWLtime** [NAStool/nas-tools#3598]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本：3.0
>
> 环境: docker
>

## 你遇到什么问题了？

> 左侧列表目录缺少了很多功能，以及无法搜索，页面搜索为只读。没有qb等下载功能或插件，也无法订阅

##是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已浏览并搜索

## 你期望的结果

> 解决问题

##给出程序界面截图、后台运行日志或配置文件

![image](https://user-images.githubusercontent.com/51859383/221968698-1d265f14-6b59-4b85-b783-cd47b8e37636.png)
![image](https://user-images.githubusercontent.com/51859383/221968724-5cab14e1-d333-4abd-bdd4-59d54e3a87b7.png)
![image](https://user-images.githubusercontent.com/51859383/221969027-7de663ac-577d-49af-8a3d-0e1e58b48986.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by pxbiuibiu** [comment]
但凡你看一下更新说明……都不会问这问题了

**Comment by DWLtime** [comment]
看更新说是更新了插件……可是插件里只有上面5个，没其他的了。

**Comment by accors** [comment]
左下角不是有站点验证？你看了更新日志没看注意部分吗。。

**Comment by huluohu** [comment]
> 看更新说是更新了插件……可是插件里只有上面5个，没其他的了。

<img width="826" alt="image" src="https://user-images.githubusercontent.com/7138642/222040792-3238840e-c830-4896-82c2-0715b2bd0657.png">

**Comment by vpjacob** [comment]
同样问题

**Comment by vpjacob** [comment]
• 新增插件系统，部分功能移植至插件，新增了一些插件。
• 支持同时配置使用多个下载器。
• 搜索栏支持搜索人物。
• 媒体库同步支持选择媒体库范围。
• 播放限速插件支持Emby/Jellyfin/Plex，支持多下载器。
• Docker版本增加了Redis缓存，减少站点搜索访问次数。
• 其它功能细节优化以及修复了部分问题。

注意：
1、由于下载器使用逻辑调整，刷流任务与自动删种任务需要重新维护才能正常使用，存量任务将自动暂停。
2、基于一些因素考虑，目前需要完成用户认证才能打开全量功能（认证站点陆续增加中）。
3、由于中间存在断层，建议重新拉取最新镜像使用，升级前版本过旧的建议重新配置。


看起来像是，需要认证，才可以使用全量功能

**Comment by vpjacob** [comment]
19970688/nastools-bt

可以用这个image

**Comment by love5461** [comment]
> 19970688/nastools-bt

用完事一直转圈圈怎么解决？

**Comment by 1320414964** [comment]
> > 19970688/nastools-bt
> 
> 用完事一直转圈圈怎么解决？

我也是用这个镜像的话，用默认账号登陆之后就一直转圈圈，看日志是说进入debug模式了，不知道怎么回事
