### ISSUE TITLE
希望能够添加支持馒头站用户认证的功能

### ISSUE THREAD

**Issue by SugarmanZhu** [NAStool/nas-tools#3603]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.0
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 希望能够添加支持馒头站用户认证的功能。

## 这个功能有什么可以参考的资料吗？

> https://kp.m-team.cc/

**Comment by bit649** [comment]
这个得要自己想办法绕过cloudflare吧

**Comment by 0xZzOrz** [comment]
> 这个得要自己想办法绕过cloudflare吧

FlareSolverr

**Comment by huifan** [comment]
希望增加btschool/hdmayi/hdtime/ptt等任意一个站的支持

**Comment by jxxghp** [comment]
#3612
