### ISSUE TITLE
文件转移重复执行

### ISSUE THREAD

**Issue by yellowstrong** [NAStool/nas-tools#3607]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.0

> 环境: docker 

> 当前版本下载器里面的监控跟服务里的下载文件转移两个功能冲突了 开启下载器的监控功能后种子下载完成后会直接进行自动转移，服务里的下载文件转移还是依旧会按照5分钟定时运行，造成了二次转移失败，但是不影响使用，而且如果把下载器的监控功能关掉以后，服务中的下载文件转移也将无法运行，下方不显示5分钟

> 希望能够修成这两个转移任务冲突，只保留一个，以免造成重复转移错误

<img width="900" alt="image" src="https://user-images.githubusercontent.com/34505611/222038048-019ffb53-d90d-4733-bf17-800748882222.png">

**Comment by Shurelol** [comment]
监控就是以前的下载文件转移
