### ISSUE TITLE
每次升级都要求重新认证

### ISSUE THREAD

**Issue by huluohu** [NAStool/nas-tools#3608]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.0
>
> 环境: docker
>

## 你遇到什么问题了？

> 1、每次升级后都要重新认证，过于麻烦
> 2、认证时貌似不走设置的代理，有时会因为墙的原因无法正常完成认证

## 你期望的结果

> 1、能否认证一次后，升级就不用再认证了
> 2、建议有设置代理的时候走代理

**Comment by jxxghp** [comment]
这个已经修复了
