### ISSUE TITLE
未来能接入小爱同学不？

### ISSUE THREAD

**Issue by Arly521** [NAStool/nas-tools#3609]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.0
>
> 环境: docker 

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？
消息直接推送到小爱同学，可以选择性播报一些内容。
当然最想实现的是可以语音下载。比如：小爱同学，给我下一部叫XXXX的电影。小爱同学，订阅XXXX电视剧

## 这个功能有什么可以参考的资料吗？
小米小爱开放平台：https://developers.xiaoai.mi.com/skill/create/index
我不会编程，只是想着这样可能更方便一些。可能有点想太多。大佬如果觉得不行就一笑了之。
毕竟用爱发电已经很好了。不要增加过多的工作量。
> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by luoban** [comment]
非作者，只是对小爱有一定经验的路人回答：
理论上是可以的，但是需要假设公网服务器来接受小爱训练的指令。分两种情况
1. 如果你自己有能力接入小爱训练计划能力，可以自己接入并调用nastool的api去控制订阅就行了。这种情况需要个人具有一定的开发能力，也需要有自有的服务器。
2. 如果你指望作者接入小爱，那么作者需要增加对接服务器，需要作者学习并了解小爱接入方式。而且将nastool接入小爱授权，那么需要nastool建立完善的账户体系。这种情况只会给作者增加不必要的成本。
另外：小爱的媒资库可能无法满足你的请求，存在无法准确识别文字。
综上：难度太大，成本太高，投入产出比非常低。
最后：下载电影订阅啥的，不都是提前订阅吗？我都是提前大半年就把想看的电影和电视剧订阅了，或者隔一段时间点一下，也没啥不方便的。

**Comment by Arly521** [comment]
> 非作者，只是对小爱有一定经验的路人回答： 理论上是可以的，但是需要假设公网服务器来接受小爱训练的指令。分两种情况
> 
> 1. 如果你自己有能力接入小爱训练计划能力，可以自己接入并调用nastool的api去控制订阅就行了。这种情况需要个人具有一定的开发能力，也需要有自有的服务器。
> 2. 如果你指望作者接入小爱，那么作者需要增加对接服务器，需要作者学习并了解小爱接入方式。而且将nastool接入小爱授权，那么需要nastool建立完善的账户体系。这种情况只会给作者增加不必要的成本。
>    另外：小爱的媒资库可能无法满足你的请求，存在无法准确识别文字。
>    综上：难度太大，成本太高，投入产出比非常低。
>    最后：下载电影订阅啥的，不都是提前订阅吗？我都是提前大半年就把想看的电影和电视剧订阅了，或者隔一段时间点一下，也没啥不方便的。

是个想法。没想到这么麻烦啊。而且还要架设服务器。能不能曲线救国对接home assistant里面。实现个通知的功能。

**Comment by jxxghp** [comment]
现在NT有Webhook功能，所有事件都可以向第三方发送请求，可以自己写个程序接收报文，解析然后转发到小爱同学。
不过我没想明白这是啥应用场景，有通知了让小爱喊出来是不是有点尴尬。

**Comment by jxxghp** [comment]
如果只是通知类的场景，这个NT有Webhook功能，所有事件都可以向第三方发送请求，可以自己写个程序解析报文然后转发到小爱，但是这个应用场景有点尴尬。

如果是语音订阅之类的，如楼上，应该是要统一的服务器中转的，而且得不米放开接口。
