### ISSUE TITLE
增加集数识别方案

### ISSUE THREAD

**Issue by naoki66** [NAStool/nas-tools#3610]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
[v3.0.0 d01f8a3](https://github.com/NAStool/nas-tools)

> 环境: docker or windows or synology
 docker in 
synology
## 你想要新增或者改进什么功能？

部分纪录片命名方案，NASTOOLS无法识别和定位{ep}
[BBC.A.History.of.Christianity.1of6.The.First.Christianity.HDTV.x264.AC3.MVGroup.org.mkv]
例如这个，前面的剧名，集数是  第n集 of 总集数 ，剧集名称。
使用关键词  BBC.A.History.of.Christianity.{ep}of6，依旧无法定位集数。

emby直接搜刮是按show name SXXEXX Episode Name，也能识别，但是NASTOOLS无法识别也就无法转移。

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.
BBC.A.History.of.Christianity.1of6.The.First.Christianity.HDTV.x264.AC3.MVGroup.org.mkv
BBC.A.History.of.Christianity.2of6.Catholicism.The.Unpredictable.Rise.of.Rome.HDTV.x264.AC3.MVGroup.org
BBC.A.History.of.Christianity.3of6.Orthodoxy.From.Empire.To.Empire.HDTV.x264.AC3.MVGroup.org
BBC.A.History.of.Christianity.4of6.Reformation.The.Individual.Before.God.HDTV.x264.AC3.MVGroup.org
BBC.A.History.of.Christianity.5of6.Protestantism.The.Evangelical.Explosion.HDTV.x264.AC3.MVGroup.org
BBC.A.History.of.Christianity.6of6.God.In.The.Dock.HDTV.x264.AC3.MVGroup.org.mkv

**Comment by Shurelol** [comment]
建议看看？里的说明
