### ISSUE TITLE
不玩pt的是不是就用不了nastool

### ISSUE THREAD

**Issue by BearHero520** [NAStool/nas-tools#3611]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本:3.0
>3.0
> 环境: docker or windows or Synology
> Synology

## 你遇到什么问题了？

> 没有那些pt 站，连认证的过不了,

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是
> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果
喜欢2.9.1版本的内置索引器，不玩pt,现在连认证都过不了，我就想简单的找个电影看。。。

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by laotycoon** [comment]
一样的问题~现在基本无用了。

**Comment by Shurelol** [comment]
是的

**Comment by BearHero520** [comment]
> 是的

唉，难过

**Comment by liweijun21** [comment]
退出舞台给了高端玩家了
