### ISSUE TITLE
希望增加一些大站的认证啊

### ISSUE THREAD

**Issue by wuabuhuan** [NAStool/nas-tools#3612]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.0
>
> 环境: docker
>

## 你遇到什么问题了？

认证

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

是

## 你期望的结果

希望增加一些大站的认证啊，馒头、天空之类的呀

**Comment by jxxghp** [comment]
得看站点愿不愿意，不是单方面决定的

**Comment by xx791117** [comment]
馒头馒头馒头

**Comment by SugarmanZhu** [comment]
@xx791117 馒头Elite User区有人发药

**Comment by xingyue19820805** [comment]
我只有hdsky 的帐号不知道什么时候能认证上

**Comment by SugarmanZhu** [comment]
> @jxxghp 目前有 10 来个站，但目前都不在里面。想问下，一个站认证成功后就可以添加任意 PT 站了吗?

对的 跟之前版本一样

**Comment by xuanyuanhuo** [comment]
感觉都是新站，一个都没有

**Comment by yongman** [comment]
试了一下，IYUU 认证还是很方便的。

**Comment by skywolf123** [comment]
我用IYUU认证不通过

**Comment by Wooo0** [comment]
可以增加馒头的认证么

**Comment by skywolf123** [comment]
> 试了一下，IYUU 认证还是很方便的。

你用IYUU认证过了吗？我的提示：非法请求：用户未绑定合作站点账号！请查阅绑定！

**Comment by skywolf123** [comment]
> 试了一下，IYUU 认证还是很方便的。

你用IYUU认证过了吗？我认证失败，提示：非法请求：用户未绑定合作站点账号！请查阅绑定！

**Comment by thsrite** [comment]
> > 试了一下，IYUU 认证还是很方便的。
> 
> 你用IYUU认证过了吗？我认证失败，提示：非法请求：用户未绑定合作站点账号！请查阅绑定！

docker iyuu 用iyuu的合作站点认证之后 nt才能用

**Comment by caesarli** [comment]
> 得看站点愿不愿意，不是单方面决定的

真的很感谢各位开发这套工具， 确实方便了许多，但升级了3.0.x后现在的认证方式太单一了，造成无法认证也就无法使用nastool， 

为什么非要用合作网站的秘钥来验证呢？ 

既然自动签到其他PT网站都可以用cookie的信息完成， 为啥不能简单加入一些热门的PT网站然后用COOKIE的信息去认证呢？  M-Team，  PTSchool 这些热门的PT不支持的话 那nastool注定要变成小众中的小众才能使用的产品了。。。。。。 好可惜。。。。。。

**Comment by SugarmanZhu** [comment]
> 为什么非要用合作网站的秘钥来验证呢？

> 既然自动签到其他PT网站都可以用cookie的信息完成， 为啥不能简单加入一些热门的PT网站然后用COOKIE的信息去认证呢？

你要是想支持Cookie认证的话 为什么不搞个PR呢

与其等cookie认证不如直接搞个支持站点的药

**Comment by yongman** [comment]
> 还不如把项目撤了，老实说怕就别搞了，PT你都支持了，要搞你还有什么不能搞你的。

@penwong 
1. 不好用你可以不用。
2. 为了减少非忠实用户可能带来的风险，采取一些提高使用门槛的措施很有必要。
3. 有建议可以提，但不要 pua。

再次感谢作者@jxxghp 付出，开源出大幅提升幸福感的工具。

**Comment by penwong** [comment]
这就pua了，哈哈哈哈。

yongman ***@***.***> 于2023年3月8日周三 23:56写道：

**Comment by Benson80** [comment]
Docker进去界面不一样，原来还需要用户认证！

**Comment by laplaceyang** [comment]
吃相真的好难看

**Comment by zsedc800** [comment]
看来应该fork一份了，完全没有注册过pt

**Comment by zsedc800** [comment]
<img width="242" alt="image" src="https://user-images.githubusercontent.com/17945767/225556345-82938316-ccf4-4b8b-a3ce-fe8d4c1e20b3.png">
user模块故意做成so文件了，menu信息估计都在里面，看来3.x版本应该是打算商业化或者圈子专属了。老老实实找份2.x的去用了。有空，反编译一下看看

**Comment by jxxghp** [comment]
> 吃相真的好难看

收你钱了吗？不问缘由无脑喷？

**Comment by hijakke** [comment]
> 得看站点愿不愿意，不是单方面决定的

有个疑问，为什么不能用COOKIE认证，一定要用API，这样不就不需要站点支持了吗？

**Comment by jxxghp** [comment]
> > 得看站点愿不愿意，不是单方面决定的
> 
> 有个疑问，为什么不能用COOKIE认证，一定要用API，这样不就不需要站点支持了吗？

主要就是要控制用户规模，将来可能会放开，但现阶段还不行。之前被200万的大V宣传，要不是反应快可能已经凉透了。

**Comment by jxxghp** [comment]
IYUU也是这种方式，还是稳一定吧，要不然大家都玩不了。

**Comment by sunr1s6** [comment]
PT的宗旨就是 免费分享， 现在提高门栏，让进了圈的收门票费 真是恶臭。

**Comment by Wenjungang** [comment]
> 

并没有。也有很多pt用户无偿，没有高要求的邀请遇到的小伙伴加入nastool使用的。比如我已经邀请10多个人了。不要光抱怨，去了解，去沟通，才能解决你的问题。

**Comment by diobachio** [comment]
> PT的宗旨就是 免费分享， 现在提高门栏，让进了圈的收门票费 真是恶臭。

有卖药的去举报啊,提高点门槛就是收门票费?要免费去用bt 阿里云什么的嘛,又没人强迫你混pt
