### ISSUE TITLE
关于NASTOOL五个小小的建议，希望大佬能够采纳，万分感谢

### ISSUE THREAD

**Issue by yangke098** [NAStool/nas-tools#3613]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 3.0
>
> 环境: docker for synology

## 你想要新增或者改进什么功能？

> 1.希望刷流功能回归后，可以参考vertex增加删种功能的拓展性
      比如，增加平均下载速度<50kb和上传速度>20MB同时满足的条件就删种（VT俗称黑车）
      再比如，有HR的站点，可以在完成进度达到50%自动限流，70%自动删种的功能
   2.刷流希望增加一个自动汇报时间，参考vt，自由设置汇报时间，不然靠QB 自己的汇报，会少很多流量
   3.小小的一个建议，希望把以前BT的功能做成PT类似的手动添加BT网站，既可以满足用户需求，也可以合理解决责任性问题，你只是开放接口，不负责提供渠道。
   4.希望增加豆瓣挂削功能，可以参考jellyfin的豆瓣插件，国内的电影，电视剧，豆瓣会比tmdb支持好一点，主要是人物列表是中文，tmdb只有英文。
   5.希望和iyuu一样不用每次更新都认证一次，谢谢
如果以上建议能采纳，将万分感谢
## 这个功能有什么可以参考的资料吗？

> VERTEX

**Comment by yangke098** [comment]
是否可以调用站点维护里面已经录入站点的信息自动进行认证。

**Comment by yangke098** [comment]
> ## 你使用的 NAStool 是什么版本，什么环境？
> > NAStool 版本: 3.0
> > 环境: docker for synology
> 
> ## 你想要新增或者改进什么功能？
> > 1.希望刷流功能回归后，可以参考vertex增加删种功能的拓展性
> > 比如，增加平均下载速度<50kb和上传速度>20MB同时满足的条件就删种（VT俗称黑车）
      再比如，完成进度达到50%自动限速，70%自动删种
> > 2.刷流希望增加一个自动汇报时间，参考vt，自由设置汇报时间，不然靠QB 自己的汇报，会少很多流量
> > 3.小小的一个建议，希望把以前BT的功能做成PT类似的手动添加BT网站，既可以满足用户需求，也可以合理解决责任性问题，你只是开放接口，不负责提供渠道。
> > 4.希望增加豆瓣挂削功能，可以参考jellyfin的豆瓣插件，国内的电影，电视剧，豆瓣会比tmdb支持好一点，主要是人物列表是中文，tmdb只有英文。
> > 5.希望和iyuu一样不用每次更新都认证一次，谢谢
> > 如果以上建议能采纳，将万分感谢
> 
> ## 这个功能有什么可以参考的资料吗？
> > VERTEX

**Comment by jxxghp** [comment]
刷流用vertex，bt不会再支持，以免被自媒体拿来引流。

**Comment by yangke098** [comment]
那能否增加一个豆瓣刮削的功能呢，谢谢大佬，这个功能还是挺有用的
