### ISSUE TITLE
作者你好，可否集成ARM64架构的python认证鉴权so库

### ISSUE THREAD

**Issue by 07031218** [NAStool/nas-tools#3617]
项目里只有amd64架构的so库。对于arm64机器党来说想自己build镜像都无从下手了。

**Comment by git-0101** [comment]
还是希望作者大大支持arm64。真的是每天都盼着回归，每天刷新几遍有信息没，哈哈。

**Comment by 98kevinxiao** [comment]
希望作者大大支持arm64。卑微甲骨文在线求求了。我是作者大大的十年老粉

**Comment by jxxghp** [comment]
我目前没有ARM环境编译，估计得等一下了

**Comment by CraKeyBoy** [comment]
+1 支持 arm 的 dcoker 版本

**Comment by zyywo** [comment]
构建多平台的docker镜像相对容易点，我看官方文档有详细的步骤 https://docs.docker.com/build/building/multi-platform/

**Comment by DDSDerek** [comment]
> 我目前没有ARM环境编译，估计得等一下了

应该可以通过交叉编译工具实现吧？

**Comment by jxxghp** [comment]
> > 我目前没有ARM环境编译，估计得等一下了
> 
> 
> 
> 应该可以通过交叉编译工具实现吧？

需要运行环境才能生成

**Comment by jxxghp** [comment]
己支持arm64

**Comment by icezxf** [comment]
> 己支持arm64

作者你好 是不是armV8还是不支持 我n1 拉取还是提示 no matching manifest for linux/arm/v8 in the manifest list entries

**Comment by icezxf** [comment]
> 己支持arm64

是需要先安装pthon3吗？
