### ISSUE TITLE
zhuque经常无法正常获取数据且速度很慢

### ISSUE THREAD

**Issue by luoxiao-xy** [NAStool/nas-tools#3620]
zhuque适配必须使用浏览器仿真，性能很差，经常无法正常获取数据。

`站点 zhuque 获取流量数据失败：Message: unknown error: cannot connect to chrome at 127.0.0.1:46131 from unknown error: unable to discover open pages`

多数报错都是浏览器仿真失败导致的，希望适配非浏览器仿真，通过接口获取。

**Comment by lightolly** [comment]
关闭仿真即可
