### ISSUE TITLE
没有pt站的账户怎么使用全部功能

### ISSUE THREAD

**Issue by bearcloney** [NAStool/nas-tools#3624]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本:3.0
docker

我就一个臭看番的，上述的电影pt站都不用，主要的种子站就只有动漫花园和蜜柑计划
上述的pt站好像都需要邀请注册，而且这种站好像还要定期上线保号，我这种萌豚怎么验证这个工具啊呜呜呜

**Comment by Steven52065** [comment]
> ## 你使用的 NAStool 是什么版本，什么环境？
> > NAStool 版本:3.0
> > docker
> 
> 我就一个臭看番的，上述的电影pt站都不用，主要的种子站就只有动漫花园和蜜柑计划 上述的pt站好像都需要邀请注册，而且这种站好像还要定期上线保号，我这种萌豚怎么验证这个工具啊呜呜呜

如果想玩pt的话可以去贴吧学习一下相关要求并且求大佬给个邀请
pt在有一些设备后并不难玩（至少在下载速度和资源数量上是BT很难比的）

**Comment by netduke777** [comment]
作者不如直接收费吧，这样也给我们这些不完pt的个选择？
