### ISSUE TITLE
没有linux/arm64/v8的版本 无法拉取

### ISSUE THREAD

**Issue by zuoshiyue** [NAStool/nas-tools#3630]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: lattest
>
> 环境: openwrt linux/arm64/v8
>

## 你遇到什么问题了？

> docker hub镜像拉取失败

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 查阅 但可能没找到或注意到相关问题

## 你期望的结果

> 希望有相关解决办法或尽快支持相关环境

## 给出程序界面截图、后台运行日志或配置文件
<img width="565" alt="image" src="https://user-images.githubusercontent.com/29472925/222326273-73020877-e058-49da-a426-9be89e333c14.png">

**Comment by jxxghp** [comment]
#3617
