### ISSUE TITLE
处理RSS发生错误

### ISSUE THREAD

**Issue by zc0982** [NAStool/nas-tools#3633]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.0 0f0f155
>
> 环境: docker
>

## 你遇到什么问题了？

> 运行自定义RSS的时候提示以下错误：

处理RSS发生错误：Query.filter() got an unexpected keyword argument 'TYPE' - Traceback (most recent call last): File "/nas-tools/app/rsschecker.py", line 301, in check_task_rss if self.dbhelper.check_rss_history(media_info): File "/nas-tools/app/helper/db_helper.py", line 2112, in check_rss_history count = self._db.query(RSSHISTORY).filter( TypeError: Query.filter() got an unexpected keyword argument 'TYPE'

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是
> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
![image](https://user-images.githubusercontent.com/76107160/222350704-11c786c7-3c2a-4795-b323-574ca788e985.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
RSS_HISTORY 这个表的表结构好像不对了，是否有自己改过数据库？
没有的话建个新环境试下。

**Comment by caohaofei1** [comment]
> RSS_HISTORY 这个表的表结构好像不对了，是否有自己改过数据库？ 没有的话建个新环境试下。

我也是新版本有这个问题，删镜像容器，重新建还是这样
![Uploading Screenshot_20230304_121101_org.mozilla.firefox.jpg…]()

**Comment by caohaofei1** [comment]
![Screenshot_20230304_121101_org mozilla firefox](https://user-images.githubusercontent.com/104366346/222942725-e53db250-728f-4259-b8d9-c9633ce22b2d.jpg)
