### ISSUE TITLE
同步plex媒体服务器出现问题

### ISSUE THREAD

**Issue by wintekk** [NAStool/nas-tools#3634]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: V3.0.0
>
> 环境: Synology
>

## 你遇到什么问题了？

> 同步plex媒体服务器不成功，不显示媒体数量

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
<img width="542" alt="截屏2023-03-02 18 04 05" src="https://user-images.githubusercontent.com/32199008/222397308-cbda6a64-bda4-4f97-9528-2a3a8a782286.png">
<img width="720" alt="截屏2023-03-02 18 04 22" src="https://user-images.githubusercontent.com/32199008/222397328-a307366d-009c-428b-83f3-2b91f75d671f.png">
<img width="491" alt="截屏2023-03-02 18 03 29" src="https://user-images.githubusercontent.com/32199008/222397355-f51f3f0a-0952-4021-b63a-66d915ea7c8f.png">

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by aiwu12** [comment]
更新之后范围选择电影的同步还是有问题的，电视剧是正常的

**Comment by wintekk** [comment]
更新3.0.1之后，连接plex同步电视剧正常，电影还是有问题

**Comment by Sowevo** [comment]
#3655 处理了一下,等更新...

**Comment by Sowevo** [comment]
> 更新3.0.1之后，连接plex同步电视剧正常，电影还是有问题

更新下试试

**Comment by aiwu12** [comment]
> > 更新3.0.1之后，连接plex同步电视剧正常，电影还是有问题
> 
> 更新下试试

同步正常了，感谢
