### ISSUE TITLE
关于默认的识别刮削设置建议

### ISSUE THREAD

**Issue by aa4929101832** [NAStool/nas-tools#3638]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？

自动识别刮削有时候会失败然后手动又可以，所以我希望能增加自定义的设置，可以来设置识别失败的再次尝试识别，自定义次数和间隔，自定义识别失败多少次就停止再次识别，望采纳。感谢亲们的付出努力。
## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by jxxghp** [comment]
已有相同issues

**Comment by jxxghp** [comment]
#3561
