### ISSUE TITLE
在“电影重命名格式“中增加{imdb_id}字段（以简洁文件名、方便plex刮削）

### ISSUE THREAD

**Issue by estost** [NAStool/nas-tools#3642]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 3.0.1
>
> 环境: windows

## 你想要新增或者改进什么功能？

> 在“电影重命名格式“中增加{imdb_id}字段，方便plex刮削，简洁文件名
>
>plex可以直接识别名称带”ttxxxxx“的电影
>ex.   [2000-Aftersun] tt19770238.mkv
>
>而不需要像tmdb_id那样需要指定source {[source]-[id]}
>ex.   [2005-Aftersun] {tmdb-965150}.mkv

## 这个功能有什么可以参考的资料吗？

> TMDB API 可获取 'imdb_id' 字段
https://deeplearningproject.readthedocs.io/en/latest/section_3/build_dataset.html

**Comment by jxxghp** [comment]
早就从tmdb采集过imdb_id号了，只是因为并不是所有的都有关联imdb_id，所以没有做为命名要素。
实际上很多都没有。

**Comment by estost** [comment]
> 

嗯… 一般pt站搜索都是用imdb_id好像…
长片基本都会有imdb号，短片没有的会比较多。
基本用nastool是下长片为主，imdb_id作为重命名字段以供选择还是不错的。
毕竟更通用，除了pt站，豆瓣 字幕网站 还有各种论坛 都能用上。
希望大佬能考虑添加以下，感谢🥹

**Comment by estost** [comment]
> 早就从tmdb采集过imdb_id号了，只是因为并不是所有的都有关联imdb_id，所以没有做为命名要素。
> 实际上很多都没有。

嗯… 一般pt站搜索都是用imdb_id好像…
长片基本都会有imdb号，短片没有的会比较多。
基本用nastool是下长片为主，imdb_id作为重命名字段以供选择还是不错的。
毕竟更通用，除了pt站，豆瓣 字幕网站 还有各种论坛 都能用上。
希望大佬能考虑添加以下，感谢🥹
