### ISSUE TITLE
3.0.1找不到[媒体服务器]等设置项

### ISSUE THREAD

**Issue by gfgjs** [NAStool/nas-tools#3643]
3.0.1
docker

第一次用，教程中提到要设置媒体服务器，但找不到该设置项，如图
https://i.postimg.cc/SN6LBYjh/20230303040758.png

教程中正常的应该是如下
https://i.postimg.cc/pVDnrbvQ/636ca695b75594966-png-e1080.png

**Comment by dream10201** [comment]
用户认证你是一个字不截

**Comment by gfgjs** [comment]
翻了下发现了，要pt认证才能使用那些功能，但我只是想用下改名刮削的功能，嗨，算了吧
