### ISSUE TITLE
建议增加媒体服务器消息通知

### ISSUE THREAD

**Issue by zraxx** [NAStool/nas-tools#3644]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.1
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？
建议增加首页媒体服务器相关信息（如用户登录和播放信息），通过消息通知功能发送到手机

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by zraxx** [comment]
![IMG_20230303_102044.jpg](https://user-images.githubusercontent.com/25578054/222615301-9c4cde80-4ced-4d0e-a0b1-8e821abf9045.jpg)

**Comment by thsrite** [comment]
emby、flex不是有么？
