### ISSUE TITLE
无法通过Cloudflare验证

### ISSUE THREAD

**Issue by wxjerry** [NAStool/nas-tools#3645]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>3.0.1
> 环境: docker or windows or Synology
>Synology

## 你遇到什么问题了？

> 无法通过Cloudflare验证

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 麻烦问下此问题如何处理

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by a18ccms** [comment]
cf的作用不就是防止自动化吗？
