### ISSUE TITLE
请求媒体库增加剧场版分类

### ISSUE THREAD

**Issue by p199654** [NAStool/nas-tools#3648]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.1
>
> 环境: docker

## 你想要新增或者改进什么功能？

>希望媒体库分类里面增加剧场版这个分类，电影和动漫的剧场版分开归类方便整理、观看。

## 这个功能有什么可以参考的资料吗？

> \

**Comment by p199654** [comment]
![image](https://user-images.githubusercontent.com/17405323/222632777-4431e15d-a097-4068-a39f-1648a348a7af.png)
我剧场版和电影的位置都是固定好的，订阅剧场版后就跑到电影文件夹里面去了。希望剧场版能单独设置文件夹路径。

**Comment by XINGYUZHMM** [comment]
自己设个下载目录单独下剧场版，再用目录同步
