### ISSUE TITLE
现在不认证站点是没法使用该工具了吗？

### ISSUE THREAD

**Issue by vvkkhjt** [NAStool/nas-tools#3652]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.1
>
> 环境: docker
>

## 你遇到什么问题了？

> 现在不做站点认证是没法使用了？

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 搜索过了

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
可以使用同步和整理功能

**Comment by yongman** [comment]
@jxxghp 感谢大佬的付出。
想问下 v3.0.1 什么时候上 DSM7 ？v3.0.0 上的认证站点太少。

**Comment by weiyideai520** [comment]
用之前的版本呗：07031218/nas-tools:2.9.1-amd64。
