### ISSUE TITLE
1pt和carpt新抓的cookie但显示失效

### ISSUE THREAD

**Issue by zero617** [NAStool/nas-tools#3661]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.1
>
> 环境: docker
>

## 你遇到什么问题了？

> 1pt和carpt新抓的cookie但显示失效

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 查过了

## 你期望的结果

> 修复

## 给出程序界面截图、后台运行日志或配置文件

> ![截图_选择区域_20230303223126](https://user-images.githubusercontent.com/67105838/222747499-56591fcd-eae7-48cb-9531-38512e7521fb.png)

**Comment by lijiai** [comment]
同样的问题一直困扰着我，carPT签到后不刷新cookie，无法显示站点资源，每次都要在站点维护中，点击更新站点cookie和User-Agent后，输入账号密码手动更新才行。这两大平民站希望得到大大的照顾

**Comment by jxxghp** [comment]
1pt我没有，carpt设置的cf墙太严格了。

**Comment by lijiai** [comment]
好吧，期待后续版本更给力！
