### ISSUE TITLE
希望过滤规则能根据地区和类型自动选择过滤组

### ISSUE THREAD

**Issue by Linyue-GitHub** [NAStool/nas-tools#3662]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.1
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 希望过滤规则能根据视频类型(剧集 电影）和地区(内地 港澳台 外国） 来自动选择过滤器组，因为我国内剧集和国外剧集都是独立的过滤器组，国内的过滤器我没有设置必须要中文字幕，国外组的设置了必须要中文字幕才会下载，为了微信订阅方便，默认都是国内组的过滤器，但是一旦我需要订阅国外的剧集时候，就不能使用微信订阅了，只能去web端给这个订阅手动设置过滤器。如果过滤器可以自动选择了的话，就可以都通过微信订阅来订阅剧集或者电影了，大大方便了操作。

## 这个功能有什么可以参考的资料吗？

> 无

**Comment by jxxghp** [comment]
过于复杂，不好实现。
