### ISSUE TITLE
新版本站点认证可以多增加一些站嘛，手里只有几个小站，升级后无法认证

### ISSUE THREAD

**Issue by alguojian** [NAStool/nas-tools#3663]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 3.0.1
> 环境:  Synology

## 你遇到什么问题了？
升级最新版本后，无法认证，导致无法使用完整功能了，可能有些站不支持认证，但是这样就导致很多人没办法升级最新版了

## 你期望的结果

> 描述以下你期望的结果

可以正常使用完整功能

**Comment by SugarmanZhu** [comment]
https://github.com/NAStool/nas-tools/issues/3612

**Comment by skysolf** [comment]
不玩pt的都被玩死了

**Comment by 757957414** [comment]
大意了，还以为支持得多，都没有，又得麻烦倒退版本了
