### ISSUE TITLE
建议增加豆瓣削刮功能！

### ISSUE THREAD

**Issue by 21denli** [NAStool/nas-tools#3665]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>
> 环境: docker or windows or synology
最近整理国内旧老电影，发现大部分无法通过TMBD削刮成功！但是在豆瓣网上都可以找到。如果能能增加豆瓣削功能，就很好解决这个问题！我想nastool的核心功能之一就是削刮功能，希望在这方面进一步完善！nastool功能就更完美！

**Comment by 21denli** [comment]
可以考虑增加削刮器选项，

**Comment by 21denli** [comment]
![Uploading 8E979BFA-1F25-4DF8-BB00-3ECFE4A52834.jpeg…]()

**Comment by Linyue-GitHub** [comment]
可以自己去tmdb添加信息，从豆瓣复制过去就行了。豆瓣刮削是不现实的。

**Comment by AuntYang** [comment]
豆瓣刮削用不长的，tmdb开放api，就靠大家补充信息，tmdb编辑也不难啊

**Comment by luoxiao-xy** [comment]
可以支持豆瓣作为备选方案。优先使用tmdb，但tmdb无法正常削刮时，尝试豆瓣削刮。特别是部分用户网络不佳，tmdb经常失灵。

**Comment by yangke098** [comment]
我也想要这个功能
