### ISSUE TITLE
Jellyfin无法通过webhook插件进行播放限速

### ISSUE THREAD

**Issue by somethingwjy** [NAStool/nas-tools#3667]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.1
>
> 环境: docker
>

## 你遇到什么问题了？

> Jellyfin无法通过webhook插件进行播放限速
> 报错：Jellyfin.Plugin.Webhook.Destinations.Generic.GenericClient: 
Notification failed with "POST" request to http://192.168.0.109:3000/jellyfin

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 未找到Jellyfin相关的问题

## 你期望的结果

> Jellyfin通过使用webhook插件实现播放限速功能

## 给出程序界面截图、后台运行日志或配置文件

**图1-播放限速的设置**（内网ip为192.168.0.0/24，为方便得出测试结果，图中设置为其他地址）

![image](https://user-images.githubusercontent.com/35595344/222886192-6a53e56f-6472-4df4-8bed-b158b40e0111.png)

**图2-Jellyfin中webhook插件的设置**

![1](https://user-images.githubusercontent.com/35595344/222886424-beaa9a80-05b6-4b04-bced-566810f516b7.png)
![2](https://user-images.githubusercontent.com/35595344/222886428-df71d35d-6da5-4cef-8e13-3e17ab3a2911.png)

**以下三段为Jellyfin结束播放后部分日志**（选择一个视频播放几十秒，结束播放）

```
[2023-03-04 14:42:36.218 +08:00] [INF] [36] Emby.Server.Implementations.Session.SessionManager: 
Playback stopped reported by app "Jellyfin Web" "10.8.8" playing "我不是药神". Stopped at "3045751" ms
```

> [2023-03-04 14:42:36.642 +08:00] [WRN] [31] 
**Jellyfin.Plugin.Webhook.Destinations.Generic.GenericClient: 
Notification failed with "POST" request to http://192.168.0.109:3000/jellyfin**: 
"{\"ServerId\":\"9b9ee5425c974309a7e1c47743189f6d\",\"ServerName\":\"QAQ\",\"ServerVersion\":\"10.8.9\",\"ServerUrl\":\"\",\"NotificationType\":\"PlaybackStop\",\"Timestamp\":\"2023-03-04T14:42:36.612747+08:00\",\"UtcTimestamp\":\"2023-03-04T06:42:36.6127512Z\",\"Name\":\"\u6211\u4E0D\u662F\u836F\u795E\",\"Overview\":\"\u4E00\u4F4D\u4E0D\u901F\u4E4B\u5BA2\u7684\u610F\u5916\u5230\u8BBF\uFF0C\u6253\u7834\u4E86\u795E\u6CB9\u5E97\u8001\u677F\u7A0B\u52C7\u7684\u5E73\u51E1\u4EBA\u751F\uFF0C\u4ED6\u4ECE\u4E00\u4E2A\u4EA4\u4E0D\u8D77\u623F\u79DF\u7684\u7537\u6027\u4FDD\u5065\u54C1\u5546\u8D29\uFF0C\u4E00\u8DC3\u6210\u4E3A\u5370\u5EA6\u4EFF\u5236\u836F\u201C\u683C\u5217\u5B81\u201D\u7684\u72EC\u5BB6\u4EE3\u7406\u5546\u3002\u6536\u83B7\u5DE8\u989D\u5229\u6DA6\u7684\u4ED6\uFF0C\u751F\u6D3B\u5267\u70C8\u53D8\u5316\uFF0C\u88AB\u75C5\u60A3\u4EEC\u51A0\u4EE5\u201C\u836F\u795E\u201D\u7684\u79F0\u53F7\u3002\u4F46\u662F\uFF0C\u4E00\u573A\u5173\u4E8E\u6551\u8D4E\u7684\u62C9\u952F\u6218\u4E5F\u5728\u6CE2\u6D9B\u6697\u6D8C\u4E2D\u6162\u6162\u5C55\u5F00......\",\"Tagline\":\"\",\"ItemId\":\"8666d8ca72657b6cabfa47d1ab34418f\",\"ItemType\":\"Movie\",\"RunTimeTicks\":69766397952,\"RunTime\":\"01:56:16\",\"Year\":2018,\"Provider_tmdb\":\"532753\",\"Provider_imdb\":\"tt7362036\",\"Video_0_Title\":\"1080p H264 SDR\",\"Video_0_Type\":\"Video\",\"Video_0_Codec\":\"h264\",\"Video_0_Profile\":\"High\",\"Video_0_Level\":41,\"Video_0_Height\":1040,\"Video_0_Width\":1920,\"Video_0_AspectRatio\":\"1.85:1\",\"Video_0_Interlaced\":false,\"Video_0_FrameRate\":24,\"Video_0_VideoRange\":\"SDR\",\"Video_0_ColorSpace\":null,\"Video_0_ColorTransfer\":null,\"Video_0_ColorPrimaries\":null,\"Video_0_PixelFormat\":\"yuv420p\",\"Video_0_RefFrames\":1,\"Audio_0_Title\":\"Chi - Dolby Digital - 5.1 - Default\",\"Audio_0_Type\":\"Audio\",\"Audio_0_Language\":\"chi\",\"Audio_0_Codec\":\"ac3\",\"Audio_0_Channels\":6,\"Audio_0_Bitrate\":640000,\"Audio_0_SampleRate\":48000,\"Audio_0_Default\":true,\"Subtitle_0_Title\":\"\u7B80\u4F53 - Chi - \u9ED8\u8BA4 - SUBRIP\",\"Subtitle_0_Type\":\"Subtitle\",\"Subtitle_0_Language\":\"chi\",\"Subtitle_0_Codec\":\"subrip\",\"Subtitle_0_Default\":true,\"Subtitle_0_Forced\":false,\"Subtitle_0_External\":false,\"Subtitle_1_Title\":\"\u7E41\u4F53 - Chi - SUBRIP\",\"Subtitle_1_Type\":\"Subtitle\",\"Subtitle_1_Language\":\"chi\",\"Subtitle_1_Codec\":\"subrip\",\"Subtitle_1_Default\":false,\"Subtitle_1_Forced\":false,\"Subtitle_1_External\":false,\"PlaybackPositionTicks\":30457518540,\"PlaybackPosition\":\"00:50:45\",\"MediaSourceId\":\"8666d8ca72657b6cabfa47d1ab34418f\",\"IsPaused\":false,\"IsAutomated\":false,\"DeviceId\":\"TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzExMC4wLjAuMCBTYWZhcmkvNTM3LjM2fDE2NzY3Nzg0NDU5MjE1\",\"DeviceName\":\"Chrome\",\"ClientName\":\"Jellyfin Web\",\"PlayedToCompletion\":false,\"NotificationUsername\":\"wjy\",\"UserId\":\"b44adfa3d6d94d19a5095ad102cbe0f3\"}"

```
[2023-03-04 14:42:36.643 +08:00] [WRN] [31] 
Jellyfin.Plugin.Webhook.Destinations.Generic.GenericClient: 
Notification failed with response status code BadRequest: "<!doctype html>
<html lang=en>
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>The browser (or proxy) sent a request that this server could not understand.</p>
"
```

**nastools未产生类似emby的交互日志**（`如：
INFO: 处理事件：emby.webhook ......
INFO: 【Plugin】下载器 Qbittorrent 开始限速
`）

```
2023-03-04 14:03:03,169	INFO: 播放限速服务启动
2023-03-04 14:04:20,124	INFO: 【Rss】开始RSS订阅...
2023-03-04 14:04:20,154	WARNING: 【Rss】没有正在订阅的电影
2023-03-04 14:04:20,201	WARNING: 【Rss】没有正在订阅的电视剧
2023-03-04 14:24:20,155	INFO: 【Rss】开始RSS订阅...
2023-03-04 14:24:20,237	WARNING: 【Rss】没有正在订阅的电影
2023-03-04 14:24:20,263	WARNING: 【Rss】没有正在订阅的电视剧
2023-03-04 14:42:17,342	INFO: 播放限速服务启动
2023-03-04 14:44:20,135	INFO: 【Rss】开始RSS订阅...
2023-03-04 14:44:20,190	WARNING: 【Rss】没有正在订阅的电影
2023-03-04 14:44:20,244	WARNING: 【Rss】没有正在订阅的电视剧

```

**Comment by zraxx** [comment]
jellyfink 中用户名不要勾，勾上是指忽略该用户操作![Screenshot_2023-03-06-16-09-21-420_com.github.android.png](https://user-images.githubusercontent.com/25578054/223053317-6d8e6160-310c-42d5-8b9a-986b61c17ce1.png)

**Comment by somethingwjy** [comment]
> jellyfink 中用户名不要勾，勾上是指忽略该用户操作![Screenshot_2023-03-06-16-09-21-420_com.github.android.png](https://user-images.githubusercontent.com/25578054/223053317-6d8e6160-310c-42d5-8b9a-986b61c17ce1.png)

我也尝试过取消勾选用户， 还有那个“发送所有属性”也取消勾选过。 日志结果是一样的，都是 Notification failed with "POST" request to http://192.168.0.109:3000/jellyfin
您使用nt对jellyfin限速能够成功吗？  请问是我通知的url写的不对，还是说其他部分出错了？谢谢

**Comment by zraxx** [comment]
媒体播放器通知钉钉 设置成了，这个还在研究

**Comment by somethingwjy** [comment]
> 媒体播放器通知钉钉 设置成了，这个还在研究

我暂时在用群友推荐的这个项目 ”steve0x2a/dlimiter“ 对jellyfin做限速（作者已弃坑，表示等nt更新功能）改了一个小bug后使用还算可以。
nt的代码我没仔细研究，但看起来作者已经对jellyfin做了适配。可惜我这里怎么搞都成功不了，泪目了

**Comment by zraxx** [comment]
设置成功，媒体服务器不要设置

**Comment by somethingwjy** [comment]
> 设置成功，媒体服务器不要设置

哇哦，您能展开讲一下嘛  媒体服务器不要设置
是什么意思?  jellyfin那边和nastools具体应该怎么配置呢？

**Comment by zraxx** [comment]
就设置nastool中播放限速，即可。

**Comment by zraxx** [comment]
设置成功。
1、nastool限速设置
![Screenshot_2023-03-06-17-11-38-978_com.android.browser.png](https://user-images.githubusercontent.com/25578054/223066957-aaf23dd8-1d15-4e55-8c8d-c5f1afb42416.png)
2、容器日志
![Screenshot_2023-03-06-17-13-26-358_com.android.browser.png](https://user-images.githubusercontent.com/25578054/223067103-f01cfe69-9a5b-49ea-9205-0e936c3fbec3.png)

3、tr实际效果
![Screenshot_2023-03-06-17-13-57-476_com.android.browser.png](https://user-images.githubusercontent.com/25578054/223067163-133bd1c8-aaaf-43e0-9696-6a9df4555699.png)

退出播放后，不知道会不会停止限速

**Comment by somethingwjy** [comment]
感谢您的测试结果，我去另开一个nastools重新配置然后测试下。

**Comment by somethingwjy** [comment]
唉，我在docker里创建新的了nastools和jellyfin  测试结果还是   大失败...   我放弃了

**Comment by shan-guo** [comment]
> 唉，我在docker里创建新的了nastools和jellyfin 测试结果还是 大失败... 我放弃了

限速是每 5分钟检查一次，多播放一会儿试试看

**Comment by somethingwjy** [comment]
> > 唉，我在docker里创建新的了nastools和jellyfin 测试结果还是 大失败... 我放弃了
> 
> 限速是每 5分钟检查一次，多播放一会儿试试看

![image](https://user-images.githubusercontent.com/35595344/223317257-11d824b8-0dff-45b8-8933-55faa76b2fa5.png)
感谢解惑！ 终于成功了555   
就是感觉5分钟延迟有些久，不够实用。以后能像emby那样引入webhook实时限速就好了
[steve0x2a/dlimiter](https://github.com/Steve0x2a/DLimiter) 这个项目实现了jellyfin通过webhook插件完成限速操作（开发大大看到这条issue的话，希望能参考下QAQ

再次感谢！

**Comment by zraxx** [comment]
执行2次，隔25秒执行。
![Screenshot_2023-03-07-17-37-57-780_com.android.browser.png](https://user-images.githubusercontent.com/25578054/223383340-32c46ec9-e350-4c97-9f3e-6466681205a5.png)

![Screenshot_2023-03-07-17-38-23-598_com.alibaba.android.rimet.png](https://user-images.githubusercontent.com/25578054/223383375-c94cc658-e74a-4e28-85c3-226e733e053a.png)

**Comment by somethingwjy** [comment]
> 这个的原因应该是Jellyfin的webhook没设置请求头吧

这个我不懂怎么设置QAQ

**Comment by somethingwjy** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/58116139/223466397-6f61dc63-1e56-4114-a581-894c96d8970f.png)
> 
> Key:Content-Type Value:application/json

感谢大佬！  解决了~
![81TKM}7_E(OQ$P(ED9K{5 E](https://user-images.githubusercontent.com/35595344/223468676-42156f47-38ec-4d09-b49e-9b516d417837.png)

拜谢 ○|￣|_

**Comment by zraxx** [comment]
之前有设置过，难怪成功！

**Comment by zraxx** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/58116139/223466397-6f61dc63-1e56-4114-a581-894c96d8970f.png)
> 
> Key:Content-Type
> Value:application/json

之前jellyfin webhook插件有设置过，难怪一次成功！

**Comment by somethingwjy** [comment]
> 请教 webhook 完整设置，谢谢！

安装插件： 控制台-高级-插件-目录-Notifications  安装后需要重启jellyfin

安装插件后：
![image](https://user-images.githubusercontent.com/35595344/223474478-b6da6e6a-787c-47b9-b54a-3c765bc19793.png)

然后做下列配置，url改成你自己的IP，其他地方均无需勾选，最后save即可
![image](https://user-images.githubusercontent.com/35595344/223473998-d31b3793-9bfe-48d3-be0c-68694f978b73.png)
![image](https://user-images.githubusercontent.com/35595344/223474070-90dec688-b84b-4e5f-93a9-97a671dae0d8.png)
![image](https://user-images.githubusercontent.com/35595344/223474138-2e77a4b3-dfa2-439a-8fc9-b54871aa5c89.png)

**Comment by zraxx** [comment]
> > 请教 webhook 完整设置，谢谢！
> 
> 安装插件： 控制台-高级-插件-目录-Notifications  安装后需要重启jellyfin
> 
> 安装插件后：
> ![image](https://user-images.githubusercontent.com/35595344/223474478-b6da6e6a-787c-47b9-b54a-3c765bc19793.png)
> 
> 然后做下列配置，url改成你自己的IP，其他地方均无需勾选，最后save即可
> ![image](https://user-images.githubusercontent.com/35595344/223473998-d31b3793-9bfe-48d3-be0c-68694f978b73.png)
> ![image](https://user-images.githubusercontent.com/35595344/223474070-90dec688-b84b-4e5f-93a9-97a671dae0d8.png)
> ![image](https://user-images.githubusercontent.com/35595344/223474138-2e77a4b3-dfa2-439a-8fc9-b54871aa5c89.png)
> 

谢谢！设置成功，信息通知中也有提示了！![Screenshot_2023-03-08-00-01-15-027_com.tencent.mm.png](https://user-images.githubusercontent.com/25578054/223477823-7f8e35a6-8292-4497-b459-48582952210d.png)

![Screenshot_2023-03-08-00-02-17-206_com.android.browser.png](https://user-images.githubusercontent.com/25578054/223477895-7b46a77a-8714-457a-b16a-516dc1359bb9.png)

**Comment by somethingwjy** [comment]
再次感谢abc大佬指点迷津

**Comment by zraxx** [comment]
另外 消息通知 中增加播放影视名字？![Screenshot_2023-03-08-00-01-15-027_com.tencent.mm.png](https://user-images.githubusercontent.com/25578054/223478814-44f864f6-1e4a-41d3-bcd3-7655e288acf9.png)

**Comment by abczi** [comment]
> 另外 消息通知 中增加播放影视名字？![Screenshot_2023-03-08-00-01-15-027_com.tencent.mm.png](https://user-images.githubusercontent.com/25578054/223478814-44f864f6-1e4a-41d3-bcd3-7655e288acf9.png)

Jellyfin的webhook通知的内容里是有名字的，看代码好像是NasTools的播放通知没有把名字什么的解析出来，可以去提个需求

**Comment by garybrandam** [comment]
可以自己修改检测是否正在播放的间隔时间，docker镜像目录下/nas-tools/app/plugins/modules/speedlimiter.py，如下图，默认是300秒，我改成了10秒
![image](https://user-images.githubusercontent.com/119486146/223630567-30f3e6db-b14c-4fad-ae13-e83563ed9309.png)

**Comment by abczi** [comment]
我提交不了新的issues，在这里放个功能建议
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.2
>
> 环境: docker

## 你想要新增或者改进什么功能？

**目前**播放通知仅有播放器logo和开始结束播放时间；
**期望**为webhook播放通知增加具体播放内容，如图：
![image](https://user-images.githubusercontent.com/58116139/223625709-a9cf6048-e9b8-45c7-bcab-a10f8aa6a443.png)

各字段在webhook中的取值：
- 媒体标题 \"Name\" 
- 年份 \"Year\" 
- 季 \"SeasonNumber\" 
- 集 \"EpisodeNumber\"  
- 通知类型 \"NotificationType\"
- 用户名 \"NotificationUsername\"
- 时间 \"Timestamp\"

因为该功能来源于播放限速，也可考虑将当前媒体的码率和转码码率展示出来，但我没有在webhook中找到对应的值，大佬有别的办法取到值会更好。感谢大佬！

## 这个功能有什么可以参考的资料吗？
Jellyfin中webhook插件的项目地址：[](https://github.com/jellyfin/jellyfin-plugin-webhook)
> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by zraxx** [comment]
> 可以自己修改检测是否正在播放的间隔时间，docker镜像目录下/nas-tools/app/plugins/modules/speedlimiter.py，如下图，默认是300秒，我改成了10秒，改完保存，重启nastool即可
> ![image](https://user-images.githubusercontent.com/119486146/223630567-30f3e6db-b14c-4fad-ae13-e83563ed9309.png)
> 

没找到这个目录 只有config目录

**Comment by FireGodson** [comment]
> 可以自己修改检测是否正在播放的间隔时间，docker镜像目录下/nas-tools/app/plugins/modules/speedlimiter.py，如下图，默认是300秒，我改成了10秒，改完保存，重启nastool即可 ![image](https://user-images.githubusercontent.com/119486146/223630567-30f3e6db-b14c-4fad-ae13-e83563ed9309.png)

想问一下windows 版在哪里修改呢，怎么找不到呀

**Comment by zraxx** [comment]
> > 可以自己修改检测是否正在播放的间隔时间，docker镜像目录下/nas-tools/app/plugins/modules/speedlimiter.py，如下图，默认是300秒，我改成了10秒，改完保存，重启nastool即可 ![image](https://user-images.githubusercontent.com/119486146/223630567-30f3e6db-b14c-4fad-ae13-e83563ed9309.png)
> 
> 想问一下windows 版在哪里修改呢，怎么找不到呀
> 

媒体服务器中wbhook插件设置好后，不用调整时间

**Comment by FireGodson** [comment]
> > > 可以自己修改检测是否正在播放的间隔时间，docker镜像目录下/nas-tools/app/plugins/modules/speedlimiter.py，如下图，默认是300秒，我改成了10秒，改完保存，重启nastool即可 ![image](https://user-images.githubusercontent.com/119486146/223630567-30f3e6db-b14c-4fad-ae13-e83563ed9309.png)
> > 
> > 
> > 想问一下windows 版在哪里修改呢，怎么找不到呀
> 
> 媒体服务器中wbhook插件设置好后，不用调整时间

好啦，谢谢啦

**Comment by jxxghp** [comment]
这个问题应该已经解决了。
