### ISSUE TITLE
设置刷流任务，后面的站点获取到RSS也不添加下载任务，只刷第一个站点

### ISSUE THREAD

**Issue by abbcbbdd** [NAStool/nas-tools#3669]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 3.0.1
>
> 环境: docker
>

## 你遇到什么问题了？

> 设置好了刷流任务，只刷第一个站点，设置的下载数量也未达上限，查看日志，其他站点获取到了RSS数据，可就是不添加下载，第一个站点达到保种体积上限后，其他站点仍然不下载，还有部分站点无法获取RSS，站点测试是通过的，设置的刷流条件也比较宽松，无法获取RSS

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已查看和搜索，无法解决

## 你期望的结果

> 所有站点均能按照设定规则自动刷流

## 给出程序界面截图、后台运行日志或配置文件

> 
![1](https://user-images.githubusercontent.com/83579554/222934154-6479ffdf-e959-4506-a5ae-2517c902c538.jpg)
![2](https://user-images.githubusercontent.com/83579554/222934155-b4d778bd-0f95-4920-af3a-314616854a52.jpg)
![3](https://user-images.githubusercontent.com/83579554/222934156-96f75e89-51fa-4828-b2f8-673772e30243.jpg)

**Comment by VincentShin** [comment]
遇到同样的问题，求解。
设置的HDDOLBY站的刷流任务，无法成功，日志一直弹RSS未下载到数据

**Comment by VincentShin** [comment]
解决了，RSS订阅链接生成设置里面，订阅条数默认不要改，我这默认是每页10条
