### ISSUE TITLE
[目录同步] 同步方式为复制/移动时的 下载未完就开始复制/移动，导致文件损坏 （已解决）

### ISSUE THREAD

**Issue by estost** [NAStool/nas-tools#3670]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 3.0.1
>
> 环境: windows
>

## 你遇到什么问题了？

> #### 当目录同步方式选为复制或移动时，视频还没下完就被复制/移动到目的目录，导致视频文件损坏无法播放。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> #### 希望 目录同步 能等下载完成后再复制或移动

## 给出程序界面截图、后台运行日志或配置文件
>如下图，下载刚开始十几秒目录同步就开始复制视频文件，最后”完成时“视频文件损坏，大小不一致
<a href="https://imgbox.com/6oyVeMbJ" target="_blank"><img src="https://thumbs2.imgbox.com/4a/f0/6oyVeMbJ_t.png" alt="image host"/></a>

**Comment by pp2xx** [comment]
> 已解决可以关闭issue

请问怎么解决的？
