### ISSUE TITLE
新功能太牛逼了，但是…

### ISSUE THREAD

**Issue by Wangsc1** [NAStool/nas-tools#3673]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.1
>
> 环境: docker

## 你想要新增或者改进什么功能？
新的刮削功能太牛逼了大佬，666，我之前提的 #3002 能提前安排不😂，也是刮削类功能需求，🙏

**Comment by dajiangfu** [comment]
请问新的刮削功能和之前的对比具体差别体现在哪些方面？
