### ISSUE TITLE
自动追剧下载器一直添加失败

### ISSUE THREAD

**Issue by xushier** [NAStool/nas-tools#3674]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.1
>
> 环境: docker
>

## 你遇到什么问题了？
![image](https://user-images.githubusercontent.com/31540107/222940153-e0262c98-ea8b-4713-8249-2c9e7205ae25.png)

![image](https://user-images.githubusercontent.com/31540107/222940192-23c1aefd-79de-4ddf-8c08-c1bb7c9e72f0.png)

![image](https://user-images.githubusercontent.com/31540107/222940087-7ada6d7f-fb1f-4213-93e9-c8976def2677.png)

![image](https://user-images.githubusercontent.com/31540107/222940103-cd158337-527a-4058-96e3-b0f328287010.png)

![image](https://user-images.githubusercontent.com/31540107/222940115-4a1ee533-dd9c-45f3-bb1f-6f27f19fd015.png)

自动追剧下载器一直添加失败。站点的下载设置都是默认，下载器和下载设置也都设置了默认。手动搜索推送下载正常推送。

> 描述一下你遇到的问题

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by Doraemonsan** [comment]
我也是这样，请问你如何解决的
