### ISSUE TITLE
能不能开放IYUU的设置界面？

### ISSUE THREAD

**Issue by tdg2088** [NAStool/nas-tools#3677]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 3.0.1
>
> 环境: Synology
>

## 你遇到什么问题了？

> 描述一下你遇到的问题

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

我有海胆PT的号，但是没有3.0.1版本中那些小PT的号。据说IYUU可以绑定海胆的号，但我在用户认证中输入IYUU的key，因为IYUU无绑定过我的海胆PT号，导致我无法使用全部功能。希望IYUU设置这块可以单独放出来。

## 你期望的结果

> 描述以下你期望的结果

![jt](https://user-images.githubusercontent.com/5585540/222950648-a099e3c5-7706-4f4c-9ad2-106cb97a6a9d.jpg)> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by XINGYUZHMM** [comment]
”据说“，建议百度IYUU呢

**Comment by DDSDerek** [comment]
自己安装验证IYUUPlus啊，来NT这边提issue有什么用？
