### ISSUE TITLE
2.9.2从docker升级上来这样正常吗

### ISSUE THREAD

**Issue by xrain0610** [NAStool/nas-tools#3678]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.1
>
> 环境: docker 
>

## 你遇到什么问题了？

> 从2.9.2升级完之后,变得少了好多东西,似乎也没啥能用的, 是需要全新安装3.0.1吗
<img width="1519" alt="image" src="https://user-images.githubusercontent.com/11401602/222953905-b8b99a06-0de2-49bf-b45d-c389f3ff0bf6.png">

**Comment by Tartarus2014** [comment]
左下角认证
