### ISSUE TITLE
刚更新的ARM64版本有bug

### ISSUE THREAD

**Issue by 07031218** [NAStool/nas-tools#3681]
容器日志中错误信息如图：
<img width="1643" alt="image" src="https://user-images.githubusercontent.com/3378408/222957320-c7a0ec11-f515-4c45-8336-6640ec88bd97.png">

**Comment by Shurelol** [comment]
ld.so手动建个软连接命名为图中缺少名字的试试

**Comment by 07031218** [comment]
最新镜像测试已修复，感谢作者！
