### ISSUE TITLE
RSS自定义订阅支持设置代理

### ISSUE THREAD

**Issue by OGRLEAF** [NAStool/nas-tools#3685]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.1
>
> 环境: docker or windows or synology
docker
## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？
希望RSS自定义订阅能支持代理访问，有些RSS源访问不太稳定，会导致无法获取数据。

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by jxxghp** [comment]
已支持
