### ISSUE TITLE
同一集不同文件名重复硬链的问题，下载软件监控模式

### ISSUE THREAD

**Issue by casselluu** [NAStool/nas-tools#3686]
Docker 2.90
发现有一些追更中的新剧出现媒体库重复硬链的情况，媒体整理中手动删除媒体库文件，再到文件管理里转移则不出现重复。怀疑是因新剧TMDB的集名称存在被修改的情况，导致重复硬链，希望能修改一下硬链的判定标准或者逻辑，解决重复硬链的问题。
<img width="1135" alt="截屏2023-03-05 21 59 01" src="https://user-images.githubusercontent.com/39119438/222965571-657cb9e5-79c8-4d4c-8a27-eaf51d554d10.png">
<img width="1135" alt="截屏2023-03-05 22 10 24" src="https://user-images.githubusercontent.com/39119438/222965593-4675b76f-7004-4dd4-81ec-9a009625778e.png">

**Comment by Shurelol** [comment]
更新
