### ISSUE TITLE
忘记密码重置

### ISSUE THREAD

**Issue by ncdri** [NAStool/nas-tools#3690]
我用的是群晖docker版2.9.0， 登陆时密码忘记，无法进入nastool。

删除后重新安装还是提醒 “用户名或密码错误”

请问如何解决， 谢谢！

**Comment by jxxghp** [comment]
不再支持3.0以下版本

**Comment by ncdri** [comment]
非常感谢您快速的答复，因为我无法马上申请到PT站的注册邀请，于是安装3.0后，就无法使用nastool。 不知道您有何建议？感谢！
