### ISSUE TITLE
2.9升级到3.0后，搜索目录等小时不见了，重装后亦如此？

### ISSUE THREAD

**Issue by star2k** [NAStool/nas-tools#3691]
## 你使用的 NAStool 是什么版本，：V3

> NAStool 版本: v3.0
>
> 环境: Synology
>
![Snipaste_2023-03-06_08-49-06](https://user-images.githubusercontent.com/9582078/222996561-a5ab9c50-75da-4828-aca1-de49f7b22163.png)

**Comment by thsrite** [comment]
左下角，用户认证……

**Comment by star2k** [comment]
> 左下角，用户认证……

这个需要pt账号 我没有，以前自带bt站点资源，现在没有了么？

**Comment by ReddotCleaner** [comment]
> > 左下角，用户认证……
> 
> 这个需要pt账号 我没有，以前自带bt站点资源，现在没有了么？

3.0及以上需要认证，如果使用BT，请使用3.0以下版本，如2.9.1

**Comment by star2k** [comment]
群晖第三方套件形式下载安装的，只有最新版本3，没法退回了2.9

**Comment by blue-eric** [comment]
只有M-T的账号，无法认证，也回滚不了，头疼。。。

**Comment by sypopo** [comment]
去hub.docker.com找个低版本的镜像

**Comment by stevesgit** [comment]
不要升级！ 不要升级！ 不要升级！
