### ISSUE TITLE
v3.0.1 探索-豆瓣电视剧无法正常加载电视剧，部分电视剧搜索时一直加载无法显示结果

### ISSUE THREAD

**Issue by ThierryCheng** [NAStool/nas-tools#3698]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.1
>
> 环境: docker
>

## 你遇到什么问题了？

> v3.0.1 探索-豆瓣电视剧无法正常加载电视剧，页面一直停留在加载中。除豆瓣电视剧之外其他栏目都能够正常加载。
换了设备也是同样的问题，包括移动端
搜索电视剧的时候，页面也是一直在加载，无法显示正确的电视剧海报，但是部分电视剧搜索的时候可以出结果

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是的

<img width="971" alt="image" src="https://user-images.githubusercontent.com/8851199/223094370-28f41888-3282-461f-a547-c189fcdbaa0b.png">
<img width="891" alt="image" src="https://user-images.githubusercontent.com/8851199/223094411-9761169e-e1d7-41ad-b393-9340ba8ca2b8.png">

**Comment by AuntYang** [comment]
我这里显示正常，应该不是nt的问题，看看日志吧
![Screenshot_2023-03-07-01-23-32-339_com android chrome](https://user-images.githubusercontent.com/49216233/223184798-c9f77649-79dd-4394-816b-0a7c13d6b088.jpg)
