### ISSUE TITLE
以后会考虑添加迅雷下载支持不？

### ISSUE THREAD

**Issue by DrAlanY** [NAStool/nas-tools#3699]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>
> 环境: docker 

## 你想要新增或者改进什么功能？

> 以后会考虑添加迅雷下载支持不？

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by Linyue-GitHub** [comment]
太离谱啦

**Comment by AuntYang** [comment]
迅雷还是不好吧，都已经遗弃bt了，为啥还要迅雷？

**Comment by markddd268** [comment]
远离迅雷，人人有责
