### ISSUE TITLE
千与千寻豆瓣电影不显示打钩

### ISSUE THREAD

**Issue by kvtong93** [NAStool/nas-tools#3700]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.01
>
> 环境: docker or windows or Synology
> Truenas Docker

## 你遇到什么问题了？

> 描述一下你遇到的问题
千与千寻豆瓣电影不显示打钩，实际已下载入库
![image](https://user-images.githubusercontent.com/56487514/223302308-5ba743d4-9575-4620-9aa6-49d4ab8eca4e.png)
![image](https://user-images.githubusercontent.com/56487514/223302389-1a3c1471-6a4c-4e13-816d-93fb6cd9f739.png)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是
> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果
能够正确显示已下载
## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
<img width="231" alt="image" src="https://user-images.githubusercontent.com/51039935/227752395-396b0d49-4866-44f3-be37-72e759f5f234.png">
