### ISSUE TITLE
刷流文件被错误转移到媒体库

### ISSUE THREAD

**Issue by 2Dou** [NAStool/nas-tools#3703]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.1
>
> 环境: docker
>

## 你遇到什么问题了？

> 现在刷流取消了指定目录，就会根据下载器下载目录设置，下载到指定的分类目录。
> 刷流任务中即使没有开启`转移到媒体库`，但另一边目录同步的监控功能，也会把文件转移到媒体库。

## 你期望的结果

> 可以在刷流任务界面和下载器一样设置下载目录，可以给这个功能加个开关，关闭时使用下载器目录设置，开启时使用刷流任务的目录设置。

> 我个人还挺习惯把刷流的全下载到temp目录，然后自动删种里面去匹配路径删除的。

**Comment by AuntYang** [comment]
我之前也遇到过这个问题，但可以通过添加一个刷流专用的下载器配置，将下载目录设置为非媒体库转移目录，即可解决此问题

**Comment by 2Dou** [comment]
> 我之前也遇到过这个问题，但可以通过添加一个刷流专用的下载器配置，将下载目录设置为非媒体库转移目录，即可解决此问题

soga，明白了，效果一样。
