### ISSUE TITLE
RSS订阅电视剧直接就结束并删除了，并没有去下载

### ISSUE THREAD

**Issue by wlnxing** [NAStool/nas-tools#3708]
## 你使用的 NAStool 是什么版本，什么环境？

 NAStool 版本: v3.0.2

 环境: docker

## 你遇到什么问题了？

> 描述一下你遇到的问题

在搜索电视剧后 点击订阅，成功订阅随后开始下载，但是日志直接提示：剧集已经全部存在 删除订阅。。。实际上我并没有下载过。测试所有的电视剧订阅都有问题。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

修复

## 给出程序界面截图、后台运行日志或配置文件

<img width="906" alt="image" src="https://user-images.githubusercontent.com/77608284/223345626-67315f38-f117-4b00-b8c3-30bf94e06682.png">

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by thsrite** [comment]
清空RSS缓存试试

**Comment by wlnxing** [comment]
更新：在微信里下载也是直接全部已存在

PS：中间有去更新rss缓存 更新后也现象
<img width="945" alt="image" src="https://user-images.githubusercontent.com/77608284/223411867-47abf752-f29c-487a-9376-37c2f82cbcfd.png">

**Comment by wlnxing** [comment]
对不起 是我的问题 我plex重新扫描之后正常了 🙇‍♀️
