### ISSUE TITLE
nfo文件内容没有正确写入

### ISSUE THREAD

**Issue by 188334911** [NAStool/nas-tools#3709]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.2
>
> 环境: docker or windows or Synology
>amd x64 docker

## 你遇到什么问题了？

> 削刮内容没有正确写入nfo文件

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是的

## 你期望的结果

> 修复bug

## 给出程序界面截图、后台运行日志或配置文件
1 设置
![set2](https://user-images.githubusercontent.com/54146909/223351129-7fa29418-8110-4cb0-9c64-98f25e3d3d72.png)
2 设置
![set1](https://user-images.githubusercontent.com/54146909/223350928-a6b5c305-7671-4f95-a459-517a74f30344.png)
3 tmdb网页
![tmdb](https://user-images.githubusercontent.com/54146909/223351184-78ec8a6d-0d10-4d30-8a0d-a73f0ceca1ef.png)
4 日志
![log](https://user-images.githubusercontent.com/54146909/223351615-eca8523f-b9ee-40a0-b2c2-aeeedee72322.png)
5 nfo文件内容
![nfo](https://user-images.githubusercontent.com/54146909/223351657-ec9bf5e3-f5e9-402a-aabb-57122068b07a.png)

前几天开始所有刮削的电影都是这样了,当时还以为电影太新了.没有简介,后来下了一部老电影才发现还是没有正确写入的nfo的简介内容

**Comment by honestpony** [comment]
是的 我也很确认有此问题 大约是3.01版本开始的 群晖 矿神套件安装

**Comment by Travisss** [comment]
我也有这个问题

**Comment by Shurelol** [comment]
更新
