### ISSUE TITLE
媒体库刮削

### ISSUE THREAD

**Issue by PoiYuudachi** [NAStool/nas-tools#3712]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>v3.0.2 a035370
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

> 描述一下你遇到的问题
由于emby与nastool刮削时文件的明明不一样 导致emby不读取原有已经刮好的图片，而去读取nas-tools刮削的图片
![Q${%05PA12RIU$0Z{NY0BLJ](https://user-images.githubusercontent.com/41389186/223372094-31446ef6-d6c7-42bb-a969-606b8ba2e3bc.png)

emby命名是clearlogo和landscape   而nastools命名的是logo和thumb

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果
logo和thumb改成和emby一致或增加clearlogo和landscape选项并提示
## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
现在的命名emby和jellyfin是可以读取的吧？并不是严格跟emby一致。

**Comment by PoiYuudachi** [comment]
可以读取，但是emby会优先读取logo和thumb而不是emby自己刮削的clearlogo和landscape
