### ISSUE TITLE
希望修复chanify信息推送无声音提示的问题！

### ISSUE THREAD

**Issue by 21denli** [NAStool/nas-tools#3717]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>
> 环境: docker or windows or Synology
>

## 你遇到什么问题了？

> 描述一下你遇到的问题

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> chanify推送消息，手机上无声音提醒！麻烦修复一下！

**Comment by AuntYang** [comment]
chanify的问题来nt提issue干啥

**Comment by 21denli** [comment]
chanify在其他平台使用正常，但是在nastools推送消息就没声音，曾咨询过chanify开发者，说是有个声音的参数没加上！

**Comment by Sowevo** [comment]
#3722 
已修改,等新版本更新

附加参数填`sound=1`就有声音了
<img width="399" alt="image" src="https://user-images.githubusercontent.com/31763582/223462518-fe2e374f-d456-4263-a6f9-822505a09bd4.png">
