### ISSUE TITLE
可配置默认订阅和搜索站点

### ISSUE THREAD

**Issue by yongman** [NAStool/nas-tools#3729]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.2
>
> 环境: synology

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？

添加订阅时可以选择订阅的站点，或者全局配置默认订阅站点。现在是默认订阅和搜索全部站点，如果有修改需求，需要先添加订阅再进行编辑。

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by AuntYang** [comment]
不知道我理解的对不对，订阅和搜索都可以选择站点
![image](https://user-images.githubusercontent.com/49216233/223610055-262cf0de-047c-4bae-84f3-4212201bfc0d.png)

**Comment by Wangsc1** [comment]
> 不知道我理解的对不对，订阅和搜索都可以选择站点
> 
> ![image](https://user-images.githubusercontent.com/49216233/223610055-262cf0de-047c-4bae-84f3-4212201bfc0d.png)
> 
> 

他的意思是添加订阅的时候直接可以选择站点，而不是添加完订阅再去编辑订阅选择站点

**Comment by yongman** [comment]
是在资源页面点击❤快捷订阅，是默认全选了。

**Comment by AuntYang** [comment]
> 是在资源页面点击❤快捷订阅，是默认全选了。

是不太方便，我都是点完订阅后编辑的

**Comment by yongman** [comment]
> > 是在资源页面点击❤快捷订阅，是默认全选了。
> 
> 是不太方便，我都是点完订阅后编辑的

但是如果是和 douban 同步，自动订阅的话就不好编辑了，所以期望能加个默认订阅站点的配置

**Comment by garybrandam** [comment]
+1，默认是在所有站点订阅，期待增加一个配置默认订阅站点的选项

**Comment by jxxghp** [comment]
现已支持单独设置
