### ISSUE TITLE
能多添加一些用户认证站点

### ISSUE THREAD

**Issue by caesarli** [NAStool/nas-tools#3731]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 3.0.0
>
> 环境: docker in synology

## 你想要新增或者改进什么功能？

> 用户认证站点

## 至少增加m-team用户认证站点，现在多用户认证站点太少了，2.X版本升级后不认证就不能搜索， NASTOOL就没啥用了， 能否多增加一些用户站点？ 唉， 用了几个月结果现在升级后啥都用不了了

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.
m-team,  [ptschool](https://pt.btschool.club/) 等
<img width="1338" alt="Screenshot 2023-03-08 at 2 55 40 pm" src="https://user-images.githubusercontent.com/3290124/223615974-bb4eab44-a8c6-41c4-a796-f92ed5d2eb77.png">
<img width="1016" alt="Screenshot 2023-03-08 at 2 58 13 pm" src="https://user-images.githubusercontent.com/3290124/223616264-46382a7d-7470-4f01-afdf-689c15da82c4.png">
<img width="1081" alt="Screenshot 2023-03-08 at 2 58 26 pm" src="https://user-images.githubusercontent.com/3290124/223616279-c473d8d2-5678-4240-9bfe-f4b8161e94a2.png">

**Comment by AuntYang** [comment]
#3612

**Comment by zzbbluesky** [comment]
同问、没有这些网站的，可以去哪搞到邀请？

**Comment by torch132** [comment]
> 同问、没有这些网站的，可以去哪搞到邀请？

公众号PT邀请码网会公布开放注册的站点的即时信息，或者找你想要的站点花钱捐进去（推荐馒头，200）

**Comment by zzbbluesky** [comment]
> > 同问、没有这些网站的，可以去哪搞到邀请？
> 
> 公众号PT邀请码网会公布开放注册的站点的即时信息，或者找你想要的站点花钱捐进去（推荐馒头，200）

现在是个人有的pt站，老板并米有开通认证。比如HDfans，比如springsunday

**Comment by torch132** [comment]
> > > 同问、没有这些网站的，可以去哪搞到邀请？
> > 
> > 
> > 公众号PT邀请码网会公布开放注册的站点的即时信息，或者找你想要的站点花钱捐进去（推荐馒头，200）
> 
> 现在是个人有的pt站，老板并米有开通认证。比如HDfans，比如springsunday

现在支持那些站点了啊，我还是2.9.1版本，在想要不要升级

**Comment by rryuliu** [comment]
同希望增加M-team。其它PT都没有帐号……

**Comment by shinshin-hub** [comment]
同样只有HDfans

**Comment by leien0529** [comment]
8个站点，都没有可以认证的

**Comment by Shallowhave** [comment]
能否求个HDfans的码子？

**Comment by YonQua** [comment]
同求支持 hdatmos.club 这个站点认证

**Comment by chenjienail** [comment]
> > > > 同问、没有这些网站的，可以去哪搞到邀请？
> > > 
> > > 
> > > 公众号PT邀请码网会公布开放注册的站点的即时信息，或者找你想要的站点花钱捐进去（推荐馒头，200）
> > 
> > 
> > 现在是个人有的pt站，老板并米有开通认证。比如HDfans，比如springsunday
> 
> 现在支持那些站点了啊，我还是2.9.1版本，在想要不要升级

别升级，很多站点不支持，我升级后到现在不能用
