### ISSUE TITLE
可否新增对已经刮削好的文件直接链接目录或者文件到媒体库

### ISSUE THREAD

**Issue by GGBond-98** [NAStool/nas-tools#3737]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 3.0.2
>
> 环境: docker 

## 你想要新增或者改进什么功能？
手动链接功能或者识别已有刮削文件的目录跳过刮削直接链接
> 你想要新增或者改进什么功能？

## 这个功能有什么可以参考的资料吗？
> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.
下载到已经刮削好的文件无法自动刮削时可以更方便（全自动）链接到媒体库

**Comment by jxxghp** [comment]
目录同步关掉识别重命名
