### ISSUE TITLE
通过用户认证之后，索引器无法索引

### ISSUE THREAD

**Issue by xiuzi1119** [NAStool/nas-tools#3738]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.2
>
> 环境: docker 
>

## 你遇到什么问题了？

> 通过用户认证后，索引器内只有内建索引器，且内建索引器内无开放站点选项，无法使用索引功能。
![image](https://user-images.githubusercontent.com/127284706/223702939-b623ef65-bccb-48f9-9c26-0e551a821a24.png)

**Comment by Wangsc1** [comment]
早就没了啊，现在没pt玩不了

**Comment by xiuzi1119** [comment]
我已经用PT验证通过了，仍然功能缺失。

**Comment by AuntYang** [comment]
是否在**站点维护**内添加站点？

**Comment by AuntYang** [comment]
> > 是否在**站点维护**内添加站点？
> 
> 站点维护内添加的应该是私密站点吧？之前的内建索引器是可以选择公开站点的，现在没有了。并且只有内建索引器，没有jackett了，之前的索引器里面是有3个索引器的，现在只有内建索引器。现在最主要的问题是无法索引资源。

#3503

**Comment by xiuzi1119** [comment]
> > > 是否在**站点维护**内添加站点？
> > 
> > 
> > 站点维护内添加的应该是私密站点吧？之前的内建索引器是可以选择公开站点的，现在没有了。并且只有内建索引器，没有jackett了，之前的索引器里面是有3个索引器的，现在只有内建索引器。现在最主要的问题是无法索引资源。
> 
> #3503

我了解你的意思了，现在是需要自行在”站点维护“内添加站点是吧？公开站点也需要每个都自己逐一设置吗？

**Comment by AuntYang** [comment]
> > > > 是否在**站点维护**内添加站点？
> > > 
> > > 
> > > 站点维护内添加的应该是私密站点吧？之前的内建索引器是可以选择公开站点的，现在没有了。并且只有内建索引器，没有jackett了，之前的索引器里面是有3个索引器的，现在只有内建索引器。现在最主要的问题是无法索引资源。
> > 
> > 
> > #3503
> 
> 我了解你的意思了，现在是需要自行在”站点维护“内添加站点是吧？公开站点也需要每个都自己逐一设置吗？

是的

**Comment by Wangsc1** [comment]
> > 是否在**站点维护**内添加站点？
> 
> 
> 
> 站点维护内添加的应该是私密站点吧？之前的内建索引器是可以选择公开站点的，现在没有了。并且只有内建索引器，没有jackett了，之前的索引器里面是有3个索引器的，现在只有内建索引器。现在最主要的问题是无法索引资源。

第一，之前的公开站点全部取消了
第二，之前的第三方索引器也取消了
第三，既然你能通过用户认证就说明你有pt站，站点维护里面添加pt站，然后在现有的索引器内选中你添加的站点就可以搜索资源了

**Comment by xiuzi1119** [comment]
> > > 是否在**站点维护**内添加站点？
> > 
> > 
> > 站点维护内添加的应该是私密站点吧？之前的内建索引器是可以选择公开站点的，现在没有了。并且只有内建索引器，没有jackett了，之前的索引器里面是有3个索引器的，现在只有内建索引器。现在最主要的问题是无法索引资源。
> 
> 第一，之前的公开站点全部取消了 第二，之前的第三方索引器也取消了 第三，既然你能通过用户认证就说明你有pt站，站点维护里面添加pt站，然后在现有的索引器内选中你添加的站点就可以搜索资源了

感谢解答，我已经明白方法了。谢谢大佬！！！

**Comment by xiuzi1119** [comment]
> > > > > 是否在**站点维护**内添加站点？
> > > > 
> > > > 
> > > > 站点维护内添加的应该是私密站点吧？之前的内建索引器是可以选择公开站点的，现在没有了。并且只有内建索引器，没有jackett了，之前的索引器里面是有3个索引器的，现在只有内建索引器。现在最主要的问题是无法索引资源。
> > > 
> > > 
> > > #3503
> > 
> > 
> > 我了解你的意思了，现在是需要自行在”站点维护“内添加站点是吧？公开站点也需要每个都自己逐一设置吗？
> 
> 是的

这就得每个站都自己注册账号，然后才能获取RSS和cookie，还得是能选择使用第三方插件方便，现在这个使用起来太不方便了。
