### ISSUE TITLE
希望增加定时开始和关闭刷流的功能。

### ISSUE THREAD

**Issue by bhj128128** [NAStool/nas-tools#3753]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.2
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 定时开启和关闭刷流的功能，比如凌晨开启，白天关闭。

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by jxxghp** [comment]
已支持cron

**Comment by bhj128128** [comment]
> 已支持cron

谢谢佬儿！
