### ISSUE TITLE
点击“搜索资源”按钮后，提示“网络错误”

### ISSUE THREAD

**Issue by zhaoyi4j** [NAStool/nas-tools#3755]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.2 d68921e
>
> 环境:  Synology
>

> 描述一下你遇到的问题

点击搜索后，报错

日志如下：

2023-03-10 00:01:28,893 INFO: 【Meta】正在查询TMDB电影：615777 ...
2023-03-10 00:01:28,903 INFO: 【Web】从TMDB中匹配到电影：巴比伦 (2022)
2023-03-10 00:01:28,904 INFO: 【Web】开始检索 巴比伦 ...
2023-03-10 00:01:28,907 INFO: 处理事件：search.start - [<function Webhook.send at 0x7f476c36b2e0>]

已经设置对应的PT站，并且在PT站中可以搜到相关资源

> 描述以下你期望的结果

解决该问题

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by akonegod** [comment]
![image](https://user-images.githubusercontent.com/39025585/224217336-c9f7d7f6-f20b-4781-984c-d3f29c3c04bc.png)
我也出现了同样的问题，点击搜索任何资源都汇报网络错误
![image](https://user-images.githubusercontent.com/39025585/224217536-18523923-2fee-4373-8ca6-081dd7fd0d26.png)

**Comment by wenhua2008** [comment]
同样的问题

**Comment by laobanbiefangcu** [comment]
我也是这个错误

**Comment by eeezae** [comment]
需要安装python3.10，如果安装了还是报这个错误，说明是启动套件后再安装的，重启一下套件就好了

**Comment by laobanbiefangcu** [comment]
> 需要安装python3.10，如果安装了还是报这个错误，说明是启动套件后再安装的，重启一下套件就好了

docker怎么安装python3.10
