### ISSUE TITLE
希望可以增加按照日期命名种子的搜刮

### ISSUE THREAD

**Issue by paysenyu** [NAStool/nas-tools#3756]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.2
>
> 环境: docker 

## 你想要新增或者改进什么功能？

这可能是一个小众需求，但也会经常遇到，希望可以增加按照日期命名种子的搜刮。

## 这个功能有什么可以参考的资料吗？

<img width="527" alt="image" src="https://user-images.githubusercontent.com/51367628/224199546-662b23ac-9f6e-4159-89b4-eb614e0653e7.png">

如上图所示，文件命名是按照日期的方式，但也有规律可循。

希望可以增加一个“自定义集”的功能，按照日期排训来自动解决。

目前解决的方案是手动 hlink 然后用第三方批量重命名软件根据日期自动命名成 E01- EXX 

希望可以实现

**Comment by jxxghp** [comment]
这个支持不了
