### ISSUE TITLE
刷流任务异常

### ISSUE THREAD

**Issue by tone88** [NAStool/nas-tools#3757]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: [v3.0.2 38ab92f]
> 环境:  群晖下 docker

## 你遇到什么问题了？
1、刷流任务设置见下图，设置同时下载为1（之前设置5出问题所以改为1，结果问题依旧），但是当存在下载任务的时候还是会自动添加下载任务，且日志中会提示添加种子报错（图2），结果就是会一直不停的添加任务。

2、无法查看刷流种子明细，点击查看种子明细一直显示都是“未下载种子或未获取到种子明细”（图3），这样的结果是不是会导致保种体积设置无效，会一直不停的下载，直到硬盘爆满（以我目前观察应该是会不停的下，因为现在已经超过了保种体积下载任务的添加并没有停止）。

## 你期望的结果
2.9+的时候刷流没出现上述问题，望作者修复，辛苦了!!!

## 给出程序界面截图、后台运行日志或配置文件
![33](https://user-images.githubusercontent.com/47731895/224201571-114767ab-80e9-4ebe-8c1f-6bc7c8770775.png)
![11](https://user-images.githubusercontent.com/47731895/224201601-7a7f1689-1570-4439-b26c-a3231fb47ef9.png)
![44](https://user-images.githubusercontent.com/47731895/224201666-be0dc117-ec39-4ad3-93c7-5adbbae5809f.png)
下载任务都是设置为同时下载为1的时候，自动添加的，目前还在持续添加！
![55](https://user-images.githubusercontent.com/47731895/224201819-892fac79-e2a7-475f-8e20-64df7f5960ce.png)
另一个站的刷流设置
![22](https://user-images.githubusercontent.com/47731895/224201889-7ae8e1f2-2978-4375-8d90-b73ccf1efbf2.png)

**Comment by tone88** [comment]
停止任务好像也有问题，在提这个issues的时候我就关掉了刷流任务，结果还在添加下载
![QQ截图20230310132823](https://user-images.githubusercontent.com/47731895/224231453-e72cc28b-12b1-4849-b101-c0638a11bd48.png)
![QQ截图20230310132958](https://user-images.githubusercontent.com/47731895/224231552-412ae7cc-352c-4741-8653-e9efd497f6e9.png)

**Comment by zongzipan** [comment]
相同的问题
