### ISSUE TITLE
刷流配置不转移媒体库，但是不生效

### ISSUE THREAD

**Issue by dyimo** [NAStool/nas-tools#3761]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 
> 3.0.2
> 环境: docker
>docker

## 你遇到什么问题了？

> 使用刷流任务时，配置了不转移媒体库，但是没有生效，我使用目录同步的方式硬链接转移的媒体库

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已搜索

## 你期望的结果

> 期望不转移媒体库

## 给出程序界面截图、后台运行日志或配置文件

> 
![image](https://user-images.githubusercontent.com/10841232/224253117-b7420d64-465e-4e9e-b65a-c6fd98f10f8b.png)
![image](https://user-images.githubusercontent.com/10841232/224253463-c4f2a3dd-b77e-4d74-a868-13d86a83f9e8.png)
![image](https://user-images.githubusercontent.com/10841232/224253538-4460b88f-154c-4f3f-98d4-8770fae830d1.png)

![image](https://user-images.githubusercontent.com/10841232/224253032-5dfc3e61-975f-45bd-a261-e62d042e67ee.png)

> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
是否转移到媒体库是以是否有添加“已整理”标签来判断的，请观察下新增的刷流任务（还没有触发转移时）是否有这个标签。

**Comment by dyimo** [comment]
> 是否转移到媒体库是以是否有添加“已整理”标签来判断的，请观察下新增的刷流任务（还没有触发转移时）是否有这个标签。

确认新增的刷流任务是有这个标签的，但是我的媒体库是通过目录同步的方式来转移的，是否这个方式本身就是没有考虑兼容性的？

目前的解决办法只有新增一个下载器，并且将下载的目录与目录同步中的目录进行区分，才能达到下载候不转移。

**Comment by jxxghp** [comment]
> > 是否转移到媒体库是以是否有添加“已整理”标签来判断的，请观察下新增的刷流任务（还没有触发转移时）是否有这个标签。
> 
> 确认新增的刷流任务是有这个标签的，但是我的媒体库是通过目录同步的方式来转移的，是否这个方式本身就是没有考虑兼容性的？
> 
> 目前的解决办法只有新增一个下载器，并且将下载的目录与目录同步中的目录进行区分，才能达到下载候不转移。

用目录监控，你就分开目录，不要监控这个目录。
