### ISSUE TITLE
Web通知中心能选择通知内容

### ISSUE THREAD

**Issue by git-0101** [NAStool/nas-tools#3780]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.3
>
> 环境: docker
## 你想要新增或者改进什么功能？

> 希望作者大大可以改动一下。之前是支持选择的。一直都是直接把web当app用。没有弄第三方通知，都是直接看自带通知中心，哈哈。

**Comment by jxxghp** [comment]
这个意义不大，实现很麻烦。

**Comment by git-0101** [comment]
> 这个意义不大，实现很麻烦。

好滴，收到。
