### ISSUE TITLE
plex实时刷新存在问题

### ISSUE THREAD

**Issue by voncoin** [NAStool/nas-tools#3783]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 3.0.0-3.0.2
>
> 环境: docker
>

## 你遇到什么问题了？

> 重启nastools，plex实时刷新正常，过一段时间就不自己刷新了，2.*版本不存在该问题

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by honestpony** [comment]
我也出现这个问题了 PLEX无法实时刷新 3.02版本正常 3.03出现了此问题

**Comment by jxxghp** [comment]
v3.0.3应该修复了，请试试

**Comment by voncoin** [comment]
> v3.0.3应该修复了，请试试

吧nastools和plex都升级到最新版本，问题还在…会不会与我之前从老版本升上来有关系，我尝试下重新安装吧

**Comment by zlhdd108** [comment]
NAS-toos: v3.1.0 59003e7
plex:1.31.2.6810
还是有实时刷新问题，手动刷新媒体库才能看到；入库提示里面有提示新的媒体入库，但是plex要手动刷新一下媒体库才行
