### ISSUE TITLE
正在下载页面显示没有下载任务

### ISSUE THREAD

**Issue by leekyy** [NAStool/nas-tools#3785]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.2 d5cfa49
>
> 环境: Synology docker
>

## 你遇到什么问题了？

> 通过订阅添加的任务，在transmission中可以正常下载，但是在 正在下载页面 中显示没有下载任务

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是的

## 你期望的结果

> 最好可以修复下这个问题，不然没法自动转移下载文件

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

![image](https://user-images.githubusercontent.com/20851015/224467094-de18bb4b-e2f3-44ad-89ed-1d69406d94b4.png)

![image](https://user-images.githubusercontent.com/20851015/224466932-4fef535e-dfa5-4868-85bc-b72f4234d310.png)
[nas-tools.csv](https://github.com/NAStool/nas-tools/files/10947699/nas-tools.csv)

**Comment by Shurelol** [comment]
设置默认下载器

**Comment by leekyy** [comment]
> 设置默认下载器

设置过了

![image](https://user-images.githubusercontent.com/20851015/224472350-82c6ed11-fd62-4878-a86f-54bebdcc8910.png)

**Comment by thsrite** [comment]
<img width="327" alt="image" src="https://user-images.githubusercontent.com/54088512/224475914-b5b0db6a-01fb-4a5f-b0ab-2f16f7e888b6.png">
默认下载器，有没有可能你那个是下载设置？

**Comment by leekyy** [comment]
> ## 你使用的 NAStool 是什么版本，什么环境？
> > NAStool 版本: v3.0.2 [d5cfa49](https://github.com/NAStool/nas-tools/commit/d5cfa496cff6ed65ff4446c7a47ce99b3a3cd228)
> > 环境: Synology docker
> 
> ## 你遇到什么问题了？
> > 通过订阅添加的任务，在transmission中可以正常下载，但是在 正在下载页面 中显示没有下载任务
> 
> ## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
> > 是的
> 
> ## 你期望的结果
> > 最好可以修复下这个问题，不然没法自动转移下载文件
> 
> ## 给出程序界面截图、后台运行日志或配置文件
> > 如UI BUG请提供截图及配置文件截图
> > 其它问题提供后台日志，如为Docker请提供docker的日志
> 
> ![image](https://user-images.githubusercontent.com/20851015/224467094-de18bb4b-e2f3-44ad-89ed-1d69406d94b4.png)
> 
> ![image](https://user-images.githubusercontent.com/20851015/224466932-4fef535e-dfa5-4868-85bc-b72f4234d310.png) [nas-tools.csv](https://github.com/NAStool/nas-tools/files/10947699/nas-tools.csv)
