### ISSUE TITLE
3.0.3认证失败 不存在该用户或者此用户被禁

### ISSUE THREAD

**Issue by Mikcoono1** [NAStool/nas-tools#3787]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 3.0.3
>
> 环境: docker
>

## 你遇到什么问题了？

> 升级3.0.3后 用户认证提示失败 不存在该用户或者此用户被禁 账号可以正常访问憨憨

![微信截图_20230311160844](https://user-images.githubusercontent.com/119794060/224473271-fd73e178-5dda-47e2-b70d-444f9fd8ec10.png)

**Comment by zylyg** [comment]
我也一样

**Comment by jxxghp** [comment]
是哪个站点？

**Comment by d407565739** [comment]
me too
