### ISSUE TITLE
下载器-下载设置点击无反应，刷流没有强制做种选项

### ISSUE THREAD

**Issue by c939984606** [NAStool/nas-tools#3789]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
> v3.0.3 e19b002
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？
下载器-下载设置点击无反应，刷流没有强制做种选项

**Comment by L0yy** [comment]
相同问题+1

**Comment by whale-fall-wh** [comment]
相同问题+1

**Comment by csu97** [comment]
3.0.3版本没遇见，更新了3.0.4后点击下载设置也没有反应了

**Comment by luyufan498** [comment]
+1 我也遇到了 3.0.4

**Comment by huluohu** [comment]
+1 点击无反应，控制台报错：
```javascript
VM2194:467 
        
       Uncaught ReferenceError: None is not defined
    at goto_download_setting (<anonymous>:467:149)
    at <anonymous>:1:1
goto_download_setting @ VM2194:467
(匿名) @ VM2459:1

```

**Comment by jxxghp** [comment]
3.0.4下载设置无法点开的，更新下程序应该可以了，有个PR加了字段但是没有赋默认值

**Comment by lbwstco** [comment]
3.0.5 仍然无法点开
![image](https://user-images.githubusercontent.com/6779378/226534963-6727ce69-be01-45ba-9ca8-9103330d8a6f.png)
