### ISSUE TITLE
刮削图片的fanart.tv，不走基础设置中的代理服务器

### ISSUE THREAD

**Issue by djydtzh** [NAStool/nas-tools#3793]
你使用的 NAStool 是什么版本，什么环境？
NAStool 版本: v 3.0.3

环境: 群晖套件

你想要新增或者改进什么功能？

刮削图片的fanart.tv，不走基础设置中的代理服务器，只能路由器代理

**Comment by thofx** [comment]
看看你的代理加入这个域名没有

**Comment by djydtzh** [comment]
> 看看你的代理加入这个域名没有

加入了，使用的是shellclash的纯净模式。clash日志里可以看见其他的包括规则分流到直连的网址， fanart.tv没在日志里出现。

**Comment by thofx** [comment]
> > 看看你的代理加入这个域名没有
> 
> 加入了，使用的是shellclash的纯净模式。clash日志里可以看见其他的包括规则分流到直连的网址， fanart.tv没在日志里出现。

webservice.fanart.tv 这个域名

**Comment by djydtzh** [comment]
> > > 看看你的代理加入这个域名没有
> > 
> > 
> > 加入了，使用的是shellclash的纯净模式。clash日志里可以看见其他的包括规则分流到直连的网址， fanart.tv没在日志里出现。
> 
> webservice.fanart.tv 这个域名

现在走了，服务里的连接测试也能通过，但是刮削图片有一部分下载速度很慢，会卡一分多钟。直接用clash代理的话图片下载时间会缩短到两三秒。

**Comment by thofx** [comment]
> > > > 看看你的代理加入这个域名没有
> > > 
> > > 
> > > 加入了，使用的是shellclash的纯净模式。clash日志里可以看见其他的包括规则分流到直连的网址， fanart.tv没在日志里出现。
> > 
> > 
> > webservice.fanart.tv 这个域名
> 
> 现在走了，服务里的连接测试也能通过，但是刮削图片有一部分下载速度很慢，会卡一分多钟。直接用clash代理的话图片下载时间会缩短到两三秒。

 看了一下 这个域名没有cdn  所以如果你网络环境不理想的情况 只能上代理。我这边可以直连

**Comment by djydtzh** [comment]
> shellclash



> > > > > 看看你的代理加入这个域名没有
> > > > 
> > > > 
> > > > 加入了，使用的是shellclash的纯净模式。clash日志里可以看见其他的包括规则分流到直连的网址， fanart.tv没在日志里出现。
> > > 
> > > 
> > > webservice.fanart.tv 这个域名
> > 
> > 
> > 现在走了，服务里的连接测试也能通过，但是刮削图片有一部分下载速度很慢，会卡一分多钟。直接用clash代理的话图片下载时间会缩短到两三秒。
> 
> 看了一下 这个域名没有cdn 所以如果你网络环境不理想的情况 只能上代理。

排查了一下，基础设置中的
