### ISSUE TITLE
希望能有个媒体格式的设置选项，就算遇到新的文件格式也只需在设置里面添加一行内容就能识别出媒体。

### ISSUE THREAD

**Issue by zyywo** [NAStool/nas-tools#3794]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.3
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 希望能有个媒体格式的设置选项，就算遇到新的文件格式也只需在设置里面添加一行内容就能识别出媒体。

## 这个功能有什么可以参考的资料吗？

> 比如我今天新下载的电视剧是fak格式，当前版本不认，如果有个设置把.fak添加进去就能识别会很方便很多。
![图片](https://user-images.githubusercontent.com/13588748/224486764-74cf2106-0e8b-43a9-957b-1a54bd0ac85f.png)
![图片](https://user-images.githubusercontent.com/13588748/224487034-c9644ea4-e47f-4a03-84e9-a9e60f78c6d8.png)

**Comment by jxxghp** [comment]
媒体格式并不是加上去就能正常使用，要看情况。
