### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by 1245040330** [NAStool/nas-tools#3799]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 3.0.3
>
> 环境: docker or windows or Synology
>

## 你遇到什么问题了？

> 无法安装

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
![image](https://user-images.githubusercontent.com/32012815/224522041-4ae55168-90c9-4d71-9442-748f7c5a4430.png)

**Comment by jxxghp** [comment]
#3721
