### ISSUE TITLE
实时刷新emby不生效

### ISSUE THREAD

**Issue by Yinghai75** [NAStool/nas-tools#3801]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>3.0.3
> 环境: docker or windows or Synology
>Synology

## 你遇到什么问题了？

> 如标题. 已经开启实时刷新媒体库, 媒体服务器也测试正常.

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> transfer.finished - [<function LibraryRefresh.refresh at 0x7f6258a61630>, <function Webhook.send at 0x7f6258a74160>]

**Comment by Nothend** [comment]
我的也是这样，最新的群晖docker 版本

**Comment by jxxghp** [comment]
3.0.3最新程序已修复

**Comment by Yinghai75** [comment]
可是我就是用的3.03

**Comment by Nothend** [comment]
> 可是我就是用的3.03

我现在的可以了，3.0.3分好几个版本的。。

**Comment by Yinghai75** [comment]
安装3.0.4后解决了
但是刷流任务莫名刷出来几十个...  我设了同时下载2个种子的...  直接把我威联通刷崩溃了
