### ISSUE TITLE
电视剧不能以剧名展示

### ISSUE THREAD

**Issue by hxlex** [NAStool/nas-tools#3804]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.3
> 环境: Synology

> 描述一下你遇到的问题
当下载了两部电视剧时,目录同步会将两部电视剧同时放入国产剧--第一季-- A片01集,B片01集.无法分开展示.

<img width="1439" alt="截屏2023-03-12 20 43 21 1" src="https://user-images.githubusercontent.com/103516954/224545436-40c268e6-06c0-436a-bbc0-e9799cd0d631.png">

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是

## 你期望的结果

> 描述以下你期望的结果

**Comment by TerminalReed** [comment]
在基础设置里关闭二级分类策略，删除媒体库中文件重新刮削

**Comment by hxlex** [comment]
已删除二级分类策略,重新刮削后问题依旧.

**Comment by hxlex** [comment]
> 在基础设置里关闭二级分类策略，删除媒体库中文件重新刮削

大神您好,按照你要求的设置设置后问题依旧,请问还有什么处理办法吗
