### ISSUE TITLE
建议刷流功能单独设置下载目录

### ISSUE THREAD

**Issue by zraxx** [NAStool/nas-tools#3810]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.3
>
> 环境: docker
>

## 你遇到什么问题了？
刷流功能未打开目录同步，仍然自动同步，建议干脆为刷流功能单独设置下载目录
> 描述一下你遇到的问题

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by EliteOtaku** [comment]
本来就可以，下载器那边多设置几个，专门用做PT，比如起名A、B，然后刷流的时候指定那几个PT用的下载器A、B即可

**Comment by zraxx** [comment]
> 本来就可以，下载器那边多设置几个，专门用做PT，比如起名A、B，然后刷流的时候指定那几个PT用的下载器A、B即可

谢谢！
