### ISSUE TITLE
刮削图片支持添加语言偏好

### ISSUE THREAD

**Issue by xushier** [NAStool/nas-tools#3813]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.2
>
> 环境: docker

## 你想要新增或者改进什么功能？

大部分影视的英文海报更加清晰且简洁清爽，中文海报很多文字，较为杂乱、或为繁体、或为蹩脚的台译片名，观感差。
所以建议刮削图片添加可选的语言偏好，喜欢清爽的设置优先英语或原产地语种，喜欢中文的设置优先中文。

TMDB 海报默认尺寸较大，多是 2000x3000，这个分辨率都快能填满整个 4K 屏幕了，但是媒体播放器显示的时候并没有全屏显示的场景，浪费空间。设置小尺寸可以显著加快 Emby 的图片加载速度，Tmm 的 500x750 效果还可以。所以如果可以的话，也建议添加自定义海报尺寸参数。

## 这个功能有什么可以参考的资料吗？

TMDB 的 API 有这些提交参数。

**Comment by EliteOtaku** [comment]
同感

**Comment by jxxghp** [comment]
#3494
