### ISSUE TITLE
定时刷流任务不触发

### ISSUE THREAD

**Issue by csu97** [NAStool/nas-tools#3814]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>v3.0.3
> 环境: docker or windows or Synology
>docker 

## 你遇到什么问题了？
定时刷流任务无法触发。
17:40修改了定时任务，17:47系统自动刷新，设置的定时触发时间为10分钟，在17:50或17：57两个时间节点任务都没有触发

在18:01再一次重新设置定任务，18:11任务触发

## 给出程序界面截图、后台运行日志或配置文件
![Capture](https://user-images.githubusercontent.com/22322995/224669647-8762dce8-a3b4-41d0-a9cc-5ab6154f8b8b.PNG)
![Capture1](https://user-images.githubusercontent.com/22322995/224669672-5165f0e0-e334-4e4b-b198-2e8c5547d0d5.PNG)
![Capture3](https://user-images.githubusercontent.com/22322995/224669701-b3a41bca-136f-4436-b57f-873e6188dc59.PNG)

![image](https://user-images.githubusercontent.com/22322995/224672679-ff80dc65-1df9-4bc5-be6d-047e8d4c70ac.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by csu97** [comment]
<img width="668" alt="image" src="https://user-images.githubusercontent.com/22322995/224725373-3011fb26-fa5a-400e-93f9-1ed8bafa270e.png">

18:01重新设置定时后，任务可以正常触发。在18：47系统再一次自动刷新后，定时任务不再触发
<img width="742" alt="image" src="https://user-images.githubusercontent.com/22322995/224725475-831cb18c-2bbd-4279-b777-9857e65b072f.png">
<img width="758" alt="image" src="https://user-images.githubusercontent.com/22322995/224725623-a9bb3ec6-23f2-4596-acc5-5041b22056f5.png">

**Comment by csu97** [comment]
自定义订阅也有同样的问题

**Comment by kfqkfy** [comment]
同样的问题，重启回来要手动保存下刷流任务，不然没反应

**Comment by csu97** [comment]
3.0.5使用cron表达式仍然存在这个问题

**Comment by csu97** [comment]
目前发现配置文件修改的event触发以后，刷流和自定义订阅这些服务就不会正常触发了
