### ISSUE TITLE
订阅搜索周期增加时间点搜索

### ISSUE THREAD

**Issue by git-0101** [NAStool/nas-tools#3815]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.3
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 目前的订阅搜索周期最小间隔6小时，一天四次。大多数站点发布资源基本集中每天下午和晚上时间段。比方17:00和23:00各搜一次，只需要两次。目前想实现就需要设置最小间隔6小时，这样就搜了四次。并且要在17:00重启配置，让按照这个方式运行下去。如果其它时间因为升级系统重启，还需要等到在这个规律时间点再重启配置，让按照此规律运行下去。所以能否增加时间点搜索，比方17:00；23:00；…最多配置四个点，最小间隔依然是6小时，配置几个点就搜索几次。要是能配置半小时内的随机点就更好了（原因都懂，哈哈）。比方16:30-17:00；23:00-23:30，其它同理。

**Comment by jxxghp** [comment]
订阅应该靠rss，而不是靠搜索

**Comment by git-0101** [comment]
> 订阅应该靠rss，而不是靠搜索

好滴，作者大大，收到！
