### ISSUE TITLE
docker版下载完成后转移失败

### ISSUE THREAD

**Issue by zyywo** [NAStool/nas-tools#3820]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.3
>
> 环境: docker

## 你遇到什么问题了？

> docker版下载完成后提示文件不存在，转移失败
> 怀疑转移用的是宿主机路径，而非容器内路径导致的

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> docker版下载完成后能正常转移

## 给出程序界面截图、后台运行日志或配置文件
文件在容器内的路径：`/home/media/qb_downloads/SCTV.Ji.Gong.You.Ji.1998.HDTV.1080i.H264-HDCTV`
文件在宿主机内的路径：`/home/pi/nextcloud/html/data/media/qb_downloads/SCTV.Ji.Gong.You.Ji.1998.HDTV.1080i.H264-HDCTV/`

**nastool的日志**
<img width="839" alt="NASTOOL转移失败日志" src="https://user-images.githubusercontent.com/13588748/224865725-86477b31-7efd-46de-95c2-407a58045f39.png">

**下载器设置**
<img width="535" alt="下载器设置" src="https://user-images.githubusercontent.com/13588748/224865924-ccafc199-3966-4024-b979-ad3e5c01d80d.png">

**文件在容器内的路径**
<img width="987" alt="容器中的路径" src="https://user-images.githubusercontent.com/13588748/224865962-9ce32970-38d4-42d8-9a03-ffb3cb1faecc.png">

**Comment by sypopo** [comment]
你自己没把路径写对吧

**Comment by zyywo** [comment]
> 你自己没把路径写对吧


要怎么写呢？

**Comment by zyywo** [comment]
已解决
在下载器设置里面把下载目录设置为宿主机目录，访问目录设置为容器目录即可。
