### ISSUE TITLE
老大，能不能增加一个新功能，新出的热门电影，电视剧评分大于多少分的自动加订阅。

### ISSUE THREAD

**Issue by 26712681** [NAStool/nas-tools#3821]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>
> 环境: docker or windows or synology

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by oynt** [comment]
这个听着不错

**Comment by jxxghp** [comment]
豆瓣榜单订阅插件，且支持设置评分。
