### ISSUE TITLE
cf优选插件运行不了

### ISSUE THREAD

**Issue by SchrodingerBarbatos** [NAStool/nas-tools#3840]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
> v3.0.4 3284ef7
> 环境: docker or windows or Synology
> docker

## 你遇到什么问题了？

> cf优选插件运行不了

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 无法解决

## 你期望的结果

> 正常运行

## 给出程序界面截图、后台运行日志或配置文件

> ![image](https://user-images.githubusercontent.com/78670748/225353224-96afb2de-7d10-4e3e-a9ac-1ee52e9ba131.png)
![image](https://user-images.githubusercontent.com/78670748/225353308-a0a97a5e-2186-4a58-bc60-536f4575e459.png)
![image](https://user-images.githubusercontent.com/78670748/225353420-0f88467f-5745-4379-9f05-d8e9dabbd75a.png)

**Comment by zouhy2001** [comment]
> ## 你使用的 NAStool 是什么版本，什么环境？
> > NAStool 版本: vx.x.x
> > v3.0.4 [3284ef7](https://github.com/NAStool/nas-tools/commit/3284ef7de2005d8f6abb41b523ae77ab34358f0b)
> > 环境: docker or windows or Synology
> > docker
> 
> ## 你遇到什么问题了？
> > cf优选插件运行不了
> 
> ## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
> > 无法解决
> 
> ## 你期望的结果
> > 正常运行
> 
> ## 给出程序界面截图、后台运行日志或配置文件
> > ![image](https://user-images.githubusercontent.com/78670748/225353224-96afb2de-7d10-4e3e-a9ac-1ee52e9ba131.png)
> > ![image](https://user-images.githubusercontent.com/78670748/225353308-a0a97a5e-2186-4a58-bc60-536f4575e459.png)
> > ![image](https://user-images.githubusercontent.com/78670748/225353420-0f88467f-5745-4379-9f05-d8e9dabbd75a.png)

把代理给删了，下载完再提填回去。

**Comment by thsrite** [comment]
网络问题，有的梯子访问github api受限

**Comment by SchrodingerBarbatos** [comment]
可以了，谢谢各位

**Comment by foreverlove1995** [comment]
怎么解决的

**Comment by thsrite** [comment]
> 怎么解决的

上面说了，网络问题，如果你基础设置里面设置了代理服务器就去掉再用优选插件，有些梯子万人骑访问github api受限
