### ISSUE TITLE
ChatGPT是否走代理

### ISSUE THREAD

**Issue by huluohu** [NAStool/nas-tools#3841]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.4
>
> 环境: docker

## 你遇到什么问题了？

> 开启ChatGPT识别增强，访问openai时是否走代理？

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 没有类似的Issue

## 你期望的结果

> 支持走代理，目前国内无法直接访问openai；另外建议在网络连通性检测中加入openai的域名

**Comment by thsrite** [comment]
已经支持代理了

**Comment by huluohu** [comment]
> 已经支持代理了

好的，谢谢啦。
