### ISSUE TITLE
添加默认链接方式；添加剧集主题音乐刮削。

### ISSUE THREAD

**Issue by xushier** [NAStool/nas-tools#3846]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.4
>
> 环境: docker

## 你想要新增或者改进什么功能？

以前的版本中基本设置里可以选择**默认链接方式**。现在默认是硬链，手动转移的时候，如果不是默认的硬链接，每次都要手动切换为其他的，容易忘记。

剧集的主题音乐目前没有刮削，Tmm 可以刮削，但不清楚音乐刮削源是哪里。

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by jxxghp** [comment]
默认选项已回归。
主题音乐不考虑。
