### ISSUE TITLE
希望能自定义openAI api 的 url

### ISSUE THREAD

**Issue by shanyan-wcx** [NAStool/nas-tools#3848]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.4
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 希望能自定义openAI api 的 url

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by jxxghp** [comment]
dev己支持
