### ISSUE TITLE
界面UI BUG，选择目录显示不完整

### ISSUE THREAD

**Issue by Kev1nT** [NAStool/nas-tools#3849]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本:  v3.0.4 56cc51a
>
> 环境: docker
>

## 你遇到什么问题了？

[>]
选择目录显示不完整
![网页捕获_16-3-2023_113354_10 10 10 100](https://user-images.githubusercontent.com/49979564/225507986-503d845b-0efc-4e06-9dc8-df175f9fa11c.jpg)

**Comment by Wangsc1** [comment]
手机端刷流这里也是
![image](https://user-images.githubusercontent.com/26079238/225520616-1ad06444-feff-43b3-81a2-8ac45b1de04f.jpeg)

**Comment by jxxghp** [comment]
已修复
