### ISSUE TITLE
能否增加刮削设置，例如刮削海报的分辨率和语言

### ISSUE THREAD

**Issue by 248931367** [NAStool/nas-tools#3850]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本:3.04
>
> 环境:  synology

## 你想要新增或者改进什么功能？

能否增加刮削设置，例如刮削海报的分辨率和语言。
目前NAStool刮削下来的海报分别率都是最大的，芝杜的海报墙和KODI的海报墙都经常显示不出来。

**Comment by jxxghp** [comment]
#3494
