### ISSUE TITLE
从2.9.0版本直接拉取3.0.4镜像后前端无下载器等各类设置选项

### ISSUE THREAD

**Issue by sn066** [NAStool/nas-tools#3855]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.4
>
> 环境: docker
>

## 你遇到什么问题了？

> 从2.9.0版本直接拉取3.0.4镜像后前端无下载器等各类设置选项, 且搜索框点击无响应
> 已清除浏览器缓存,页面更新版本,均无效
> 页面展示如下:

<img width="1510" alt="image" src="https://user-images.githubusercontent.com/32016161/225568375-fcb18dbc-a930-416a-a220-557d3fe8fc3c.png">

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by coco-w** [comment]
解决了吗？我也遇到了这个问题
