### ISSUE TITLE
内置搜索器有问题

### ISSUE THREAD

**Issue by orzcz** [NAStool/nas-tools#3858]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.04
>
> 环境: docker
>

## 你遇到什么问题了？

> 站点cookie都是生效的，但是搜索结果只展示一个站
![image](https://user-images.githubusercontent.com/26238769/225657978-d4516d17-2f43-41de-9ae3-90f155a2ebd3.png)
![image](https://user-images.githubusercontent.com/26238769/225658145-b676bf70-10aa-49f7-ab9b-42036bdde4a5.png)
![image](https://user-images.githubusercontent.com/26238769/225658559-1223e1ef-7cf9-4b4f-8e7c-8e412021f49e.png)

我确保这个资源很多站都有的，从2.9.x升上来的，之前搜索很多资源的

**Comment by xnoods** [comment]
正常，这个搜索器本身搜索的结果就不是很准，一直都这样，多搜几次试试

**Comment by dlovew** [comment]
试了一下显微镜下的大明，一大堆资源，正常搜索。

**Comment by orzcz** [comment]
> 试了一下显微镜下的大明，一大堆资源，正常搜索。

对啊我之前的版本也可以搜到很多，所以我才说有Bug

**Comment by xnoods** [comment]
检索的效果确实不咋地，还有自定义订阅，问题更多，经常本地已经下载了，还是显示本地不存在

**Comment by dlovew** [comment]
你是什么环境，我是x86 docker最新版没问题！基本上稍微大一点的版本更新我都是重新拉镜像！建议重拉镜像！

**Comment by dlovew** [comment]
有问题可以看看日志或者把日志贴出来让大家分析分析

**Comment by jxxghp** [comment]
过滤规则检查了吗？也不贴日志谁知道你在说啥。

**Comment by jxxghp** [comment]
> 正常，这个搜索器本身搜索的结果就不是很准，一直都这样，多搜几次试试

别瞎说行吗？

**Comment by jxxghp** [comment]
> 检索的效果确实不咋地，还有自定义订阅，问题更多，经常本地已经下载了，还是显示本地不存在

是的，求你别用了，无脑喷子这里不欢迎。

**Comment by orzcz** [comment]
<img width="771" alt="image" src="https://user-images.githubusercontent.com/26238769/225835482-6c380276-dedc-4fd1-8ffd-bc8732109440.png">
<img width="430" alt="image" src="https://user-images.githubusercontent.com/26238769/225835597-adce652d-8b6e-4579-8437-c83e9fac616c.png">

**Comment by orzcz** [comment]
> 

规则升级前后无变化

**Comment by orzcz** [comment]
**
<img width="897" alt="image" src="https://user-images.githubusercontent.com/26238769/225836224-ec064d2e-6046-4ebc-9ef8-35104c97ff48.png">
**
其他资源也是这样，而且这个有结果的站，在cookie测试中是提示失败的

**Comment by orzcz** [comment]
开源项目，提倡大家心态平和哈，有问题说问题。来提issue也是想帮助项目走得更好

**Comment by jxxghp** [comment]
> <img width="771" alt="image" src="https://user-images.githubusercontent.com/26238769/225835482-6c380276-dedc-4fd1-8ffd-bc8732109440.png">
> 
> <img width="430" alt="image" src="https://user-images.githubusercontent.com/26238769/225835597-adce652d-8b6e-4579-8437-c83e9fac616c.png">
> 
> 

你这个更像是网络上完全连不上，开发们自己也在用，这么明显的问题我们自己就能发现，我这重现不了。
或者试试重新拉镜像重新搭建。

**Comment by jxxghp** [comment]
> 开源项目，提倡大家心态平和哈，有问题说问题。来提issue也是想帮助项目走得更好

赞成。本来大家都是基于兴趣，也从未求回报，还冒着被曝光的风险。开源项目有问题需要大家一起解决，有的人白嫖还当自己是大爷，不讲缘由各种喷，不好用你可以不用，非要把大家唯一的一点点动力都给磨没了。

**Comment by orzcz** [comment]
> > <img alt="image" width="771" src="https://user-images.githubusercontent.com/26238769/225835482-6c380276-dedc-4fd1-8ffd-bc8732109440.png">
> > <img alt="image" width="430" src="https://user-images.githubusercontent.com/26238769/225835597-adce652d-8b6e-4579-8437-c83e9fac616c.png">
> 
> 你这个更像是网络上完全连不上，开发们自己也在用，这么明显的问题我们自己就能发现，我这重现不了。 或者试试重新拉镜像重新搭建。

重拉镜像好了，我之前一直是用你们内置的升级
