### ISSUE TITLE
大佬，可以加一个丐帮的(https://gainbound.net/),最近有邀请，可以联系我295558386@qq.com,你可以先测试一下，麻烦了

### ISSUE THREAD

**Issue by liluosheng** [NAStool/nas-tools#3863]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 最新版
>
> 环境:  synology的docker

## 你想要新增或者改进什么功能？
添加新的站点：丐帮：  https://gainbound.net/
         海胆： https://www.haidan.video/index.php
        高清世界：https://www.hdarea.co/torrents.php
> 你想要新增或者改进什么功能？
      最近丐帮我可以帮你邀请一个，希望可以添加以上的站点，真心希望，原来的版本是可以用的现在用不了了。
## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by c939984606** [comment]
你在说啥，加一个什么？站点验证还是什么

**Comment by liluosheng** [comment]
对加一个丐帮的站点就可以

**Comment by jxxghp** [comment]
这三个部索引都支持。但认证不支持，找支持的站认证进去后就可以用了
