### ISSUE TITLE
订阅搜索结果显示不匹配

### ISSUE THREAD

**Issue by kfqkfy** [NAStool/nas-tools#3869]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: [v3.0.4 8982d19]
>
> 环境: docker 
>

## 你遇到什么问题了？

搜索订阅 回响，查到了结果了但是提示不匹配

查询结果：Echo
--
18:46:02 | Indexer | Echo 2023 S01E01-E04 1080p WEB-DL H.264 AAC-JKCT 识别为 电视剧 Echo (2023) 不匹配

**Comment by urzz** [comment]
同一个问题，tmdb是有收录的。

https://www.themoviedb.org/tv/222186?language=zh

**Comment by MyFaith** [comment]
我也一样，tmdb上也有一部剧叫Echo，也是2023年，这两个识别和搜索的时候总是错，完全随缘

**Comment by sypopo** [comment]
同样问题

**Comment by urzz** [comment]
在新增了自定义识别词后，暂时解决了

![image](https://user-images.githubusercontent.com/11271721/226231886-e333d0d2-a2e1-413b-995d-a32507100c76.png)

**Comment by MyFaith** [comment]
> 在新增了自定义识别词后，暂时解决了
> 
> ![image](https://user-images.githubusercontent.com/11271721/226231886-e333d0d2-a2e1-413b-995d-a32507100c76.png)

确实能解决，但是在转移的时候会识别成另外一部 Echo(2023)

**Comment by urzz** [comment]
> > 在新增了自定义识别词后，暂时解决了
> > ![image](https://user-images.githubusercontent.com/11271721/226231886-e333d0d2-a2e1-413b-995d-a32507100c76.png)
> 
> 确实能解决，但是在转移的时候会识别成另外一部 Echo(2023)

我这边转移和刮削是正常的，或者你手动识别一下试试
![image](https://user-images.githubusercontent.com/11271721/226232480-9f50e9bf-c792-4d60-95c0-cded3bc0e7b2.png)

**Comment by jxxghp** [comment]
关键在于回响这个剧没有Echo的别名，Echo的是另一部，所以不匹配。
TMDB数据问题，无解。
