### ISSUE TITLE
存储空间容量获取错误

### ISSUE THREAD

**Issue by Hcczz** [NAStool/nas-tools#3877]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.4
>
> 环境: docker Unraid
>

## 你遇到什么问题了？

> 媒体库设置了4块4T的硬盘，实际总容量只显示了一块的容量

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已经浏览过

## 你期望的结果

> 总容量应该显示为4*3.64=14.56

## 给出程序界面截图、后台运行日志或配置文件

> ![image](https://user-images.githubusercontent.com/125752805/226099569-a121e2df-945d-453a-b0da-6a961d3e2bf2.png)
![image](https://user-images.githubusercontent.com/125752805/226099574-79acaea1-dd87-451a-b391-f592e7b5b5d0.png)

**Comment by jxxghp** [comment]
3.1.0已调整算法

**Comment by Hcczz** [comment]
> 3.1.0已调整算法

已更新 比之前的负数观感好多了 不过还有点小问题
![image](https://user-images.githubusercontent.com/125752805/227757983-1dadf83b-3d0d-4aa7-b3e6-7341ce7b013f.png)
目前来看还是少算了一块盘 存储空间是3*3.64=10.92≈图中的10.91

下面是我Unraid中的
4块4T应该共使用了9.87T
![image](https://user-images.githubusercontent.com/125752805/227758088-5bc4ec19-5ee1-4de2-a90a-bc6e8aeb6e8f.png)
