### ISSUE TITLE
有些资源只能使用高级搜索才能返回结果

### ISSUE THREAD

**Issue by git-0101** [NAStool/nas-tools#3879]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.4
>
> 环境: docker
>

## 你遇到什么问题了？

> 如题：比如 回响 这部剧。之前还有几次也遇到过。作者大大看看啥情况。
<img width="380" alt="f99220a34350e13" src="https://user-images.githubusercontent.com/115487446/226101597-66658f67-3c75-4f50-aead-23c352b92f85.png">

**Comment by thofx** [comment]
tmdb未收录

**Comment by git-0101** [comment]
> tmdb未收录

大佬！明白了
