### ISSUE TITLE
企业微信应用消息通知的智能识别问题

### ISSUE THREAD

**Issue by akonegod** [NAStool/nas-tools#3881]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: [v3.0.4 b66edb7](https://github.com/NAStool/nas-tools)
>
> 环境: docker
>

## 你遇到什么问题了？

> 企业微信通知消息我设置了两个应用，两个应用中Token和EncodingAESKey不同，但似乎nastool不能智能的识别哪个应用发送的互动消息，并据此解密消息，它只会机械的应用某一个应用的token和EncodingAESKey并回复此应用。另一个应用不能识别互动消息。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 智能识别微信应用消息并回复那个应用

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
![image](https://user-images.githubusercontent.com/39025585/226107802-f7f6cb49-ae9f-407c-963f-a7fff16e41d0.png)

![image](https://user-images.githubusercontent.com/39025585/226107724-3e230983-c6b2-42b3-b0d1-95b8ebb4d48a.png)

**Comment by thsrite** [comment]
有没有可能你token和key填错了？

**Comment by akonegod** [comment]
> 有没有可能你token和key填错了？

没有可能，因为我在消息通知界面设置完最后点哪个应用的确定哪个应用就能正常互动，另一个则不能。

**Comment by thsrite** [comment]
交互只能开启一个。这里有个bug，你自己去掉一个

**Comment by akonegod** [comment]
> 交互只能开启一个。这里有个bug，你自己去掉一个
好的，谢谢。请问以后会修复这个bug吗？

**Comment by akonegod** [comment]
如果我将两个应用的token和key填成相同的则会出现这种情况，它的互动消息集中到某个应用回复，另一个不会回复。
![image](https://user-images.githubusercontent.com/39025585/226111446-22c5c363-a63d-4544-8f99-99a66c0754d4.png)
![a15e1c10b74a4b010bc68bd365a98b0](https://user-images.githubusercontent.com/39025585/226111600-cf05c3d2-b807-4bab-b046-b6077304663b.jpg)

**Comment by thsrite** [comment]
> > 交互只能开启一个。这里有个bug，你自己去掉一个
> > 好的，谢谢。请问以后会修复这个bug吗？

嗯 很快修复了

**Comment by thsrite** [comment]
> 如果我将两个应用的token和key填成相同的则会出现这种情况，它的互动消息集中到某个应用回复，另一个不会回复。 ![image](https://user-images.githubusercontent.com/39025585/226111446-22c5c363-a63d-4544-8f99-99a66c0754d4.png) ![a15e1c10b74a4b010bc68bd365a98b0](https://user-images.githubusercontent.com/39025585/226111600-cf05c3d2-b807-4bab-b046-b6077304663b.jpg)

同理，统一类型的只能开启一个交互，不能多个

**Comment by akonegod** [comment]
> > 如果我将两个应用的token和key填成相同的则会出现这种情况，它的互动消息集中到某个应用回复，另一个不会回复。 ![image](https://user-images.githubusercontent.com/39025585/226111446-22c5c363-a63d-4544-8f99-99a66c0754d4.png) ![a15e1c10b74a4b010bc68bd365a98b0](https://user-images.githubusercontent.com/39025585/226111600-cf05c3d2-b807-4bab-b046-b6077304663b.jpg)
> 
> 同理，同一消息类型的只能开启一个交互，不能多个
