### ISSUE TITLE
【功能建议】按照「剧集」订阅

### ISSUE THREAD

**Issue by leekyy** [NAStool/nas-tools#3894]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本:  v3.0.4 b66edb7
>
> 环境: synology

## 你想要新增或者改进什么功能？

> 
目前我是刚使用nas-tool，不太确定剧集订阅的机制。说错的话请反驳

但是根据我目前看到的功能来讲剧集订阅需要手动选择要订阅的「季」，
这样的话如果出了最新的一季的话是否需要重新去订阅最新的一季剧集？

如果需要的话这样是否有些麻烦。是否可以推出按照「整部剧集」来订阅而不是按照「季」来订阅的功能。

## 这个功能有什么可以参考的资料吗？

> 因为我之前使用的是sonnar，他可以规避上述提到的问题

**Comment by thsrite** [comment]
你这一部剧订阅完成了，然后后台得一直定时检索已订阅完成的剧，查查有没有新季出来，再给你自动重新订阅？

**Comment by leekyy** [comment]
> 

大概是这样，目前可以用这种功能吗？

**Comment by leekyy** [comment]
> 你这一部剧订阅完成了，然后后台得一直定时检索已订阅完成的剧，查查有没有新季出来，再给你自动重新订阅？

大概是这样，目前可以用这种功能吗？

**Comment by thsrite** [comment]
> > 你这一部剧订阅完成了，然后后台得一直定时检索已订阅完成的剧，查查有没有新季出来，再给你自动重新订阅？
> 
> 大概是这样，目前可以用这种功能吗？

没有

**Comment by leekyy** [comment]
> > > 你这一部剧订阅完成了，然后后台得一直定时检索已订阅完成的剧，查查有没有新季出来，再给你自动重新订阅？
> > 
> > 
> > 大概是这样，目前可以用这种功能吗？
> 
> 没有

不知道sonnar是如何实现的，但是希望可以添加这样的功能，要不有些麻烦

**Comment by thsrite** [comment]
> > > > 你这一部剧订阅完成了，然后后台得一直定时检索已订阅完成的剧，查查有没有新季出来，再给你自动重新订阅？
> > > 
> > > 
> > > 大概是这样，目前可以用这种功能吗？
> > 
> > 
> > 没有
> 
> 不知道sonnar是如何实现的，但是希望可以添加这样的功能，要不有些麻烦

如果订阅过的不想看了呢，按你的想法，还得手动去历史订阅里面删掉不想看的剧？

**Comment by thsrite** [comment]
倒是可以订阅的时候加个参数，选择该剧是否自动追新，默认否

**Comment by leekyy** [comment]
> 倒是可以订阅的时候加个参数，选择该剧是否自动追新，默认否

可以，之前用sonnar的时候，我的操作动线一般是
看到了想看的剧，在sonnar订阅之后就不管了，下载完成之后看到推送的消息，就在电视上看了。
不会反复操作同一部剧集这样的
