### ISSUE TITLE
建议刷流功能 增加定时启动、关闭功能。

### ISSUE THREAD

**Issue by zraxx** [NAStool/nas-tools#3895]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.4
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？
建议刷流功能增加 定时启动、关闭功能。谢谢！![Screenshot_2023-03-19-15-24-02-644_com.android.browser.png](https://user-images.githubusercontent.com/25578054/226160384-f878b0e0-76a3-4b46-9693-64b01f147ee2.png)

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by XiaYi1002** [comment]
大概的意思 应该就是 可以设置时间段 比如白天7：00-18：00 家里没人可以开起来刷流 晚上 家里有人 就关闭刷流 防止抢占带宽

**Comment by XiaYi1002** [comment]
我的想法就是   非刷流时间段 就禁止添加新种   已存在的种子 添加上下行限速   到了执行时间段 就解除限速 ，种子如果连接性好点的，上传被跑满，微信信息都有转圈圈，更别说玩游戏了，个人经历

**Comment by urzz** [comment]
可以考虑先设置qb和tr的备用速度限制，可以分时段上传/下载速度限制

比如qb：
![image](https://user-images.githubusercontent.com/11271721/226169835-639de8ca-65a3-49a1-9140-c064b318bcda.png)

**Comment by XiaYi1002** [comment]
用过这个功能 qb的限速跟闹着玩一样 无效设置用的是win的4.4.5  然后docker版本的4.3.9都测试过 都不行  很无语 问过其他人也是如此

**Comment by jxxghp** [comment]
下个版本会支持cron表达式，应该可以通过这个来设定运行时间

**Comment by urzz** [comment]
> 用过这个功能 qb的限速跟闹着玩一样 无效设置用的是win的4.4.5 然后docker版本的4.3.9都测试过 都不行 很无语 问过其他人也是如此

@XiaYi1002 我丢，我设置了就没咋管了，看了眼ikuai的监控发现确实没啥用= =

**Comment by jxxghp** [comment]
> > 下个版本会支持cron表达式，应该可以通过这个来设定运行时间
> 
> 
> 
> @jxxghp 哈喽，咨询一下，支持cron表达式后，在非允许运行时间会控制下载器自动停止刷流做种吗？还是只会停止刷流任务的进行，不再新增/删除刷流的种子

只是不会新增刷流，已经在刷的还会维护。

**Comment by zraxx** [comment]
> > > 下个版本会支持cron表达式，应该可以通过这个来设定运行时间
> > 
> > 
> > 
> > @jxxghp 哈喽，咨询一下，支持cron表达式后，在非允许运行时间会控制下载器自动停止刷流做种吗？还是只会停止刷流任务的进行，不再新增/删除刷流的种子
> 
> 只是不会新增刷流，已经在刷的还会维护。

建议：增加刷流功能批量操作，全选或部分选择站点开始或暂停，谢谢！
