### ISSUE TITLE
重启Nas掉站点认证

### ISSUE THREAD

**Issue by tsymr** [NAStool/nas-tools#3903]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 3.0.4
>
> 环境: docker
>

## 你遇到什么问题了？

> 重启nas后偶现掉站点认证

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 如果已经认证过是否可以不再需要进行认证，不然重启nas后如果没有进入过nas-tools可能会不知道是否掉了验证

## 给出程序界面截图、后台运行日志或配置文件

> 无
> 无

**Comment by jxxghp** [comment]
重启是会自动重新认证的，只有自动重新认证的时候站点连不上或者你的账号状态不正常了才需要手工认证。

另外，重启后不管是否认证都不影响已经配置好的后台功能正常运行，只是后台界面菜单看不到。

**Comment by tsymr** [comment]
> 重启是会自动重新认证的，只有自动重新认证的时候站点连不上或者你的账号状态不正常了才需要手工认证。
> 
> 另外，重启后不管是否认证都不影响已经配置好的后台功能正常运行，只是后台界面菜单看不到。

好的，明白了，辛苦大佬。
