### ISSUE TITLE
Audiences 站点 报错

### ISSUE THREAD

**Issue by codeses** [NAStool/nas-tools#3905]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.2
>
> 环境: Synology
>

## 你遇到什么问题了？

> 描述一下你遇到的问题

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

![image](https://user-images.githubusercontent.com/58210554/226243816-f0bdbd50-6647-42c3-b3b6-8d14c1d31cef.png)

cookie和订阅都是新的，但是测试的时候提示cookie过期
![image](https://user-images.githubusercontent.com/58210554/226243779-39a1349d-4153-46df-bc2e-68b56d852a80.png)

**Comment by codeses** [comment]
现在配置对了  但是索引还是报错
![image](https://user-images.githubusercontent.com/58210554/226245141-91eb4fec-ee45-4f79-af61-8b45d9b71ed4.png)

**Comment by thsrite** [comment]
tmdb key配置了吗。网络连通测试都正常吗？
看看日志 请求tmdb的时候是不是报错了

**Comment by codeses** [comment]
> tmdb key配置了吗。网络连接测试都正常吗？ 看日志请求tmdb的时候不是报错了

重启以后没问题了
