### ISSUE TITLE
新增下载功能增加种子链接进行下载

### ISSUE THREAD

**Issue by cend1s** [NAStool/nas-tools#3907]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.4
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 目前版本网页中进行下载，只能通过上传种子进行，希望增加通过种子链接进行下载的方式。每次从站点中下载种子再上传到网页中很繁琐，直接上传链接会方便很多。

## 这个功能有什么可以参考的资料吗？

>

**Comment by jxxghp** [comment]
已支持
