### ISSUE TITLE
电视剧硬链接同步问题

### ISSUE THREAD

**Issue by huoxinghao** [NAStool/nas-tools#3908]
## 矿神的源，黑群晖

> NAStool 版本: 3.0.2
>
> 环境:  Synology
>

## 你遇到什么问题了？：电视剧硬链接同步问题

> 描述一下你遇到的问题：电视剧同步格式如果为两级的目录，即每一季电视剧一个文件夹，则会出现同步出错
![c90c6ed4c614845a953c77f24b11c55](https://user-images.githubusercontent.com/41751084/226285973-fae9f5bf-e6b0-42b3-8278-9777fabf8495.jpg)

![8e9b78ceaaf9e3499d5b2bbeb12a4d2](https://user-images.githubusercontent.com/41751084/226285956-6045dbed-0986-47ab-a200-77eb9e50d4a9.jpg)

## 你期望的结果：希望电视剧识别为一季一个文件夹

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
![d08c4e7fa024936c6fc7665754e735b](https://user-images.githubusercontent.com/41751084/226286346-14987ceb-f7b7-4c9e-8d9f-0d3f6ee1e936.jpg)

**Comment by jxxghp** [comment]
不支持这种目录结构

**Comment by huoxinghao** [comment]
请问以后会支持吗？因为我用的infuse，如果是三级目录的话会出现第一层目录没有海报的情况，如图所示[图片]，最后，感谢您的回复。
