### ISSUE TITLE
emby播放时限速功能无法实现

### ISSUE THREAD

**Issue by anyishusheng** [NAStool/nas-tools#3914]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.5
> 环境: unraid  docker
## 你遇到什么问题了？
> emby已经设置webhook，nastool日志里也有处理事件。如下：处理事件：emby.webhook - [<function MovieLike.favtransfer at 0x14e63e199d80>, <function SpeedLimiter.emby_action at 0x14e63e19add0>]。可是下载器不限速，日志也没有限速的提示
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是的
> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 希望可以帮我解决这个问题，实现emby播放时限速功能

## 给出程序界面截图、后台运行日志或配置文件
![Screenshot 2023-03-20 185155](https://user-images.githubusercontent.com/128374731/226321876-9e0ad680-7364-4a83-aae4-2eb22888f8b7.png)
![Screenshot 2023-03-20 185222](https://user-images.githubusercontent.com/128374731/226321903-17d126a4-87fc-4257-b154-46bd58e07758.png)

> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
这个已经被证实是可以正常工作的。
你要看你是不是外网播放，还有是不是Ipv6
