### ISSUE TITLE
转移默认配置错位

### ISSUE THREAD

**Issue by git-0101** [NAStool/nas-tools#3916]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.5
>
> 环境: docker
>

## 你遇到什么问题了？

> 第一个应该是 硬链接 手动转移里面是硬链接
这里应该选项错位了 复制应该在下面
![Screenshot_20230320_203619](https://user-images.githubusercontent.com/115487446/226341754-69abf68d-2702-436e-b6c2-4c399ac649dc.jpg)

**Comment by jxxghp** [comment]
不影响，选项实际值是对的就行
