### ISSUE TITLE
蓝光原盘可识别成功，但元数据的命名不对

### ISSUE THREAD

**Issue by mrwensim** [NAStool/nas-tools#3917]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.5
>
> 环境: docker
>

## 你遇到什么问题了？

> 比如蓝光原盘目录 Unbreakable.2000.2160p.UHD.Blu-ray.HEVC.DTS-HD.MA.5.1-DiY@HDHome 可以成功识别，并硬链接到新的蓝光原盘目录 不死劫（2000），但刮削后的元数据文件名为 不死劫 (2000) - 2160p.nfo，此为默认命名规则，2160p为videoformat。
> 但是对于蓝光原盘目录，Jellyfin支持的NFO文件名格式为 movie.nfo, VIDEO_TS.nfo 或者 不死劫 (2000).nfo 。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是的。

## 你期望的结果

> 一种解决办法是把videoformat从命名规则里拿掉。
> 但是能不能对蓝光原盘的元数据命名进行单独处理，这样其他的movie文件也可以保留 videoformat？

**Comment by jxxghp** [comment]
emby中能识别吗？
