### ISSUE TITLE
plex webook 无法正常触发限速

### ISSUE THREAD

**Issue by beermedlar** [NAStool/nas-tools#3919]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.5
>
> 环境: docker
>

## 你遇到什么问题了？

> plex webhook请求后，能在后台日志看到请求，但随即抛出异常

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> webhook正常触发限速

## 给出程序界面截图、后台运行日志或配置文件

```
2023-03-20 21:06:46,560 INFO: 处理事件：plex.webhook - [<function SpeedLimiter.plex_action at 0x148d8dd823b0>]
Exception: list index out of range
Callstack:
Traceback (most recent call last):
  File "/nas-tools/web/backend/web_utils.py", line 25, in get_location
    c1 = html.split('location":"')[1]
IndexError: list index out of range
```

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
这个报错是不影响的，原因不在这里。

**Comment by Shurelol** [comment]
[#3918](https://github.com/NAStool/nas-tools/pull/3918)
已解决
