### ISSUE TITLE
字幕插件好像不生效了

### ISSUE THREAD

**Issue by paysenyu** [NAStool/nas-tools#3921]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 3.0.5
>
> 环境: docker 
>

## 你遇到什么问题了？

![image](https://user-images.githubusercontent.com/51367628/226381618-26f5773d-e605-451b-b5cd-324620ff2628.png)

目前自动搜刮的片在日志中均未向chinesesubfinder 传送下载请求。

已经核对插件中，服务器地址和API KEY 是正常填写的。

同时对于nt 尝试过重启，更新，以及pull

**Comment by jxxghp** [comment]
文件管理里面手动触发下字幕下载看是否会打日志

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/51039935/226491543-44a7de7c-b747-44c0-bc45-b1643630177b.png">

**Comment by paysenyu** [comment]
> 文件管理里面手动触发下字幕下载看是否会打日志
> 
> <img alt="image" width="1132" src="https://user-images.githubusercontent.com/51039935/226491543-44a7de7c-b747-44c0-bc45-b1643630177b.png">

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/51367628/226497837-9e64e2b8-c5c2-4f6e-8cc2-4a05d2c71fcd.png">

会的，手动下载字幕能看到触发，并且csf 中也能生成任务

**Comment by jxxghp** [comment]
正常，重现不了：

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/51039935/227407354-fc526f42-e9c8-4416-b071-eb56618b6266.png">
