### ISSUE TITLE
【bug】刷流使用cron表达式时报错

### ISSUE THREAD

**Issue by dandkong** [NAStool/nas-tools#3925]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 3.0.4
>
> 环境: docker
>

## 你遇到什么问题了？

> 【bug】刷流使用cron表达式时报错

## 你期望的结果

> cron表达式正常运行

## 给出程序界面截图、后台运行日志或配置文件
![image](https://user-images.githubusercontent.com/31849833/226391137-1a2c727a-2e79-4ac9-bf6a-2a01c439e75e.png)
![image](https://user-images.githubusercontent.com/31849833/226391200-ab423c0e-272c-4a62-bcc9-e6103552d6c3.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by honue** [comment]
作者嫌弃我的pr不够优雅，重构的时候漏了taskid参数，已pr，等待merge修复。
