### ISSUE TITLE
CloudFlare CDN优选启动后没有反应，后台有报错

### ISSUE THREAD

**Issue by zxcdeyouxiang** [NAStool/nas-tools#3926]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.4-3.0.5
>
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

> 描述一下你遇到的问题
开启CF CDN优选后无反应 后台报错
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是
> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果
cf cdn 优选正常工作
## 给出程序界面截图、后台运行日志或配置文件
运行一次会提示
2023-03-20 23:40:04,621 INFO: 【Plugin】Cloudflare CDN优选服务启动，立即运行一次
2023-03-20 23:40:04,622 INFO: 【Plugin】Cloudflare CDN优选服务启动，周期：0 0 1 * *
很长时间没有反应，然后后台出现下面的报错
Pending jobs:
    CloudflareSpeedTest.__cloudflareSpeedTest (trigger: cron[month='*', day='1', day_of_week='*', hour='0', minute='0'], pending)
    CloudflareSpeedTest.__cloudflareSpeedTest (trigger: date[2023-03-20 23:45:04 CST], pending)
Job "CloudflareSpeedTest.__cloudflareSpeedTest (trigger: date[2023-03-20 23:45:04 CST], next run at: 2023-03-20 23:45:04 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/nas-tools/app/plugins/modules/cloudflarespeedtest.py", line 198, in __cloudflareSpeedTest
    err_flag, release_version = self.__check_envirment()
  File "/nas-tools/app/plugins/modules/cloudflarespeedtest.py", line 268, in __check_envirment
    os.mkdir(self._cf_path)
PermissionError: [Errno 13] Permission denied: 'cloudflarespeedtest'

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by thsrite** [comment]
权限问题

**Comment by zxcdeyouxiang** [comment]
> 权限问题

我也看到是权限问题，感觉是创建不了目录，但是我不知道要改哪个目录的权限，我容器的UID一直是99 PID一直是100，没用root权限运行

**Comment by thsrite** [comment]
> > 权限问题
> 
> 我也看到是权限问题，感觉是创建不了目录，但是我不知道要改哪个目录的权限，我容器的UID一直是99 PID一直是100，没用root权限运行

重拉镜像试试

**Comment by zxcdeyouxiang** [comment]
> > > 权限问题
> > 
> > 
> > 我也看到是权限问题，感觉是创建不了目录，但是我不知道要改哪个目录的权限，我容器的UID一直是99 PID一直是100，没用root权限运行
> 
> 重拉镜像试试

昨天反复拉过镜像，正好有3.0.4到3.0.5的升级，我也升了

**Comment by thsrite** [comment]
进入容器执行 mkdir /nas-tools/cloudflarespeedtest

**Comment by zxcdeyouxiang** [comment]
> 进入容器执行 mkdir /nas-tools/cloudflarespeedtest，看看能成功不
> 
> 执行 ls -al /nas-tools/ 看看文件权限

手动创建文件夹之后提示CloudflareSpeedTest安装失败，我手动下载放进去可以正常使用
是不是还有个文件夹对应CloudflareSpeedTest下载更新用的？

**Comment by zxcdeyouxiang** [comment]
> 进入容器执行 mkdir /nas-tools/cloudflarespeedtest，看看能成功不
> 
> 执行 ls -al /nas-tools/ 看看文件权限

而且我发现每次重新拉取镜像之后，都不能正常创建这个目录，/nas-tools的所有者是设置的99:100,权限755，/nas-tools/cloudflarespeedtest也是一样，权限777，这两个目录的权限我试着全改成777，但还是没办法正常创建
