### ISSUE TITLE
签到服务不启动了

### ISSUE THREAD

**Issue by kfqkfy** [NAStool/nas-tools#3929]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>   v3.0.5 2715f71
> 环境: docker or windows or Synology
>  docker

签到服务不自动运行了，重启重新设定时间还是不行，手动执行可以签到

**Comment by boweic** [comment]
我也碰到同样情况

**Comment by sypopo** [comment]
我也是昨晚更新了，今天就没自动签到。
