### ISSUE TITLE
下载种子将电影识别为电视剧

### ISSUE THREAD

**Issue by JeremyXING** [NAStool/nas-tools#3932]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.5
>
> 环境: docker 
>

## 你遇到什么问题了？

> 通过nastool网页下载种子，出现将电影识别为电视剧的错误，遇到了不止一次

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/15687755/226509951-bdee0d1e-74d9-402e-8470-a2c41cbdeb9e.png">

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by thofx** [comment]
后面这个 是哪里来的 1 114 godzhu

**Comment by JeremyXING** [comment]
> 后面这个 是哪里来的 1 114 godzhu

我也不太清楚，似乎是从种子里直接读出来的，文件名里是没有，出问题的看起来都会带一串类似的

**Comment by JeremyXING** [comment]
> 后面这个 是哪里来的 1 114 godzhu
搞明白了，这好像是这个种子数 下载数 发布者。。。。。只要从nastool网页端看到的种子好多都会带这个，貌似以前是没有这个问题的
<img width="1663" alt="image" src="https://user-images.githubusercontent.com/15687755/226529955-c059af12-75d9-46d3-abf7-0db5de5ad412.png">

**Comment by thofx** [comment]
> > 后面这个 是哪里来的 1 114 godzhu
> > 搞明白了，这好像是这个种子数 下载数 发布者。。。。。只要从nastool网页端看到的种子好多都会带这个，貌似以前是没有这个问题的
> 
> <img alt="image" width="1663" src="https://user-images.githubusercontent.com/15687755/226529955-c059af12-75d9-46d3-abf7-0db5de5ad412.png">

没碰到此情况

**Comment by jxxghp** [comment]
可以提供一下北洋园的种子搜索页代码看看，我没有账号分析不少这个情况，应该是适配的原因。

**Comment by jxxghp** [comment]
下个版本修复

**Comment by JeremyXING** [comment]
> 下个版本修复

抱歉GitHub没给发邮件所以没看到消息，之前有两个站点都有此类问题，刚刚升级到新版该问题貌似已经解决所以猜测不需要网页代码了应该，感谢大佬的支持～
