### ISSUE TITLE
微信搜索不了片名，7分钟后报错消息为空。之前功能都正常能用

### ISSUE THREAD

**Issue by happigs** [NAStool/nas-tools#3934]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.5
>
> 环境: Synology 920+
>

## 你遇到什么问题了？

> 描述一下你遇到的问题

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是的，去tg问了，呆呆喊我来这里看看

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

搜过 没发现
## 你期望的结果
能够正常使用微信搜索片名+下载

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
![telegram-cloud-photo-size-5-6111388220966156762-x](https://user-images.githubusercontent.com/52274774/226535687-fdbd5e52-b081-44b5-a9d6-12f00537ac8a.jpg)

我测试了 企业微信 消息能发成功  也能收到  就是不会回复  有遇到过这种情况的吗？
![telegram-cloud-photo-size-5-6111388220966156763-x](https://user-images.githubusercontent.com/52274774/226535637-cf8cee0a-7ce4-43dd-b806-8c83b515ce8e.jpg)

自己搜索  也都能搜到信息  TMDB也都是通的

![telegram-cloud-photo-size-5-6111388220966156765-x](https://user-images.githubusercontent.com/52274774/226535733-5ea0219f-455c-4f90-9161-b066d15534db.jpg)

上面这个是老图，3.0.4之前的时候 都还能用

2023-03-21 14:41:42,084	INFO: 收到微信消息：username=hhh, text=岁月神偷
2023-03-21 14:41:42,095	INFO: 处理事件：message.incoming - [<function Webhook.send at 0x7fcdc037a830>]
_2023-03-21 14:42:04,039	ERROR: 【Sites】站点 btschool 连接失败，状态码：403
2023-03-21 14:43:48,539	INFO: 刷流服务启动_
2023-03-21 14:48:07,866	INFO: 【Message】发送消息 Wechat：title=, text=
2023-03-21 14:48:07,867	ERROR: 【Message】Wechat 消息发送失败：标题和内容不能同时为空

什么情况消息会为空呢

**Comment by a928230991** [comment]
昨天也有这个问题，后面把代理，openai相关的去掉就好了

**Comment by jxxghp** [comment]
开启OpenAI后远程交互默认与ChatGPT对话，如需订阅或搜索电影，需发送“订阅/搜索/下载” + 名称，未开启OpenAI则保持不变。

**Comment by Mrxlei** [comment]
![微信图片_20230324135141](https://user-images.githubusercontent.com/95324467/227436148-1287533c-e0bb-4073-8ec0-97370327b638.jpg)
微信搜索片名无回馈，后台也看不到消息，能接收到的推送消息

**Comment by happigs** [comment]
升级后已经成功解决，通过外网vps转发API接口可解决
