### ISSUE TITLE
NavbarMenu组件Y轴滚动条无法滚动

### ISSUE THREAD

**Issue by orzcz** [NAStool/nas-tools#3935]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.5
>
> 环境: docker
>

菜单栏无法滚动。
初步排查是这个属性造成的，取消勾选后，能够正常滚动
![image](https://user-images.githubusercontent.com/26238769/226570033-396feccd-cac1-4d3b-b3f2-5fe4f127fcf5.png)

**Comment by jxxghp** [comment]
已去除
