### ISSUE TITLE
硬链接刮削后新增的动漫文件怎么取消，不让程序新建

### ISSUE THREAD

**Issue by Mrxlei** [NAStool/nas-tools#3938]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.4
>
> 环境: docker or windows or Synology
>

## 你遇到什么问题了？

> 硬链接刮削后新增的动漫文件怎么取消，不让程序新建
![0321](https://user-images.githubusercontent.com/95324467/226627447-9ec36b87-0893-4ce2-918d-3e89fc7cbf61.png)

**Comment by jxxghp** [comment]
把分类的那个default-category.yaml里的对应配置清掉，或者在基础设置中清掉二级分类的配置项，重启。

**Comment by Mrxlei** [comment]
谢谢，更新之后没注意这配置带出来，已搞定
