### ISSUE TITLE
DSM 7.1.1-42962 Update 3版本 安装是提示失败，未找到原因

### ISSUE THREAD

**Issue by mageli11** [NAStool/nas-tools#3939]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>2.9.0/2.9.1/3.0.5 均尝试
> 环境: docker or windows or Synology
>Synology DSM 7.1.1-42962 Update 3

## 你遇到什么问题了？

> 描述一下你遇到的问题
无论是手动安装还是在社群中安装，均提示安装失败。Python3.9/3.10均已安装
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
<img width="1003" alt="Snipaste_2023-03-21_22-45-28" src="https://user-images.githubusercontent.com/117364705/226645018-fd1808e9-02fe-4086-b1ff-4ca197154a74.png">

**Comment by jxxghp** [comment]
可以在矿神的群里问一下，我这边无法解答SPK的问题

**Comment by rshinesun** [comment]
遇到同款问题，解决了- -发上来供大家参考
SSH 执行
sudo synouser --del sc-nastool
sudo synouser --del NASTool
sudo synogroup --del NASTool
