### ISSUE TITLE
TTG刷流有问题

### ISSUE THREAD

**Issue by SchrodingerBarbatos** [NAStool/nas-tools#3949]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
> v3.0.5 f720bd2
> 环境: docker or windows or Synology
> docker

## 你遇到什么问题了？

> TTG刷流有问题，rss可以正常获取但是选种添加关键词是TTG|WiKi,一直不会添加种子，但是观众使用AD|Audies可以正常添加

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 可以正常刷流

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
![image](https://imgckr.com/images/2023/03/23/BvF4g.jpg)
![image](https://imgckr.com/images/2023/03/23/BvoOX.jpg)
![image](https://imgckr.com/images/2023/03/23/BvWCa.jpg)

**Comment by jxxghp** [comment]
你要发日志，从图上是看不出什么情况的

**Comment by SchrodingerBarbatos** [comment]
> 你要发日志，从图上是看不出什么情况的


![img](https://imgckr.com/images/2023/03/24/Bv1AU.png)
日志是这样貌似看不出来啥问题，但是tg群里我看到好几个群友和我一样刷不了

**Comment by SchrodingerBarbatos** [comment]
> 你要发日志，从图上是看不出什么情况的

![image](https://user-images.githubusercontent.com/78670748/227537504-495438fb-7ac4-436a-8ed5-c2d5fb6a0643.png)
![image](https://user-images.githubusercontent.com/78670748/227537130-2afc9541-8a1a-4151-a548-2c1324bd8c92.png)
![image](https://user-images.githubusercontent.com/78670748/227537219-63c240aa-82e7-4b46-8c71-29c0fe582e17.png)
![image](https://user-images.githubusercontent.com/78670748/227537281-ca637236-2c04-47c5-a273-6b2cf84473c5.png)
这4张图不知道老大能不能看出问题，

**Comment by lxm9357** [comment]
我这TTG刷流也有问题，我日志调成debug看了一下，应该是做种人数识别出了问题，我挑了几条明显不对的日志供大佬分析

> 2023-03-24 21:27:46,452	DEBUG: 【Brush】Detective Knight Redemption 2022 2160p UHD Blu-ray HEVC DTS-HD MA 5{@}1-DIY@TTG [警探奈特2：救赎/警探奈特2 ] 「4K DIY 简繁中字」 59.57 GB 解析详情, {'free': True, '2xfree': False, 'hr': False, 'peer_count': 16364}
> 2023-03-24 21:27:53,302	DEBUG: 【Brush】Detective Knight Rogue 2022 2160p UHD Blu-ray HEVC DTS-HD MA 5{@}1-DIY@TTG [警探奈特：侠盗/警探奈特 ] 「4K DIY 简繁中字」 58.67 GB 解析详情, {'free': True, '2xfree': False, 'hr': False, 'peer_count': 16566}
> 2023-03-24 22:27:49,817	DEBUG: 【Brush】A Restaurant with Many Problems S01 1080p AMZN WEB-DL DD+2 0 H 264-ARiN[問題のあるレストラン / 问题餐厅  主演: 真木阳子 / 东出昌大 / 二阶堂富美 / 高畑充希] 25.70 GB 解析详情, {'free': True, '2xfree': False, 'hr': False, 'peer_count': 1910}
> 2023-03-24 22:47:50,805	DEBUG: 【Brush】Missing 2023 1080p BluRay x264 DTS-WiKi [网络谜踪2/人肉搜寻2(港)/人肉搜索2：失踪搜救(台)] 内封中字 11.97 GB 解析详情, {'free': True, '2xfree': False, 'hr': False, 'peer_count': 1110111}

这里的做种数明显错误了，free和hr的识别都是正确的。我设置的是做种数小于3的才刷流，所以这些种子就没有刷到。

**Comment by Joe-Hill** [comment]
我的 ttg 也遇到类似的问题，不过我已经是没有添加任何限制还是无法推送到下载器。日志中获取 RSS 本身是正常的。

**Comment by SchrodingerBarbatos** [comment]
> > 我这TTG刷流也有问题，我日志调成debug看了一下，应该是做种人数识别出了问题，我挑了几条明显不对的日志供大佬分析
> > > 2023-03-24 21:27:46,452	DEBUG: 【Brush】Detective Knight Redemption 2022 2160p UHD Blu-ray HEVC DTS-HD MA 5{@}1-DIY@TTG [警探奈特2：救赎/警探奈特2 ] 「4K DIY 简繁中字」 59.57 GB 解析详情, {'free': True, '2xfree': False, 'hr': False, 'peer_count': 16364}
> > > 2023-03-24 21:27:53,302	DEBUG: 【Brush】Detective Knight Rogue 2022 2160p UHD Blu-ray HEVC DTS-HD MA 5{@}1-DIY@TTG [警探奈特：侠盗/警探奈特 ] 「4K DIY 简繁中字」 58.67 GB 解析详情, {'free': True, '2xfree': False, 'hr': False, 'peer_count': 16566}
> > > 2023-03-24 22:27:49,817	DEBUG: 【Brush】A Restaurant with Many Problems S01 1080p AMZN WEB-DL DD+2 0 H 264-ARiN[問題のあるレストラン / 问题餐厅  主演: 真木阳子 / 东出昌大 / 二阶堂富美 / 高畑充希] 25.70 GB 解析详情, {'free': True, '2xfree': False, 'hr': False, 'peer_count': 1910}
> > > 2023-03-24 22:47:50,805	DEBUG: 【Brush】Missing 2023 1080p BluRay x264 DTS-WiKi [网络谜踪2/人肉搜寻2(港)/人肉搜索2：失踪搜救(台)] 内封中字 11.97 GB 解析详情, {'free': True, '2xfree': False, 'hr': False, 'peer_count': 1110111}
> > 
> > 
> > 这里的做种数明显错误了，free和hr的识别都是正确的。我设置的是做种数小于3的才刷流，所以这些种子就没有刷到。
> 
> 2023-03-25 00:03:22,459 DEBUG: 【Brush】Detective Knight Redemption 2022 2160p UHD Blu-ray HEVC DTS-HD MA 5{@}1-DIY@TTG [警探奈特2：救赎/警探奈特2 ] 「4K DIY 简繁中字」 59.57 GB 解析详情, {'free': True, '2xfree': False, 'hr': False, 'peer_count': 1717718} 2023-03-25 00:03:22,459 DEBUG: 【Brush】Detective Knight Redemption 2022 2160p UHD Blu-ray HEVC DTS-HD MA 5{@}1-DIY@TTG [警探奈特2：救赎/警探奈特2 ] 「4K DIY 简繁中字」 59.57 GB 判断做种数, 判断条件: peer_count:1717718 lt threshold:3 2023-03-25 00:03:29,300 DEBUG: 【Brush】Detective Knight Rogue 2022 2160p UHD Blu-ray HEVC DTS-HD MA 5{@}1-DIY@TTG [警探奈特：侠盗/警探奈特 ] 「4K DIY 简繁中字」 58.67 GB 解析详情, {'free': True, '2xfree': False, 'hr': False, 'peer_count': 1653654} 2023-03-25 00:03:29,302 DEBUG: 【Brush】Detective Knight Rogue 2022 2160p UHD Blu-ray HEVC DTS-HD MA 5{@}1-DIY@TTG [警探奈特：侠盗/警探奈特 ] 「4K DIY 简繁中字」 58.67 GB 判断做种数, 判断条件: peer_count:1653654 lt threshold:3
> 
> 看了下我的也是这样，应该做种人数识别有问题

把做种人数限制去掉后就可以正常刷流了，应该可以确定是做种人数识别问题了

**Comment by djydtzh** [comment]
我也遇到类似的问题，试过关闭所有条件，修改代理，都是添加0下载。站点资源中获取 RSS 本身是正常的。
