### ISSUE TITLE
hdchina从3.0.3之后刷流有问题

### ISSUE THREAD

**Issue by SchrodingerBarbatos** [NAStool/nas-tools#3953]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
> v3.0.5 f720bd2
> 环境: docker or windows or Synology
> docker

## 你遇到什么问题了？

> 瓷器刷流我的是从3月11号没添加新种子了，刚好是3.0.3版本更新，感觉是不会打开浏览器仿真刷流了，因为我在站点设置打开仿真可以在资源列表获取到free标志，而关了仿真就不会有free了，因为我刷流设置了下载免费，所以我觉得可能是这个原因。rss的资源获取一直都是正常的

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已浏览

## 你期望的结果

> 正常刷流

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
![image](https://user-images.githubusercontent.com/78670748/226904903-fed25a8e-ecca-46f3-a227-c4809081d225.png)
![image](https://user-images.githubusercontent.com/78670748/226904973-7f35d57f-d62a-47ee-8652-957195e0176a.png)

**Comment by SchrodingerBarbatos** [comment]
> 这个站点要开仿真，他们的标签是动态的

开了仿真，但是不知道为什么仿真代理同时开会chrome无法模拟

**Comment by jxxghp** [comment]
> > 这个站点要开仿真，他们的标签是动态的
> 
> 谢谢老大百忙中抽空回答，开了仿真不开代理可以刷流，但是不知道为什么仿真代理同时开会chrome无法模拟，而且不开代理又会经常刷不出来rss数据

代理是什么格式的？仿真下貌似只能支持Http的代理。

**Comment by SchrodingerBarbatos** [comment]
> > > 这个站点要开仿真，他们的标签是动态的
> > 
> > 
> > 谢谢老大百忙中抽空回答，开了仿真不开代理可以刷流，但是不知道为什么仿真代理同时开会chrome无法模拟，而且不开代理又会经常刷不出来rss数据
> 
> 代理是什么格式的？仿真下貌似只能支持Http的代理。

是http的代理

**Comment by jxxghp** [comment]
仿真开代理的问题下个版本修复： #3957
