### ISSUE TITLE
修改搜索结果数量限制无效

### ISSUE THREAD

**Issue by shoumo680** [NAStool/nas-tools#3954]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.5
>
> 环境: docker
>

## 你遇到什么问题了？

> 根据 #2357 提供的site_search_result_num字段修改数量无效，已重启过

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 可以修改

## 给出程序界面截图、后台运行日志或配置文件

![微信截图_20230322201731](https://user-images.githubusercontent.com/12744973/226903375-e91e35f7-50cc-4306-a7a2-979cbccac767.png)

![微信图片_20230322201119](https://user-images.githubusercontent.com/12744973/226903504-1ef7b972-c549-41d7-82e4-463cd77c9eee.png)

**Comment by lightolly** [comment]
这个只是代表nastools在站点返回结果数里面最多取的结果数量，要站点本身能支持返回大于100条才有意义，你可以看下mt的搜索结果，网站本身不会返回超过100条记录的

**Comment by shoumo680** [comment]
MT的每页主题数最大只能100，我在MT里搜钢铁侠返回的结果是超过100条的，但是分为了2页，NASTools没有分页获取结果吗？

**Comment by jxxghp** [comment]
不支持抓多页，抓多页也会对站点靠成压力。
