### ISSUE TITLE
内建索引器支持的站点是哪些，可否列一个清单？我现在加进去的一些小站，没办法通过nas tool检索影片。谢谢大佬！

### ISSUE THREAD

**Issue by aicenluo** [NAStool/nas-tools#3955]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>3.0.5
> 环境: docker or windows or synology
docker
## 你想要新增或者改进什么功能？
现在升级到最新版本以后，内建索引只有私有站点了，我现在想根据nas tool已经支持的站点来捐赠或者求药，但是不知道哪些是nastool支持的，可否列一下？谢谢！
> 你想要新增或者改进什么功能？
内建索引器支持的站点
![11](https://user-images.githubusercontent.com/128604492/226911278-3727b490-9952-4b03-9e5c-f127c5d582ca.png)

**Comment by TerminalReed** [comment]
NexusPHP架构的绝大多数都支持吧

**Comment by aicenluo** [comment]
可问题是我了站点维护中正确配置好以后，还是不会显示，可能是没有被收录吧。部分大站有，还是希望能放开多一些站点。

TerminalReed ***@***.***> 于2023年3月22日周三 21:48写道：

**Comment by jxxghp** [comment]
现在支持68个PT站，应该相对比较全了吧，但貌似不太好在这里发清单。
仍不支持的需要线我个账号，或者等开注，才能支持。

**Comment by jxxghp** [comment]
已在频道公布：https://t.me/nastool_official

**Comment by aicenluo** [comment]
必须点赞！谢谢！

jxxghp ***@***.***> 于2023年3月23日周四 17:00写道：
