### ISSUE TITLE
Synologychat 交互环境回馈 “提问太快啦，请休息一下再问我吧”

### ISSUE THREAD

**Issue by leo2my** [NAStool/nas-tools#3961]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.5
>
> 环境: Synology
>

## 你遇到什么问题了？

> 描述一下你遇到的问题
Synology Chat交互NAStools测试失败，发送请求消息后日志为 “发送消息 Nastools：title=, text=提问太快啦，请休息一下再问我吧”

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

查询后无类似问题

## 你期望的结果

> 描述以下你期望的结果
Synology Chat可以正常交互NAStools

## 给出程序界面截图、后台运行日志或配置文件

21:30:50 | Message | 发送消息 Nastools：title=, text=提问太快啦，请休息一下再问我吧
-- | -- | --
21:32:40 | System | 收到Synology Chat消息：username=Lee, text=肖申克的救赎
21:32:40 | System | 处理事件：message.incoming - [<function Webhook.send at 0x7ff4909f0280>]
21:32:41 | Message | 发送消息 Nastools：title=, text=提问太快啦，请休息一下再问我吧
21:40:27 | System | 收到Synology Chat消息：username=Lee, text=螺丝钉
21:40:27 | System | 处理事件：message.incoming - [<function Webhook.send at 0x7ff4909f0280>]
21:40:28 | Message | 发送消息 Nastools：title=, text=提问太快啦，请休息一下再问我吧

<img width="865" alt="截屏2023-03-22 21 40 44" src="https://user-images.githubusercontent.com/39982971/226924317-fb7980a9-f9d2-4e1e-8500-ab3b018785db.png">

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
看频道：
填写OpenAI Api Key后，远程交互触发ChatGPT问答的条件

v3.0.4：（满足任一即可）
1. 以"请帮/请你/请问"开头。
2. 以"?/？"号结尾。
3. 输入文本大于15个汉字或者英文单词。

v3.0.5：
默认触发ChatGPT问答，如需订阅或搜索电影/电视剧，请在最前面添加"订阅/搜索/下载"字样。

注意：ChatGPT问答也是会通过Api计费的。

**Comment by leo2my** [comment]
果然是这个问题，不好意思没有仔细看资料，现在搞定了，感谢！
