### ISSUE TITLE
索引器使用TTG搜索资源有问题

### ISSUE THREAD

**Issue by SchrodingerBarbatos** [NAStool/nas-tools#3962]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
> v3.0.5 f720bd2
> 环境: docker or windows or Synology
> docker

## 你遇到什么问题了？

> TTG搜索资源有问题，这里过滤规则是不过滤，所以应该不是过滤规则问题
![image](https://user-images.githubusercontent.com/78670748/226942439-f8d1541b-6b62-41c3-b7e6-98ae582eba0e.png)

点开日志中的网址看到nastool请求的搜索内容有问题

![image](https://user-images.githubusercontent.com/78670748/226942742-da17d4d5-cd7a-4b94-9ee6-ef2135103460.png)

我搜索的应该是“**大宋少年志**”，nastool请求的搜索为“**大宋少年志 分类:电影DVDRip 分类:电影720p 分类:电影1080i/p 分类:BluRay原盘 分类:影视2160p 分类:UHD原盘** ”，我认为是这个地方导致搜索不出资源，开不开仿真请求的搜索都有问题。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 可以正常搜索

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
![image](https://user-images.githubusercontent.com/78670748/226943293-2c707c89-2877-4342-80e5-7d7fb0b6ac6b.png)
![image](https://user-images.githubusercontent.com/78670748/226943714-a8031981-ce34-4526-ac51-9ba639dd0197.png)
![image](https://user-images.githubusercontent.com/78670748/226943816-8cd5752b-1e35-4ce6-b216-29f114356339.png)
![image](https://user-images.githubusercontent.com/78670748/226943900-32d50858-73d1-43d6-a9d2-30182eee9d39.png)

**Comment by iamzhangzhang** [comment]
我也遇到了一样的问题，搜索会在后面自动添加一堆分类

**Comment by SchrodingerBarbatos** [comment]
> 会自动添加与影片有关的分类做检索，避免全站搜索过滤，提高效率。
> 
> 但这个站的分类处理有问题，导致只加了电影的分类，电视剧搜不到。我修了下，等下个版本更新。

感谢老大修复

**Comment by jxxghp** [comment]
另外，大宋少年志这个剧要关掉实验室的优先使用中文名才能搜出TTG的资源，因为TTG的资源英文名不对（TMDB叫Young Blood），TTG是拼音。或者在TMDB词条上加上拼音也行。

**Comment by SchrodingerBarbatos** [comment]
> 另外，大宋少年志这个剧要关掉实验室的优先使用英文名才能搜出TTG的资源，因为TTG的资源英文名不对（TMDB叫Young Blood），TTG是拼音。或者在TMDB词条上加上拼音也行。

哦哦，我默认关闭了英文优先所以没遇到这个问题，感谢老大解答
