### ISSUE TITLE
申请支持站点chdbits

### ISSUE THREAD

**Issue by MichaelYXQ** [NAStool/nas-tools#3966]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 3.0.5
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 申请支持站点chdbits

## 这个功能有什么可以参考的资料吗？

> https://chdbits.co/

**Comment by Wangsc1** [comment]
岛本来就能用

**Comment by MichaelYXQ** [comment]
> 岛本来就能用

谢谢回复，不过我在用户认证的合作站点里面找不到岛的选择，总共只能选择7个站点。
![image](https://user-images.githubusercontent.com/92349267/227099685-ad1c4e47-2de2-441e-9676-cfe254605816.png)

**Comment by Wangsc1** [comment]
> > 岛本来就能用
> 
> 
> 
> 谢谢回复，不过我在用户认证的合作站点里面找不到岛的选择，总共只能选择7个站点。
> 
> ![image](https://user-images.githubusercontent.com/92349267/227099685-ad1c4e47-2de2-441e-9676-cfe254605816.png)
> 
> 

你说的是认证啊，这个不是作者说支持就支持的，也要看站点愿不愿意

**Comment by MichaelYXQ** [comment]
> > > 岛本来就能用
> > 
> > 
> > 谢谢回复，不过我在用户认证的合作站点里面找不到岛的选择，总共只能选择7个站点。
> > ![image](https://user-images.githubusercontent.com/92349267/227099685-ad1c4e47-2de2-441e-9676-cfe254605816.png)
> 
> 你说的是认证啊，这个不是作者说支持就支持的，也要看站点愿不愿意

是的，我说的是认证站点。
现在的问题是，按照更新说明，一定需要先有一个认证站点完成用户认证才能开启全部功能。
是不是在上述7个站点中注册一个，然后进行用户认证就可以加入岛的站点并且使用全部功能了？

基于一些因素考虑，目前需要完成用户认证才能打开全量功能（认证站点陆续增加中）。

**Comment by Wangsc1** [comment]
是的，你有岛的话你可以先在iyuu里认证，然后用iyuu来认证nastool

**Comment by MichaelYXQ** [comment]
> 是的，你有岛的话你可以先在iyuu里认证，然后用iyuu来认证nastool

谢谢回复，我只有岛的账号，看来只能多注册其它的PT站了。
