### ISSUE TITLE
你好，内建站点，目前还不支持海胆。。。

### ISSUE THREAD

**Issue by baiyefeiyu** [NAStool/nas-tools#3968]
https://www.haidan.video/login.php

**Comment by baiyefeiyu** [comment]
nastools 3.0.5，群晖套件版本

**Comment by jxxghp** [comment]
这个没办法支持，他的站点种子页面的结构没办法索引。

**Comment by baiyefeiyu** [comment]
他这个页面结构确实，我去页面下载都看着一脸懵逼。另外还有两个小问题。
1、chdbits刷流任务每次都执行了，但是永远下载0添加，其他站点ok。而且暂停的刷流任务也在日志看到在执行。
2、qb删除种子，下载目录文件夹目测是不会删除的，硬链接文件及目录也需要我手动删除。所以我每次删完下载目录，就删除全部硬链接文件夹，然后全量目录同步。。。是我操作问题还是本来这样。









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NAStool/nas-tools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月23日(星期四) 下午2:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NAStool/nas-tools] 你好，内建站点，目前还不支持海胆。。。 (Issue #3968)





 
这个没办法支持，他的站点种子页面的结构没办法索引。

**Comment by c939984606** [comment]
> 他这个页面结构确实，我去页面下载都看着一脸懵逼。另外还有两个小问题。 1、chdbits刷流任务每次都执行了，但是永远下载0添加，其他站点ok。而且暂停的刷流任务也在日志看到在执行。 2、qb删除种子，下载目录文件夹目测是不会删除的，硬链接文件及目录也需要我手动删除。所以我每次删完下载目录，就删除全部硬链接文件夹，然后全量目录同步。。。是我操作问题还是本来这样。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "NAStool/nas-tools" ***@***.***&gt;; 发送时间:&nbsp;2023年3月23日(星期四) 下午2:16 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [NAStool/nas-tools] 你好，内建站点，目前还不支持海胆。。。 (Issue #3968) 这个没办法支持，他的站点种子页面的结构没办法索引。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
chdbits刷流任务我这边没这个问题
