### ISSUE TITLE
关于消息互动存在的问题和一些建议。

### ISSUE THREAD

**Issue by NikoYomi** [NAStool/nas-tools#3969]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>V3.0.5
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

> 1.配置成功微信消息通知与互动，在进行互动时候，输入电视剧时，会自动下载所有的单集电视剧，而非整季资源。而当我关闭自动择优下载时，他反馈给我的是“xxx，共搜索到xx个资源，点击下载。”，对于这条消息我点击是没有反应的。2.相关的互动指令太少。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

>1.希望能够在关闭自动下载后，反馈的消息能够是一个带序号和站点信息的清单，并让我这边回复消息进行选择下载。
2.希望能够给出更多的互动指令，比如今天刷流任务的情况，今天哪个站刷了多少。

## 给出程序界面截图、后台运行日志或配置文件
下图是关闭自动择优下载选择对应的电影名称后反馈的日志和界面图片
![1679552464531](https://user-images.githubusercontent.com/120245220/227120459-02c9e680-94a7-4b28-acb9-48bac16f3420.png)

![1679552587740](https://user-images.githubusercontent.com/120245220/227120731-611c7551-9f40-4c25-b18f-e8d799a8f734.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by SchrodingerBarbatos** [comment]
> > 你没配置外网访问地址当然打不开
> 
> 请问我应该在哪配置呢？

基础设置里面

**Comment by NikoYomi** [comment]
> > > 你没配置外网访问地址当然打不开
> > 
> > 
> > 请问我应该在哪配置呢？
> 
> 基础设置里面

是NASTOOLS的外网访问端口地址嘛

**Comment by SchrodingerBarbatos** [comment]
> > > > 你没配置外网访问地址当然打不开
> > > 
> > > 
> > > 请问我应该在哪配置呢？
> > 
> > 
> > 基础设置里面
> 
> 是NASTOOLS的外网访问端口地址嘛

外网访问地址那个

**Comment by NikoYomi** [comment]
> > > > > 你没配置外网访问地址当然打不开
> > > > 
> > > > 
> > > > 请问我应该在哪配置呢？
> > > 
> > > 
> > > 基础设置里面
> > 
> > 
> > 是NASTOOLS的外网访问端口地址嘛
> 
> 外网访问地址那个

感谢，链接已经能够访问。但是这样的话不是很不方便？因为即需要点击链接同时还需要登录nastools，希望作者能够在此基础上改成发送详细列表，用户回复对应的序号就可以直接下载。
再次感谢作者的开发与共享。

**Comment by thsrite** [comment]
> > > > > > 你没配置外网访问地址当然打不开
> > > > > 
> > > > > 
> > > > > 请问我应该在哪配置呢？
> > > > 
> > > > 
> > > > 基础设置里面
> > > 
> > > 
> > > 是NASTOOLS的外网访问端口地址嘛
> > 
> > 
> > 外网访问地址那个
> 
> 感谢，链接已经能够访问。但是这样的话不是很不方便？因为即需要点击链接同时还需要登录nastools，希望作者能够在此基础上改成发送详细列表，用户回复对应的序号就可以直接下载。 再次感谢作者的开发与共享。

开了择优下载  不就是回复序号直接下载吗？

**Comment by NikoYomi** [comment]
> > > > > > > 你没配置外网访问地址当然打不开
> > > > > > 
> > > > > > 
> > > > > > 请问我应该在哪配置呢？
> > > > > 
> > > > > 
> > > > > 基础设置里面
> > > > 
> > > > 
> > > > 是NASTOOLS的外网访问端口地址嘛
> > > 
> > > 
> > > 外网访问地址那个
> > 
> > 
> > 感谢，链接已经能够访问。但是这样的话不是很不方便？因为即需要点击链接同时还需要登录nastools，希望作者能够在此基础上改成发送详细列表，用户回复对应的序号就可以直接下载。 再次感谢作者的开发与共享。
> 
> 开了择优下载 不就是回复序号直接下载吗？

并不是哦 ，我这里是直接下载了，如图
![image](https://user-images.githubusercontent.com/120245220/227490305-dbea734f-da9a-415d-8069-6f6f628bb4d5.png)
