### ISSUE TITLE
nastool win版無法在線升級

### ISSUE THREAD

**Issue by Amexcent** [NAStool/nas-tools#3977]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
> nastool_win_v3.0.3
> 环境: docker or windows or Synology
> windows 

## 你遇到什么问题了？

> 
1. windows版本，我按在線升級，就永無止境的繞圈圈無反應，點一下又回到原本的畫面而已
如圖 https://imgur.com/bZJIARZ.jpg、https://imgur.com/O92nYVV.jpg
2.改單獨下載nastool_win_v3.0.5.exe後，丟到原本3.03執行，卻顯示下圖的錯誤
https://imgur.com/9XMqz56.jpg

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 解決
## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by AisukaYuki** [comment]
#3799 #3721 类似问题。
使用sqllite studio编辑user.db，在数据表DOWNLOADER中增加MATCH_PATH字段
![image](https://user-images.githubusercontent.com/17586327/227694609-b4d6aeb1-4d46-4803-9239-aafebe586d90.png)

**Comment by jxxghp** [comment]
Win版本不仅不能自动升级，同时手工下载新版本后如表结构无法启动，需要重配，目前暂无法解决。

**Comment by jxxghp** [comment]
#3721

**Comment by sakumakenshin** [comment]
> #3799 #3721 类似问题。 使用sqllite studio编辑user.db，在数据表DOWNLOADER中增加MATCH_PATH字段 ![image](https://user-images.githubusercontent.com/17586327/227694609-b4d6aeb1-4d46-4803-9239-aafebe586d90.png)
大佬牛逼！！
