### ISSUE TITLE
rclone移动模式下刮削图片不会转移

### ISSUE THREAD

**Issue by royzheng** [NAStool/nas-tools#3979]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: [v3.0.5 f720bd2](https://github.com/NAStool/nas-tools)
>
> 环境: Debian 11 / python 10原生运行
>

## 你遇到什么问题了？

> 1. 下载器设置的Qbittorrent, 监控[是],转移方式[RClone移动]， 基础设置 刮削元数据及图片[开启]
> 2. 下载后视频能自动Rclone转移，但是刮削的数据还保留在本地没有rclone，测试日志如下(如下图，Rmt事件只转移了视频，刮削的资料并没转移)

10:04:18 | Downloader | 下载器 QB 开始转移下载文件...
-- | -- | --
10:04:18 | Rmt | 开始处理：/movie/Dying.to.Survive.2018.WEB-DL.4k.H265.DDP5.1.AAC2.0-Anonymous.mp4，转移方式：Rclone移动
10:04:18 | Meta | 正在查询TMDB电影：532753 ...
10:04:18 | Meta | 查询结果：我不是药神
10:04:18 | Meta | 正在查询TMDB电影：532753 ...
10:04:18 | Meta | 查询结果：Dying to Survive
10:04:18 | Rmt | 正在转移文件：Dying.to.Survive.2018.WEB-DL.4k.H265.DDP5.1.AAC2.0-Anonymous.mp4 => /movie/华语电影/我不是药神(2018)/我不是药神.2018.4k.WEB-DL.mp4
10:08:21 | Rmt | 文件 Dying.to.Survive.2018.WEB-DL.4k.H265.DDP5.1.AAC2.0-Anonymous.mp4 Rclone移动完成
10:08:21 | Meta | 正在查询TMDB电影：532753 ...
10:08:21 | Meta | 查询结果：我不是药神
10:08:21 | Message | 发送消息 Telegram：title=我不是药神 (2018) 已入库, text=评分：8.1，类型：电影，类别：华语电影，质量： WEB-DL 4k，大小：4.54G，来自：QB
10:08:24 | Scraper | 正在生成电影NFO文件：我不是药神.2018.4k.WEB-DL
10:08:26 | Scraper | 正在保存NFO文件：/movie/华语电影/我不是药神(2018)/我不是药神.2018.4k.WEB-DL.nfo
10:08:26 | Scraper | NFO文件已保存：/movie/华语电影/我不是药神(2018)/我不是药神.2018.4k.WEB-DL.nfo
10:08:26 | Scraper | 正在下载poster图片：https://image.tmdb.org/t/p/original/qrhEWQjR3AyMbyy5l3vFuwA576W.jpg...
10:08:26 | Scraper | poster图片已保存：/movie/华语电影/我不是药神(2018)/poster.jpg
10:08:26 | Scraper | 正在下载fanart图片：http://assets.fanart.tv/fanart/movies/532753/moviethumb/dying-to-survive-5f339d65e053d.jpg...
10:08:27 | Scraper | fanart图片已保存：/movie/华语电影/我不是药神(2018)/fanart.jpg
10:08:27 | Scraper | 正在下载background图片：http://assets.fanart.tv/fanart/movies/532753/moviebackground/dying-to-survive-5f339d369f8cf.jpg...
10:08:27 | Scraper | background图片已保存：/movie/华语电影/我不是药神(2018)/background.jpg
10:08:27 | Scraper | 正在下载logo图片：http://assets.fanart.tv/fanart/movies/532753/hdmovielogo/dying-to-survive-5dda56106abb4.png...
10:08:28 | Scraper | logo图片已保存：/movie/华语电影/我不是药神(2018)/logo.png
10:08:28 | Scraper | 正在下载banner图片：http://assets.fanart.tv/fanart/movies/532753/moviebanner/dying-to-survive-5f339d49d60b9.jpg...
10:08:28 | Scraper | banner图片已保存：/movie/华语电影/我不是药神(2018)/banner.jpg
10:08:28 | Scraper | 正在下载thumb图片：http://assets.fanart.tv/fanart/movies/532753/moviethumb/dying-to-survive-5f339d65e053d.jpg...
10:08:29 | Scraper | thumb图片已保存：/movie/华语电影/我不是药神(2018)/thumb.jpg
10:08:29 | Rmt | /movie/Dying.to.Survive.2018.WEB-DL.4k.H265.DDP5.1.AAC2.0-Anonymous.mp4 处理完成，总数：1，失败：0
10:08:29 | Downloader | 下载器 QB 移动模式下删除种子文件：befa50739ab57008e074fbb29b21eb67560aaf84
10:08:29 | System | 处理事件：subtitle.download - [<function ChineseSubFinder.download at 0x7f96172923b0>, <function OpenSubtitles.download at 0x7f96172cb370>, <function Webhook.send at 0x7f96153e9090>]
10:08:29 | System | 处理事件：transfer.finished - [<function LibraryRefresh.refresh at 0x7f96172ca200>, <function Webhook.send at 0x7f96153e9090>]
10:08:29 | Downloader | 下载器 QB 下载文件转移结束

## 你期望的结果

> 描述以下你期望的结果

希望能够在开启刮削及图片后，刮削的资料一并转移

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by Wangsc1** [comment]
元数据转移需要挂载网盘

**Comment by royzheng** [comment]
> 元数据转移需要挂载网盘，把你的挂载路径映射到容器内，和你的同步目录保持一致即可

听不大明白你意思，感谢你花费时间帮我看看
1. 我是在debian下运行nas-tools以及rclone
2. 我rclone config里有一个 NASTOOL的 drive (同时 我也在服务器上挂载路径/gd为网盘)
3. 我看qb的监控说明写的是 【监控下载软件，下载完成后自动进行文件转移，与目录同步监控下载目录二选一开启】
4. 从现在看起来变成下载步骤和结果是这样
    4.1 下载原始文件 Dying.to.Survive.2018.WEB-DL.4k.H265.DDP5.1.AAC2.0-Anonymous.mp4
    4.2 远程RCLONE移动到网盘的路径/movie/华语电影/我不是药神(2018)/我不是药神.2018.4k.WEB-DL.mp4
    4.3 刮削元数据到本地目录/movie/华语电影/我不是药神(2018)/
    4.4 现在远程网盘有/movie/华语电影/我不是药神(2018)/我不是药神.2018.4k.WEB-DL.mp4
                  本地硬盘有/movie/华语电影/我不是药神(2018)/所有元数据.jpg/nfo......
