### ISSUE TITLE
Plex参数说明错误

### ISSUE THREAD

**Issue by royzheng** [NAStool/nas-tools#3980]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.5 2715f71
>
> 环境: Debian11
>

## 你遇到什么问题了？

设置->媒体服务器->说明中的X-Plex-Token在Cookie中已经不存在了，我看了下是在LocalStroage中，名字叫myPlexAccessToken 

## 你期望的结果

> 有空改下描述（不过也可能旧版就在cookie里？）

## 给出程序界面截图、后台运行日志或配置文件
![1679624772957.png](https://s1.yesimg.com/2023/03/24/405568d2cb8d2.png)
![1679624809744.png](https://s1.yesimg.com/2023/03/24/cec36fef29cfd.png)

**Comment by jxxghp** [comment]
是URL里面的，不是Cookie：

<img width="693" alt="image" src="https://user-images.githubusercontent.com/51039935/227415747-fa526794-cca5-4012-b698-2f8f2220705d.png">

**Comment by royzheng** [comment]
> 是URL里面的，不是Cookie：
> 
> <img alt="image" width="693" src="https://user-images.githubusercontent.com/51039935/227415747-fa526794-cca5-4012-b698-2f8f2220705d.png">

OK，我关闭issue了，但是说明里写的是cookie，这个url可能小白也不好找（因为如果登录状态下不会出现这个）
