### ISSUE TITLE
提个建议，开发者不如在认证之外弄个捐赠认证

### ISSUE THREAD

**Issue by yunzhongci** [NAStool/nas-tools#3981]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.5
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 因为认证的问题，自己常用的比如馒头、学校、pt时间都不在合作认证的网站中，又不想去到处求邀请码，打算直接找个合作网站能捐赠入站的捐个邀请码。
准备付款的时候想到，这么一个站我捐了其实也未必常用，主要用的应该也还是原本的大站，为了这个认证捐个邀请码，为什么不能直接捐给开发者呢？
所以建议开发者直接弄个捐助认证的渠道，让我们这种想要花钱省事的有个更简单方便的途径。

**Comment by jxxghp** [comment]
这个项目目前未从任何渠道获取过任何利益，以前没有将来也不会接受任何损赚。
加认证的目的就是因为前段时间被大V爆光，适当增加门槛控控用户量才能活的更久。
