### ISSUE TITLE
希望增加下载器剩余空间识别功能

### ISSUE THREAD

**Issue by lemontree9223** [NAStool/nas-tools#3982]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x

>3.0.5

> 环境: docker or windows or synology

synology

## 你想要新增或者改进什么功能？

刷流功能可识别下载器剩余空间，用户可设置空间小于xG不添加种子，或自动删老种腾出空间。

> 你想要新增或者改进什么功能？

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

vertex可实现此功能。

**Comment by jxxghp** [comment]
#2542
