### ISSUE TITLE
nastool内置的站点没有馒头

### ISSUE THREAD

**Issue by chenxudong2020** [NAStool/nas-tools#3984]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 3.0.2
>
> 环境: docker or windows or Synology
>Synology

## 你遇到什么问题了？

> nastool内置的站点没有馒头

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
现在支持68个站的索引，有馒头。
如果是说认证，目前是没有的。

**Comment by qianqisj** [comment]
强烈需求，认证里加mteam馒头站，感谢大大！

**Comment by zraxx** [comment]
馒头站点登录不了
