### ISSUE TITLE
关闭OpenAI聊天交互

### ISSUE THREAD

**Issue by Rexexe** [NAStool/nas-tools#3985]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.5
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 希望可以手动关闭OpenAI聊天交互功能，我不需要聊天，只需要它辅助识别就行。而且不知道是不是bug，我用搜索关键词，nastool直接就开始下载。比如“搜索爱死机”，nastool直接开始下载第一季、第二季、第三季，都没有给我选择

**Comment by jxxghp** [comment]
看频道说明

**Comment by Rexexe** [comment]
> 看频道说明

看过3.1.0的说明了，没有关闭远程交互的东西啊

我需要这个功能
![image](https://user-images.githubusercontent.com/27289798/227697987-e8e6c3b7-020d-4a1c-9ba3-db39387d7f6b.png)

但是不需要这个功能
![image](https://user-images.githubusercontent.com/27289798/227698019-04ea5d28-ecd2-4759-9fe3-a810e8b916dd.png)

就是说我不需要跟openAI聊天，它就是工具，能不能添加一个开关，关闭ChatGPT对话功能

**Comment by Rexexe** [comment]
因为这样很麻烦，原来只需要直接发送电影名称，然后123选择，开启ChatGPT之后还要加关键词
但是增强识别又是一个很不错的功能，希望两个功能不要耦合在一起
