### ISSUE TITLE
微信消息怎么那个成员查询，单独反馈给那个成员？

### ISSUE THREAD

**Issue by Mrxlei** [NAStool/nas-tools#3987]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>
> 环境: docker or windows or Synology
>

## 微信消息怎么那个成员查询，单独反馈给那个成员？请教如何设置？

**Comment by thsrite** [comment]
默认不就是这样？

**Comment by Mrxlei** [comment]
比如我查询了下载一个电影，下载完毕的消息反馈能不能指定到查询成员

**Comment by thsrite** [comment]
> 比如我查询了下载一个电影，下载完毕的消息反馈能不能指定到查询成员

那需不需要个能接受所有消息的。
例如你家人只能看到自己查询下载的消息，而你能看所有

**Comment by jxxghp** [comment]
交互类消息原路返回，通知类消息群发。
