### ISSUE TITLE
类似radarr和sonarr的ical日历功能

### ISSUE THREAD

**Issue by litianyu0707** [NAStool/nas-tools#3995]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.9.1
>unraid
> 环境: docker

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？
ical日历功能，比如最后的生还者刚上映，一个周一集，我订阅了，通过ical我可在我的日历上清晰的显示几号会有电视剧看

## 这个功能有什么可以参考的资料吗？
radarr和sonarr都有此功能。谢谢作者大大考虑一下。另外想问一下，我只用pt（通过jackett）不用bt，是不是可以放心大胆的升级最新版呢？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by jxxghp** [comment]
你说你用了2.9.1是乱写的吧，不然怎么会不知道老早就有这个功能？

![image](https://user-images.githubusercontent.com/51039935/227522710-3e48cdae-5294-4124-a49b-c9d205608b9f.png)

**Comment by litianyu0707** [comment]
> 你说你用了2.9.1是乱写的吧，不然怎么会不知道老早就有这个功能？
> 
> ![image](https://user-images.githubusercontent.com/51039935/227522710-3e48cdae-5294-4124-a49b-c9d205608b9f.png)

额。。。。。我意思是生成ical链接，然后加入到手机日历。这样我在手机日历就能看到了。可以实现吗

**Comment by litianyu0707** [comment]
![image](https://user-images.githubusercontent.com/22993989/227523969-def0dd4d-8081-49ee-bc9e-0906d5ed9213.png)

**Comment by yubanmeiqin9048** [comment]
这个功能好

**Comment by litianyu0707** [comment]
> 这个功能不错

希望能出此功能🫠

**Comment by jxxghp** [comment]
已支持，将http://ip:port/ical 添加到日历App
