### ISSUE TITLE
3.1版本，重启功能似乎bug了，点了转圈圈但是没重启

### ISSUE THREAD

**Issue by zmmcyzmmcy** [NAStool/nas-tools#3999]
rt

**Comment by thsrite** [comment]
看看日志。如果当时正在进行检索或订阅、刷流等的话，不会立即重启的，会等上述任务结束之后再重启

**Comment by zmmcyzmmcy** [comment]
![image](https://user-images.githubusercontent.com/59245218/227722051-324f525d-9f6b-4195-85b3-f3213ec643ea.png)
14:39 的时候强制关机再开机的，如日志显示。
现在是22点，我点击重启后，日志没有任何显示，仍停留在14:39的时刻

**Comment by djydtzh** [comment]
我也遇到了相同的问题，重新安装，清空配置依然无法解决问题，无法重启也无法更新，日志最后一条是加载插件：<class 'app.plugins.modules.autosub.AutoSub'>，版本群晖套件版， v3.1.0 e5838c3
