### ISSUE TITLE
搜索、站点资源查询失败

### ISSUE THREAD

**Issue by jialuming** [NAStool/nas-tools#4002]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.0
>
> 环境: docker
>

## 你遇到什么问题了？

> 站点数据可以获取到,但是搜索、站点资源查询失败，

## 给出程序界面截图、后台运行日志或配置文件

> 站点数据
![image](https://user-images.githubusercontent.com/22130741/227700594-005b0b7e-d090-41e5-8a37-81607ebfb425.png)

> 站点资源无数据
![image](https://user-images.githubusercontent.com/22130741/227700690-b0ad5596-849a-4ba9-b31a-1a6fca18be23.png)

> 索引器图表，都是31秒
![image](https://user-images.githubusercontent.com/22130741/227700421-66edd96d-9669-400c-ac54-1b2f23ef1885.png)

> docker后台日志
![image](https://user-images.githubusercontent.com/22130741/227700379-6138175e-ad18-4257-891b-76388ec45818.png)

**Comment by Jagernb** [comment]
你好，我也遇到了同样的问题，有解决吗？

**Comment by jialuming** [comment]
> 你好，我也遇到了同样的问题，有解决吗？

docker 网络改成桥接就好了
