### ISSUE TITLE
请求同时开启多个微信交互开关，方便好友使用微信chatgpt

### ISSUE THREAD

**Issue by xyswordzoro** [NAStool/nas-tools#4010]
> NAStool 版本: v3.1
> 环境: docker 
> 你想要新增或者改进什么功能？

请求同时开启多个微信交互开关，方便好友使用微信chatgpt，
目前只能打开一个交互开关，
不知道能否实现，谢谢
![QQ截图20230325183958](https://user-images.githubusercontent.com/86150433/227712534-c7690a58-25d8-4605-9dd0-2d9d7588b097.png)

**Comment by thsrite** [comment]
chatgpt谁发的回复谁，你们一起用一个呗

**Comment by xyswordzoro** [comment]
> chatgpt谁发的回复谁，你们一起用一个呗

另一个给朋友 只推送入库消息，我自己一个是接受所有消息，所以才有这个情况
