### ISSUE TITLE
站点自动签到失效bug（带复现过程）

### ISSUE THREAD

**Issue by EliteOtaku** [NAStool/nas-tools#4015]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 3.10
>
> 环境: docker 

我发现自动签到经常莫名其妙失效，目前找到可复现过程如下：

1. 重新启动nastools后，可以部分解决问题
因为系统会正常启动站点自动签到服务启动，如图
![image](https://user-images.githubusercontent.com/29235152/227737099-5aa07db6-b32b-4cdb-87ad-985850a21f5b.png)

2. 但是在设定中修改并保存后，就没有看到系统提示启动站点自动签到服务，不知道是不是这个原因？
![image](https://user-images.githubusercontent.com/29235152/227737166-16267c42-b8ac-4a84-aed5-889b539857f7.png)
我试过用不同的时间格式，包括cron什么的，但都是在这里保存后，就会失效，只能通过重启nastools来恢复正常。

**Comment by jxxghp** [comment]
这个在3.10中已经修复了，请再测试看看。

**Comment by EliteOtaku** [comment]
> 这个在3.10中已经修复了，请再测试看看。

好的，我再去试试，对了，如果我想设定为每天凌晨00：05自动签到，那么这样设定是否正确？
![image](https://user-images.githubusercontent.com/29235152/227749797-19db3f92-727e-4ba6-9599-a0a18c528d5a.png)

**Comment by EliteOtaku** [comment]
今天凌晨，自动签到运行正常
