### ISSUE TITLE
电视剧无法识别是否已存在于媒体库中

### ISSUE THREAD

**Issue by genesis-lua** [NAStool/nas-tools#4016]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本:  v3.1.0 59003e7
>
> 环境: docker 
>

## 你遇到什么问题了？

> 下载的剧集无法识别是否已存在于媒体库中，而电影是可以的，历史版本2.9.1也是可以的

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 暂未查询到类似问题

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

>
![image](https://user-images.githubusercontent.com/26401920/227744819-20c0c0d9-900a-469c-a16a-44655fd8b6b3.png)
![image](https://user-images.githubusercontent.com/26401920/227744840-eda1a768-279f-4458-82f0-e73e14453d54.png)
![image](https://user-images.githubusercontent.com/26401920/227744845-4aa139be-bf1c-457d-ae48-6fc02d313270.png)
![image](https://user-images.githubusercontent.com/26401920/227744851-effe4596-13c0-4043-86ea-6ab14a257da2.png)
以上是3.1.0的截图
以下是2.9.1的截图能正常显示是否已存在
![image](https://user-images.githubusercontent.com/26401920/227744915-0e56a41e-6213-49aa-a6f9-e0a1534da254.png)

**Comment by Wangsc1** [comment]
我看了眼我的，同是59003e7版本，电影电视剧都没识别😂

**Comment by log-time** [comment]
我的媒体库-媒体库同步，点一下试试？

**Comment by log-time** [comment]
看一下同步的媒体库列表选择正确吗

**Comment by Wangsc1** [comment]
> 
> 
> <img width="533" alt="截屏2023-03-26 08 29 19" src="https://user-images.githubusercontent.com/66826612/227748768-ef87ddcf-18ad-402f-9d1e-7f908def93e3.png">
> 
> 看一下同步的媒体库列表选择正确吗

可以了，这玩意不是会自动同步的吗，怎么还要手动的

**Comment by zraxx** [comment]
电视剧不行，电影可以!![Screenshot_2023-03-26-09-08-14-636_com.android.browser.png](https://user-images.githubusercontent.com/25578054/227749798-1fdeb018-f3c1-43a4-9754-25d553d9ac1f.png)

**Comment by log-time** [comment]
> 同步

![Uploading 截屏2023-03-26 09.16.11.png…]()

**Comment by log-time** [comment]
> 

<img width="296" alt="截屏2023-03-26 09 16 11" src="https://user-images.githubusercontent.com/66826612/227750024-d6b8072d-7487-4ed7-a7a0-22a48745fcd0.png">

**Comment by jxxghp** [comment]
<img width="1338" alt="image" src="https://user-images.githubusercontent.com/51039935/227751393-7ca63fec-88fb-499a-a1b2-29745427b742.png">

**Comment by genesis-lua** [comment]
目录有同步好，我看你们的又用emby试了，emby的可以正常识别电视剧，用jellyfin是不行的，不是没点到同步。我用jellyfin在2.9.1的版本是可以识别电视剧的，目录设置也没有错，识别转移那些都是正常的

**Comment by genesis-lua** [comment]
> 电视剧不行，电影可以!![Screenshot_2023-03-26-09-08-14-636_com.android.browser.png](https://user-images.githubusercontent.com/25578054/227749798-1fdeb018-f3c1-43a4-9754-25d553d9ac1f.png)

你是不是也用的jellyfin做媒体服务器

**Comment by zraxx** [comment]
> > 电视剧不行，电影可以!![Screenshot_2023-03-26-09-08-14-636_com.android.browser.png](https://user-images.githubusercontent.com/25578054/227749798-1fdeb018-f3c1-43a4-9754-25d553d9ac1f.png)
> 
> 你是不是也用的jellyfin做媒体服务器

是的

**Comment by genesis-lua** [comment]
> 

这个是用什么搜索？在jellyfin里搜索？

> <img alt="image" width="1338" src="https://user-images.githubusercontent.com/51039935/227751393-7ca63fec-88fb-499a-a1b2-29745427b742.png">

大佬要不重开这个issue再看看有没有问题？

**Comment by genesis-lua** [comment]
> <img alt="image" width="1338" src="https://user-images.githubusercontent.com/51039935/227751393-7ca63fec-88fb-499a-a1b2-29745427b742.png">

大佬要不重开这个issue再看看有没有问题？
