### ISSUE TITLE
媒体库设置、功能签到等设置均没有了

### ISSUE THREAD

**Issue by LucifielHack** [NAStool/nas-tools#4020]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
> v3.1.0
> 环境: docker or windows or Synology
> docker

## 你遇到什么问题了？

> 界面中部分设置没有了，包括媒体库设置、PT站设置、签到设置

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 浏览过了，没有相关问题

## 你期望的结果

> 像之前一样正常使用这些功能

## 给出程序界面截图、后台运行日志或配置文件
![image](https://user-images.githubusercontent.com/43723112/227755429-60de0433-0029-43fc-9903-02383c539b44.png)

**Comment by log-time** [comment]
左下角认证下

**Comment by LucifielHack** [comment]
> 左下角认证下

没有这些站点的账号啊。。。目前哪个是可以注册的

**Comment by LeoMonkey** [comment]
有同样问题
