### ISSUE TITLE
群辉docker电视剧订阅下载推送不到下载器

### ISSUE THREAD

**Issue by Minecraft-Cube** [NAStool/nas-tools#4022]
## 你使用的 NAStool 是什么版本，什么环境？
>黑群晖DS918+
>v3.1.0
>群辉套件版/Docker版均使用过
## 你遇到什么问题了？
群辉docker订阅下载推送不到下载器
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是
## 你期望的结果
可以正常订阅推送
## 给出程序界面截图、后台运行日志或配置文件

![photo_2023-03-26_17-23-48](https://user-images.githubusercontent.com/77788545/227768248-2a9ba91b-02c5-4ab3-af07-427e5f1c5be3.jpg)

**Comment by H2Aoi** [comment]
我也是这样

**Comment by Dapong** [comment]
我也是这样

**Comment by Dapong** [comment]
> 我也是这样

重新配置下下载器的账号密码，好像是因为升级导致密码字符失效了

**Comment by Dapong** [comment]
> ## 你使用的 NAStool 是什么版本，什么环境？
> > 黑群晖DS918+
> > v3.1.0
> > 群辉套件版/Docker版均使用过
> 
> ## 你遇到什么问题了？
> 群辉docker订阅下载推送不到下载器
> 
> ## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
> 是
> 
> ## 你期望的结果
> 可以正常订阅推送
> 
> ## 给出程序界面截图、后台运行日志或配置文件
> ![photo_2023-03-26_17-23-48](https://user-images.githubusercontent.com/77788545/227768248-2a9ba91b-02c5-4ab3-af07-427e5f1c5be3.jpg)

重新配置下下载器的账号密码，好像是因为升级导致密码字符失效了

**Comment by Minecraft-Cube** [comment]
> > 我也是这样
> 
> 重新配置下下载器的账号密码，好像是因为升级导致密码字符失效了

没有用啊 我是4.5.2 你是什么版本啊
