### ISSUE TITLE
刷流出错并没有显示

### ISSUE THREAD

**Issue by lyj0309** [NAStool/nas-tools#4024]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
> 3.10
> 环境: docker or windows or Synology
> docker

## 你遇到什么问题了？

> 描述一下你遇到的问题

![image](https://user-images.githubusercontent.com/50474995/227778052-edc38529-f3b5-43e1-90fd-d880ebbba0ae.png)

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
这种就是RSS格式有问题，看日志
