### ISSUE TITLE
索引器里只有内建索引器了，添加不了外部索引如Jackett

### ISSUE THREAD

**Issue by oynt** [NAStool/nas-tools#4027]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.0 cd39688
>
> 环境: docker
>

## 你遇到什么问题了？

> 描述一下你遇到的问题
索引器里只有内建索引了，添加不了外部索引如Jackett

**Comment by genesis-lua** [comment]
3.0之后的版本都不能用外置的种子索引器，只能在添加的PT站里搜索

**Comment by oynt** [comment]
> 3.0之后的版本都不能用外置的种子索引器，只能在添加的PT站里搜索

只支持PT站的话资源不够啊,而且PT站还有一定的门槛限制,另外,pt站资源都是高清和超高清居多,一般家庭电视的分辨率一部电影2G-5G左右就可以了,再高也没有什么意义,而我在PT站下了妇联系列直接用了将近600G的空间,我一个2T的硬盘也就存存一部电视剧的样子,所以,普通BT站的资源还是需要的.
请问有加站外索引或者扩充内部索引内容的计划吗?
另外,我翻了一圈没有找到放弃外置索引的解释说明,请问放弃外置索引有什么优势吗?

**Comment by chengnan049** [comment]
> 

既然是内建了那么业务范围就更大了，有问题也好排查，至于清晰度多高这个那是你的需求，世界太大了照顾不了所有人
有些用户甚至还用的是自己的电脑，要怪只能怪之前的某T事件了，迫于压力只能删掉了

如果你的硬盘不够大而且资源热门不妨可以用「资源频道」+[「Alist」](https://github.com/alist-org/alist/)+「阿里云盘」来实现，还省了空间，搭配 CloudDrive2 也能实现刮削+个人影视库的需求

**Comment by oynt** [comment]
某T事件是什么？我刚从ra转过来，入坑时间短😅😅



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月28日(周二) 晚上6:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [NAStool/nas-tools] 索引器里只有内建索引器了，添加不了外部索引如Jackett (Issue #4027)




   
既然是内建了那么业务范围就更大了，有问题也好排查，至于清晰度多高这个那是你的需求，世界太大了照顾不了所有人
 有些用户甚至还用的是自己的电脑，要怪只能怪之前的某T事件了，迫于压力只能删掉了
 
如果你的硬盘不够大而且资源热门不妨可以用「资源频道」+「Alist」+「阿里云盘」来实现，还省了空间，搭配 CloudDrive2 也能实现刮削+个人影视库的需求

**Comment by chengnan049** [comment]
> 某 T 事件是什么？我刚从 ra 转过来，入坑时间短😅😅
> […](#)
> --- 原始邮件 --- 发件人: ***@***.***&gt; 发送时间: 2023 年 3 月 28 日 (周二) 晚上 6:43 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [NAStool/nas-tools] 索引器里只有内建索引器了，添加不了外部索引如 Jackett (Issue #4027) 既然是内建了那么业务范围就更大了，有问题也好排查，至于清晰度多高这个那是你的需求，世界太大了照顾不了所有人 有些用户甚至还用的是自己的电脑，要怪只能怪之前的某 T 事件了，迫于压力只能删掉了 如果你的硬盘不够大而且资源热门不妨可以用「资源频道」+「Alist」+「阿里云盘」来实现，还省了空间，搭配 CloudDrive2 也能实现刮削 + 个人影视库的需求 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

我也不知道能不能说，一个大V介绍了本工具，你想想后果是啥，后来赶紧删掉了，项目停更一段时间，因此这种好东西自己私下分享就行，绝对不能出名
