### ISSUE TITLE
刮削不到直接删除？

### ISSUE THREAD

**Issue by royzheng** [NAStool/nas-tools#4029]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.0
>
> 环境: Debian11
>

## 你遇到什么问题了？

> 下载了一个迪士尼合集，发现没法刮削 直接就删除了？

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 就算没有结果也不能删除啊，我用的移动模式，结果发现文件就不见了（尝试了2次都有这个情况)

## 给出程序界面截图、后台运行日志或配置文件

09:53:25 | Meta | 正在查询TMDB电影：348666 ...
-- | -- | --
09:53:25 | Meta | 查询结果：迪士尼动画工作室短片收藏集
09:53:25 | Meta | 迪士尼动画收集 在TMDB中未找到媒体信息!

**Comment by jxxghp** [comment]
能先自己先弄明白再提问题？NT所有涉及文件删除的都会打印日志。
未识别成功的情况下设置了未识别目录会转移到未识别目录，没设置的则不处理。

**Comment by royzheng** [comment]
> 能先自己先弄明白再提问题？NT所有涉及文件删除的都会打印日志。 未识别成功的情况下设置了未识别目录会转移到未识别目录，没设置的则不处理。

1. 下载器:
QB, 监控选[是],标签隔离选[是],目录隔离[否],转移方式[移动]
下载目录设置
电影，下载保存目录 /movie 访问目录 /movie
2. 基础设置:
刮削[开启], 二级目录 default_category
3. 在qb里下载
【迪士尼官方56部长篇动画及其续集 全收集】
保存目录/movie 
并打上[NASTOOL]标签
4. 下载完成后日志显示
09:53:25		
正在查询TMDB电影：348666 ...
09:53:25		
查询结果：迪士尼动画工作室短片收藏集
09:53:25		
迪士尼动画收集 在TMDB中未找到媒体信息!
5. 文件都不见了
确实没设置 未识别目录

**Comment by jxxghp** [comment]
NT是不会不打日志就删除文件的，代码开源你可以看，有删除文件的就那几个地方。
同时也检查了下文件转移的逻辑，你这个场景并不会触发删除。
你要是下载器的任务，倒是要提醒你检查下是不是下载器联动删除掉了。

**Comment by jxxghp** [comment]
另外，手动删除历史记录时，如果选择的同步删除源文件的菜单，也是会删除文件的，但是也会打印日志。
