### ISSUE TITLE
记录一个启动脚本的问题

### ISSUE THREAD

**Issue by eric1932** [NAStool/nas-tools#4030]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 某个旧版升级到最新
>
> 环境: Docker on Synology
>

## 你遇到什么问题了？

> 旧容器无法启动

![CleanShot 2023-03-26 at 20 09 13@2x](https://user-images.githubusercontent.com/10938293/227831998-b563a818-118d-433c-a9d8-ac6e9d35c06e.png)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 排查发现环境变量`$REPO_URL`使用的是旧的repo地址，需要在环境变量中手动更新

![CleanShot 2023-03-26 at 20 15 15@2x](https://user-images.githubusercontent.com/10938293/227832170-9f4f540c-2717-4e5d-9bc6-13edaf69525e.png)

**Comment by jxxghp** [comment]
重新镜像

**Comment by eric1932** [comment]
> 重新拉镜像重新配置，机器里旧的镜像配置如何干预的了

有的时候不是特别方便重新配置共享文件夹
觉得可以在某个地方记录一下这个问题

**Comment by jxxghp** [comment]
> > 重新拉镜像重新配置，机器里旧的镜像配置如何干预的了
> 
> 有的时候不是特别方便重新配置共享文件夹 觉得可以在某个地方记录一下这个问题

可以联系下群里的Wiki的管理员添加到Wiki里，在Issues中打开会影响其它问题的处理。
