### ISSUE TITLE
又对比了首页刷新的问题

### ISSUE THREAD

**Issue by git-0101** [NAStool/nas-tools#4032]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.0
>
> 环境: docker
>

## 你遇到什么问题了？

> 之前版本速度很快，又对比了下，作者大大看下能否定位哪里改动导致变化了。

https://user-images.githubusercontent.com/115487446/227854098-febbc6f7-4187-44cc-a09e-4dd5eeb9c401.mp4

https://user-images.githubusercontent.com/115487446/227854208-8779c2f9-4330-42e5-9ad0-cab869f4773c.mp4

**Comment by jxxghp** [comment]
感谢这么详细的反馈。为了避免刷新时浏览器会提示“是否要重新提交表单“的问题，3.10登录后做了次重定向，这个可能会有一点点影响；
另外，在浏览器中看一下地址栏地址的变化情况，3.10有个小Bug就是如果在地址栏按回车可能会多次刷新，地址栏有多次变化说明是有问题，最多应该是变化一次，如果是这个问题下个版本会修复。

**Comment by git-0101** [comment]
感谢作者大大才是！好滴，收到！
