### ISSUE TITLE
Jellyfin媒体库同步后在nastools界面无法识别电视剧是否已存在

### ISSUE THREAD

**Issue by genesis-lua** [NAStool/nas-tools#4047]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.0 59003e7
>
> 环境: docker UNRAID
>

## 你遇到什么问题了？

> 测试发现通过jellyfin媒体库同步无法识别页面中电视剧是否已入库，但emby可以；对比了3.0和2.9的功能，可能是由于新版本添加了识别“电视剧-季数据”导致，如下图：

3.1版本jellyfin电视剧界面
![image](https://user-images.githubusercontent.com/26401920/228421019-50e2c28f-a0ee-493e-b370-b32e04be9828.png)  
![image](https://user-images.githubusercontent.com/26401920/228421171-235b80ff-7b85-4f79-bb02-039248db71b1.png)
------------------------
3.1版本emby电视剧界面
![image](https://user-images.githubusercontent.com/26401920/228421485-eb9288dd-db0e-49ea-a9a7-c4353e052b85.png)
![image](https://user-images.githubusercontent.com/26401920/228421590-4090b8a8-b18f-47db-a247-e97c09df3dd3.png)
-------------------------
2.9版本jellyfin电视剧界面
![image](https://user-images.githubusercontent.com/26401920/228422591-3b96ebe6-c75b-4fc9-8c4d-3c2d96b42ced.png)
![image](https://user-images.githubusercontent.com/26401920/228422719-2ab26857-07f5-44c7-a957-8f67a6a33d5b.png)

PS：均已配置好数据文件，视频下载、识别、转移均正常，媒体库有设置自动同步，测试前手动同步

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已提过issue，被关闭，问题未解决故重提issue，未发现有相关讨论；
现阶段解决办法：专门部署一个emby用于识别资源是否已下载，实际还是使用jellyfin

## 你期望的结果

> jellyfin媒体库同步能正常识别电视剧

## 给出程序界面截图、后台运行日志或配置文件
>该识别过程日志没有直接打出，不知道在哪里可以找到

**Comment by genesis-lua** [comment]
> 刚专门测试了一下Jellyfin，是可以正确识别是否存在的。

能否对一下文件结构？这中间不知道是不是存在没考虑到的因素

**Comment by genesis-lua** [comment]
我主要设置如下：
![image](https://user-images.githubusercontent.com/26401920/228454184-0f9b7a87-b77e-467e-b375-d5bb107e640d.png)
![image](https://user-images.githubusercontent.com/26401920/228454274-06fb8428-66c6-40e5-b5fe-0f6c97dec72d.png)
![image](https://user-images.githubusercontent.com/26401920/228454348-b1f92b3b-19ef-480f-b2ee-0840cca64caa.png)
其他的设置没有特别的地方
NAS的电视剧文件结构：
![image](https://user-images.githubusercontent.com/26401920/228455122-f44e51f7-fac8-46e8-92b7-afbbec861f90.png)
![image](https://user-images.githubusercontent.com/26401920/228455342-61bff175-bb20-451a-826b-49670dea4566.png)
![image](https://user-images.githubusercontent.com/26401920/228456105-0b60d063-61f8-4382-829d-1ae5ef0db21f.png)

**Comment by genesis-lua** [comment]
> 跟文件结构没有关系，数据是调Jellyfin的Api同步回来的，存到本地数据库。

请问下您用的是哪个jellyfin的镜像？我用的是nyanmisaka的，我等下再测试下官方的

**Comment by genesis-lua** [comment]
> 跟文件结构没有关系，数据是调Jellyfin的Api同步回来的，存到本地数据库。

从media.db文件里面找出了点端倪
jellyfinea4d08af0acc2abfcb9aaddaa981412bbd8a18cadde3e216ec2d361ee6422673Series曼达洛人The Mandalorian201982856tt8111088\\192.168.50.168\gene-nas\Media\Videos\电视剧\曼达洛人 (2019)[{"season_num": 0, "episode_num": 1}, {"season_num": 0, "episode_num": 2}, {"season_num": 0, "episode_num": 3}, {"season_num": 0, "episode_num": 4}, {"season_num": 0, "episode_num": 5}, {"season_num": 0, "episode_num": 6}, {"season_num": 0, "episode_num": 7}, {"season_num": 0, "episode_num": 8}]
jellyfin记录的电视剧的季度数均为0（"season_num": 0）
------
emby5179Series曼达洛人The Mandalorian201982856tt8111088/mnt/Videos/电视剧/曼达洛人 (2019)[{"season_num": 1, "episode_num": 1}, {"season_num": 1, "episode_num": 2}, {"season_num": 1, "episode_num": 3}, {"season_num": 1, "episode_num": 4}, {"season_num": 1, "episode_num": 5}, {"season_num": 1, "episode_num": 6}, {"season_num": 1, "episode_num": 7}, {"season_num": 1, "episode_num": 8}]
emby记录的电视剧季度数正常

**Comment by genesis-lua** [comment]
另外换了几个不同镜像的jellyfin一样无法识别，我再尝试看季数据如何修复

**Comment by zraxx** [comment]
最新3.1.1版本已修复，谢谢！![Screenshot_2023-03-30-08-54-13-798_com.android.browser.png](https://user-images.githubusercontent.com/25578054/228700376-725ad53a-b755-4cfd-a8bb-83be7e46c0ee.png)
