### ISSUE TITLE
能否给“Cloudflare IP优选”插件增加“是否走代理服务器”选项？

### ISSUE THREAD

**Issue by LoSiTeE** [NAStool/nas-tools#4049]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.0
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 能否给“Cloudflare IP优选”插件增加“是否走代理服务器”选项？

## 这个功能有什么可以参考的资料吗？

> 查询日志发现这个插件使用的是cloudflarespeedtest，查看测试结果发现此插件在nastool“基础设置”中设置了代理服务器时，测速及更新好像会默认走代理服务器，而我的nastool里的站点设置都是不走代理的，不知道这样会不会影响cloudflare的ip优选结果。如果有影响的话能否在该插件中加上“是否走代理服务器”这个选项会好一些？

**Comment by thsrite** [comment]
加了个自定义参数，自己玩吧
