### ISSUE TITLE
春天  做种数量bug反馈

### ISSUE THREAD

**Issue by Tartarus2014** [NAStool/nas-tools#4052]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>
> 环境: docker or windows or Synology
>

## 你遇到什么问题了？

> 描述一下你遇到的问题

春天 保种数量不对，站点实际做种1000+，nastool只能显示200个，为第一页做种数量。 

## 你期望的结果

期望改进，可以显示完整的做种数量

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
<img width="742" alt="截屏2023-03-29 18 42 48" src="https://user-images.githubusercontent.com/39802246/228509534-73933a81-e965-4d63-a558-e61da9b53374.png">

**Comment by jxxghp** [comment]
修复了
