### ISSUE TITLE
OCR服务502

### ISSUE THREAD

**Issue by thofx** [NAStool/nas-tools#4054]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>
> 环境: docker or windows or Synology
>

## 你遇到什么问题了？

> OCR服务502了

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 是否有必要内置ocr

**Comment by jxxghp** [comment]
磁盘日志打满了，昨天下午处理了一下，现在应该好了吧

**Comment by thofx** [comment]
> 磁盘日志打满了，昨天下午处理了一下，现在应该好了吧

好了
