### ISSUE TITLE
目录转移支持转移字幕文件

### ISSUE THREAD

**Issue by Eucliddd** [NAStool/nas-tools#4057]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.0
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 目录转移支持转移字幕文件

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by zraxx** [comment]
一直都支持，如果字幕在目录里，一起同步的。
