### ISSUE TITLE
nastools刮削的nfo元数据引起外网进度条卡顿

### ISSUE THREAD

**Issue by Jushb** [NAStool/nas-tools#4061]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.9.1
>
> 环境: docker in unraid
>

## 你遇到什么问题了？

> nastools刮削的nfo元数据，emby（正版）读取后，获取不到时间轴。安卓tv端，播放中按两下【上】键，灰框进度条，一般5-10分钟一个。
这个最大的问题，就是没有时间轴的话，【安卓电视盒子】【外网播放】时无法拖拽【进度条】，查了一个月才查到是元数据的问题。
安卓手机不受影响。
emby自己刮削的元数据就没这个问题
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是的，没找到相关问题答案
> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果
期望回复，请大佬帮忙找到解决方案

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by Jushb** [comment]
另外日志里有一个报错
Callstack:
Traceback (most recent call last):
  File "/nas-tools/app/media/scraper.py", line 434, in gen_scraper_files
    seasonposter = media.fanart.get_seasonposter(media_type=media.type,
  File "/nas-tools/app/media/fanart.py", line 190, in get_seasonposter
    return self._images.get("seasonposter", {}).get(season, "") or default
AttributeError: 'str' object has no attribute 'get'

**Comment by jxxghp** [comment]
2.9.1不再支持

**Comment by Jushb** [comment]
> 

昨晚重装了，升级了3.1.1，还是同样的情况
