### ISSUE TITLE
windows运行，报错缺少文件

### ISSUE THREAD

**Issue by AisukaYuki** [NAStool/nas-tools#4066]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.1
>
> 环境: docker or windows or Synology
>windows

## 你遇到什么问题了？

>  报错

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

![image](https://user-images.githubusercontent.com/17586327/228800940-86172cd0-920e-4c33-920a-ad0494cc9bc5.png)

**Comment by jxxghp** [comment]
release附件已更新，请重新下载
