### ISSUE TITLE
下载器会自动添加非刷流、正常下载任务，且无标签，无分类。是否和我的nastool或者下载器的设置有关系？

### ISSUE THREAD

**Issue by aicenluo** [NAStool/nas-tools#4072]
3.1.1 docker

NAStool 版本: vx.x.x
V3.1.1
环境: docker or windows or Synology
docker

你遇到什么问题了？
描述一下你遇到的问题
我正确设置了下载器及刷流下载器，并且正常运行了一段时间。直到前几天，我突然发现我的qp下载器，每过几分钟，会莫名添加很多无标签及分类的下载任务，我经过查看，发现并不是我的下载器或者刷流下载器添加的任务，在nastool的日志里面也没有看到添加这些下载任务书的记录，并且，这些任务的存储路径是我的qb默认下载路径（我的耍流任务专门设置了耍流路径，具体见图），而不是我已经设置好的movie、耍流路径。

是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是

请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

你期望的结果
描述以下你期望的结果
希望大佬帮忙分析一下这个情况出现的原因，是否和我的nastool设置有关？谢谢！

给出程序界面截图、后台运行日志或配置文件
![微信图片_20230330202513](https://user-images.githubusercontent.com/128604492/228843466-a017c53c-3452-48f2-80b4-c6173c38d964.png)

**Comment by aicenluo** [comment]
补充一下截图，发现所有的任务，TRACKER都来自于HDHome，我查询了所有的设置，实在找不到是哪里的原因，请大佬们解惑
![微信图片_20230331123202](https://user-images.githubusercontent.com/128604492/229023438-136ef0d5-7ed4-4e6a-896f-d368acb29847.png)

**Comment by aicenluo** [comment]
这个是我在nastool正在下载列表中的下载任务，都是每过几分钟莫名其妙自己添加的任务，既不是我订阅的，也不是刷流任务添加的。到底是nastool的问题还是qb的问题？
![微信图片_20230331141748](https://user-images.githubusercontent.com/128604492/229039178-429ce89a-4054-4f2f-ba67-8227cc4b126d.png)

**Comment by QAQQL** [comment]
日志传上来看看吧,实在不行qt改个密码不就知道了
