### ISSUE TITLE
HDSky网站站点维护功能无法正常连接使用

### ISSUE THREAD

**Issue by Phantom2000X** [NAStool/nas-tools#4082]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.1
>
> 环境: docker
>

## 你遇到什么问题了？

> HDSky网站站点维护功能无法正常连接使用
> 已经填写Cookie，获取User Agent
>  开启浏览器仿真提示Chrome模拟访问失败，耗时为0
![截屏2023-03-31 01 23 47](https://user-images.githubusercontent.com/11485809/228915962-8daf7adc-cfb9-4abf-b21c-5fd544770d7e.png)

> 关闭浏览器仿真提示无法打开网站，耗时339 毫秒
![截屏2023-03-31 01 20 26](https://user-images.githubusercontent.com/11485809/228915664-9a71e71b-32d2-46c0-9266-a0c2e55c4c62.png)

> 使用更新站点Cookie功能也会提示 Chrome模拟访问失败

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已经搜索过，发现没有列出的问题

## 你期望的结果

> 希望能够正常连接，并使用站点维护相关功能

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by ReddotCleaner** [comment]
天空在用户页是套了CF盾的，先看看是不是这个问题

**Comment by Phantom2000X** [comment]
> 天空在用户页是套了CF盾的，先看看是不是这个问题

这个一般要怎么绕过去…有文档我查阅了解一下吗，不太清楚cf盾的触发条件。我发现在rss订阅好像也拉不到资源列表

**Comment by Phantom2000X** [comment]
> 

好的，今晚我尝试一下，之前我使用2.X版本的时候还是能正常访问的

>

**Comment by Phantom2000X** [comment]
> > > 天空在用户页是套了CF盾的，先看看是不是这个问题
> > 
> > 
> > 这个一般要怎么绕过去…有文档我查阅了解一下吗，不太清楚cf盾的触发条件。我发现在rss订阅好像也拉不到资源列表
> 
> 据我所知，这个盾百分百触发，绕不过去；至于rss拉不到资源，应该跟这个关系不大；可以用连接nastool命令行尝试能不能访问天空的网站

好的，今晚我尝试一下，之前我使用2.X版本的时候还是能正常访问的

**Comment by Phantom2000X** [comment]
> > > 天空在用户页是套了CF盾的，先看看是不是这个问题
> > 
> > 
> > 这个一般要怎么绕过去…有文档我查阅了解一下吗，不太清楚cf盾的触发条件。我发现在rss订阅好像也拉不到资源列表
> 
> 据我所知，这个盾百分百触发，绕不过去；至于rss拉不到资源，应该跟这个关系不大；可以用连接nastool命令行尝试能不能访问天空的网站

您好，请问下有具体教程吗？我要怎么连接到nastool的命令行

**Comment by Phantom2000X** [comment]
最后测试挂了代理服务器后可以正常拉取订阅和访问，虽然开启模拟chrome模式还是会失败，但非模拟模式下可以成功
