### ISSUE TITLE
目录同步无法自动运行

### ISSUE THREAD

**Issue by jder1234** [NAStool/nas-tools#4089]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.1
>
> 环境: Synology 套件
>

## 你遇到什么问题了？

> Nastool 能成功添加transmission下载， 但下载完后，无法自动实时同步。 我手动点击目录同步后， 才会创建硬链接同步文件（后续流程正常）。   

> 怀疑是否没法监测文件夹内容变动？   查看日志只看到成功添加下载的日志，后续就没有日志了。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 下载完后， 实时检测目录文件变化，同步文件（创建硬链接）。

## 给出程序界面截图、后台运行日志或配置文件

> Nastool 日志： 
![image](https://user-images.githubusercontent.com/106365097/229039980-2e06cfb9-c3c0-4fed-b3a1-d00065d1d66d.png)

> Nastool 同步设置：
![image](https://user-images.githubusercontent.com/106365097/229040177-7dc65e2a-a1a1-4971-948f-4d6969636143.png)

**Comment by jxxghp** [comment]
1、打开兼容模式试试
2、观察启动是否有报错，有的话要解决，参考群里的常见问题。
还不行就放弃吧，我也不知道什么情况。
