### ISSUE TITLE
ai字幕自动生成插件  第一次运行，生成了英文字幕文件，但是生成中文这步就出错了

### ISSUE THREAD

**Issue by MidnightShake** [NAStool/nas-tools#4090]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>3.1.1
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

> 描述一下你遇到的问题
ai生成字幕出错
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
已经浏览过Issues找不到相关
> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果
希望能成功生成中文字幕

## 给出程序界面截图、后台运行日志或配置文件
出错日志内容：
Plugin】cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "/nas-tools/app/plugins/modules/autosub.py", line 310, in __process_folder_subtitle
    self.__translate_zh_subtitle(lang, f"{file_path}.{lang}.srt", f"{file_path}.zh.srt")
  File "/nas-tools/app/plugins/modules/autosub.py", line 646, in __translate_zh_subtitle
    result = self.__do_translate_with_retry(batch_content)
  File "/nas-tools/app/plugins/modules/autosub.py", line 600, in __do_translate_with_retry
    ret, result = OpenAiHelper().translate_to_zh(text)

> 如UI BUG请提供截图及配置文件截图
![WX20230331-144447@2x](https://user-images.githubusercontent.com/103491263/229043869-3d472c31-5051-4232-854d-0d21bdc0314e.png)
![WX20230331-144412@2x](https://user-images.githubusercontent.com/103491263/229043880-77c4a391-c6a7-43f7-86cb-3ccf2e8f7273.png)

> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by MidnightShake** [comment]
<img width="1008" alt="WeChat9059ee212e64eb60bdcf021054524ac8" src="https://user-images.githubusercontent.com/103491263/229045956-6fc3f10f-f208-4476-a360-7149ae1df0e6.png">

**Comment by lightolly** [comment]
gpt apikey是不是没有配置

**Comment by MidnightShake** [comment]
> GPT APIKEY是不是没有配置，翻译依赖GPT 的API Key

谢谢提醒，应该是，刚看到了开发者的更新涉及了这部分的优化，因为当时一时忘了填API，错误日志也并没有其他提示，造成了困惑
