### ISSUE TITLE
希望能改进自动签到

### ISSUE THREAD

**Issue by djydtzh** [NAStool/nas-tools#4092]
## 你使用的 NAStool 是什么版本，什么环境？
3.1.1
> NAStool 版本: 3.1.1
>
> 环境: 群晖套件版

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？
部分网站签到有概率失败，不会重新签到，希望增加自动重新签到功能。
今天如果签到过，重新设置的签到时间明天才会生效，没办法测试自己签到设置的对不对，希望增加签到时间当日生效的选项。
不确定的问题：签到功能的cron表达式是否支持例如【 0 6,12,18 * * * 】这种格式的重复签到，并且每到触发时间都尝试签到一次。
## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by EliteOtaku** [comment]
确实，有时候会缺一个站点签到失败，如果针对失败的站点，在间隔一段时间后再次签到，这样说不定就成功了。

然后再等一段时间后，如果依然签到失败，再发送签到失败消息提示，这样更合理。
