### ISSUE TITLE
希望NAStool的首页信息提示能改进一下

### ISSUE THREAD

**Issue by EliteOtaku** [NAStool/nas-tools#4097]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 3.11
>
> 环境: docker
>

## 你遇到什么问题了？
如图，我的emby媒体库有一个JAV，保存成人节目，在NAStool里面并没有关联，但NAStool的播放记录提示里面居然也显示了……这这这……总之希望开发者大大看看能否改进一些……囧

![image](https://user-images.githubusercontent.com/29235152/229260450-0989d9c3-0de8-4496-9717-c34fe307c03c.png)

**Comment by c939984606** [comment]
半夜23点还在看😬

**Comment by fxqq** [comment]
那是调用的emby的api，没办法的
