### ISSUE TITLE
能否加上刷流任务总容量限制

### ISSUE THREAD

**Issue by wshocn** [NAStool/nas-tools#4103]
能否在刷流任务里加个所有运行的刷流任务总容量限制

比如我有1t的固态刷流
分配了5个站点一个200g单容量限制，为了不爆盘我只能刷5个

如果有总容量限制，我可能会刷更多，毕竟每个站不一定实时用得上200g

感谢大佬辛苦付出

**Comment by c939984606** [comment]
希望刷流增加自动删除错误下载任务并发送通知
