### ISSUE TITLE
仿真签到提示成功，实际未签到

### ISSUE THREAD

**Issue by kfqkfy** [NAStool/nas-tools#4110]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.1
>
> 环境: docker or windows or Synology
>docker

ttg签到开启仿真之后，提示仿真签到成功，实际未签到成功

**Comment by EliteOtaku** [comment]
HDArea今天也发现这个问题了

**Comment by yangc-vip** [comment]
HDArea今天是浏览器能打开，NT上模拟登陆都失败。改了ag ck都不行。浏览器仿真打开也不行。

**Comment by AfeirWu** [comment]
sharkpt也是这个问题，docker版本和群晖套件版都试了，都不行

**Comment by linjhon** [comment]
猪猪网和学校也是这样

**Comment by jxxghp** [comment]
可能是cf墙导致的，更新最新程序再试试看吧

**Comment by kfqkfy** [comment]
> 可能是cf墙导致的，更新最新程序再试试看吧

ttg一直都没有cf墙，最近这两天好像正常了，到时猪猪一直提示打开网站失败，开不开仿真都这样
