### ISSUE TITLE
订阅编辑增加包含和排除项

### ISSUE THREAD

**Issue by git-0101** [NAStool/nas-tools#4111]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.2
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 能否和自定义订阅一样增加包含和排除项。最近一些剧好几个版本，4k、4k 60fps、4k 60fps HQ，如果想获得4k 60fps，包含60fps,排除HQ，再结合默认的过滤规则和分辨率选择，可以很灵活的订阅指定版本。如果出现其它一些特定版本也可以灵活配置。这样就不用额外一条条增加过滤规则了。

**Comment by garybrandam** [comment]
+1

**Comment by yellowstrong** [comment]
+1

**Comment by git-0101** [comment]
感谢作者大大！收到！
