### ISSUE TITLE
订阅的综艺分为上下集，只订阅了上集或下集

### ISSUE THREAD

**Issue by shoumo680** [NAStool/nas-tools#4112]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.2
>
> 环境: docker 
>

## 你遇到什么问题了？

> 订阅的综艺分为上下集，只订阅了上集或下集

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 上集和下集能全订阅

### 日志
![img-2023 04 02-11 48 49](https://user-images.githubusercontent.com/12744973/229330925-ee75748d-15ff-4930-ac3f-a4b33699de90.jpg)

### 下载的文件
![Quicker_20230402_115507](https://user-images.githubusercontent.com/12744973/229330979-d51863ad-f0f3-4aa5-9b76-17089a6a7e5a.png)

### 刮削后的文件

Plus和陪你看进行集偏移了

![Quicker_20230402_121525](https://user-images.githubusercontent.com/12744973/229331030-c33df2c6-899d-4e3f-9c12-7a2c91498442.png)

**Comment by jxxghp** [comment]
综艺命名不规范，跟TMDB不一致。
自已想办法通过自定义识别词解决。
