### ISSUE TITLE
链接可访问，但是提示没有检索到结果

### ISSUE THREAD

**Issue by Mantoui** [NAStool/nas-tools#4121]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.2
>
> 环境: docker
>

## 你遇到什么问题了？

> 描述一下你遇到的问题

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果
实际请求页面是有返回结果的，但是提示没有检索到信息

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
![image](https://user-images.githubusercontent.com/4598262/229428668-1ddf3593-604a-4ac3-85aa-1223f9215e6f.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by aaaa9990aaaa** [comment]
我也遇到了同样的问题，最新版本的docker host

**Comment by jxxghp** [comment]
你的电脑能访问，不代表docker环境能访部
