### ISSUE TITLE
无法使用，左侧资源列表无法显示

### ISSUE THREAD

**Issue by love5461** [NAStool/nas-tools#4122]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 3.012
>
> 环境: docker or openwrt
>

## 你遇到什么问题了？
左侧资源列表没有，无法找到，豆瓣资源都找不到

> 描述一下你遇到的问题
[](url)
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
![image](https://user-images.githubusercontent.com/21037152/229453276-11b74e35-f0ed-4036-bada-4a65b515c344.png)

**Comment by reputati0n** [comment]
新版本要pt站认证的，你这没认证吧
