### ISSUE TITLE
怎么解决？

### ISSUE THREAD

**Issue by love5461** [NAStool/nas-tools#4125]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.9.1
>
> 环境: docker 
>
![image](https://user-images.githubusercontent.com/21037152/229525673-105b4cb0-5b7a-4a62-a75d-82f55fac1ee7.png)

stdout: 程序自动升级已关闭，如需自动升级请在创建容器时设置环境变量：NASTOOL_AUTO_UPDATE=true
stdout: 以PUID=0，PGID=0的身份启动程序...
stdout: 2023-04-03T21:33:45: PM2 log: Launching in no daemon mode
stdout: 2023-04-03T21:33:45: PM2 log: App [NAStool:0] starting in -fork mode-
stdout: 2023-04-03T21:33:45: PM2 log: App [NAStool:0] online
stdout: 正在加载配置：/config/config.yaml
stdout: NAStool 当前版本号：v2.9.1
stdout: 开始初始化数据库...
stdout: 数据库初始化完成
stdout: 开始更新数据库...
stdout: 数据库更新完成
stdout: 开始初始化数据...
stdout: 数据初始化完成
stdout: 日志输出类型为：console
stdout: WEB管理页面用户：admin
stdout: 未启用https，请使用 http://IP:3000 访问管理页面
stdout: TMDB API Key未配置，媒体整理、搜索下载等功能将无法正常运行！
stdout: TMDB匹配模式：正常模式
stdout: 媒体管理软件设置为：emby
stdout: emby配置不完整
stdout: 未配置电影媒体库目录
stdout: 未配置电视剧媒体库目录
stdout: 下载软件设置为：qbittorrent
stdout: 默认文件转移模式为：硬链接
stdout: 索引器设置为：builtin
stdout: 微信等移动端渠道搜索已开启自动择优下载
stdout: 下载软件监控未开启，下载器监控功能已关闭
stdout: 开始启动服务...
stderr: 2023-04-03 21:33:48,388	INFO: 站点自动签到服务启动
stderr: 2023-04-03 21:33:48,936	INFO: RSS订阅服务启动
stderr: 2023-04-03 21:33:48,936	INFO: 订阅定时搜索服务启动
stderr: 2023-04-03 21:33:48,936	INFO: 媒体库同步服务启动
stdout: Pending jobs:
stdout:     SiteSignin.signin (trigger: cron[hour='8', minute='1'], pending)
stdout:     Rss.rssdownload (trigger: interval[0:30:00], pending)
stdout:     Subscribe.subscribe_search_all (trigger: interval[6:00:00], pending)
stdout:     MediaServer.sync_mediaserver (trigger: interval[12:00:00], pending)
stdout:     MetaHelper.save_meta_data (trigger: interval[0:10:00], pending)
stdout:     Sync.transfer_mon_files (trigger: interval[0:01:00], pending)
stdout:     Subscribe.subscribe_search (trigger: interval[0:05:00], pending)
stdout:     SiteUserInfo.refresh_pt_date_now (trigger: interval[6:00:00], next run at: 2023-04-03 21:34:48 CST)
stdout:     Subscribe.refresh_rss_metainfo (trigger: interval[6:00:00], pending)
stdout:     MetaHelper.delete_unknown_meta (trigger: interval[12:00:00], pending)
stdout:     get_login_wallpaper (trigger: interval[1:00:00], next run at: 2023-04-03 21:33:48 CST)
stdout:  * Serving Flask app 'web.main' (lazy loading)
stdout:  * Environment: production
stdout:    WARNING: This is a development server. Do not use it in a production deployment.
stdout:    Use a production WSGI server instead.
stdout:  * Debug mode: on

**Comment by jxxghp** [comment]
旧版本不支持
