### ISSUE TITLE
请教一下Windows版本如何正确升级？

### ISSUE THREAD

**Issue by hn0550** [NAStool/nas-tools#4128]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 3.12
>
> 环境: Windows11
>

## 你遇到什么问题了？

> 我之前使用的是2.7.4版本，今天下载了3.12版本后直接运行3.12版本发现很多功能项缺失。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表发现之前有人提问过关于Windows无法自动更新的问题，请问如今Windows新版本仍然是需要重新配置吗？

## 你期望的结果

> 希望能解决这个问题，谢谢

**Comment by jxxghp** [comment]
已可正常升级，功能缺失看左下角按钮
