### ISSUE TITLE
认证站点可以增加下 PTTime嘛？🙏

### ISSUE THREAD

**Issue by tabris233** [NAStool/nas-tools#4131]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.2
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 认证站点增加 PTTime

## 这个功能有什么可以参考的资料吗？

> 以下是 PTtime 的官方文档：
> https://www.pttime.org/forums.php?action=viewtopic&topicid=3878&page=p19096#pid19096

我们参考了IYUUPlus校验文档
### 请求参数：
| 字段名称 | 字段说明   | 类型   | 必填 | 备注                                                     |
| -------- | ---------- | ------ | ---- | -------------------------------------------------------- |
| token    | 随机字符串 | string | Y    | 请求方随机生成，永不重复                                 |
| id       | 用户数字ID | int    | Y    | 用户在站点的唯一数字ID                                   |
| verity   | 验证字段   | string | Y    | 验证算法：`MD5($token . $id . sha1($passkey) . $secret)` |
### 响应参数：
| 字段名称 | 字段说明 | 类型    | 必填 | 备注                    |
| -------- | -------- | ------- | ---- | ----------------------- |
| success  | 验证结果 | boolean | Y    | 成功`true`、失败`false` |
| msg      | 错误消息 | string  | N    | 失败提示信息            |
### 验证步骤：
1. 双方提前约定私有密钥：`$secret`
2. IYUU服务器携带3个请求参数，对接口地址发起HTTP`GET`请求
3. 站点接收3个请求参数
4. 站点验证用户id是否存在、账户是否异常等
5. 站点得到用户`$passkey`字段
6. 验证算法：`$verity === MD5($token . $id . sha1($passkey) . $secret)`
7. 验证成功返回报文：`{"success": true}`
8. 验证失败返回报文：`{"success": false, "msg": "失败提示信息"}`

申请校验API：注意是应用开发者申请，应用使用者并不需要该API
1、联系管理，发送站内信，告知应用名称，申请用户校验。
2、等待管理回复，获得$secret
3、校验链接：`https://www.pttime.org/接口地址?token=你随机生成的token&id=用户所填id&verity=验证算法值（$verity = MD5($token . $id . sha1(用户所填$passkey) . $secret)）`

验证成功返回报文
1、验证成功：{"success": true}

失败返回报文如下
1、{"success": false, "msg": "缺少参数：token"}
2、{"success": false, "msg": "缺少参数：id"}
3、{"success": false, "msg": "缺少参数：verrity"}
4、{"success": false, "msg": "用户不存在"}
5、{"success": false, "msg": "用户已封禁"}
6、{"success": false, "msg": "校验失败"}

**Comment by kingcard1131** [comment]
支持！

**Comment by log-time** [comment]
IYUU不是已经支持了

**Comment by tabris233** [comment]
> IYUU不是已经支持了

我又看了下 IYUU 的资料。
好像是新的 IYUUPlus 不行（因为我没有 IYUU 鉴权的 8 个站点）。
但旧的 IYUUAutoReseed 貌似可以，只要该配置文件执行就好？ 等晚上回家试试。

**Comment by jxxghp** [comment]
你是站点方吗？如果是的话可以的。

**Comment by bxb100** [comment]
@jxxghp 上次我和站长聊过, 他是同意的, 我也发邮件给你了, 可能你没能看见...

如果方便的话, 我可以把站长的微信通过邮件的方式发给你, 你可以直接和他联系

**Comment by chenxi520** [comment]
希望支持，iyuuplus里面也需要8站点认证，直接就不能玩了

**Comment by blankvip** [comment]
希望支持

**Comment by synebula** [comment]
辛苦作者了，确实就这个站还能有望验证，要不看着那么好的工具用不了了😂
