### ISSUE TITLE
手动识别蓝光原盘时日志显示错误

### ISSUE THREAD

**Issue by shendoublexiang** [NAStool/nas-tools#4134]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: [v3.1.2 ef5984f]
>
> 环境: Synology 中的 docker 
>

## 你遇到什么问题了？

> 手动识别蓝光原盘时转移错误

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是的

## 你期望的结果

> 正确识别并转移原盘文件

日志显示如下

14:38:59 | Rmt | 正在硬链接目录：/video/动画/[BDMV][190226] 機動戦士ガンダムUC Blu-ray BOX => /video/Link/动漫/动漫/机动战士高达UC（独角兽） (2010)/Season 1
-- | -- | --
14:39:03 | Rmt | 文件 /video/动画/[BDMV][190226] 機動戦士ガンダムUC Blu-ray BOX 硬链接完成
14:39:03 | Meta | 正在查询TMDB电视剧：45500 ...
14:39:03 | Meta | 45500 查询结果：机动战士高达UC（独角兽）
14:39:06 | Rmt | 文件转移时发生错误：expected str, bytes or os.PathLike object, not NoneType - Traceback (most recent call last): File "/nas-tools/app/filetransfer.py", line 801, in transfer_media file_name=os.path.basename(ret_file_path), File "/usr/lib/python3.10/posixpath.py", line 142, in basename p = os.fspath(p) TypeError: expected str, bytes or os.PathLike object, not NoneType
14:39:06 | Message | 发送消息 Server：title=机动战士高达UC（独角兽） (2010) S01 共0集 已入库, text=评分：7.9，类型：动漫，类别：动漫，总大小：804.0B，来自：手动整理

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by shendoublexiang** [comment]
补充，实时消息推送内容为：
<img width="424" alt="image" src="https://user-images.githubusercontent.com/16017140/229711011-2388f54e-db18-480d-9af0-cd63973bec9c.png">

**Comment by jxxghp** [comment]
剧集的蓝光原盘？
不支持。
