### ISSUE TITLE
播放限速插件功能改进

### ISSUE THREAD

**Issue by CookieJaySJ** [NAStool/nas-tools#4135]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.2
>
> 环境: docker 

## 你想要新增或者改进什么功能？

> 播放器限速插件在我播放的时候能限制到设置的上传带宽，但是在我停止播放，插件恢复限速的时候，插件把我上传限速恢复成不限速了。 我希望播放器限速插件能记住我播放前的限速状态，而不是彻底不限速。
举个例子：
播放前（限速2000kb/s）
播放中（限速500kb/s）
停止播放后（无限制，NAStool没有记住播放前的速度）

**Comment by sbzhaopeng** [comment]
同样有次需求

**Comment by jxxghp** [comment]
已支持
