### ISSUE TITLE
升级最新docker版左侧功能菜单显示不完整

### ISSUE THREAD

**Issue by lucifer2099-ui** [NAStool/nas-tools#4139]
![1680659420345](https://user-images.githubusercontent.com/60416633/229960532-17a7db15-6b88-4560-81e2-f1527b57cc64.jpg)

**Comment by Summer-Tail** [comment]
看到最下面那个用户认证了嘛，认证一下就好了，你可以自己关掉这个issue了

**Comment by thsrite** [comment]
左下角是不是多了点东西？
