### ISSUE TITLE
win版浏览器仿真无法选择

### ISSUE THREAD

**Issue by zero617** [NAStool/nas-tools#4141]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.3
>
> 环境: windows
>

## 你遇到什么问题了？

> win版浏览器仿真无法选择

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 以查找

## 给出程序界面截图、后台运行日志或配置文件

> ![image](https://user-images.githubusercontent.com/67105838/229975800-4a0945af-3ab2-4482-a2e8-4456e6d70a98.png)

**Comment by log-time** [comment]
试着用chrome打开看看呢
