### ISSUE TITLE
api  /subscribe/add 接口无法正常处理包含 search_sites字段的请求

### ISSUE THREAD

**Issue by xuanqb** [NAStool/nas-tools#4145]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本:  v3.1.3 bd0cf45
>
> 环境: docker
>

## 你遇到什么问题了？

> 想使用api接口`/api/v1/subscribe/add` 添加电影订阅，填写了搜索站点字段，尝试了下 `search_sites:'月月'`和`search_sites:['月月']`都不能正常订阅，翻了下源码，parser.add_argument('search_sites', type=list, help='搜索站点', location='form')
中的type为list，flask-restx 好像并不能处理list这种类型
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 正确处理请求

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by wmbin** [comment]
@xuanqb  你好，请问获取到token，怎么带给其他接口使用呢,把token不管反正请求头还是数据里都是403错误
{"code": 403, "success": false, "message": "安全认证未通过，请检查Token"}
