### ISSUE TITLE
rclone整理报错

### ISSUE THREAD

**Issue by youyifentian** [NAStool/nas-tools#4153]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 3.1.3
>
> 环境: docker on Synology
>

**Comment by Wangsc1** [comment]
rclone配置文件映射路径调整为：/nt/.config/rclone

**Comment by youyifentian** [comment]
> rclone配置文件映射路径调整为：/nt/.config/rclone

懂了，感谢感谢
