### ISSUE TITLE
[建议] 刷流任务支持单独设置保存目录

### ISSUE THREAD

**Issue by link2fun** [NAStool/nas-tools#4159]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 最新
>
> 环境: docker

## 你想要新增或者改进什么功能？

>  刷流任务支持设置单独的保存目录，刷流的时候虽然用的是同一个下载器，但是想放在不同的目录下（多盘的情况）

## 这个功能有什么可以参考的资料吗？
https://github.com/NAStool/nas-tools/issues/3967
https://github.com/NAStool/nas-tools/pull/3989

**Comment by zraxx** [comment]
可以的，专门设置一个下载器并设置目录，再在刷流任务中选定该下载器下载。

**Comment by LONER-LAU** [comment]
3.0以前是有的，3.0以后没有了

**Comment by jxxghp** [comment]
已支持
