### ISSUE TITLE
搜索框无法输入，找不到一些设置：Jellyfin、下载器、用户权限等

### ISSUE THREAD

**Issue by latorc** [NAStool/nas-tools#4163]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.3
>
> 环境: docker
>

## 你遇到什么问题了？

> 顶部搜索框无法输入（只读），找不到如何设置Jellyfin、下载器、用户权限

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是。我不使用PT，没有用左下角的用户 认证。

## 你期望的结果

>  可以 搜索，设置Jellyfin和下载器，新建用户等。

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
![image](https://user-images.githubusercontent.com/65785354/230443520-9e1a17cf-8fe5-4826-9db7-7558ebf30785.png)

**Comment by pengjugame** [comment]
也碰到了相同的情况

**Comment by link2fun** [comment]
资源来自站点, 你不认证添加站点, 你搜索啥....

**Comment by latorc** [comment]
> 资源来自站点, 你不认证添加站点, 你搜索啥....

2.x版本的内置公共BT索引器都不能用了吗？ 我不用PT，之前只用内置索引搜索公共资源

**Comment by link2fun** [comment]
> > 资源来自站点, 你不认证添加站点, 你搜索啥....
> 
> 2.x版本的内置公共BT索引器都不能用了吗？ 我不用PT，之前只用内置索引搜索公共资源

没了, 去掉了

**Comment by latorc** [comment]
> > > 资源来自站点, 你不认证添加站点, 你搜索啥....
> > 
> > 
> > 2.x版本的内置公共BT索引器都不能用了吗？ 我不用PT，之前只用内置索引搜索公共资源
> 
> 没了, 去掉了

项目变成PT专用了吗？ 监管还是其他原因呀？
