### ISSUE TITLE
一个关于订阅功能的 自定义搜索词功能的 BUG

### ISSUE THREAD

**Issue by CangShui** [NAStool/nas-tools#4172]
> NAStool 版本: vx.x.x
> docker

## 你遇到什么问题了？

> See tittle

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> Y

> 描述以下你期望的结果

<img src="https://pic6.58cdn.com.cn/nowater/webim/big/n_v2e6d01d04482f4b2d99fd382d29938d2c.png">

**Comment by Shurelol** [comment]
更新版本
