### ISSUE TITLE
日志间歇性报错：Can't mix absolute and relative paths

### ISSUE THREAD

**Issue by zjjxwhh** [NAStool/nas-tools#4178]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.3 bd0cf45
>
> 环境: docker
>

## 你遇到什么问题了？

> 描述一下你遇到的问题

通过 portainer 查看 nas-tool 日志，发现间歇性报错：Can't mix absolute and relative paths
具体日志如下：

```
Exception: Can't mix absolute and relative paths
Callstack:
Traceback (most recent call last):
  File "/nas-tools/app/downloader/client/_base.py", line 160, in is_download_dir
    if os.path.commonpath([directory['save_path'], path]) == directory['save_path']:
  File "/usr/lib/python3.10/posixpath.py", line 527, in commonpath
    raise ValueError("Can't mix absolute and relative paths") from None
ValueError: Can't mix absolute and relative paths
```

看日志似乎是下载器设置相关的问题，但无论是刷流任务还是资源下载功能都没发现异常

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

是，未搜索到相关问题及解决方法

## 你期望的结果

> 描述以下你期望的结果

如果是程序 bug，希望修复
如果是设置问题，希望告知正确的设置方法

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

如问题描述所示，间歇性报错，每次重复上述错误日志多次

**Comment by zjjxwhh** [comment]
似乎是下载器未设置下载目录导致，希望增加相关提示

**Comment by jxxghp** [comment]
已增加判断
