### ISSUE TITLE
自动删除对于辅种的处理逻辑优化

### ISSUE THREAD

**Issue by dlovew** [NAStool/nas-tools#4179]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>
> 环境: docker or windows or synology

删除种子前检测有无同名或同大小种子，有则只删除种子保留文件

> 你想要新增或者改进什么功能？

(https://github.com/Dreamray/qB-Torrents-Auto-Delete)
> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by WannaYoung** [comment]
最好能设置辅种数量超过某个数量时不自动删种，低于这个数量删除所有站点任务

**Comment by jxxghp** [comment]
最新的下载任务删除插件已可删除转种和辅种。

**Comment by dlovew** [comment]
大佬，下载任务删除插件好像和我提的功能并不一样！希望大佬有闲的时候能看看！
