### ISSUE TITLE
下载任务清理插件有bug，删不掉同名辅种任务

### ISSUE THREAD

**Issue by CookieJaySJ** [NAStool/nas-tools#4186]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.3
>
> 环境: docker 
>

## 你遇到什么问题了？

> 下载任务清理插件在删除历史记录源文件时，如果该源文件对应好几个同名辅种任务，则该任务运行失败，种子任务不删除。以下是日志截图：

<img width="1603" alt="截屏2023-04-08 12 55 59" src="https://user-images.githubusercontent.com/10297471/230708018-ee52ca5c-3553-40ec-8efa-73c5f6ed0caf.png">

当该源文件只对应一个任务种子的时候，该插件可以正常工作：
<img width="1603" alt="截屏2023-04-08 12 56 49" src="https://user-images.githubusercontent.com/10297471/230708061-4f45dcf2-e123-422d-9dcd-7580bfcd58ad.png">

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是的

## 你期望的结果

> 描述以下你期望的结果

## 希望可以处理下该bug，使该插件能够删除所有同名的辅种任务。

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by Shurelol** [comment]
![image](https://user-images.githubusercontent.com/16237201/230718550-ba941274-6352-4b7d-8267-521d4c0e6694.png)

**Comment by CookieJaySJ** [comment]
> ![image](https://user-images.githubusercontent.com/16237201/230718550-ba941274-6352-4b7d-8267-521d4c0e6694.png)

可是其中一个种子本身就是nastool添加的  也没被删除掉😂
