### ISSUE TITLE
媒体搜索排序不按站点顺序列出

### ISSUE THREAD

**Issue by zhouyh1899** [NAStool/nas-tools#4187]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本:  v3.1.3 bd0cf45
>
> 环境: Synology 套件
>

## 你遇到什么问题了？

> 媒体资源搜索时，结果无法按照预期列出。搜索结果中一级列表和二级列表都无法按照定制的顺序列出。
> 二级：站点维护中某岛优先级列为最低，但是同样的一级搜索结果下某岛最新限免版本仍然排名最前。
> 一级：过滤规则中默认不过滤，岛按照免费的1080-720-4K过滤，但是搜索结果仍按照日常观影顺序1080-4K-720列出，看起来是有默认的排序规则无法更改。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已查看issue和tgwiki没有看到类似问题，zdm上也没有找到相关内容。

## 你期望的结果

> 1.同一视频规格下，实现优先站点优先下载。
> 2.能够自定义结果输出顺序，比如视频规格/字幕顺序，便于自动索引下载。

## 给出程序界面截图、后台运行日志或配置文件

> 基础设置：下载优先规则--站点优先。
> 站点维护：TJU优先级1，不过滤；CHD优先级3，过滤条件按免费的1080-720-4K。
> 资源搜索：结果中一级标题为1080p(webdl)-2160p(webdl)-4K(webdl)-720p(webdl)，1080p下CHD今日限免优先于TJU。

14:15:12	Meta	正在查询TMDB电影：76600 ...
14:15:12	Meta	76600 查询结果：阿凡达：水之道
14:15:12	Web	从TMDB中匹配到电影：阿凡达：水之道 (2022)
14:15:12	Web	开始检索 阿凡达：水之道 ...
14:15:12	System	处理事件：search.start - [<function Webhook.send at 0x7fa7a4405f30>]
14:15:12	Indexer	开始并行检索 Avatar: The Way of Water，线程数：4 ...
14:15:12	Indexer	开始检索Indexer：TJUPT ...
14:15:12	Indexer	开始检索Indexer：CHDbits ...
14:15:12	Spider	开始请求：（北）
14:15:12	Spider	开始请求：（岛）
14:15:14	Indexer	TJUPT 返回数据：11（然后是逐条过滤略）
14:15:14	Indexer	TJUPT 11 条数据中，过滤 0，不匹配 1，错误 0，有效 10，耗时 2 秒
14:15:17	Indexer	CHDbits 返回数据：15（然后是逐条过滤略）
14:15:17	Indexer	CHDbits 15 条数据中，过滤 12，不匹配 0，错误 0，有效 3，耗时 5 秒
14:15:18	Web	共检索到 13 个有效资源

**Comment by Shurelol** [comment]
搜索结果显示按默认过滤规则中优先级排序，同一种子排在一起
