### ISSUE TITLE
IYUU自动辅种插件里不辅种标签设置未起作用

### ISSUE THREAD

**Issue by CookieJaySJ** [NAStool/nas-tools#4196]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.4
>
> 环境: docker
>

## 你遇到什么问题了？

> 这是我的IYUU自动辅种插件设置：
![截屏2023-04-09 00 17 00](https://user-images.githubusercontent.com/10297471/230731934-7aaf7c43-d5d1-4fd9-a1c8-56dea0cec85a.png)
如图，设置了 刷流标签不启用辅种。但是下载器中的刷流标签种子还是下载辅种了，如下图：
<img width="1284" alt="image" src="https://user-images.githubusercontent.com/10297471/230732005-35a6948c-b6f2-47ab-b0be-9a0b0c797b70.png">

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 我希望IYUU自动辅种插件的标签隔离能起作用。

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by honue** [comment]
tr会出现这个bug吗

**Comment by zjuht** [comment]
问一下这个插件怎么用不了，需要额外装什么嘛
