### ISSUE TITLE
建议添加剩余容量检测,在添加下载项目前

### ISSUE THREAD

**Issue by QAQQL** [NAStool/nas-tools#4198]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.2
>
> 环境: synology

## 你想要新增或者改进什么功能？
当刷流任务大于磁盘剩余空间时不进行添加该任务,更换其他任务
![图片](https://user-images.githubusercontent.com/51136763/230736141-d0d1e23c-de13-4282-852c-01c1eb687fe4.png)
我的磁盘剩余100G,而刷流添加了上述种子,导致磁盘堆满

**Comment by aicenluo** [comment]
这个功能可以有！！我的硬盘全红了
