### ISSUE TITLE
[已解决]重启NAS后正常 最新3.1.4版本更新后进不去了

### ISSUE THREAD

**Issue by loveu5522** [NAStool/nas-tools#4202]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 3.1.4
>
> 环境: docker or windows or Synology
>Synology docker

## 你遇到什么问题了？
部署后进不去web界面
> 描述一下你遇到的问题

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是的,无法解决

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI B
![clipboard_20230409_103451](https://user-images.githubusercontent.com/44762565/230751149-0f955a0d-7e68-46d6-9d97-15ebaf9779a9.png)
UG请提供截图及配置文件截图

> 其它问题提供后台日志，如为Docker请提供docker的日志
[02-nas-tools (1).csv](https://github.com/NAStool/nas-tools/files/11184663/02-nas-tools.1.csv)

**Comment by fxqq** [comment]
哎，我是更新到最新后认证过不了，一直提示无法连接站点

**Comment by vivagonna** [comment]
+1
