### ISSUE TITLE
Transmission未活动时间删种异常

### ISSUE THREAD

**Issue by zhouyh1899** [NAStool/nas-tools#4203]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: [v3.1.4 8691362]
>
> 群晖版本:  DSM7.1.1
>
> Transmission：群晖SPK7社区套件版3.0.0（官方4.0.2也存在类似问题）
> （下载器和下载目录都安装在volume2（ssd），nastool安装在volume1）

## 你遇到什么问题了？

> transmission刷流，只要设定删除规则中包括N小时不活动，很快种子就都会被删除

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是的

## 你期望的结果

> transmission正常刷流

## 给出程序界面截图、后台运行日志或配置文件

> 不开启未活动时间，正常刷流，部分种子还在上传中。
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/113171746/230780821-fbf8494f-3672-48f7-97cd-7fee8823220c.png">
<img width="1533" alt="image" src="https://user-images.githubusercontent.com/113171746/230781193-c2eb6ed6-794f-4503-9cfd-a8925fa3d9df.png">
> 开启3小时不上传删除种子，5分钟后，全部种子都被清空。
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/113171746/230780702-f0b4b437-d4c0-4578-84cc-8c14a897a5be.png">

**Comment by zhouyh1899** [comment]
该情况大量发生，夜里重复了十来次，早上transmission因内存不足闪退。

**Comment by jxxghp** [comment]
修过了
