### ISSUE TITLE
刷流任务BUG

### ISSUE THREAD

**Issue by xiachf** [NAStool/nas-tools#4211]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.4 668654b
>
> 环境: Synology
>

## 你遇到什么问题了？

> 刷流任务的种子在qBit里手动删除后在刷流任务中不会更新，导致显示的保种体积一直是满额的，无法更新

**Comment by QAQQL** [comment]
尝试一下这个
![image](https://user-images.githubusercontent.com/51136763/230816777-adf7bf9a-c0ae-4497-9f81-3370bae7e040.png)
![image](https://user-images.githubusercontent.com/51136763/230816872-4f008550-9057-4869-b1de-3c6116b80dc1.png)

**Comment by xiachf** [comment]
感谢解答，不过测试了后任然无效！
我是刷流任务的种子，在qbit里手动把种子和源文件已经删除，但是在nastool里的刷流任务里始终存在这些种子，已经测试了下载任务清理，无效

**Comment by xiachf** [comment]
![Screenshot_2023-04-10-16-48-20-346_com microsoft emmx](https://user-images.githubusercontent.com/107197579/230867684-38714139-d2e6-4399-b418-8e940205897e.jpg)
![Screenshot_2023-04-10-16-48-36-090_com microsoft emmx](https://user-images.githubusercontent.com/107197579/230867691-c4fe533e-1e5e-4219-bbdc-c27c83e0a843.png)
![Screenshot_2023-04-10-16-50-28-147_com microsoft emmx](https://user-images.githubusercontent.com/107197579/230867997-b3213ce9-d812-43e9-af8d-81c5c75fd90f.png)

实际qbit中已无这些种子

**Comment by dengrenbocq** [comment]
我也遇到了，重启下服务就正常了

**Comment by jxxghp** [comment]
修过了
