### ISSUE TITLE
订阅添加订阅优先规则

### ISSUE THREAD

**Issue by yellowstrong** [NAStool/nas-tools#4212]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.4
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 订阅添加订阅优先规则，比如PT站点一部电影或者电视剧同时上了1080P、4k、4khdr、4k杜比视界，能够优先订阅最高视频规格的影片

**Comment by thsrite** [comment]
过滤规则不是有？
