### ISSUE TITLE
无法获取柠檬下载链接

### ISSUE THREAD

**Issue by gravitation-ch** [NAStool/nas-tools#4222]
## 你使用的 NAStool 是什么版本，什么环境？
> NAStool 版本: vx.x.x
>3.1.4
> 环境: docker or windows or Synology
>Synology
## 你遇到什么问题了？
可以正常订阅，正常搜索到资源，但是无法获取柠檬下载链接，进网站手动下载正常。网站添加正确，cookie正确，其他PT站均无问题。
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

【柠檬】Infernal Affairs 2023 S01E17-E18 2160p WEB-DL H265 DDP-LeagueWEB 添加下载失败 下载链接为空。

**Comment by gravitation-ch** [comment]
> 我的也是下载链接为空，不过我是馒头下载为空，不知道你怎么处理的 种子链接：None 错误信息：添加下载任务失败：下载链接为空
我跟你不一样，nastool本身是能获到种子链接的，因为手动点击能进去，只是触发添加下载任务的时候提示下载链接为空

**Comment by jxxghp** [comment]
换docker试试，群晖套件没办法分析。或者试试看是不是python版本的问题
