### ISSUE TITLE
微信推送通知重复问题Server酱、爱语飞飞和PushPlus

### ISSUE THREAD

**Issue by cy6669** [NAStool/nas-tools#4228]
## 你使用的 NAStool 是什么版本，什么环境？
Synology Docker
> NAStool 版本:  v3.1.4 31c206e
>
> 环境: docker or windows or Synology
>Synology

## 你遇到什么问题了？

> 描述一下你遇到的问题
使用消息通知功能，微信收到的通知都是双份，一般都是过几分钟推送一次，我测试过Server酱、爱语飞飞和PushPlus，全部是一样的问题，我点击新增编辑里面的测试按钮点击测试，点击一次测试，能收到2分测试通知，这个通知不是马上就发出2次，第二次是不定时的随机发出，有时候是几分钟，有时候是好几个小时后，发出（但是一般出现都是在几分钟后就会发出第二份一样的测试通知），我使用这么久，我发现只有签到通知不会重复推送，其余的站内消息，刷流下种，刷流删种，全部都会重复退送消息。我看过日期，确实只发送了一次通知，麻烦作者大大帮看看程序有无问题，套件版我也重新装过好多个版本，还是同样的问题。我同时胚子bark推送通知，收到的就没有重复的消息。
[jxxghp-nas-tools1.zip](https://github.com/NAStool/nas-tools/files/11188468/jxxghp-nas-tools1.zip)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是
> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
已经搜索，无此问题。

## 你期望的结果
修复bug
> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
![11](https://user-images.githubusercontent.com/121591904/230846999-00b07ed3-65d0-4662-9dd4-09ecb9078821.png)
![12](https://user-images.githubusercontent.com/121591904/230847087-1d6ec56b-9d9b-4b8b-80fd-485c2512e2b2.png)
[jxxghp-nas-tools1.zip](https://github.com/NAStool/nas-tools/files/11188477/jxxghp-nas-tools1.zip)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by c939984606** [comment]
刚测试了，正常只有一条

**Comment by cy6669** [comment]
我重装docker和套件都试过好些版本还是不行，请问大佬有好的解决方法吗，麻烦帮指点一下，非常感谢。

**Comment by c939984606** [comment]
并没有什么操作呀，就是装完了就正常呀，实在不行建议你不要用原来的配置，重新装完全新配置试试，包括数据库啥的，先找原因

**Comment by cy6669** [comment]
我从2.9左右版本就遇到了这个问题，直到现在还是没能研究出来是啥问题导致的。拜托了。非常感谢。

**Comment by cy6669** [comment]
您好，您说的全新安装配置，我都试过，全新安装docker和套件我都试过，安装完我都是全新只配置了一个通知和刷流下载，测试后通知还是双份，还要麻烦您帮找下问题看看，如果需要，我可以提供账号给您测试，我也有重启NAS等多种方法都试过了，我从2.9左右版本就遇到了这个问题，直到现在还是没能研究出来是啥问题导致的。拜托了。非常感谢。
