### ISSUE TITLE
新发现关于自定义订阅重复订阅问题

### ISSUE THREAD

**Issue by dlovew** [NAStool/nas-tools#4232]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>
> 环境: docker or windows or Synology
>

## 你遇到什么问题了？

>利用自定义订阅追观众的番剧，在完成订阅后，每一次运行自定义订阅都会重复添加已经完成的订阅，然后再删除订阅！
刚刚发现，如果是利用自定义订阅下载，处理过资源会被标记为已处理，下次再运行也不会重复下载！能否将利用自定义订阅添加过订阅的资源设为已处理呢？

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by dlovew** [comment]
抑或是能不能像处理自定义订阅-下载一样，先判断本地是否存在？
自定义订阅-订阅，先判断是否匹配，本地是否存在，如果存在则不添加订阅。

**Comment by dlovew** [comment]
上图片，自定义订阅-订阅处理过的报文并没有变为已处理
![1e8dbbc3e233bfb16448f787f6a32d4](https://user-images.githubusercontent.com/59035223/231121748-e3d0af1a-5d10-47fb-ac0f-c5e8dac1a9de.jpg)

![c1d03bb572e426bc982dfb760e9c12e](https://user-images.githubusercontent.com/59035223/231122178-4d138522-db1e-4866-a3fe-0bff2a07c717.jpg)

![b4bbee093612f79aa960bc0436fa41d](https://user-images.githubusercontent.com/59035223/231122211-10bd43a2-c3d6-48bf-a540-2424ad267bc2.jpg)

**Comment by Shurelol** [comment]
等更新
