### ISSUE TITLE
自动转移做种源下载器是qb时，转移的种子会失去tracker，导致无法做种

### ISSUE THREAD

**Issue by dwhmofly** [NAStool/nas-tools#4233]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.4 8691362
>
> 环境: docker
>

## 你遇到什么问题了？

> 自动转移做种源下载器是qb时，转移的种子会失去tracker，导致无法做种，这是好像由于新版本的qb移除了BT_backup目录下种子的tracker信息，
但qb官方好像并没有改回去的想法

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 我查找了qb官方的issue，有人提到了这个，但官方好像没有要改的想法[#18569](https://github.com/qbittorrent/qBittorrent/issues/18569) 

## 你期望的结果

> 我应该可以通过降版本解决 但我不可能一直使用旧版本的qb, [#18569](https://github.com/qbittorrent/qBittorrent/issues/18569#issuecomment-1431478060)提到了一个解决方案，通过qb的[webui](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#get-torrent-trackers)的api去抓取tracker信息然后添加到种子里，我希望自动转移做种插件能实现这个。或者可以改成从nas-tools保存的种子进行转移做种

**Comment by jxxghp** [comment]
已修复
