### ISSUE TITLE
自动删种中做种时间应该只关联已完成种子 未完成的种子还没下载完就被一起删掉了

### ISSUE THREAD

**Issue by guanyi1024** [NAStool/nas-tools#4236]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.3
>
> 环境: docker 
>

## 你遇到什么问题了？

> 自动删种中的保种时间 描述为 种子做种时间（未完成种子从添加时间开始，完成种子从完成时间开始）大于等于
设置值视为满足该条件。设置完后把还在下载的种子也一并删除了 我觉得这个做种时间 不能包含未完成的种子 
未完成的种子不应该算做种中 

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 将做种时间中 只保留已完成的种子 未完成的种子还要继续下载 有的种子下载就没有那么快 可能要下个一天两天才下载完 
这样将未完成的种子也算是做种时间不太合理 有的站点可能因为这样会吃到HR警告

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by Shurelol** [comment]
下载中的种子不上传么，删种条件里有种子状态过滤
