### ISSUE TITLE
猪猪无法获取RSS,手动浏览器打开RSS有反馈，签到也是失败

### ISSUE THREAD

**Issue by Mrxlei** [NAStool/nas-tools#4237]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.4
>
> 环境: docker 
>

## 猪猪无法获取RSS,手动浏览器打开RSS有反馈，猪猪和冬樱签到也是失败。
![00](https://user-images.githubusercontent.com/95324467/230918489-16217f81-b50f-4c8d-b57d-cbca0cc734a4.png)
![01](https://user-images.githubusercontent.com/95324467/230918496-d262b56a-07f3-4417-94ef-38fa24c5fd89.png)
![03](https://user-images.githubusercontent.com/95324467/230918497-4c92d081-7052-49ae-abbc-8eb24a73563c.png)

**Comment by jokari888** [comment]
我的猪猪怎么提示
![image](https://user-images.githubusercontent.com/123940268/231919686-0ed42239-ea48-4bf8-bac9-af2577b43b80.png)

**Comment by jxxghp** [comment]
piggo cf墙加厚了，无能为力。
