### ISSUE TITLE
目录同步必须手动

### ISSUE THREAD

**Issue by BLINGXIN** [NAStool/nas-tools#4238]
## 你使用的 NAStool 是什么版本，什么环境？
群晖
> NAStool 版本: vx.x.x
3.1.4
> 环境: docker or windows or Synology
docker

## 你遇到什么问题了？

目录同步无法自动，必须进入 服务 手动点击目录同步 才能正常同步
已经尝试可这个方法不行
 •   宿主机上（不是docker容器里），执行以下命令：
    echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
    echo fs.inotify.max_user_instances=524288 | sudo tee -a /etc/sysctl.conf
  sudo sysctl -p

![ab9cce874173fd90725da2a292608f0](https://user-images.githubusercontent.com/33460197/230920146-5e11f70b-fea5-44ba-8a45-bab3afa118bd.png)

> 其它问题提供后台日志，如为Docker请提供docker的日志

![a7604290aa349e94dac919312a17c3b](https://user-images.githubusercontent.com/33460197/230920245-20854470-2cf1-40d1-ab6a-37a0d9e601d6.png)

![53aedca9215d57b9d681068e8e3788d](https://user-images.githubusercontent.com/33460197/230920274-fee18753-4f06-4f3a-a30d-3d037178fff7.png)
请懂得大佬赐教下。

**Comment by link2fun** [comment]
监控目录和目标目录不能是包含或被包含关系

**Comment by BLINGXIN** [comment]
> 监控目录和目标目录不能是包含或被包含关系

谢谢您，您意思是下载一个文件夹，硬链接一个文件夹是吧，例如下载到DOWN文件夹，硬链接到LINK文件夹，DOWN和LINK文件夹可以包含在一个文件夹下吧，我看作者例子是可以的

**Comment by link2fun** [comment]
> > 监控目录和目标目录不能是包含或被包含关系
> 
> 谢谢您，您意思是下载一个文件夹，硬链接一个文件夹是吧，例如下载到DOWN文件夹，硬链接到LINK文件夹，DOWN和LINK文件夹可以包含在一个文件夹下吧，我看作者例子是可以的

LINK 和 DOWN 可以在同一个目录下, 但是 LINK不能包含DOWN啊
![image](https://user-images.githubusercontent.com/19241982/231316389-64531fdb-ac1f-4764-b882-c2aa38f9418e.png)

你这成啥了,  下载到 `/media/PT下载` 转移到父目录 `/media`, 这成了 LINK 包含 DOWN了
你起码是 从 `/media/PT下载` 到 `/media/整理后` 这种的
