### ISSUE TITLE
通过搜索影片编辑订阅无法更改年份

### ISSUE THREAD

**Issue by dmhmb0908** [NAStool/nas-tools#4247]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.1
>
> 环境: docker 
>

## 你遇到什么问题了？

> 描述一下你遇到的问题

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 通过搜索影片编辑订阅无法更改年份，年份为空白。可以理解通过搜索得到的的影片订阅不需要更改年份和名字，但是目前年份显示为空白且无法手动更改。

## 你期望的结果

> 修复bug

## 给出程序界面截图、后台运行日志或配置文件

>

**Comment by Shurelol** [comment]
年份不需要修改
