### ISSUE TITLE
Chat GPT 交互异常，返回用户信息错误

### ISSUE THREAD

**Issue by HankunYu** [NAStool/nas-tools#4248]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.4 67e1063
>
> 环境: docker
>

## 你遇到什么问题了？

> Chat GPT api 设置之后无法使用，返回用户信息错误。搜索下载订阅没问题，只是与Chat GPT交互有问题。api key没问题，自己用Python跑过。之前使用正常，但是免费credit过期没注意，后来续上了并更换了api key就一直返回用户信息错误。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 能正常工作

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
<img width="590" alt="image" src="https://user-images.githubusercontent.com/11606969/231136615-75c99587-9d9c-4391-bbf6-a5a7a095cd66.png">
<img width="587" alt="image" src="https://user-images.githubusercontent.com/11606969/231137386-7dddea78-4c98-4ddb-bbce-1ec4a8675bdd.png">
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/11606969/231137849-11fe01c0-88db-4a3b-b92d-09f05cd61821.png">

**Comment by HankunYu** [comment]
大致确认是bug？

如果直接与bot对话没有问题，能获取用户ID。如果是mention事件的话就不行。自己搭了个bot试了一下。。。
有可能是main.py这里问题。。。因为事件是"app_mention"? (但是不应该直接return error么。。。。。
```
    if msg_json:
        if msg_json.get("type") == "message":
            userid = msg_json.get("user")
            text = msg_json.get("text")
            username = msg_json.get("user")
        elif msg_json.get("type") == "block_actions":
            userid = msg_json.get("user", {}).get("id")
            text = msg_json.get("actions")[0].get("value")
            username = msg_json.get("user", {}).get("name")
        elif msg_json.get("type") == "event_callback":
            userid = msg_json.get("user", {}).get("id")
            text = re.sub(r"<@[0-9A-Z]+>", "", msg_json.get("event", {}).get("text"), flags=re.IGNORECASE).strip()
            username = ""
        elif msg_json.get("type") == "shortcut":
            userid = msg_json.get("user", {}).get("id")
            text = msg_json.get("callback_id")
            username = msg_json.get("user", {}).get("username")
        else:
            return "Error"
```

总之应该是个BUG，无法正常获取用户id

**Comment by jxxghp** [comment]
![image](https://user-images.githubusercontent.com/51039935/231611011-7aaf5baa-65ff-4ed5-9a93-fedd0b37453d.png)

**Comment by jxxghp** [comment]
我这里正常，偿试兼容了下，看是否能解决问题。
