### ISSUE TITLE
升级到矿神3.1.3之后，配置的二级分类文件无效

### ISSUE THREAD

**Issue by Ohh97** [NAStool/nas-tools#4256]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: V3.1.3
>
> 环境:  Synology
>

## 你遇到什么问题了？

> 我使用群晖矿神套件安装V3.1.3版本之后，并用PT站已经进行用户认证，在配置二级分类时发生问题。
我使用WINSCP下载default-category.yaml配置文件到PC，并使用Visual Studio Code打开配置文件进行自定配置，大致配置如下：
华语电影:
    # 分类依据，可以是：original_language 语种、production_countries(电影)/origin_country(电视剧) 国家或地区、genre_ids 内容类型等，只要TMDB API返回的字段中有就行
    # 配置多项条件时，需要同时满足；不需要的匹配项可以删掉或者配置为空
    # 匹配值对应用,号分隔，这里是匹配语种
    production_countries: 'CN,TW,HK'
  日本电影:
    production_countries: 'JP'
  韩国电影:
    production_countries: 'KP,KR'
  欧美电影:
    production_countries: 'US,FR,GB,DE,ES,IT,NL,PT,RU,UK,CH,CZ,DK,GR,NO,PL,SE'
  印度电影: 
    production_countries: 'TH'
  泰国电影: 
    production_countries: 'IN'
  东南亚电影: 
    production_countries: 'SG,PH,MY,MM,LA'
  动漫电影: 
    genre_ids: '16' 

通过以上配置之后，在nastool二级分类设置文件名称，保存重启之后，对文件进行识别都显示外语电影，其中包含：变形金刚、碟中谍等热门资源。
以上环境都是在关闭nastool下进行的，同时我最后命名也是和默认的命名相同‘default-category’，同样我使用新名称进行设置之后也无法解决。
在此谢谢作者

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
已经浏览过，没有发现类似问题

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 希望作者能帮忙看下是什么问题，有偿协助。

##
![%$@9S}9GVC {AJ$ DWXP(4B](https://user-images.githubusercontent.com/127936476/231203500-e52c598d-8902-47db-9057-c2d47e0f8459.png)
![image](https://user-images.githubusercontent.com/127936476/231203628-74c75374-27f4-4e60-8ac2-d2eaa34fc090.png)
![image](https://user-images.githubusercontent.com/127936476/231203763-da769cb9-9c8e-48a2-9527-8b679737f0f5.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
没有重启生效吧？

**Comment by Ohh97** [comment]
我直接删了，但是没有删配置库，我重新安装，重新配置的文件，配置完修改后进行了重启，还是没有生效；我在某吧发了这个问题，下面留言也有遇到同样的问题，但是一直没解决。这个二级分类真的觉得很好用。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月12日(星期三) 上午7:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [NAStool/nas-tools] 升级到矿神3.1.3之后，配置的二级分类文件无效 (Issue #4256)





 
没有重启生效吧？
