### ISSUE TITLE
希望刷流任务增加克隆功能

### ISSUE THREAD

**Issue by huluohu** [NAStool/nas-tools#4261]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 3.1.4
>
> 环境: docker

## 希望刷流任务增加克隆功能

> 有时候刷流的规则基本都是一样的，只是站点不同，系统能增加在已有的任务基础上快速克隆一个任务的功能

**Comment by xlongshu** [comment]
在想要克隆的规则上点编辑 然后取消再点添加就要有类似的效果了

**Comment by huluohu** [comment]
> 在想要克隆的规则上点编辑 然后取消再点添加就要有类似的效果了

可以可以，谢啦
