### ISSUE TITLE
自定义订阅，误报剧集已存在，实际不存在，导致下载不了

### ISSUE THREAD

**Issue by psychopasss** [NAStool/nas-tools#4264]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.3
>
> 环境: docker 
>

## 你遇到什么问题了？

> 描述一下你遇到的问题

找到一个bug，像动漫海贼王这种分季，但是每一季的集数是连续的，不是从1开始的，这样判断有问题。怪不得我自定义订阅海贼王一直说集数已存在。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

没有找到类似问题。

## 你期望的结果

> 描述以下你期望的结果

修复这个问题

## 给出程序界面截图、后台运行日志或配置文件

<img width="718" alt="image" src="https://user-images.githubusercontent.com/11738089/231407297-559c962a-db2f-4ac3-9af9-3f34f792f6e2.png">

<img width="900" alt="image" src="https://user-images.githubusercontent.com/11738089/231407708-e21db042-5c39-4e1f-a9b3-e630daaf3151.png">

**Comment by jxxghp** [comment]
这个问题早就知道，只是改动比较复杂，且只是很特殊的几个剧有问题，没动力改。

**Comment by psychopasss** [comment]
好吧，或者可以手动设置一下开始集数？简单解决一下？或者就是自定义订阅那边给个忽略本地已存在的选项。曲线救国一下🤔
