### ISSUE TITLE
synology-chat 消息发送失败

### ISSUE THREAD

**Issue by lolseru** [NAStool/nas-tools#4269]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.4
>
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？
在和chatgpt聊天过程中，gpt返回结果发送失败
> 描述一下你遇到的问题
在和chatgpt聊天过程中，gpt返回结果发送失败
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是
> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果
能够返回结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/115959506/231456818-9f2d52a7-aea4-4aaf-a279-bf76cad22f24.png">

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
synology chat对特殊字符特别敏感，跟chatgpt问答不要用这个。
