### ISSUE TITLE
bdmv及iso原盘统一硬链接到指定目录

### ISSUE THREAD

**Issue by tardlk** [NAStool/nas-tools#4275]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 3.1.4
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 下载的bdmv及iso原盘统一硬链接到指定目录

## 这个功能有什么可以参考的资料吗？

> 我使用的是plex链接infuse使用，plex不支持iso原盘和bdmv文件夹，infuse支持。设想是将下载来的原盘统一链接到某个文件夹，这样infuse额外扫描这个文件夹就能识别到完整的媒体库了，目前原盘和普通mkv媒体都连接到一起，infuse额外添加这个文件夹会造成媒体库重复

**Comment by link2fun** [comment]
你为啥不直接把圆盘下载到那个指定目录呢
你下载的时候混一起, 又要分开, 为什么不一开始就分开

**Comment by tardlk** [comment]
> 你为啥不直接把圆盘下载到那个指定目录呢 你下载的时候混一起, 又要分开, 为什么不一开始就分开

好多资源是nastool订阅下载来的，如果是手动下载的我都指定到那个目录。

**Comment by updatedb** [comment]
可以整合makemkv做个转换不

**Comment by DDSDerek** [comment]
> 可以整合makemkv做个转换不

如果有技术欢迎PR插件
