### ISSUE TITLE
重启后已认证失效，弹出认证框。

### ISSUE THREAD

**Issue by git-0101** [NAStool/nas-tools#4279]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.4
>
> 环境: docker
>

## 你遇到什么问题了？

> 如题。

**Comment by thsrite** [comment]
号被ban了？站点维护了？

**Comment by git-0101** [comment]
> 号被ban了？站点维护了？

鲨鱼确实打不开了。每次重启都要重新认证么

**Comment by thsrite** [comment]
> > 号被ban了？站点维护了？
> 
> 鲨鱼确实打不开了。每次重启都要重新认证么

站点没问题的话，重启会自动重新认证，认证通过不会弹出框重新认证
鲨鱼打不开了，没法去鲨鱼校验你的认证当然要弹出来重新认证啊

**Comment by git-0101** [comment]
> > > 号被ban了？站点维护了？
> > 
> > 
> > 鲨鱼确实打不开了。每次重启都要重新认证么
> 
> 站点没问题的话，重启会自动重新认证，认证通过不会弹出框重新认证 鲨鱼打不开了，没法去鲨鱼校验你的认证当然要弹出来重新认证啊

明白了，感谢大佬！
