### ISSUE TITLE
1pt 登录/测试失败

### ISSUE THREAD

**Issue by Nutiar** [NAStool/nas-tools#4281]
## 你使用的 NAStool 是什么版本，什么环境？
> NAStool 版本: 3.1.4 
>
> 环境: docker
>

## 你遇到什么问题了？
1pt 登录成功 但是再测试页面仍然显示cookie失效，站点地址填写的签到页

## 给出程序界面截图、后台运行日志或配置文件
![图片](https://user-images.githubusercontent.com/75288569/231638865-e43f1c13-e056-45ef-995f-99717ce1b4df.png)
![图片](https://user-images.githubusercontent.com/75288569/231638886-bbff7bf9-b3d4-430c-844d-74f4c593b0d6.png)

**Comment by updatedb** [comment]
好像一直有这个问题好几个月了，我目前也是这样子

**Comment by jxxghp** [comment]
没有账号，无法排查。

**Comment by AllenPu2020** [comment]
<img width="714" alt="image" src="https://user-images.githubusercontent.com/32997662/232750180-bb1d63db-640c-4b43-8e21-40c32ab36620.png">

冬樱也失败，但是资源倒是好的

<img width="1622" alt="image" src="https://user-images.githubusercontent.com/32997662/232750371-6bcac46d-f3ee-489f-b0f9-a0e4e2cf5ab8.png">

版本： v3.1.5 af06232

**Comment by AllenPu2020** [comment]
<img width="1630" alt="image" src="https://user-images.githubusercontent.com/32997662/232750694-9757272d-c635-4122-9329-dfdab4aae7cd.png">
<img width="718" alt="image" src="https://user-images.githubusercontent.com/32997662/232750916-86e2a61b-3633-4ddf-9596-d7d8b7fd9cfc.png">
朱雀也是测试失败，但是资源页面却是好的

**Comment by jxxghp** [comment]
> <img alt="image" width="1630" src="https://user-images.githubusercontent.com/32997662/232750694-9757272d-c635-4122-9329-dfdab4aae7cd.png">
> 
> <img alt="image" width="718" src="https://user-images.githubusercontent.com/32997662/232750916-86e2a61b-3633-4ddf-9596-d7d8b7fd9cfc.png">
> 
> 朱雀也是测试失败，但是资源页面却是好的

朱雀要开仿真。

**Comment by AllenPu2020** [comment]
> 
谢谢，开了仿真就通过了。




<img width="725" alt="image" src="https://user-images.githubusercontent.com/32997662/233320398-ad12f6b8-c06a-499c-8c01-8723bebe084b.png">
