### ISSUE TITLE
豆瓣榜单订阅无法获取部分RSSHub问题

### ISSUE THREAD

**Issue by caohaofei1** [NAStool/nas-tools#4288]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.5
>
> 环境: docker 
>

## 你遇到什么问题了？

> 描述一下你遇到的问题
1、插件豆瓣榜单订阅无法获取部分RSSHub问题，自定义订阅测试链接正常识别
如：https://rsshub.app/douban/movie/weekly/tv_hot
2、能否新增是否代理功能，正常自定义订阅够用了，但是没有插件评分筛选功能

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是的
> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
已经确认无类似需求

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
豆瓣榜单订阅 - 标题或链接为空：他跨越山海而来 -
18:32:39 	
豆瓣榜单订阅 - 标题或链接为空：黏人俱乐部 -
18:32:39 	
豆瓣榜单订阅 - 标题或链接为空：光·渊 -
18:32:39 	
豆瓣榜单订阅 - RSS地址：http://192.168.50.x:xxxx/douban/movie/weekly/tv_hot，未查询到数据

**Comment by caohaofei1** [comment]
![Uploading Screenshot_20230413_183307_org.mozilla.firefox.jpg…]()

**Comment by caohaofei1** [comment]
![Uploading Screenshot_20230413_121230_org.mozilla.firefox.jpg…]()

**Comment by caohaofei1** [comment]
![Screenshot_20230413_183307_org mozilla firefox](https://user-images.githubusercontent.com/104366346/231736550-db1b6509-ce73-4209-b555-8e09793aae52.jpg)

**Comment by jxxghp** [comment]
这个确实没有链接啊：
<img width="792" alt="image" src="https://user-images.githubusercontent.com/51039935/231935185-8f7e053d-305d-4f8a-8b63-db39e59dda34.png">

**Comment by caohaofei1** [comment]
是的，这个链没有链接，获取过来只有标题。但是自定义订阅可以正常识别，也就是技术上应该可以在榜单插件上面解决这个问题？![Screenshot_20230414_115612_org mozilla firefox](https://user-images.githubusercontent.com/104366346/231937802-981b2d34-5dfd-41a7-ba7e-5f951526b549.jpg)
![Screenshot_20230414_115326_org mozilla firefox](https://user-images.githubusercontent.com/104366346/231937812-f672057b-52d0-4ac7-a531-6f2d324c56aa.jpg)

**Comment by jxxghp** [comment]
那就应该用自定义订阅。
没link无法准确识别。
