### ISSUE TITLE
PT站认证时，无法连接站点

### ISSUE THREAD

**Issue by wannantian** [NAStool/nas-tools#4295]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.5
>
> 环境: docker 
>

## 你遇到什么问题了？

> PT站认证时，无法连接站点

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> ![QQ截图20230414100051](https://user-images.githubusercontent.com/126653344/231930271-2345107d-7af9-4b65-8ea4-323f085e64f1.jpg)

**Comment by jxxghp** [comment]
你也不说是哪个站点，也不说你直接打开能不能打开。。。

**Comment by wannantian** [comment]
> 你也不说是哪个站点，也不说你直接打开能不能打开。。。

抱歉没有描述清楚，目前观众 iyuu 红豆都无法连接，Windows环境下可以连接。直接打开这些网站是可以的
