### ISSUE TITLE
【刷流】【3.1.5】所有站点刷流任务可以获得RSS数据，但不会接受任何下载（无限制条件）

### ISSUE THREAD

**Issue by c939984606** [NAStool/nas-tools#4297]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>3.1.5
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

   1. 所有站点刷流任务可以获得RSS数据，但不会接收任何下载，即使条件那里不做任何限制，或者RSS全站都不会添加任何下载
   2. 重新拉3.14没有这个问题
   3. 重新拉3.15 问题依旧有，3.14升3.15问题依旧有

**Comment by c939984606** [comment]
<img width="1576" alt="image" src="https://user-images.githubusercontent.com/34211368/231963906-f1c29ee6-e031-499b-9466-e937867dd4fd.png">

**Comment by c939984606** [comment]
问题应该出在brushtask.py里 totalsize的值是空的
```
if torrent_size:
            if float(torrent_size) + int(total_size) >= (float(seed_size) + 5) * 1024 ** 3:
                log.warn("【Brush】刷流任务 %s 当前保种体积 %sGB，种子大小 %sGB，不添加刷流任务"
                         % (task_name, round(int(total_size) / (1024 ** 3), 1),
                            round(int(torrent_size) / (1024 ** 3), 1)))
                return False
```

**Comment by jxxghp** [comment]
关联pr #4259
