### ISSUE TITLE
3.1.5 刷流任务bug

### ISSUE THREAD

**Issue by Qiulock** [NAStool/nas-tools#4298]
## 你使用的 NAStool 是什么版本，什么环境？
3.1.5
Synology docker

## 你遇到什么问题了？

刷流任务bug

## 给出程序界面截图、后台运行日志或配置文件
![chrome_n7b3U1Gw9A](https://user-images.githubusercontent.com/17078949/231961987-53fcbc6c-9f55-4149-82da-c1a82284da2e.png)

**Comment by jxxghp** [comment]
#4297
