### ISSUE TITLE
RSS过期提醒一直提醒，更新RSS链接后仍然再提醒

### ISSUE THREAD

**Issue by Mrxlei** [NAStool/nas-tools#4310]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.5
>
> 环境: docker or windows or Synology
>

## 你遇到什么问题了？

> RSS过期提醒一直提醒，更新RSS链接后仍然再提醒![修改后](https://user-images.githubusercontent.com/95324467/232175094-37628845-4415-4973-9b7a-b910c731a79b.png)
![2](https://user-images.githubusercontent.com/95324467/232175090-d65ed187-8a7e-4667-8f33-10e63052d640.png)
![Uploading 修改后.png…]()

**Comment by log-time** [comment]
重启nastool试试？
