### ISSUE TITLE
增加手动删除刷流种子

### ISSUE THREAD

**Issue by zraxx** [NAStool/nas-tools#4312]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.5
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？
建议增加手动删除刷流种子![Screenshot_2023-04-15-10-46-25-914_com.android.browser.png](https://user-images.githubusercontent.com/25578054/232179501-fb60c11c-642d-4c47-af36-69eceb6aa91d.png)

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by cend1s** [comment]
这个功能好，有时候刷流种子站里面删了，这边还站着坑位也没办法手动删除。

**Comment by Shurelol** [comment]
自动删种任务，删除无效种子就行了
![image](https://user-images.githubusercontent.com/16237201/232346483-e30ffc8f-9b72-4232-b306-605ac2d7c1f8.png)

**Comment by zraxx** [comment]
停止站点刷流后，过段时间想删除正在做种种子就比较麻烦，如果有手动删除，就可随时删除。

**Comment by zraxx** [comment]
> 自动删种任务，删除无效种子就行了
> ![image](https://user-images.githubusercontent.com/16237201/232346483-e30ffc8f-9b72-4232-b306-605ac2d7c1f8.png)
> 

停止站点刷流后，过段时间想删除正在做种种子就比较麻烦，如果有手动删除，就可随时删除。

**Comment by Shurelol** [comment]
停了干嘛，不想刷了，直接保种体积改成0不就好了。删种继续
