### ISSUE TITLE
请教: 能否导出历史记录的列表, 以方便查重？

### ISSUE THREAD

**Issue by netduke999** [NAStool/nas-tools#4318]
## 你使用的 NAStool 是什么版本，什么环境？
2.9.1 docker
> NAStool 版本: vx.x.x
>
> 环境: docker or windows or synology
nas
## 你想要新增或者改进什么功能？
1. 不知道能否导出"历史记录"中的列表, 这样可以用来查重, 即一些其他操作? TXT就行, 找了半天也没办法, 只能按屏copy , 太痛苦了, 或者有其他方法, 望告知, 谢谢.

2. 可以点击文件进入目录, 这个功能强大方便, 但是目录中的文件, 实在是搞不明白, 是按照什么方式排列的, 上千文件, 很难查找。看了下大概是按照文件名称排列, 但不是拼音或字幕顺序 ,实在痛苦, 如果能点击文件进入后就可高亮并导引到此文件, 那就是太方便了！实在不行, 能让列表出的文件严格按照拼音或字母顺序排列也可，至少可手工寻找。或者在此处增加一个搜索框，可以方便定位文件，也可。也可告知文件排列的准则。目前这个功能用起来实在不方便, 文件少的时候还可以, 谢谢
> 你想要新增或者改进什么功能？

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by Shurelol** [comment]
历史记录不是可以搜索吗？

**Comment by netduke999** [comment]
> 历史记录不是可以搜索吗？

 那仅能单次，如果批量导入1000个文件，想看看其中有没有重复的，怎么办呢？

**Comment by netduke999** [comment]
> > > 历史记录不是可以搜索吗？
> > 
> > 
> > 那仅能单次，如果批量导入1000个文件，想看看其中有没有重复的，怎么办呢？
> 
> 不是有高质量文件覆盖么，质量更高的覆盖过去就是了，如果只是单纯不想覆盖那就没办法了

这样是可以,但是目录会越来越大, 如果想去除一些早期版本就没有线索了, 如果能导出记录,至少可以手工剔除. 另外有时忘了, 我发现有的电影有56个文件, 浪费很大.

**Comment by netduke999** [comment]
作者用的是sqlite数据库, 历史记录在nas-tools/config/media.db中, 网上下载一个sqlitespy.exe 然后可以自行导出记录来查重和其他操作, 记着拷贝出来,不要操作源数据库.
