### ISSUE TITLE
IYUU插件辅种失败

### ISSUE THREAD

**Issue by Sajotim** [NAStool/nas-tools#4322]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.5
>
> 环境: Windows
>

## 你遇到什么问题了？

> IYUU插件辅种一直失败，报错Url转换失败，downhash。目前使用的站点有观众，鲨鱼和杜比，使用独立IYUU容器可以正常辅种。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 能确定报错失败的问题

## 给出程序界面截图、后台运行日志或配置文件
错误如图
![image](https://user-images.githubusercontent.com/20022853/232244690-63502bc0-b65e-4102-b62b-dde4f54be61c.png)

**Comment by jxxghp** [comment]
最新的代码，不支持的都会尝试通过详情页下载种子了。
