### ISSUE TITLE
自定义订阅设定的保存路径没有被使用

### ISSUE THREAD

**Issue by XINMENG96** [NAStool/nas-tools#4323]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>3.1.5
> 环境: docker or windows or Synology
>Synology

## 你遇到什么问题了？

> 描述一下你遇到的问题
之前用的2.9.1自定义订阅设定保存路径下载，保存路径正常。最近开始玩PT后升级到3.1.5，自定义订阅设定的保存路径没有被使用，下载路径为下载器默认路径。
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是
> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果
自定义订阅设定的保存路径能正常使用
## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
下载器设置的种子自动管理模式？

**Comment by XINMENG96** [comment]
谢谢，解决了
