### ISSUE TITLE
点击 下载设置 按钮无反应

### ISSUE THREAD

**Issue by a1751504** [NAStool/nas-tools#4325]
## 你使用的 NAStool 是什么版本，什么环境？
nastool v3.1.4,  但前几个版本就有问题了 
 环境: docker

## 你遇到什么问题了？
点击下载设置就报错，点击后界面无反应
更换debian版本也出现同样的错误，在另外的机器上安装新的也没碰到这个问题
所以应该是我映射到本地的配置文件里出问题了

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是的

## 你期望的结果
请指点修改哪里可以修复这个问题

## 给出程序界面截图、后台运行日志或配置文件
日志没报错
控制台
![image](https://user-images.githubusercontent.com/31113826/232262748-c07b465a-81e8-4e58-b3b9-b015a1a04dad.png)

**Comment by jxxghp** [comment]
把下载器全部删了，重新添加一遍

**Comment by a1751504** [comment]
好的，谢谢
