### ISSUE TITLE
无法连接站点认证

### ISSUE THREAD

**Issue by git-0101** [NAStool/nas-tools#4326]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.5
>
> 环境: docker
>

## 你遇到什么问题了？

> 鲨鱼已恢复，但是还是无法认证。可能站点改动了什么东西。弹出如下图：
![Screenshot_20230416_000353](https://user-images.githubusercontent.com/115487446/232264278-8c866767-f944-4f11-85e7-e188be803ee5.jpg)

**Comment by git-0101** [comment]
作者大大能否实现，认证成功一次后，生成个key什么的，存储在配置文件。配置文件在就不需要再次认证，重启直接读取配置文件。这样不会因站点稳定波动，影响使用NAStool。

**Comment by jxxghp** [comment]
都放配置文件了，我直接改个进去不就跳过了？

**Comment by CoralTan** [comment]
我也出现了相同的问题， 连接的站点是shark

**Comment by git-0101** [comment]
> 我也出现了相同的问题， 连接的站点是shark

只能等了，站点刚恢复，可能还有些问题。
