### ISSUE TITLE
同步目录过早的自动同步可能会导致媒体库识别文件失败

### ISSUE THREAD

**Issue by soundlift** [NAStool/nas-tools#4333]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: [v3.1.5 af06232]
>
> 环境: docker

## 问题描述

我现在下载器用的qbittorrent，设置了保存未完成的torrent到“下载目录”，下载完成后会自动转移到“中转目录”；
然后nastools监控的是“中转目录”，目录同步完成后我会人为的判定媒体是否正确刮削/转移，没问题的会手动转移到”上传目录“；
媒体库是jellyfin，开启了实时监控；

现在问题出在nastools实时监控到“中转目录”中下载完成后正在转移进来的文件，自动硬链接到我的“归档目录”；
一般情况是qbit下载完成刚开始转移，我这边就能收到硬链接完成的推送；问题是这个时候硬链接的过去的并**不是一个完整的文件**；
然后到媒体库中，实时监控入库时就会无法识别媒体信息；

## 解决思路

我不知道目录同步的实时监控能不能检测到文件是否转移完成了，如果可以的话是最好了；
我现在是关闭了目录的自动同步，目录同步的实时监控好像没有独立的开关，只能在设置里面把目录同步的状态改成关闭；

## 其它

这个问题困扰了我好久，最初是在jellyfin中发现有些视频无法播放，以为是编码的问题，重新识别也不管用（后来发现jellyfin应该是按照文件的路径去存储一个媒体的信息的，只有目录或文件名变更才会重新去识别）；并且因为jellyfin实时监控的不确定性，这种问题并不是每次都会有。导致我走了很多的弯路才定位到问题；

**Comment by jxxghp** [comment]
不理解为什么搞的这么复杂。
1、可以通过下载器设置文件后缀，避免未下载完成的被转移处理。
2、如果是硬链接，提前硬链并没有什么问题，两个文件指向的是同一块数据，等那边下载完成另一边自然也是完整的。

**Comment by soundlift** [comment]
> 不理解为什么搞的这么复杂。 1、可以通过下载器设置文件后缀，避免未下载完成的被转移处理。 2、如果是硬链接，提前硬链并没有什么问题，两个文件指向的是同一块数据，等那边下载完成另一边自然也是完整的。

我的目录有3个
- 下载目录：下载盘是固态，所有下载过程都是在这个盘上进行的，下载完成会转移到“中转目录”；
- 中转目录：里面都是待刮削的文件。1是不想每次目录同步都扫几十T的文件，2是nastool文件管理里面的文件树顺序是乱的，我总是找不到文件，只能ctrl+f搜索；
- 上传目录：这里面是保种的目录；

感觉都是很必要的，并不复杂；

现在我遇到的问题应该就是提前硬链接，导致媒体库实时监控到，入库时识别不了媒体信息；
我知道硬链接的原理，jellyfin目前除了重命名找不到怎么去重新识别媒体信息的方法；
等我闲了去jellyfin问问有没有什么办法，emby也有同样的问题；

**Comment by jxxghp** [comment]
自己研究下吧，帮不上你
