### ISSUE TITLE
nastool配置好就,点击重启就无法访问了,全新安装的,不能配置,配置好设置就这样,感觉是哪个插件导致的

### ISSUE THREAD

**Issue by loveu5522** [NAStool/nas-tools#4334]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.5
>
>群辉docker

## 你遇到什么问题了？

> 插件]配置好nastool后导致打不开进不去web界面

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

是的,没能解决,重装了无数次,删除了配置,全新重装也不行,感觉是插件问题,那个插件有问题

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 
[02-nas-tools.csv](https://github.com/NAStool/nas-tools/files/11241686/02-nas-tools.csv)

![clipboard_20230416_163334](https://user-images.githubusercontent.com/44762565/232286926-7f682850-4baa-45d1-a0ad-57bf2308982a.png)

**Comment by jxxghp** [comment]
常见问题：
常见问题

•  启动inotify报错/无法自动目录同步
———————-
※  问题描述
 •   无法启动，日志报inotify instance limit reached、inotify watch limit reached等与inotify相关错误
 •   目录同步无法自动同步或只有部份目录正常，但在服务中手动启动可以正常同步

※  解决办法：
 •   宿主机上（不是docker容器里），执行以下命令：
    echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
    echo fs.inotify.max_user_instances=524288 | sudo tee -a /etc/sysctl.conf
  sudo sysctl -p

 •   插件-定时目录同步

👉 频道目录
