### ISSUE TITLE
是否有删除清晰度(抢版)很差的文件功能

### ISSUE THREAD

**Issue by DeanFaster** [NAStool/nas-tools#4336]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.8.3
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 想要增加直接从nas-tool 删除已经下载到清晰度很差的文件，在新电影出现时，经常出现下载到了抢版视频，需要查找源文件，以及硬链接删除，很麻烦。希望大佬可以增加删除现有文件的功能，直接从近期下载里面删除

**Comment by Shurelol** [comment]
更新
