### ISSUE TITLE
增添自定义订阅可以分类分组，并且自定义订阅可以设置tmdb id辅助识别的功能

### ISSUE THREAD

**Issue by XINMENG96** [NAStool/nas-tools#4344]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.5

> 环境: docker or windows or synology
Synology
## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？
自定义订阅可以分类分组，并且自定义订阅可以设置tmdb id辅助识别

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by Shurelol** [comment]
识别不了用自定义识别词
