### ISSUE TITLE
Docker 3.1.5版本启动失败，启动时资源占用变高， 容器体积疯涨，Web UI 打不开。

### ISSUE THREAD

**Issue by cheny95** [NAStool/nas-tools#4349]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.5
>
> 环境: unraid docker (jxxghp/nas-tools)
>

## 你遇到什么问题了？

>  背景：从3.1.4最后一个版本开始（github dev），使用程序内的软升级（用户菜单-升级），点击后，整个页面的 loading 遮罩，然后一直启动不起来，之前强制更新（拉取最新镜像）即可，猜测是因为 dev 更新版本快，镜像可能未同步，所以拉取的是3.1.4老版本，就 ok 了。
> 然后后来官方镜像版本升级到3.1.5之后，还是这个问题，甚至强制拉取镜像也不行，在 TG 群里问了一下，thsrite 大佬说重新安装一次，我就删除了镜像和容器，重新安装，映射之前的目录，安装成功了。
> 但是昨天unraid 每周自动检测，发现有新版本，我就点了升级，就一直启动不起来。强制更新、删除重装、安装上面说的方法重装也都是不行。而且启动时系统资源占用会突然较高，硬盘温度很高，docker.image不停增加，停止 docker 后就恢复了。

> 现象：
1. docker images不停增加占用，直到100%，我设置的 docker.image 设置的是200G，nastools容器大小镜像100多 G。 
2. docker.image 文件所在的硬盘温度上涨（平常40~42度，出问题后大约50多度）。
3. 启动十分钟左右都起不来，web 页面打不开。 
4. 日志可以看到发送了站点数据统计，企微之类的也能收到，日志到这就没了，但是依旧打不开 web 页面。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是。

## 你期望的结果

> 确定是缺陷还是我的配置问题，然后可以正常启动。

## 给出程序界面截图、后台运行日志或配置文件

> 启动时 资源占用
![WX20230417-092813@2x](https://user-images.githubusercontent.com/6293952/232359091-1f693cbb-62d3-407f-8e7c-f487b1e8bf28.png)

> docker日志（分别是昨晚和今天的）
![日志](https://user-images.githubusercontent.com/6293952/232359130-4893ac9e-d0c9-4e21-ae0c-c60ffc4122ab.png)
![IMG_8709](https://user-images.githubusercontent.com/6293952/232359224-1a4195a9-d4ee-4855-8ddb-94ae67152f82.PNG)

> 容器大小统计（分别是昨晚和今天的）
![size](https://user-images.githubusercontent.com/6293952/232359154-0cfc636c-a8fe-4741-80a1-bbd8d0142689.png)
![IMG_8711](https://user-images.githubusercontent.com/6293952/232359205-292ba035-a312-442e-873b-4169d95941ea.PNG)

**Comment by cheny95** [comment]
附上config.yaml （yaml 无法直接上传，已打包，文件内用到的 key 已脱敏）

[config.yaml.zip](https://github.com/NAStool/nas-tools/files/11245500/config.yaml.zip)

谢谢。

**Comment by jxxghp** [comment]
会不会是你的目录同步或者下载器监控的目录错了，是没有映射的目录，导致文件转型往容器内转了？

**Comment by cheny95** [comment]
我刚才重试了一下，安装3.1.3、3.1.4版本，用历史映射的目录，也一样无限重启。该历史配置目录记为 A。
然后我全新安装了3.1.5，重新指定配置目录，就可以正常启用了。该历史配置目录记为 B。
另外，我从A 里复制 config.yaml 和default-category.yaml，用重新安装的也正常启动。但是我把 A 里的 user.db、media.db、tmdb.dat一起拷贝到 B，重启docker 后，又开始发生 issues 的问题了。我觉得，是不是 user.db 中的数据库的配置有变更。

我在 tg 群里交流了一下，有2个群友也有如此经历。
一位是回滚到旧版本就好了，不知道是否具有参考价值。
<img width="559" alt="image" src="https://user-images.githubusercontent.com/6293952/232367825-aeda02ad-a098-45ea-8e72-e0d5b7f6236d.png">
<img width="558" alt="image" src="https://user-images.githubusercontent.com/6293952/232368030-e4487dcd-a3e0-4628-88e9-b21d4482b092.png">


另一位是 OP 环境安装的，物理重启了机器就好了，我也试过物理重启，也是不行。
<img width="555" alt="image" src="https://user-images.githubusercontent.com/6293952/232367946-0d861a59-91af-4254-b5ca-c355f4c21acd.png">
<img width="558" alt="image" src="https://user-images.githubusercontent.com/6293952/232368068-f8875818-6732-4498-9372-77d16a6b0f8a.png">

**Comment by cheny95** [comment]
我现在完全重新安装了，config.yaml 可以拷贝，user.db什么的貌似没法复用了，站点、推送可能需要重新配置，请问有什么方案可以恢复吗？

**Comment by cheny95** [comment]
已经确定了 user.db 的问题了，我将其他的文件拷贝过去都正常启动。唯独 user.db 拷贝无法使用。
然后我用navicat打开了旧版本备份的user.db 和 全新安装的user.db，手动从旧的里拷贝了一些站点、推送的数据，也正常启动了。数据也都还在，虽然可能有些地方不对，比如数据复制的不全，订阅列表里没有，但是 tmdb 里显示已订阅，不过慢慢用应该会好吧… 🥺

**Comment by jxxghp** [comment]
目录同步的配置就是存在user.db的啊。你上面标红的都是乱说的，字段没有自动加上，会导致启动报错，怎么可能会导致磁盘占用爆涨？

只有一种可能，就是你的目录同步配置的目的目的在docker里没有映射，导致一启动时进行大量目录同步导致docker内容量打满，无法响应。而这个目录配置就是存在数据库的，你用旧的user.db就会有这个问题。
