### ISSUE TITLE
nastool无法唤醒Chinesesubfinder

### ISSUE THREAD

**Issue by wannantian** [NAStool/nas-tools#4351]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.3
>
> 环境: 群晖套件
>

## 你遇到什么问题了？

> 3.1.3版本下载时无法通知Chinesesubfinder下载字幕，原来的2.7.1版本没有这个问题

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 看是不是bug

## 给出程序界面截图、后台运行日志或配置文件

> 
![微信图片_20230417110148](https://user-images.githubusercontent.com/126653344/232367840-a0b191af-a28c-4989-b83e-ee446a8e6cfc.png)

**Comment by yubanmeiqin9048** [comment]
https://github.com/NAStool/nas-tools/issues/3878

**Comment by jxxghp** [comment]
重新下，或者更新下代码。
