### ISSUE TITLE
反馈一个小问题, 华语电影的字幕识别有点小问题.

### ISSUE THREAD

**Issue by netduke999** [NAStool/nas-tools#4354]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>2.9.1
> 环境: docker or windows or Synology
>nas

## 你遇到什么问题了？
华语电影中,有两个字幕文件(eng和chs),则可能会识别错误, 都会识别为中文, 见下图:
> 描述一下你遇到的问题
![图片](https://user-images.githubusercontent.com/130845445/232393506-be23aef4-6830-4da3-a718-5718478ef7b4.png)
![图片](https://user-images.githubusercontent.com/130845445/232393586-3a62cb9b-378e-4219-ba41-47cd076d2f29.png)
这两个的次序好像是随机的, 外文电影可以正常识别为一个英文一个中文, 下面给出一个正常的外文电影例子:
![图片](https://user-images.githubusercontent.com/130845445/232393751-420d5705-4d60-4ef8-b4f3-bd2380606a25.png)
![图片](https://user-images.githubusercontent.com/130845445/232393845-2311618f-5e28-457d-9645-7714629482a7.png)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by Shurelol** [comment]
因为你即日启程这个电影字幕文件名里有chinese，会被认为是中文字幕

**Comment by netduke999** [comment]
> 因为你即日启程这个电影字幕文件名里有chinese，会被认为是中文字幕
想明白了, 单独识别字幕文件名时候, 到chinese就结束了, 明白了,谢谢
