### ISSUE TITLE
通过自定义订阅添加下载任务会出现莫名其妙的tag,会导致webui无法访问

### ISSUE THREAD

**Issue by ltsj** [NAStool/nas-tools#4356]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.5 af06232
>
> 环境: docker
>

## 你遇到什么问题了？

> 自定义订阅会出现莫名其妙tag,会导致Qbittorrent webui 无法访问

![image](https://user-images.githubusercontent.com/30733960/232494086-dc05a584-7434-4bfe-a011-406bcc7f7f8b.png)
![image](https://user-images.githubusercontent.com/30733960/232494175-db674122-7eaf-446f-aaaa-b23716b2dd9b.png)
![image](https://user-images.githubusercontent.com/30733960/232494263-f90c9cd1-09b6-4162-9351-df94d0b2460a.png)
![image](https://user-images.githubusercontent.com/30733960/232494309-b71a9b67-85b4-49bc-8d8e-4a9ffaeae5de.png)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
>![image](https://user-images.githubusercontent.com/30733960/232494874-861d4043-3803-4ff9-9f39-de75da24c757.png)

**Comment by ltsj** [comment]
完全重写安装NAStool 以及qb依旧可以复现,这个标签是NT开头的随机字符

**Comment by jxxghp** [comment]
升级QB版本。
