### ISSUE TITLE
自动删种相关问题

### ISSUE THREAD

**Issue by paysenyu** [NAStool/nas-tools#4360]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 3.1.5
>
> 环境: docker 
>

## 你遇到什么问题了？

自动删种把刚添加的种子给删掉了，删之前种子为活动状态

> 其它问题提供后台日志，如为Docker请提供docker的日志

![telegram-cloud-photo-size-5-6192967396722063242-y](https://user-images.githubusercontent.com/51367628/232655481-b9a0024c-3fc3-4d33-8673-a24ea9601984.jpg)

如图，我设置的删种规则有且仅有一个，那就是未活动时间超过4小时

![telegram-cloud-photo-size-5-6192967396722063241-y](https://user-images.githubusercontent.com/51367628/232655560-38e6403e-46a2-420c-804e-28ca15be0399.jpg)

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/51367628/232655942-be73ba6f-7a21-4618-a7f5-5e5fe26abdfe.png">

**Comment by paysenyu** [comment]
第二次尝试，依旧复现问题

![telegram-cloud-photo-size-5-6192967396722063260-y](https://user-images.githubusercontent.com/51367628/232662483-8b2f4f29-d949-48d4-8809-27c53a37e30c.jpg)

**Comment by youyifentian** [comment]
tr添加之后未活动时间为默认为1970年，而不是当前时间，只有添加之后立马有下载或者上传活动的，才是当前时间，如果他超过下一轮nt的检测时间仍无下载或上传，那他的时间仍为1970年，所以就会删除

**Comment by paysenyu** [comment]
> tr添加之后未活动时间为默认为1970年，而不是当前时间，只有添加之后立马有下载或者上传活动的，才是当前时间，如果他超过下一轮nt的检测时间仍无下载或上传，那他的时间仍为1970年，所以就会删除

不成立，所有刚添加的任务我都去tr里面看了，全都是有速度的正常下载

并且pt站的未完成记录里面都是有数据的，并不是缺省的1970....

**Comment by paysenyu** [comment]
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/51367628/232688665-b05b93df-2183-444e-a9fe-4e462805e1cc.png">
<img width="278" alt="image" src="https://user-images.githubusercontent.com/51367628/232688698-0cc93f74-6bba-4c2a-99cc-96e0aec10155.png">

换了个规则还是给删了。。

**Comment by paysenyu** [comment]
> 

已测试，用nt 刷流任务并设置了删种规则，等tr有了任务之后，进nt，关闭了删种规则，大概30分钟左右时间，tr没有删除该任务。

用nt 刷流任务并设置了删种规则，等tr有了任务之后，不管不顾。。  大概10分钟一个周期， 该任务被删除。
