### ISSUE TITLE
大佬，你的插件里播放上传限速的参数搞反了哈

### ISSUE THREAD

**Issue by Jushb** [NAStool/nas-tools#4365]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 最新版
>
> 环境: docker
>

## 你遇到什么问题了？
nastools-插件-播放限制速度，有三项功能：播放时限速、统一限速、按比例限速，其中第二项，全局限速的上传和下载的设置搞反了哈！！设置上传限速，到qB里是加到了下载限速里，设置下载限速，反而限制了上传，哈哈哈哈
麻烦大佬检查一下这三类功能，另外两项不好检查！！哈

**Comment by jxxghp** [comment]
这个应该改了。

**Comment by Jushb** [comment]
大佬额外请教个问题，不知道您能否收到
&nbsp;v3.2.0 3502928
我是这个版本，docker环境拉取jxxghp/nas-tools:latest
发现站点-刷流任务，这个菜单没了
我重新拉取也没有，我用vps新的机器，拉取了一个，也没有。
是取消这个功能了码？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NAStool/nas-tools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月20日(星期四) 下午4:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NAStool/nas-tools] 大佬，你的插件里播放上传限速的参数搞反了哈 (Issue #4365)





 
这个应该改了。

**Comment by Jushb** [comment]
哈哈，j大也回复了，后面的版本改正确了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月18日(星期二) 下午5:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [NAStool/nas-tools] 大佬，你的插件里播放上传限速的参数搞反了哈 (Issue #4365)





 
我测试了下  没错啊
