### ISSUE TITLE
搜索结果、高级搜索条件、新增订阅时增加音频编码和声道筛选

### ISSUE THREAD

**Issue by MyFaith** [NAStool/nas-tools#4369]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.5 af06232
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 搜索结果、高级搜索条件、新增订阅时增加音频编码和声道筛选，并且在搜索结果页面以标签形式展示出编码和声道信息

## 这个功能有什么可以参考的资料吗？

> 
![image](https://user-images.githubusercontent.com/8826441/232750571-f98e4796-d1d6-4b87-a7ae-09c08c62e416.png)
![image](https://user-images.githubusercontent.com/8826441/232750728-2a2e546b-96b4-4a56-9a02-ec65a634b185.png)
![image](https://user-images.githubusercontent.com/8826441/232750756-2e16748a-97cf-423d-a323-67302cf3b54e.png)

**Comment by Shurelol** [comment]
过滤规则自己加
