### ISSUE TITLE
Message: unknown error: cannot connect to chrome at 127.0.0.1:49586 from chrome not reachable

### ISSUE THREAD

**Issue by jiezaizone** [NAStool/nas-tools#4378]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.0
>
> 环境: docker 
>

## 你遇到什么问题了？

> 描述一下你遇到的问题
![image](https://user-images.githubusercontent.com/28976666/232798699-30ade987-f94d-4997-b033-249170f16988.png)
![image](https://user-images.githubusercontent.com/28976666/232799645-8de00b7e-ecf9-4e24-9cea-f029c43d4fe7.png)

站点开启开启浏览器仿真后，日志提示无法连接chrome，无法自动签到，拉去统计数据异常

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果
站点可以自动签到，可以正常拉取统计诗句

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by DDSDerek** [comment]
https://github.com/NAStool/nas-tools/issues/4316
