### ISSUE TITLE
自动签到未执行

### ISSUE THREAD

**Issue by kfqkfy** [NAStool/nas-tools#4384]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本:  v3.2.0 fd8b03f
>
> 环境: docker or windows or Synology
> docker
自动签到任务未执行，日志里面未显示签到服务启动状态
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/2724562/232941585-3bc70b87-2697-41ab-a2ea-96939b28931b.png">

**Comment by jxxghp** [comment]
设签到时间了吗，这么关键的信息不说

**Comment by kfqkfy** [comment]
设置了47 7 * * *，7点47分没有运行
<img width="359" alt="image" src="https://user-images.githubusercontent.com/2724562/233321037-78154e28-2012-47c5-9d40-7660910edbd4.png">
8点39手动点了签到
<img width="711" alt="image" src="https://user-images.githubusercontent.com/2724562/233320739-e035b355-1719-4dbb-82c2-c12283a44ecd.png">
刚刚没点没动突然有自己签到了
<img width="743" alt="image" src="https://user-images.githubusercontent.com/2724562/233320935-90cab359-b090-4063-926b-e5f1f46b4a5f.png">

**Comment by KKFantasy** [comment]
我也遇到了定时任务没有按设置的时间执行的问题，然后在未设置的时间又自动执行了。
