### ISSUE TITLE
刮削未处理

### ISSUE THREAD

**Issue by Nutiar** [NAStool/nas-tools#4393]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 
> v3.1.5
> 环境: 
>docker 

## 你遇到什么问题了？
手动刮削直接提示刮削完成 在实际文件夹中 并未进行刮削

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
![图片](https://user-images.githubusercontent.com/75288569/233035615-366da2b1-ff52-49e7-bc95-a93b66f8ad95.png)

![图片](https://user-images.githubusercontent.com/75288569/233035055-b4e4fd7e-cae7-4fca-bff3-86d8acd4f425.png)
![图片](https://user-images.githubusercontent.com/75288569/233035131-e2964c0c-b655-4651-a733-b9e1964d9341.png)

**Comment by Shurelol** [comment]
看看刮削设置

**Comment by jxxghp** [comment]
看下docker后台的日志有没有异常信息。点了好几个都重现不了。

**Comment by Nutiar** [comment]
我升级了版本，然后把看到缓存的地方都清空之后可以了，应该是转移缓存的锅。

**Comment by QuaanKwan** [comment]
我是清理缓存和重建容器都不行，日志情况与题主一致

**Comment by jxxghp** [comment]
> 我是清理缓存和重建容器都不行，日志情况与题主一致
> 
> 
> 
> 而后更新到v3.2.0 0775121  部分能刮削，一部分问题依旧，已在web清除转移缓存和TMDB缓存
> 
> 
> 
> >Exception: 'NoneType' object has no attribute 'get'
> 
> Callstack:
> 
> Traceback (most recent call last):
> 
>   File "/nas-tools/app/media/scraper.py", line 502, in gen_scraper_files
> 
>     doubaninfo = self.douban.get_douban_info(media)
> 
>   File "/nas-tools/app/media/douban.py", line 110, in get_douban_info
> 
>     doubanid = self.__search_douban_id(metainfo)
> 
>   File "/nas-tools/app/media/douban.py", line 92, in __search_douban_id
> 
>     search_res = self.doubanapi.tv_search(metainfo.title).get("items") or []
> 
> AttributeError: 'NoneType' object has no attribute 'get'
> 
> 正在加载配置：/config/config.yaml
> 
> 正在加载配置：/config/config.yaml
> 
> 正在加载配置：/config/config.yaml
> 
> Exception: 'NoneType' object has no attribute 'get'
> 
> Callstack:
> 
> Traceback (most recent call last):
> 
>   File "/nas-tools/app/media/scraper.py", line 448, in gen_scraper_files
> 
>     doubaninfo = self.douban.get_douban_info(media)
> 
>   File "/nas-tools/app/media/douban.py", line 110, in get_douban_info
> 
>     doubanid = self.__search_douban_id(metainfo)
> 
>   File "/nas-tools/app/media/douban.py", line 82, in __search_douban_id
> 
>     search_res = self.doubanapi.movie_search(metainfo.title).get("items") or []
> 
> AttributeError: 'NoneType' object has no attribute 'get'
> 
> Exception: 'NoneType' object has no attribute 'get'
> 
> Callstack:
> 
> Traceback (most recent call last):
> 
>   File "/nas-tools/app/media/scraper.py", line 448, in gen_scraper_files
> 
>     doubaninfo = self.douban.get_douban_info(media)
> 
>   File "/nas-tools/app/media/douban.py", line 110, in get_douban_info
> 
>     doubanid = self.__search_douban_id(metainfo)
> 
>   File "/nas-tools/app/media/douban.py", line 82, in __search_douban_id
> 
>     search_res = self.doubanapi.movie_search(metainfo.title).get("items") or []
> 
> AttributeError: 'NoneType' object has no attribute 'get'
> 
> Exception: 'NoneType' object has no attribute 'get'
> 
> Callstack:
> 
> Traceback (most recent call last):
> 
>   File "/nas-tools/app/media/scraper.py", line 448, in gen_scraper_files
> 
>     doubaninfo = self.douban.get_douban_info(media)
> 
>   File "/nas-tools/app/media/douban.py", line 110, in get_douban_info
> 
>     doubanid = self.__search_douban_id(metainfo)
> 
>   File "/nas-tools/app/media/douban.py", line 82, in __search_douban_id
> 
>     search_res = self.doubanapi.movie_search(metainfo.title).get("items") or []
> 
> AttributeError: 'NoneType' object has no attribute 'get'
> 
> Exception: 'NoneType' object has no attribute 'get'
> 
> Callstack:
> 
> Traceback (most recent call last):
> 
>   File "/nas-tools/app/media/scraper.py", line 448, in gen_scraper_files
> 
>     doubaninfo = self.douban.get_douban_info(media)
> 
>   File "/nas-tools/app/media/douban.py", line 110, in get_douban_info
> 
>     doubanid = self.__search_douban_id(metainfo)
> 
>   File "/nas-tools/app/media/douban.py", line 82, in __search_douban_id
> 
>     search_res = self.doubanapi.movie_search(metainfo.title).get("items") or []
> 
> AttributeError: 'NoneType' object has no attribute 'get'
> 
> Exception: 'NoneType' object has no attribute 'get'
> 
> Callstack:
> 
> Traceback (most recent call last):
> 
>   File "/nas-tools/app/media/scraper.py", line 448, in gen_scraper_files
> 
>     doubaninfo = self.douban.get_douban_info(media)
> 
>   File "/nas-tools/app/media/douban.py", line 110, in get_douban_info
> 
>     doubanid = self.__search_douban_id(metainfo)
> 
>   File "/nas-tools/app/media/douban.py", line 82, in __search_douban_id
> 
>     search_res = self.doubanapi.movie_search(metainfo.title).get("items") or []
> 
> AttributeError: 'NoneType' object has no attribute 'get'
> 
> ==2023-04-22 09:43:16,790	INFO: 【Scraper】开始刮削媒体库文件：/media/shapedd/华语电影/黄飞鸿之一：壮志凌云 (1991)/黄飞鸿之一：壮志凌云 (1991) - 1080p.mkv ...
> 
> 2023-04-22 09:43:17,610	INFO: 【Meta】黄飞鸿之一：壮志凌云 识别到 电影：TMDBID=10617, 名称=黄飞鸿之一：壮志凌云, 上映日期=1991-08-15
> 
> 2023-04-22 09:43:17,611	INFO: 【Meta】正在查询TMDB电影：10617 ...
> 
> 2023-04-22 09:43:18,298	INFO: 【Meta】10617 查询结果：黄飞鸿之一：壮志凌云
> 
> 2023-04-22 09:43:18,299	INFO: 【Scraper】/media/shapedd/华语电影/黄飞鸿之一：壮志凌云 (1991)/黄飞鸿之一：壮志凌云 (1991) - 1080p.mkv 刮削完成==
> 
> 
> 
> 
> 
> 
> 
> ==2023-04-22 09:43:37,008	INFO: 【Scraper】开始刮削媒体库文件：/media/shapedd/华语电影/12夜 (2000)/12夜 (2000) - 1080p.mkv ...
> 
> 2023-04-22 09:43:37,684	INFO: 【Meta】12夜 识别到 电影：TMDBID=45488, 名称=12夜, 上映日期=2000-04-20
> 
> 2023-04-22 09:43:37,684	INFO: 【Meta】正在查询TMDB电影：45488 ...
> 
> 2023-04-22 09:43:38,358	INFO: 【Meta】45488 查询结果：12夜
> 
> 2023-04-22 09:43:38,359	INFO: 【Scraper】正在生成电影NFO文件：12夜 (2000) - 1080p
> 
> 2023-04-22 09:43:44,727	INFO: 【Scraper】豆瓣该影片或剧集无演员 Sue Au 信息
> 
> 2023-04-22 09:43:45,443	INFO: 【Scraper】豆瓣该影片或剧集无演员 Siu Ye-Jim 信息
> 
> 2023-04-22 09:43:47,527	INFO: 【Scraper】正在保存NFO文件：/media/shapedd/华语电影/12夜 (2000)/12夜 (2000) - 1080p.nfo
> 
> 2023-04-22 09:43:47,529	INFO: 【Scraper】NFO文件已保存：/media/shapedd/华语电影/12夜 (2000)/12夜 (2000) - 1080p.nfo
> 
> 2023-04-22 09:43:47,529	INFO: 【Scraper】正在下载poster图片：https://image.tmdb.org/t/p/original/rltRhIXoQ8OVV9SIFqPKzuLFAB0.jpg ...
> 
> 2023-04-22 09:43:48,857	INFO: 【Scraper】poster图片已保存：/media/shapedd/华语电影/12夜 (2000)/poster.jpg
> 
> 2023-04-22 09:43:48,857	INFO: 【Scraper】正在下载fanart图片：https://image.tmdb.org/t/p/original/uJ8Gep1iH3CjnzXBcxmEwKK169y.jpg ...
> 
> 2023-04-22 09:43:49,683	INFO: 【Scraper】fanart图片已保存：/media/shapedd/华语电影/12夜 (2000)/fanart.jpg
> 
> 2023-04-22 09:43:49,683	INFO: 【Scraper】/media/shapedd/华语电影/12夜 (2000)/12夜 (2000) - 1080p.mkv 刮削完成==
> 
> 
> 
> 
> 
> 

你这个是连不上豆瓣？连不上就不要开中文演员名。

**Comment by QuaanKwan** [comment]
感谢回复，辛苦开发大大，应该是时连得上时连不上，请问是网络问题吗，那应该没法解决了。
关闭中文演员名正常了

**Comment by jxxghp** [comment]
> 感谢回复，辛苦开发大大，应该是时连得上时连不上，请问是网络问题吗，那应该没法解决了。
> 
> 关闭中文演员名正常了

豆瓣的限制，不好说，可能是访问太频繁。
