### ISSUE TITLE
无法正确限制jellyfin播放时qBit速度

### ISSUE THREAD

**Issue by tyxxytab** [NAStool/nas-tools#4402]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
> 3.2.0
> 环境: docker or windows or Synology
> docker

## 你遇到什么问题了？

> 描述一下你遇到的问题

无法正确限制jellyfin播放时qBit速度，已经配置好了jellyfin的webhook，能够正确的发送通知，但是限速插件无法正确识别
<img width="1123" alt="截屏2023-04-19 23 35 20" src="https://user-images.githubusercontent.com/46263170/233127558-c6d6d4b1-bdc8-43da-aae4-9925a759c13d.png">

**Comment by jxxghp** [comment]
猜不出来
