### ISSUE TITLE
馒头下载链接为空

### ISSUE THREAD

**Issue by liuliumuscle** [NAStool/nas-tools#4406]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 3.2.0
>
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

> 描述一下你遇到的问题

## 只有馒头的站点  下载链接为空，但是其他的站点都没有问题，然后我从后边的种子详情去看在手动下载就没问题

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果
![微信图片_20230420111900](https://user-images.githubusercontent.com/129028391/233249757-39169323-dc91-46ff-8b68-768ab6fc747a.jpg)

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图
![微信图片_20230420111900](https://user-images.githubusercontent.com/129028391/233249771-8cf9f987-a7e8-49c6-9625-273ab2c84ea9.jpg)
及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
无法重现问题，试下重新拉最新境像重新建容器。

**Comment by liuliumuscle** [comment]
重新整了也不行，而且我看提交bug，里边有其他人有类似的情况，但不一定是馒头，有些人是其他站点



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jxxghp ***@***.***&gt;
发送时间: 2023年4月20日 16:32
收件人: NAStool/nas-tools ***@***.***&gt;
抄送: liuliumuscle ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [NAStool/nas-tools] 馒头下载链接为空 (Issue #4406)





 
无法重现问题，试下重新拉最新境像重新建容器。
