### ISSUE TITLE
刚更新到最新的3.2版本，刷流任务菜单不见了什么情况？

### ISSUE THREAD

**Issue by lvxj11** [NAStool/nas-tools#4411]
NAStool 版本: v3.2.0
环境: docker（unraid）

刚更新到最新的3.2版本，刷流任务菜单不见了。刷新，重启，更换浏览器都不行。是删掉了么还是怎么了？

**Comment by 3919887** [comment]
我也没了

**Comment by jxxghp** [comment]
检查站点数据，识别到至少有一个站入站时间超过一个月才能看到菜单。
