### ISSUE TITLE
刷流删种失效

### ISSUE THREAD

**Issue by Wangsc1** [NAStool/nas-tools#4429]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.0 3502928
>
> 环境: docker
>

## 你遇到什么问题了？
刷流未自动删种，2t硬盘都爆了，日志里面也未找到删种的日志

**Comment by Wangsc1** [comment]
> 别用

？你不会以为我是在抱怨吧，我说爆盘的意思是2t盘都下满了都没删种，删种失效了
![IMG_20230421_182251.jpg](https://user-images.githubusercontent.com/26079238/233613401-97fa8a7c-bc20-4831-ad2b-8269558da661.jpg)

![IMG_20230421_182322.jpg](https://user-images.githubusercontent.com/26079238/233613400-8b445c0a-fa34-44e2-8a52-65fef2f6f5c6.jpg)

**Comment by c939984606** [comment]
部分用户，确实存在这个问题，[v3.2.0](https://github.com/NAStool/nas-tools/releases/tag/v3.2.0)目前只会增加，不会删除，目前还在debug
