### ISSUE TITLE
消息通知增加自定义http调用选项

### ISSUE THREAD

**Issue by 05u** [NAStool/nas-tools#4435]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.0 d819955
>
> 环境: docker

## 你想要新增或者改进什么功能？
消息通知增加自定义http调用,用于普适性的支持未在列表内的通知服务
例如GET请求
http://test.com/sendMsg?msg=[aaaa]&userId=bbbb
上述[aaaa]可替换为实际消息内容
建议支持GET和POST两种方式,POST改为在json中替换实际消息内容

## 这个功能有什么可以参考的资料吗？
无

**Comment by jxxghp** [comment]
插件里已经有了个Webhook插件。

**Comment by 05u** [comment]
> 插件里已经有了个Webhook插件。

这个我看到了,请问有使用说明吗,我看只能填写请求类型和地址,不知道改用什么字段来接收消息参数
感谢
