### ISSUE TITLE
存在加入时间超过一个月的站点，刷流任务仍然不显示

### ISSUE THREAD

**Issue by zjjxwhh** [NAStool/nas-tools#4439]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本:  v3.2.0 d819955
>
> 环境: docker
>

## 你遇到什么问题了？

> 描述一下你遇到的问题

存在加入时间超过一个月的站点，刷流任务仍然不显示

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

是的，最新特性，无相关 issue

## 你期望的结果

> 描述以下你期望的结果

正常判断最长入站时间，并显示刷流任务标签

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

无相关日志，站点数据如图，怀疑是 FSM 的入站时间为 `None` 导致出错

![Snipaste_2023-04-21_17-43-17](https://user-images.githubusercontent.com/14367334/233604160-10673053-9572-436f-ab55-1d4ca0dc0db0.jpg)

**Comment by zjjxwhh** [comment]
已更新到 v3.2.0 0775121，刷流任务标签仍然不显示

**Comment by zjuht** [comment]
这个怎么改，站点加入数据库时间

**Comment by zjjxwhh** [comment]
> 这个怎么改，站点加入数据库时间

看上面引用的另一个 issue，用 DB Browser for SQLite 之类的数据库工具修改，但这两个 issue 的问题之前更新已经修过了，而且这个数据是从站点读取的，每次站点统计数据刷新的时候都会重新覆写，所以讲道理意义不大
