### ISSUE TITLE
站点资源多选框问题

### ISSUE THREAD

**Issue by xushier** [NAStool/nas-tools#4449]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.0
>
> 环境: docker

## 你遇到什么问题了？

> 站点资源页面，左边的多选框选择多条项目之后，点击右上角一键下载，结果下载的是该页面所有的种子，并非是选中的多个项目。那这个多选框貌似没有什么存在的理由了？

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by Shurelol** [comment]
测试了没问题
