### ISSUE TITLE
plex媒体库显示范围

### ISSUE THREAD

**Issue by aiwu12** [NAStool/nas-tools#4457]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本:  v3.2.0 0775121
>
> 环境: docker  synology

## 你想要新增或者改进什么功能？
目前媒体库将其他（9kg）也包含在电影里面，能否像同步那样自由选择，
> 你想要新增或者改进什么功能？

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by jxxghp** [comment]
自定义css屏蔽
