### ISSUE TITLE
馒头开启两步验证后无法通过站点维护登录

### ISSUE THREAD

**Issue by HanC890** [NAStool/nas-tools#4460]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本:  v3.2.0 0775121
>
> 环境: docker
>

## 你遇到什么问题了？

馒头开启两步验证后
在Nastool中站点维护中设置站点信息后
无法通过“更新站点Cookie和User-Agent”来获取和更新Cookie
提示“登录失败”

但是同样登录开了两步验证的大青虫是正常的~

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

未在Wiki和Issues以及TG搜索到相关信息

## 给出程序界面截图、后台运行日志或配置文件

![1](https://user-images.githubusercontent.com/18377783/233762502-96bb5a3f-e763-4888-b2ce-d8282dd1d39d.png)
![2](https://user-images.githubusercontent.com/18377783/233762507-92385e8f-5c23-4baf-9180-5db1510ff9bf.png)
![3](https://user-images.githubusercontent.com/18377783/233762509-8b677b90-f870-4f2d-a0df-d45847100660.png)
![4](https://user-images.githubusercontent.com/18377783/233762510-a5fcfe2e-ae95-49df-a9cb-d56762f1b090.png)

**Comment by Shurelol** [comment]
那就不要开
