### ISSUE TITLE
无法打开管理WEB

### ISSUE THREAD

**Issue by Wenjungang** [NAStool/nas-tools#4468]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.0
>
> 环境: docker 
>

## 你遇到什么问题了？

> 更新镜像后，就无法打开网页

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> docker的日志
F2023-04-22T11:57:19.194307920Z     from .downloader import Downloader
e2023-04-22T11:57:19.194324855Z   File "/nas-tools/app/downloader/downloader.py", line 9, in <module>
C2023-04-22T11:57:19.194622952Z     from app.conf import ModuleConf
]2023-04-22T11:57:19.194712641Z   File "/nas-tools/app/conf/__init__.py", line 1, in <module>
J2023-04-22T11:57:19.194728800Z     from .systemconfig import SystemConfig
a2023-04-22T11:57:19.194738112Z   File "/nas-tools/app/conf/systemconfig.py", line 3, in <module>
E2023-04-22T11:57:19.194809669Z     from app.helper import DictHelper
_2023-04-22T11:57:19.194857760Z   File "/nas-tools/app/helper/__init__.py", line 1, in <module>
X2023-04-22T11:57:19.195068869Z     from .chrome_helper import ChromeHelper, init_chrome
e2023-04-22T11:57:19.195088849Z   File "/nas-tools/app/helper/chrome_helper.py", line 11, in <module>
S2023-04-22T11:57:19.195099755Z     from app.utils import SystemUtils, RequestUtils
^2023-04-22T11:57:19.195116360Z   File "/nas-tools/app/utils/__init__.py", line 8, in <module>
I2023-04-22T11:57:19.195130511Z     from .system_utils import SystemUtils
b2023-04-22T11:57:19.195144029Z   File "/nas-tools/app/utils/system_utils.py", line 7, in <module>
12023-04-22T11:57:19.195574958Z     import psutil
M2023-04-22T11:57:19.195616619Z ModuleNotFoundError: No module named 'psutil'
v2023-04-22T11:57:19.407789298Z 2023-04-22T19:57:19: PM2 log: App [NAStool:0] exited with code [1] via signal [SIGINT]
e2023-04-22T11:57:19.411173000Z 2023-04-22T19:57:19: PM2 log: App [NAStool:0] starting in -fork mode-
T2023-04-22T11:57:19.418562466Z 2023-04-22T19:57:19: PM2 log: App [NAStool:0] online
B2023-04-22T11:57:22.116271818Z Traceback (most recent call last):
P2023-04-22T11:57:22.116328641Z   File "/nas-tools/run.py", line 29, in <module>
D2023-04-22T11:57:22.116342962Z     from web.action import WebAction
W2023-04-22T11:57:22.116352755Z   File "/nas-tools/web/action.py", line 19, in <module>
G2023-04-22T11:57:22.116362407Z     from app.brushtask import BrushTask
Z2023-04-22T11:57:22.116371317Z   File "/nas-tools/app/brushtask.py", line 11, in <module>
I2023-04-22T11:57:22.116747619Z     from app.downloader import Downloader
c2023-04-22T11:57:22.116888773Z   File "/nas-tools/app/downloader/__init__.py", line 1, in <module>
F2023-04-22T11:57:22.117014121Z     from .downloader import Downloader
e2023-04-22T11:57:22.117123974Z   File "/nas-tools/app/downloader/downloader.py", line 9, in <module>
C2023-04-22T11:57:22.117300549Z     from app.conf import ModuleConf
]2023-04-22T11:57:22.117415907Z   File "/nas-tools/app/conf/__init__.py", line 1, in <module>
J2023-04-22T11:57:22.118413419Z     from .systemconfig import SystemConfig
a2023-04-22T11:57:22.118644055Z   File "/nas-tools/app/conf/systemconfig.py", line 3, in <module>
E2023-04-22T11:57:22.118821484Z     from app.helper import DictHelper
_2023-04-22T11:57:22.118951466Z   File "/nas-tools/app/helper/__init__.py", line 1, in <module>
X2023-04-22T11:57:22.119124372Z     from .chrome_helper import ChromeHelper, init_chrome
e2023-04-22T11:57:22.121032858Z   File "/nas-tools/app/helper/chrome_helper.py", line 11, in <module>
S2023-04-22T11:57:22.121096221Z     from app.utils import SystemUtils, RequestUtils
^2023-04-22T11:57:22.121111113Z   File "/nas-tools/app/utils/__init__.py", line 8, in <module>
I2023-04-22T11:57:22.121122280Z     from .system_utils import SystemUtils
b2023-04-22T11:57:22.121131762Z   File "/nas-tools/app/utils/system_utils.py", line 7, in <module>
12023-04-22T11:57:22.121141956Z     import psutil
M2023-04-22T11:57:22.121151543Z ModuleNotFoundError: No module named 'psutil'
v2023-04-22T11:57:22.325487604Z 2023-04-22T19:57:22: PM2 log: App [NAStool:0] exited with code [1] via signal [SIGINT]
e2023-04-22T11:57:22.327945725Z 2023-04-22T19:57:22: PM2 log: App [NAStool:0] starting in -fork mode-
T2023-04-22T11:57:22.335827544Z 2023-04-22T19:57:22: PM2 log: App [NAStool:0] online
B2023-04-22T11:57:25.101683513Z Traceback (most recent call last):
P2023-04-22T11:57:25.101740301Z   File "/nas-tools/run.py", line 29, in <module>
D2023-04-22T11:57:25.101767329Z     from web.action import WebAction
W2023-04-22T11:57:25.101779070Z   File "/nas-tools/web/action.py", line 19, in <module>
G2023-04-22T11:57:25.101797270Z     from app.brushtask import BrushTask
Z2023-04-22T11:57:25.101904573Z   File "/nas-tools/app/brushtask.py", line 11, in <module>
I2023-04-22T11:57:25.102563886Z     from app.downloader import Downloader
c2023-04-22T11:57:25.102593941Z   File "/nas-tools/app/downloader/__init__.py", line 1, in <module>
F2023-04-22T11:57:25.102605424Z     from .downloader import Downloader
e2023-04-22T11:57:25.102618702Z   File "/nas-tools/app/downloader/downloader.py", line 9, in <module>
C2023-04-22T11:57:25.102632640Z     from app.conf import ModuleConf
]2023-04-22T11:57:25.102642496Z   File "/nas-tools/app/conf/__init__.py", line 1, in <module>
J2023-04-22T11:57:25.102651821Z     from .systemconfig import SystemConfig
a2023-04-22T11:57:25.102737394Z   File "/nas-tools/app/conf/systemconfig.py", line 3, in <module>
E2023-04-22T11:57:25.102755891Z     from app.helper import DictHelper
_2023-04-22T11:57:25.102765964Z   File "/nas-tools/app/helper/__init__.py", line 1, in <module>
X2023-04-22T11:57:25.102782142Z     from .chrome_helper import ChromeHelper, init_chrome
e2023-04-22T11:57:25.102793078Z   File "/nas-tools/app/helper/chrome_helper.py", line 11, in <module>
S2023-04-22T11:57:25.102826522Z     from app.utils import SystemUtils, RequestUtils
^2023-04-22T11:57:25.102848032Z   File "/nas-tools/app/utils/__init__.py", line 8, in <module>
I2023-04-22T11:57:25.103154951Z     from .system_utils import SystemUtils
b2023-04-22T11:57:25.103640384Z   File "/nas-tools/app/utils/system_utils.py", line 7, in <module>
12023-04-22T11:57:25.103670426Z     import psutil
M2023-04-22T11:57:25.103680914Z ModuleNotFoundError: No module named 'psutil'
v2023-04-22T11:57:25.315466995Z 2023-04-22T19:57:25: PM2 log: App [NAStool:0] exited with code [1] via signal [SIGINT]
e2023-04-22T11:57:25.317717851Z 2023-04-22T19:57:25: PM2 log: App [NAStool:0] starting in -fork mode-
T2023-04-22T11:57:25.325428485Z 2023-04-22T19:57:25: PM2 log: App [NAStool:0] online
B2023-04-22T11:57:28.009886367Z Traceback (most recent call last):
P2023-04-22T11:57:28.009943960Z   File "/nas-tools/run.py", line 29, in <module>
D2023-04-22T11:57:28.009956375Z     from web.action import WebAction
W2023-04-22T11:57:28.009969961Z   File "/nas-tools/web/action.py", line 19, in <module>
G2023-04-22T11:57:28.009984404Z     from app.brushtask import BrushTask
Z2023-04-22T11:57:28.009994970Z   File "/nas-tools/app/brushtask.py", line 11, in <module>
I2023-04-22T11:57:28.010056600Z     from app.downloader import Downloader
c2023-04-22T11:57:28.010073233Z   File "/nas-tools/app/downloader/__init__.py", line 1, in <module>
F2023-04-22T11:57:28.010087675Z     from .downloader import Downloader
e2023-04-22T11:57:28.010098126Z   File "/nas-tools/app/downloader/downloader.py", line 9, in <module>
C2023-04-22T11:57:28.010129153Z     from app.conf import ModuleConf
]2023-04-22T11:57:28.010149966Z   File "/nas-tools/app/conf/__init__.py", line 1, in <module>
J2023-04-22T11:57:28.010645884Z     from .systemconfig import SystemConfig
a2023-04-22T11:57:28.010664770Z   File "/nas-tools/app/conf/systemconfig.py", line 3, in <module>
E2023-04-22T11:57:28.010676165Z     from app.helper import DictHelper
_2023-04-22T11:57:28.010697771Z   File "/nas-tools/app/helper/__init__.py", line 1, in <module>
X2023-04-22T11:57:28.010708445Z     from .chrome_helper import ChromeHelper, init_chrome
e2023-04-22T11:57:28.010718828Z   File "/nas-tools/app/helper/chrome_helper.py", line 11, in <module>
S2023-04-22T11:57:28.010743926Z     from app.utils import SystemUtils, RequestUtils
^2023-04-22T11:57:28.010759136Z   File "/nas-tools/app/utils/__init__.py", line 8, in <module>
I2023-04-22T11:57:28.011081518Z     from .system_utils import SystemUtils
b2023-04-22T11:57:28.011103894Z   File "/nas-tools/app/utils/system_utils.py", line 7, in <module>
12023-04-22T11:57:28.011123758Z     import psutil
M2023-04-22T11:57:28.011134806Z ModuleNotFoundError: No module named 'psutil'
v2023-04-22T11:57:28.218447814Z 2023-04-22T19:57:28: PM2 log: App [NAStool:0] exited with code [1] via signal [SIGINT]
e2023-04-22T11:57:28.219835047Z 2023-04-22T19:57:28: PM2 log: App [NAStool:0] starting in -fork mode-
T2023-04-22T11:57:28.226574218Z 2023-04-22T19:57:28: PM2 log: App [NAStool:0] online

**Comment by Wenjungang** [comment]
#主要问题
2023/4/22 19:57:28  ModuleNotFoundError: No module named 'psutil'
主要问题应该是缺少psutil。但是我无法修复他

#尝试修复日志如下
root@c191b5ae5e03:/nas-tools $ pip install psutil
Collecting psutil
  Using cached psutil-5.9.5.tar.gz (493 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: psutil
  Building wheel for psutil (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for psutil (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [52 lines of output]
      /tmp/tmpnwl02v5y.c:1:10: fatal error: linux/ethtool.h: No such file or directory
          1 | #include <linux/ethtool.h>
            |          ^~~~~~~~~~~~~~~~~
      compilation terminated.
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-310
      creating build/lib.linux-x86_64-cpython-310/psutil
      copying psutil/__init__.py -> build/lib.linux-x86_64-cpython-310/psutil
      copying psutil/_common.py -> build/lib.linux-x86_64-cpython-310/psutil
      copying psutil/_compat.py -> build/lib.linux-x86_64-cpython-310/psutil
      copying psutil/_psaix.py -> build/lib.linux-x86_64-cpython-310/psutil
      copying psutil/_psbsd.py -> build/lib.linux-x86_64-cpython-310/psutil
      copying psutil/_pslinux.py -> build/lib.linux-x86_64-cpython-310/psutil
      copying psutil/_psosx.py -> build/lib.linux-x86_64-cpython-310/psutil
      copying psutil/_psposix.py -> build/lib.linux-x86_64-cpython-310/psutil
      copying psutil/_pssunos.py -> build/lib.linux-x86_64-cpython-310/psutil
      copying psutil/_pswindows.py -> build/lib.linux-x86_64-cpython-310/psutil
      creating build/lib.linux-x86_64-cpython-310/psutil/tests
      copying psutil/tests/__init__.py -> build/lib.linux-x86_64-cpython-310/psutil/tests
      copying psutil/tests/__main__.py -> build/lib.linux-x86_64-cpython-310/psutil/tests
      copying psutil/tests/runner.py -> build/lib.linux-x86_64-cpython-310/psutil/tests
      copying psutil/tests/test_aix.py -> build/lib.linux-x86_64-cpython-310/psutil/tests
      copying psutil/tests/test_bsd.py -> build/lib.linux-x86_64-cpython-310/psutil/tests
      copying psutil/tests/test_connections.py -> build/lib.linux-x86_64-cpython-310/psutil/tests
      copying psutil/tests/test_contracts.py -> build/lib.linux-x86_64-cpython-310/psutil/tests
      copying psutil/tests/test_linux.py -> build/lib.linux-x86_64-cpython-310/psutil/tests
      copying psutil/tests/test_memleaks.py -> build/lib.linux-x86_64-cpython-310/psutil/tests
      copying psutil/tests/test_misc.py -> build/lib.linux-x86_64-cpython-310/psutil/tests
      copying psutil/tests/test_osx.py -> build/lib.linux-x86_64-cpython-310/psutil/tests
      copying psutil/tests/test_posix.py -> build/lib.linux-x86_64-cpython-310/psutil/tests
      copying psutil/tests/test_process.py -> build/lib.linux-x86_64-cpython-310/psutil/tests
      copying psutil/tests/test_sunos.py -> build/lib.linux-x86_64-cpython-310/psutil/tests
      copying psutil/tests/test_system.py -> build/lib.linux-x86_64-cpython-310/psutil/tests
      copying psutil/tests/test_testutils.py -> build/lib.linux-x86_64-cpython-310/psutil/tests
      copying psutil/tests/test_unicode.py -> build/lib.linux-x86_64-cpython-310/psutil/tests
      copying psutil/tests/test_windows.py -> build/lib.linux-x86_64-cpython-310/psutil/tests
      running build_ext
      building 'psutil._psutil_linux' extension
      creating build/temp.linux-x86_64-cpython-310
      creating build/temp.linux-x86_64-cpython-310/psutil
      gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Os -fomit-frame-pointer -g -O2 -Os -fomit-frame-pointer -g -O2 -Os -fomit-frame-pointer -g -O2 -DTHREAD_STACK_SIZE=0x100000 -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=595 -DPy_LIMITED_API=0x03060000 -DPSUTIL_ETHTOOL_MISSING_TYPES=1 -DPSUTIL_LINUX=1 -I/usr/include/python3.10 -c psutil/_psutil_common.c -o build/temp.linux-x86_64-cpython-310/psutil/_psutil_common.o
      gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Os -fomit-frame-pointer -g -O2 -Os -fomit-frame-pointer -g -O2 -Os -fomit-frame-pointer -g -O2 -DTHREAD_STACK_SIZE=0x100000 -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=595 -DPy_LIMITED_API=0x03060000 -DPSUTIL_ETHTOOL_MISSING_TYPES=1 -DPSUTIL_LINUX=1 -I/usr/include/python3.10 -c psutil/_psutil_linux.c -o build/temp.linux-x86_64-cpython-310/psutil/_psutil_linux.o
      psutil/_psutil_linux.c:19:10: fatal error: linux/version.h: No such file or directory
         19 | #include <linux/version.h>
            |          ^~~~~~~~~~~~~~~~~
      compilation terminated.
      psutil could not be installed from sources. Perhaps Python header files are not installed. Try running:
        sudo apk add gcc python3-dev
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for psutil
Failed to build psutil
ERROR: Could not build wheels for psutil, which is required to install pyproject.toml-based projects
root@c191b5ae5e03:/nas-tools $

**Comment by jxxghp** [comment]
有没有想过重新拉下镜像？

**Comment by Wenjungang** [comment]
我试了至少五次，都是这样子，没办法就来求助了。为啥我装不上那个东西？

**Comment by vvnocode** [comment]
我一直是用最新的docker release镜像，然后关闭自动拉代码的方式更新。
经常出现网页打不开的情况。进入容器发现3000端口挂了。
