### ISSUE TITLE
首页显示最新媒体库的时候，链接打开emby时能否使用公网地址

### ISSUE THREAD

**Issue by naoki66** [NAStool/nas-tools#4477]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
v3.2.0 2ff3210

> 环境: docker or windows or synology
 docker

## 你想要新增或者改进什么功能？
首页链接可以自定义emby域名地址，比如我的群晖docker下配置两个docker互相访问只能是 docker的内网地址172.17.0.1+对应端口，
但是这个地址在外网使用域名时访问nastool时候无法打开。

> 你想要新增或者改进什么功能？
配置界面能否新增应该外网地址，在首页点击媒体库的时候，可以自定义emby等域名地址，点击时候自动调用公网地址进行访问。

## 这个功能有什么可以参考的资料吗？
暂时没有
> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

![image](https://user-images.githubusercontent.com/22931306/233813950-454873fb-21a7-429a-b3d6-1edcb3fa02fe.png)

**Comment by thsrite** [comment]
设置--媒体服务器--媒体播放地址

**Comment by naoki66** [comment]
> 设置--媒体服务器--媒体播放地址

非常感谢！
