### ISSUE TITLE
显示无法匹配站点

### ISSUE THREAD

**Issue by NorthCityChen** [NAStool/nas-tools#4485]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.0
>
> 环境: docker 
>

## 你遇到什么问题了？

> 在下载管理页面新增BT磁链无法正常下载，显示无法匹配站点，但是添加 PT 的磁链就是正常的

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已浏览过

## 你期望的结果

> 既然 NasTools 本身已经添加了 PT 站点认证了，就没必要再在站点内部对BT的资源做限制吧

## 给出程序界面截图、后台运行日志或配置文件

> ![image](https://user-images.githubusercontent.com/53619621/233822259-08f16820-2d92-4c2c-9bb1-09598cdcb32f.png)
> ![image](https://user-images.githubusercontent.com/53619621/233822275-5ae9a25b-d7a1-49c7-9cd6-9cc1985420e5.png)

**Comment by jxxghp** [comment]
不支持添加磁力链
