### ISSUE TITLE
媒体服务器选择plex，我的媒体库一直加载不出来。

### ISSUE THREAD

**Issue by mnwuchao** [NAStool/nas-tools#4488]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 3.2.0  fd57a40
>
> 环境: docker
>

## 你遇到什么问题了？

> 媒体服务器选择plex，我的媒体库一直加载不出来。媒体服务器换emby正常。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 
## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 
![SharedScreenshot](https://user-images.githubusercontent.com/62805118/233826534-892a2bd8-2dab-430d-be89-d00687946dcb.jpg)
![屏幕截图 2023-04-23 153712](https://user-images.githubusercontent.com/62805118/233826537-46d0d992-aa61-48b2-b837-45248e0ceed7.jpg)

>

**Comment by dihao1127** [comment]
两三天了吧 刚重装nastool也不行  朋友的升级后也是一直加载中 头大

**Comment by jxxghp** [comment]
plex使用token试试，不要用帐号密码，后者要连plex.tv官网且有限流。

**Comment by dihao1127** [comment]
是用的token

**Comment by dihao1127** [comment]
![909FD714-B5BF-4A7D-86B9-10C2DBA54AF7](https://user-images.githubusercontent.com/60700173/233831505-5322957b-84da-45e8-9733-0bb2581f9ae3.png)
测试是通过的 但是 我的媒体库一直加载中

**Comment by jxxghp** [comment]
提供一下日志

**Comment by mnwuchao** [comment]
<html>
<body>


2023/04/23 21:49:40 | stdout | 2023-04-23 21:49:40,607 INFO: 【Message】发送消息 Telegram：title=站点数据统计, text=【今日汇总】
-- | -- | --
2023/04/23 21:49:35 | stdout | 2023-04-23 21:49:35,461 ERROR: 【Sites】Piggo 无法打开网站
2023/04/23 21:49:35 | stdout |  
2023/04/23 21:49:35 | stdout | (Session info: chrome=112.0.5615.165)
2023/04/23 21:49:35 | stdout | Message: timeout: Timed out receiving message from renderer: 29.372
2023/04/23 21:48:37 | stdout | TypeError: quote_from_bytes() expected bytes
2023/04/23 21:48:37 | stdout | raise TypeError("quote_from_bytes() expected bytes")
2023/04/23 21:48:37 | stdout | File "/usr/lib/python3.10/urllib/parse.py", line 894, in quote_from_bytes
2023/04/23 21:48:37 | stdout | return quote_from_bytes(string, safe)
2023/04/23 21:48:37 | stdout | File "/usr/lib/python3.10/urllib/parse.py", line 869, in quote
2023/04/23 21:48:37 | stdout | "image": f"img?url={quote(item.artUrl)}",
2023/04/23 21:48:37 | stdout | File "/nas-tools/app/mediaserver/client/plex.py", line 511, in get_resume
2023/04/23 21:48:37 | stdout | return self.server.get_resume(num=num)
2023/04/23 21:48:37 | stdout | File "/nas-tools/app/mediaserver/media_server.py", line 387, in get_resume
2023/04/23 21:48:37 | stdout | Resumes = MediaServer().get_resume()
2023/04/23 21:48:37 | stdout | File "/nas-tools/web/main.py", line 252, in index
2023/04/23 21:48:37 | stdout | return current_app.ensure_sync(func)(*args, **kwargs)
2023/04/23 21:48:37 | stdout | File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
2023/04/23 21:48:37 | stdout | return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023/04/23 21:48:37 | stdout | File "/usr/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
2023/04/23 21:48:37 | stdout | rv = self.dispatch_request()
2023/04/23 21:48:37 | stdout | File "/usr/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
2023/04/23 21:48:37 | stdout | return original_handler(e)
2023/04/23 21:48:37 | stdout | File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 674, in error_router
2023/04/23 21:48:37 | stdout | rv = self.handle_user_exception(e)
2023/04/23 21:48:37 | stdout | File "/usr/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
2023/04/23 21:48:37 | stdout | response = self.full_dispatch_request()
2023/04/23 21:48:37 | stdout | File "/usr/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
2023/04/23 21:48:37 | stdout | return original_handler(e)
2023/04/23 21:48:37 | stdout | File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 674, in error_router
2023/04/23 21:48:37 | stdout | response = self.handle_exception(e)
2023/04/23 21:48:37 | stdout | File "/usr/lib/python3.10/site-packages/flask/app.py", line 2531, in wsgi_app
2023/04/23 21:48:37 | stdout | return self.app(environ, start_response)
2023/04/23 21:48:37 | stdout | File "/usr/lib/python3.10/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
2023/04/23 21:48:37 | stdout | return self.wsgi_app(environ, start_response)
2023/04/23 21:48:37 | stdout | File "/usr/lib/python3.10/site-packages/flask/app.py", line 2551, in __call__
2023/04/23 21:48:37 | stdout | Traceback (most recent call last):
2023/04/23 21:47:58 | stdout | * Debug mode: on
2023/04/23 21:47:58 | stdout | * Serving Flask app 'web.main'
2023/04/23 21:47:56 | stdout | 2023-04-23 21:47:56,052 INFO: 加载插件：<class 'app.plugins.modules.autobackup.AutoBackup'>
2023/04/23 21:47:56 | stdout | Wrong number of fields; got 6, expected 5
2023/04/23 21:47:56 | stdout | 2023-04-23 21:47:56,051 INFO: 【Plugin】自动备份 - 定时备份服务启动，周期：0 0 5 * * ?
2023/04/23 21:47:56 | stdout | 2023-04-23 21:47:56,051 INFO: 加载插件：<class 'app.plugins.modules.cookiecloud.CookieCloud'>
2023/04/23 21:47:56 | stdout | 2023-04-23 21:47:56,051 INFO: 加载插件：<class 'app.plugins.modules.torrenttransfer.TorrentTransfer'>
2023/04/23 21:47:56 | stdout | 2023-04-23 21:47:56,050 INFO: 加载插件：<class 'app.plugins.modules.doubansync.DoubanSync'>
2023/04/23 21:47:56 | stdout | 2023-04-23 21:47:56,044 INFO: 加载插件：<class 'app.plugins.modules.torrentremover.TorrentRemover'>
2023/04/23 21:47:56 | stdout | 2023-04-23 21:47:56,043 INFO: 加载插件：<class 'app.plugins.modules.libraryrefresh.LibraryRefresh'>
2023/04/23 21:47:56 | stdout | 2023-04-23 21:47:56,043 INFO: 【Plugin】刷新媒体库 - 媒体库实时刷新服务启动
2023/04/23 21:47:56 | stdout | 2023-04-23 21:47:56,043 INFO: 加载插件：<class 'app.plugins.modules.synctimer.SyncTimer'>
2023/04/23 21:47:56 | stdout | 2023-04-23 21:47:56,042 INFO: 加载插件：<class 'app.plugins.modules.opensubtitles.OpenSubtitles'>
2023/04/23 21:47:56 | stdout | 2023-04-23 21:47:56,041 INFO: 加载插件：<class 'app.plugins.modules.speedlimiter.SpeedLimiter'>
2023/04/23 21:47:54 | stdout | 2023-04-23 21:47:54,938 INFO: 5 个刷流服务正常启动
2023/04/23 21:47:54 | stdout | BrushTask.remove_tasks_torrents (trigger: interval[0:05:00], pending)
2023/04/23 21:47:54 | stdout | BrushTask.check_task_rss (trigger: interval[0:10:00], pending)
2023/04/23 21:47:54 | stdout | BrushTask.check_task_rss (trigger: interval[0:10:00], pending)
2023/04/23 21:47:54 | stdout | BrushTask.check_task_rss (trigger: interval[0:10:00], pending)
2023/04/23 21:47:54 | stdout | BrushTask.check_task_rss (trigger: interval[0:10:00], pending)
2023/04/23 21:47:54 | stdout | BrushTask.check_task_rss (trigger: interval[0:10:00], pending)
2023/04/23 21:47:54 | stdout | Pending jobs:
2023/04/23 21:47:52 | stdout | get_login_wallpaper (trigger: interval[1:00:00], next run at: 2023-04-23 21:47:52 CST)
2023/04/23 21:47:52 | stdout | MetaHelper.delete_unknown_meta (trigger: interval[12:00:00], pending)
2023/04/23 21:47:52 | stdout | Subscribe.refresh_rss_metainfo (trigger: interval[6:00:00], pending)
2023/04/23 21:47:52 | stdout | Subscribe.subscribe_search (trigger: interval[0:05:00], pending)
2023/04/23 21:47:52 | stdout | Sync.transfer_mon_files (trigger: interval[0:01:00], pending)
2023/04/23 21:47:52 | stdout | MetaHelper.save_meta_data (trigger: interval[0:10:00], pending)
2023/04/23 21:47:52 | stdout | MediaServer.sync_mediaserver (trigger: interval[12:00:00], pending)
2023/04/23 21:47:52 | stdout | Subscribe.subscribe_search_all (trigger: interval[6:00:00], pending)
2023/04/23 21:47:52 | stdout | Rss.rssdownload (trigger: interval[0:30:00], pending)
2023/04/23 21:47:52 | stdout | SiteUserInfo.refresh_site_data_now (trigger: interval[6:00:00], next run at: 2023-04-23 21:48:40 CST)
2023/04/23 21:47:52 | stdout | SiteSignin.signin (trigger: cron[hour='8', minute='1'], pending)
2023/04/23 21:47:52 | stdout | Pending jobs:
2023/04/23 21:47:52 | stdout | 2023-04-23 21:47:52,401 INFO: /影视/电视剧 的监控服务启动
2023/04/23 21:47:48 | stdout | 2023-04-23 21:47:48,577 INFO: /影视/电影 的监控服务启动
2023/04/23 21:47:47 | stdout | 2023-04-23 21:47:47,952 INFO: /影视/动漫剧集 的监控服务启动
2023/04/23 21:47:47 | stdout | 2023-04-23 21:47:47,749 INFO: /影视/动漫 的监控服务启动
2023/04/23 21:47:47 | stdout | 2023-04-23 21:47:47,508 INFO: 【Sync】读取到监控目录：/影视/电视剧，目的目录：/影视/links/电视剧，转移方式：硬链接，启用识别和重命名
2023/04/23 21:47:47 | stdout | 2023-04-23 21:47:47,508 INFO: 【Sync】读取到监控目录：/影视/电影，目的目录：/影视/links/电影，转移方式：硬链接，启用识别和重命名
2023/04/23 21:47:47 | stdout | 2023-04-23 21:47:47,507 INFO: 【Sync】读取到监控目录：/影视/动漫剧集，目的目录：/影视/links/动漫剧集，转移方式：硬链接，启用识别和重命名
2023/04/23 21:47:47 | stdout | 2023-04-23 21:47:47,393 INFO: 【Sync】读取到监控目录：/影视/动漫，目的目录：/影视/links/动漫，转移方式：硬链接，启用识别和重命名
2023/04/23 21:47:47 | stdout | 2023-04-23 21:47:47,219 INFO: 媒体库同步服务启动
2023/04/23 21:47:47 | stdout | 2023-04-23 21:47:47,218 INFO: 订阅定时搜索服务启动
2023/04/23 21:47:47 | stdout | 2023-04-23 21:47:47,210 INFO: RSS订阅服务启动
2023/04/23 21:47:41 | stdout | 2023-04-23 21:47:41,000 INFO: 数据统计服务启动
2023/04/23 21:47:40 | stdout | 2023-04-23 21:47:40,884 INFO: 站点自动签到服务启动
2023/04/23 21:47:34 | stdout | 2023-04-23 21:47:34,511 INFO: Telegram消息接收服务启动
2023/04/23 21:47:24 | stdout | 开始启动服务...
2023/04/23 21:47:24 | stdout | 2023-04-23 21:47:24,256 INFO: 未启用https，请使用 http://IP:3000 访问管理页面
2023/04/23 21:47:24 | stdout | 2023-04-23 21:47:24,256 INFO: WEB管理页面用户：mnwuchao
2023/04/23 21:47:24 | stdout | 2023-04-23 21:47:24,256 INFO: 日志输出类型为：console
2023/04/23 21:47:24 | stdout | 数据初始化完成
2023/04/23 21:47:24 | stdout | 开始初始化数据...
2023/04/23 21:47:24 | stdout | 数据库更新完成
2023/04/23 21:47:15 | stdout | 开始更新数据库...
2023/04/23 21:47:15 | stdout | 数据库初始化完成
2023/04/23 21:47:13 | stdout | 开始初始化数据库...
2023/04/23 21:47:13 | stdout | NAStool 当前版本号：v3.2.0
2023/04/23 21:47:04 | stdout | 正在加载配置：/config/config.yaml
2023/04/23 21:46:47 | stdout | s6-rc: info: service legacy-services successfully started
2023/04/23 21:46:47 | stdout | services-up: info: copying legacy longrun redis (no readiness notification)
2023/04/23 21:46:47 | stdout | services-up: info: copying legacy longrun NAStool (no readiness notification)
2023/04/23 21:46:47 | stdout | s6-rc: info: service legacy-services: starting
2023/04/23 21:46:47 | stdout | s6-rc: info: service legacy-cont-init successfully started
2023/04/23 21:46:47 | stdout | cont-init: info: /etc/cont-init.d/020-fixuser exited 0
2023/04/23 21:46:47 | stdout | cont-init: info: /etc/cont-init.d/020-fixuser: usermod: no changes
2023/04/23 21:46:39 | stdout | cont-init: info: /etc/cont-init.d/020-fixuser: 以PUID=1026，PGID=101的身份启动程序...
2023/04/23 21:46:39 | stdout | cont-init: info: running /etc/cont-init.d/020-fixuser
2023/04/23 21:46:39 | stdout | cont-init: info: /etc/cont-init.d/010-update exited 0
2023/04/23 21:46:39 | stdout | cont-init: info: /etc/cont-init.d/010-update: 主程序更新成功
2023/04/23 21:46:38 | stdout | cont-init: info: /etc/cont-init.d/010-update: HEAD is now at fd57a40 Merge pull request #4481 from NAStool/dev
2023/04/23 21:46:38 | stdout | cont-init: info: /etc/cont-init.d/010-update: fatal: unable to access 'https://github.com/NAStool/nas-tools.git/': HTTP/2 stream 1 was not closed cleanly before end of the underlying connection
2023/04/23 21:46:37 | stdout | cont-init: info: /etc/cont-init.d/010-update: Removing web/backend/__pycache__/
2023/04/23 21:44:36 | stdout | cont-init: info: /etc/cont-init.d/010-update: Removing web/__pycache__/
2023/04/23 21:44:36 | stdout | cont-init: info: /etc/cont-init.d/010-update: Removing scripts/versions/__pycache__/
2023/04/23 21:44:36 | stdout | cont-init: info: /etc/cont-init.d/010-update: Removing scripts/__pycache__/
2023/04/23 21:44:36 | stdout | cont-init: info: /etc/cont-init.d/010-update: Removing app/utils/__pycache__/
2023/04/23 21:44:36 | stdout | cont-init: info: /etc/cont-init.d/010-update: Removing app/sites/siteuserinfo/__pycache__/
2023/04/23 21:44:36 | stdout | cont-init: info: /etc/cont-init.d/010-update: Removing app/sites/sitesignin/__pycache__/
2023/04/23 21:44:36 | stdout | cont-init: info: /etc/cont-init.d/010-update: Removing app/sites/__pycache__/
2023/04/23 21:44:36 | stdout | cont-init: info: /etc/cont-init.d/010-update: Removing app/plugins/modules/__pycache__/
2023/04/23 21:44:36 | stdout | cont-init: info: /etc/cont-init.d/010-update: Removing app/plugins/__pycache__/
2023/04/23 21:44:36 | stdout | cont-init: info: /etc/cont-init.d/010-update: Removing app/message/client/__pycache__/
2023/04/23 21:44:36 | stdout | cont-init: info: /etc/cont-init.d/010-update: Removing app/message/__pycache__/
2023/04/23 21:44:36 | stdout | cont-init: info: /etc/cont-init.d/010-update: Removing app/mediaserver/client/__pycache__/
2023/04/23 21:44:36 | stdout | cont-init: info: /etc/cont-init.d/010-update: Removing app/mediaserver/__pycache__/
2023/04/23 21:44:36 | stdout | cont-init: info: /etc/cont-init.d/010-update: Removing app/media/tmdbv3api/objs/__pycache__/
2023/04/23 21:44:36 | stdout | cont-init: info: /etc/cont-init.d/010-update: Removing app/media/tmdbv3api/__pycache__/
2023/04/23 21:44:36 | stdout | cont-init: info: /etc/cont-init.d/010-update: Removing app/media/meta/__pycache__/
2023/04/23 21:44:36 | stdout | cont-init: info: /etc/cont-init.d/010-update: Removing app/media/doubanapi/__pycache__/
2023/04/23 21:44:36 | stdout | cont-init: info: /etc/cont-init.d/010-update: Removing app/media/__pycache__/
2023/04/23 21:44:36 | stdout | cont-init: info: /etc/cont-init.d/010-update: Removing app/indexer/client/__pycache__/
2023/04/23 21:44:36 | stdout | cont-init: info: /etc/cont-init.d/010-update: Removing app/indexer/__pycache__/
2023/04/23 21:44:36 | stdout | cont-init: info: /etc/cont-init.d/010-update: Removing app/helper/__pycache__/
2023/04/23 21:44:36 | stdout | cont-init: info: /etc/cont-init.d/010-update: Removing app/downloader/client/__pycache__/
2023/04/23 21:44:36 | stdout | cont-init: info: /etc/cont-init.d/010-update: Removing app/downloader/__pycache__/
2023/04/23 21:44:36 | stdout | cont-init: info: /etc/cont-init.d/010-update: Removing app/db/__pycache__/
2023/04/23 21:44:36 | stdout | cont-init: info: /etc/cont-init.d/010-update: Removing app/conf/__pycache__/
2023/04/23 21:44:36 | stdout | cont-init: info: /etc/cont-init.d/010-update: Removing app/__pycache__/
2023/04/23 21:44:36 | stdout | cont-init: info: /etc/cont-init.d/010-update: Removing __pycache__/
2023/04/23 21:44:35 | stdout | cont-init: info: /etc/cont-init.d/010-update: 更新主程序...
2023/04/23 21:44:35 | stdout | cont-init: info: running /etc/cont-init.d/010-update


</body>
</html>

**Comment by dihao1127** [comment]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.10/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2531, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 674, in error_router
    return original_handler(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 674, in error_router
    return original_handler(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/nas-tools/web/main.py", line 255, in index
    Latests = MediaServer().get_latest()
  File "/nas-tools/app/mediaserver/media_server.py", line 395, in get_latest
    return self.server.get_latest(num=num)
  File "/nas-tools/app/mediaserver/client/plex.py", line 533, in get_latest
    "image": f"img?url={quote(item.posterUrl)}",
  File "/usr/lib/python3.10/urllib/parse.py", line 869, in quote
    return quote_from_bytes(string, safe)
  File "/usr/lib/python3.10/urllib/parse.py", line 894, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes

**Comment by dihao1127** [comment]
上面代码的截图

![ADC82066-7AC8-4B9E-9618-45FD9485CBF2](https://user-images.githubusercontent.com/60700173/233843852-26d8f37f-24ed-47e4-909c-28d87959eb86.png)
![3A19400A-16D6-421B-9AAB-AD3F083353F9](https://user-images.githubusercontent.com/60700173/233843855-3227ee86-66e9-422d-801a-9aa1555b153e.png)

**Comment by mnwuchao** [comment]
<html>
<body>


023/04/23 21:58:01 | stdout | 2023-04-23 21:58:01,707 INFO: 【Brush】任务 织梦 本次添加了 0 个下载
-- | -- | --
2023/04/23 21:58:01 | stdout | 2023-04-23 21:58:01,479 INFO: 【Brush】织梦 RSS获取数据：200
2023/04/23 21:57:59 | stdout | 2023-04-23 21:57:59,077 INFO: 【Brush】憨憨 RSS获取数据：100
2023/04/23 21:57:58 | stdout | 2023-04-23 21:57:58,087 INFO: 【Brush】HDdolby RSS获取数据：50
2023/04/23 21:57:57 | stdout | 2023-04-23 21:57:57,428 INFO: 【Brush】馒头 RSS获取数据：50
2023/04/23 21:57:56 | stdout | RuntimeError: dictionary changed size during iteration
2023/04/23 21:57:56 | stdout | for taskid, taskinfo in self._brush_tasks.items():
2023/04/23 21:57:56 | stdout | File "/nas-tools/app/brushtask.py", line 298, in remove_tasks_torrents
2023/04/23 21:57:56 | stdout | retval = job.func(*job.args, **job.kwargs)
2023/04/23 21:57:56 | stdout | File "/usr/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
2023/04/23 21:57:56 | stdout | Traceback (most recent call last):
2023/04/23 21:57:56 | stdout | Job "BrushTask.remove_tasks_torrents (trigger: interval[0:05:00], next run at: 2023-04-23 22:02:54 CST)" raised an exception
2023/04/23 21:57:55 | stdout | 2023-04-23 21:57:55,094 WARNING: 【Brush】刷流任务 鲨鱼 当前保种体积 103.4GB，不再新增下载
2023/04/23 21:57:55 | stdout | 2023-04-23 21:57:55,079 INFO: 【Brush】开始站点 鲨鱼 的刷流任务：鲨鱼...
2023/04/23 21:57:55 | stdout | 2023-04-23 21:57:55,060 INFO: 【Brush】开始站点 馒头 的刷流任务：馒头...
2023/04/23 21:57:55 | stdout | 2023-04-23 21:57:55,050 INFO: 【Brush】开始站点 HDdolby 的刷流任务：HDdolby...
2023/04/23 21:57:55 | stdout | 2023-04-23 21:57:55,036 INFO: 【Brush】开始站点 憨憨 的刷流任务：憨憨...
2023/04/23 21:57:54 | stdout | 2023-04-23 21:57:54,976 INFO: 【Brush】开始站点 织梦 的刷流任务：织梦...
2023/04/23 21:55:36 | stdout | TypeError: quote_from_bytes() expected bytes
2023/04/23 21:55:36 | stdout | raise TypeError("quote_from_bytes() expected bytes")
2023/04/23 21:55:36 | stdout | File "/usr/lib/python3.10/urllib/parse.py", line 894, in quote_from_bytes
2023/04/23 21:55:36 | stdout | return quote_from_bytes(string, safe)
2023/04/23 21:55:36 | stdout | File "/usr/lib/python3.10/urllib/parse.py", line 869, in quote
2023/04/23 21:55:36 | stdout | "image": f"img?url={quote(item.artUrl)}",
2023/04/23 21:55:36 | stdout | File "/nas-tools/app/mediaserver/client/plex.py", line 511, in get_resume
2023/04/23 21:55:36 | stdout | return self.server.get_resume(num=num)
2023/04/23 21:55:36 | stdout | File "/nas-tools/app/mediaserver/media_server.py", line 387, in get_resume
2023/04/23 21:55:36 | stdout | Resumes = MediaServer().get_resume()
2023/04/23 21:55:36 | stdout | File "/nas-tools/web/main.py", line 252, in index
2023/04/23 21:55:36 | stdout | return current_app.ensure_sync(func)(*args, **kwargs)
2023/04/23 21:55:36 | stdout | File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
2023/04/23 21:55:36 | stdout | return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023/04/23 21:55:36 | stdout | File "/usr/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
2023/04/23 21:55:36 | stdout | rv = self.dispatch_request()
2023/04/23 21:55:36 | stdout | File "/usr/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
2023/04/23 21:55:36 | stdout | return original_handler(e)
2023/04/23 21:55:36 | stdout | File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 674, in error_router
2023/04/23 21:55:36 | stdout | rv = self.handle_user_exception(e)
2023/04/23 21:55:36 | stdout | File "/usr/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
2023/04/23 21:55:36 | stdout | response = self.full_dispatch_request()
2023/04/23 21:55:36 | stdout | File "/usr/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
2023/04/23 21:55:36 | stdout | return original_handler(e)
2023/04/23 21:55:36 | stdout | File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 674, in error_router
2023/04/23 21:55:36 | stdout | response = self.handle_exception(e)
2023/04/23 21:55:36 | stdout | File "/usr/lib/python3.10/site-packages/flask/app.py", line 2531, in wsgi_app
2023/04/23 21:55:36 | stdout | return self.app(environ, start_response)
2023/04/23 21:55:36 | stdout | File "/usr/lib/python3.10/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
2023/04/23 21:55:36 | stdout | return self.wsgi_app(environ, start_response)
2023/04/23 21:55:36 | stdout | File "/usr/lib/python3.10/site-packages/flask/app.py", line 2551, in __call__
2023/04/23 21:55:36 | stdout | Traceback (most recent call last):
2023/04/23 21:55:27 | stdout | TypeError: quote_from_bytes() expected bytes
2023/04/23 21:55:27 | stdout | raise TypeError("quote_from_bytes() expected bytes")
2023/04/23 21:55:27 | stdout | File "/usr/lib/python3.10/urllib/parse.py", line 894, in quote_from_bytes
2023/04/23 21:55:27 | stdout | return quote_from_bytes(string, safe)
2023/04/23 21:55:27 | stdout | File "/usr/lib/python3.10/urllib/parse.py", line 869, in quote
2023/04/23 21:55:27 | stdout | "image": f"img?url={quote(item.artUrl)}",
2023/04/23 21:55:27 | stdout | File "/nas-tools/app/mediaserver/client/plex.py", line 511, in get_resume
2023/04/23 21:55:27 | stdout | return self.server.get_resume(num=num)
2023/04/23 21:55:27 | stdout | File "/nas-tools/app/mediaserver/media_server.py", line 387, in get_resume
2023/04/23 21:55:27 | stdout | Resumes = MediaServer().get_resume()
2023/04/23 21:55:27 | stdout | File "/nas-tools/web/main.py", line 252, in index
2023/04/23 21:55:27 | stdout | return current_app.ensure_sync(func)(*args, **kwargs)
2023/04/23 21:55:27 | stdout | File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
2023/04/23 21:55:27 | stdout | return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023/04/23 21:55:27 | stdout | File "/usr/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
2023/04/23 21:55:27 | stdout | rv = self.dispatch_request()
2023/04/23 21:55:27 | stdout | File "/usr/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
2023/04/23 21:55:27 | stdout | return original_handler(e)
2023/04/23 21:55:27 | stdout | File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 674, in error_router
2023/04/23 21:55:27 | stdout | rv = self.handle_user_exception(e)
2023/04/23 21:55:27 | stdout | File "/usr/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
2023/04/23 21:55:27 | stdout | response = self.full_dispatch_request()
2023/04/23 21:55:27 | stdout | File "/usr/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
2023/04/23 21:55:27 | stdout | return original_handler(e)
2023/04/23 21:55:27 | stdout | File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 674, in error_router
2023/04/23 21:55:27 | stdout | response = self.handle_exception(e)
2023/04/23 21:55:27 | stdout | File "/usr/lib/python3.10/site-packages/flask/app.py", line 2531, in wsgi_app
2023/04/23 21:55:27 | stdout | return self.app(environ, start_response)
2023/04/23 21:55:27 | stdout | File "/usr/lib/python3.10/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
2023/04/23 21:55:27 | stdout | return self.wsgi_app(environ, start_response)
2023/04/23 21:55:27 | stdout | File "/usr/lib/python3.10/site-packages/flask/app.py", line 2551, in __call__
2023/04/23 21:55:27 | stdout | Traceback (most recent call last):
2023/04/23 21:53:55 | stdout | TypeError: quote_from_bytes() expected bytes
2023/04/23 21:53:55 | stdout | raise TypeError("quote_from_bytes() expected bytes")
2023/04/23 21:53:55 | stdout | File "/usr/lib/python3.10/urllib/parse.py", line 894, in quote_from_bytes
2023/04/23 21:53:55 | stdout | return quote_from_bytes(string, safe)
2023/04/23 21:53:55 | stdout | File "/usr/lib/python3.10/urllib/parse.py", line 869, in quote
2023/04/23 21:53:55 | stdout | "image": f"img?url={quote(item.artUrl)}",
2023/04/23 21:53:55 | stdout | File "/nas-tools/app/mediaserver/client/plex.py", line 511, in get_resume
2023/04/23 21:53:55 | stdout | return self.server.get_resume(num=num)
2023/04/23 21:53:55 | stdout | File "/nas-tools/app/mediaserver/media_server.py", line 387, in get_resume
2023/04/23 21:53:55 | stdout | Resumes = MediaServer().get_resume()
2023/04/23 21:53:55 | stdout | File "/nas-tools/web/main.py", line 252, in index
2023/04/23 21:53:55 | stdout | return current_app.ensure_sync(func)(*args, **kwargs)
2023/04/23 21:53:55 | stdout | File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
2023/04/23 21:53:55 | stdout | return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023/04/23 21:53:55 | stdout | File "/usr/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
2023/04/23 21:53:55 | stdout | rv = self.dispatch_request()
2023/04/23 21:53:55 | stdout | File "/usr/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
2023/04/23 21:53:55 | stdout | return original_handler(e)
2023/04/23 21:53:55 | stdout | File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 674, in error_router
2023/04/23 21:53:55 | stdout | rv = self.handle_user_exception(e)
2023/04/23 21:53:55 | stdout | File "/usr/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
2023/04/23 21:53:55 | stdout | response = self.full_dispatch_request()
2023/04/23 21:53:55 | stdout | File "/usr/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
2023/04/23 21:53:55 | stdout | return original_handler(e)
2023/04/23 21:53:55 | stdout | File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 674, in error_router
2023/04/23 21:53:55 | stdout | response = self.handle_exception(e)
2023/04/23 21:53:55 | stdout | File "/usr/lib/python3.10/site-packages/flask/app.py", line 2531, in wsgi_app
2023/04/23 21:53:55 | stdout | return self.app(environ, start_response)
2023/04/23 21:53:55 | stdout | File "/usr/lib/python3.10/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
2023/04/23 21:53:55 | stdout | return self.wsgi_app(environ, start_response)
2023/04/23 21:53:55 | stdout | File "/usr/lib/python3.10/site-packages/flask/app.py", line 2551, in __call__
2023/04/23 21:53:55 | stdout | Traceback (most recent call last):


</body>
</html>

**Comment by jxxghp** [comment]
plex有没有图片的数据时就会这样，等更新

**Comment by jiezaizone** [comment]
> 

plex就是用token登陆的 好些人都遇到了这个问题 更新后媒体页面就访问不了了 。我已经回归了版本 看不到日志了
