### ISSUE TITLE
订阅资源可以从`订阅站点`和`搜索站点`这两种模式中选择开启与否

### ISSUE THREAD

**Issue by boeto** [NAStool/nas-tools#4490]
## 你使用的 NAStool 是什么版本，什么环境？

NAStool 版本: [v3.2.0 fd57a40](https://github.com/NAStool/nas-tools)

环境: docker

## 你想要新增或者改进什么功能？

一些订阅的资源，不需要通过`订阅站点的RSS`或`搜索站点`下载，例如完结的剧集不需要`订阅站点的RSS`（自动等下一次搜索站点的周期时搜索并下载一次），追更的新剧集不需要`搜索站点`（只通过订阅rss识别资源并下载）。

所以如果`订阅资源`可以从`订阅站点`和`搜索站点`这两种模式中选择开启与否，这样也可以减少订阅的压力提高订阅的效率，如下图所示：

![订阅设置](https://user-images.githubusercontent.com/34640489/233826150-ba4125ab-0116-498f-99f9-a71c5d575bae.png)

**Comment by Shurelol** [comment]
从订阅rss方面来说，不会减小。

只要你有一个站点订阅选了这个站点，那么这个站点的rss就会被定时过一遍

但是不论有多少个订阅，订阅了这个站点，这个站点的rss还是只被定时过一遍

没有区别
