### ISSUE TITLE
哪位大佬教教如何配置豆瓣榜单订阅

### ISSUE THREAD

**Issue by Mikcoono1** [NAStool/nas-tools#4495]
想订阅 豆瓣近期热门电影  电视剧 动漫 不知订阅链接是否正确 望大佬们指导

![44](https://user-images.githubusercontent.com/119794060/233835635-67956698-c0f0-4e6a-9aff-ab2bee35b740.png)
![微信截图_20230423184647](https://user-images.githubusercontent.com/119794060/233835647-03af457f-3238-4323-8b71-ee903e85b6b5.png)
![22](https://user-images.githubusercontent.com/119794060/233835649-b92b1770-3540-4171-8cf1-43e1b9adacab.png)

**Comment by Shurelol** [comment]
粘到浏览器里看rss里报文就知道是不是你想要的了

教程去rsshub找
