### ISSUE TITLE
片名搜索出现bug

### ISSUE THREAD

**Issue by felix061230** [NAStool/nas-tools#4497]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本:  v3.2.0 fd57a40 
> 环境: docker
>

## 片名搜索问题

> 当片名出现season的时候，nastools会把season识别为季。比如国产剧“漫长的季节”搜索返回的结果是”the long season“，而nastools会把season当成季。从而不能匹配正确片名

这是nastools的日志：
The Long Season S01E01-E03 2023 2160p WEB-DL H265 AAC-ADWeb 识别为 The Long 未匹配到媒体信息

**Comment by Shurelol** [comment]
自己识别词替换
