### ISSUE TITLE
建议增加自动备份配置文件

### ISSUE THREAD

**Issue by zhouyh1899** [NAStool/nas-tools#4498]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.0
>
> 环境: synology

## 你想要新增或者改进什么功能？

> 建议适当增加自动备份配置文件，比如在日志目录里保存最近几次修改。
> 因为升级容易导致崩溃，最近一次提示“未启用https，请使用 http://IP:3003 访问管理页面”后，简单停用和保留数据卸载都没用，必须完全卸载不留文件重装后才能恢复系统。如果加入自动备份配置会方便很多。

**Comment by aiwu12** [comment]
插件市场不就有自动备份
