### ISSUE TITLE
【需求】增加TMDB电影 TMDB电视剧 的排序功能 

### ISSUE THREAD

**Issue by dihao1127** [NAStool/nas-tools#4503]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本:  v3.2.0 fd57a40
>
> 环境: docker

> 你想要新增或者改进什么功能？

增加TMDB电影 TMDB电视剧 的排序功能 ，因为用豆瓣排序订阅的话也是查询的TMDB，TMDB更新不及时就获取集数失败，干脆直接去TMDB查看比较好，直接就能订阅了！目前按热门排序 没有多少参考价值，太多老剧霸屏！希望增加排序功能，辛苦！

## 这个功能有什么可以参考的资料吗？
豆瓣电视剧 和豆瓣电影 并且我去TMDB官网查看 官网有多种排序！
![01](https://user-images.githubusercontent.com/60700173/233850869-fe4f9b8c-5652-4faa-bc17-5c78f0127eb4.jpg)

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by jxxghp** [comment]
TMDB的排序是没有意义的，除了现在的这个默认按流行度排序，其他情况排出来的图片都没有名字也乱七八糟在前面的根本不是你想要
