### ISSUE TITLE
更新最新的 v3.2.0 fd57a40版本后，我的媒体库没法访问了，一直都是在加载中

### ISSUE THREAD

**Issue by jiezaizone** [NAStool/nas-tools#4510]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
> v3.2.0 fd57a40
> 环境: docker or windows or Synology
> docker

## 你遇到什么问题了？

> 描述一下你遇到的问题
更新最新的 v3.2.0 fd57a40版本后，我的媒体库没法访问了，一直都是在加载中，测试媒体服务器是连通的
![image](https://user-images.githubusercontent.com/28976666/233892186-fae31204-26c3-429a-a11f-38c3ec50e17e.png)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by roadinger** [comment]
媒体播放器用Plex，首页就出不来  我的也是
