### ISSUE TITLE
站点数据刷新时间和豆瓣榜单订阅刷新周期无响应

### ISSUE THREAD

**Issue by rockhia** [NAStool/nas-tools#4513]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.0 fd57a40
>
> 环境: docker
>
站点数据刷新时设置为23:30-23:55
豆瓣榜单订阅刷新周期设置为10 15 * * 1
虽然docker重启后，上述两个有提示信息，但经过多次测试均没有执行。
![2023-04-24_15-21-07](https://user-images.githubusercontent.com/90016652/233926897-db3bcf18-6894-45f8-8250-8a160b55b202.jpg)

**Comment by rockhia** [comment]
豆瓣榜单订阅刷新周期设置为55 15 * * *就可以正常刷新。
5位的corn表达式是否支持不完整？

**Comment by jxxghp** [comment]
星期不能用数字要用简称

**Comment by rockhia** [comment]
星期用简称运行成功。
但是站点数据刷新时设置为23:30-23:55仍然无效

**Comment by rockhia** [comment]
> 星期不能用数字要用简称

星期用简称运行成功。
但是站点数据刷新时设置为23:30-23:55仍然无效

**Comment by ZXiangQAQ** [comment]
10 15 * * 1 不是每周一的 15:10:00 执行么

**Comment by rockhia** [comment]
星期不支持数字，10 15 * * 1 不会执行，修改为10 15 * * mon就可以了
