### ISSUE TITLE
Plex智能限速异常

### ISSUE THREAD

**Issue by beermedlar** [NAStool/nas-tools#4520]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.0
>
> 环境: docker
>

## 你遇到什么问题了？

> 智能限速设置为50Mbps，无论观看任何视频，都是限速为6103KB/s

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 正确根据plex播放的视频代码进行限速

![image](https://user-images.githubusercontent.com/32614465/234021441-cfc86f32-00bc-4c65-ae26-a87a98621608.png)
![image](https://user-images.githubusercontent.com/32614465/234021543-5b112bdf-55e7-4594-b0bd-4aa897d84fe7.png)

**Comment by asavakitming** [comment]
请问plex的webhook是如何发送至nastool的？

**Comment by Sowevo** [comment]
> 请问plex的webhook是如何发送至nastool的？

<img width="730" alt="image" src="https://user-images.githubusercontent.com/31763582/235227234-1e532cbb-e921-475d-9dbf-1714ec4e7502.png">

**Comment by asavakitming** [comment]
> > 请问plex的webhook是如何发送至nastool的？
> 
> <img alt="image" width="730" src="https://user-images.githubusercontent.com/31763582/235227234-1e532cbb-e921-475d-9dbf-1714ec4e7502.png">

感谢回复，请问这个地址是nastool的地址吗？我的nastool地址是10.10.10.9:3003，此处应是3003端口吗？

**Comment by Sowevo** [comment]
> > > 请问plex的webhook是如何发送至nastool的？
> > 
> > 
> > <img alt="image" width="730" src="https://user-images.githubusercontent.com/31763582/235227234-1e532cbb-e921-475d-9dbf-1714ec4e7502.png">
> 
> 感谢回复，请问这个地址是nastool的地址吗？我的nastool地址是10.10.10.9:3003，此处应是3003端口吗？

是的,如果nt开了https的话要注意下地址通不通

**Comment by jxxghp** [comment]
看清楚你填的那个输入框是什么意思？
