### ISSUE TITLE
自定义订阅能否新增限制评分功能？

### ISSUE THREAD

**Issue by caohaofei1** [NAStool/nas-tools#4535]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.0

> 环境: docker

## 你想要新增或者改进什么功能？

>自定义订阅能否新增限制评分功能，如

## 这个功能有什么可以参考的资料吗？

> 如下报文中，只筛选评分大于8分的条文。
<item>
<title>
<![CDATA[ 长月烬明 ]]>
</title>
<description>
<![CDATA[ <p>标题：长月烬明</p><p>评分：6.1分</p><p>标签：2023 / 中国大陆 / 剧情 爱情 奇幻 古装 / 鞠觉亮 / 罗云熙 白鹿</p><p>影片信息：</p><p><img src="" referrerpolicy="no-referrer"> <img src="https://img2.doubanio.com/view/photo/m/public/p2717365452.jpg" referrerpolicy="no-referrer"> <img src="https://img2.doubanio.com/view/photo/m/public/p2717365762.jpg" referrerpolicy="no-referrer"> <img src="https://img9.doubanio.com/view/photo/m/public/p2717365396.jpg" referrerpolicy="no-referrer"> <img src="https://img2.doubanio.com/view/photo/m/public/p2717365503.jpg" referrerpolicy="no-referrer"> </p> ]]>
</description>
<guid isPermaLink="false">长月烬明</guid>
<link/>
</item>

**Comment by Shurelol** [comment]
rsshub有筛选评分的，自己找找吧
