### ISSUE TITLE
bug 海胆的FREE识别有问题，过滤规则设置免费，订阅海胆RSS新上种但不是FREE，依然通过了过滤规则

### ISSUE THREAD

**Issue by sjh00** [NAStool/nas-tools#4543]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.0
>
> 环境: docker
>

## 你遇到什么问题了？

> bug 海胆的FREE识别有问题，过滤规则设置免费，订阅海胆RSS新上种但不是FREE，依然通过了过滤规则

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> fix bug，有个思路，海胆魔改页面所以与以往pt不同，访问种子页面后，种子信息是包裹在id="torrent-<种子编号>"的div标签里的（比如id="torrent-20416"，对应URL路径中的 &torrent_id=20416），所以应该判断该div里是否有class="pro_free"的img；
> 或者将种子标题去掉开头的[...]中括号（经测试标题后跟副标题、大小、发布者的情况下不影响搜索），使用海胆种子页面url...?&spstate=2,4&search=<种子标题>进行检索（spstate=2,4即FREE和2XFREE），若搜到单个条目即说明为FREE种，否则不是

## 给出程序界面截图、后台运行日志或配置文件

> Docker重启过，没保留，具体是我订阅的十二怒汉 [12 Angry Men]，海胆中该条目有的是FREE，RSS中给的不是FREE，可能是nastools识别到了页面有FREE就下了

**Comment by jxxghp** [comment]
海胆没法支持，直接取消了。
