### ISSUE TITLE
希望增加订阅cron功能，和远程搜索自动择优下载确认机制，谢谢

### ISSUE THREAD

**Issue by yangke098** [NAStool/nas-tools#4550]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本:  v3.2.0 fd57a40
>
> 环境: synology

## 你想要新增或者改进什么功能？

> 1.订阅搜索时间间隔可以更改为cron表达式么，最好是每个订阅增加一项cron表达式，因为每部剧不同地方更新时间可能不一致，最近长月烬明就是晚上5点过的样子更新，我设置六小时搜索一次，但是还是会时间错过，只有靠手动点一次。
   2.可以给远程搜索自动择优下载给一个确认的机制么，比如有些电影只在TMDB有一个记录，但是并不是我想要的电影，微信发送名字后就会自动下载，希望能像TMDB有多个记录时一样，在单个记录时也能通过序号发送确认一次再下载，万分感谢。

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by yangke098** [comment]
最后有一个小小的建议，可以让127.0.0.1的地址访问EMBY的时候实现限速么，因为我现在使用的是FRP来访问，访问地址都是127.0.0.1，相信部分朋友也是这个策略访问NAS，谢谢大佬

**Comment by rockhia** [comment]
> 

不是用抓取RSS的方式下载订阅吗？怎么使用搜索的方式去下载了呀。
我是通过每30分钟刷新RSS的方式订阅下载，根本用不上定时搜索；如果订阅数量过多。用定时搜索的功能也不太好，对站点压力太大了。

**Comment by yangke098** [comment]
RSS也可以啊，我rss在刷流，最好rss也能用cron表达式，定点RSS也不错

**Comment by honue** [comment]
> RSS也可以啊，我rss在刷流，最好rss也能用cron表达式，定点RSS也不错

rss支持cron

**Comment by yangke098** [comment]
怎么设置

**Comment by yangke098** [comment]
> > RSS也可以啊，我rss在刷流，最好rss也能用cron表达式，定点RSS也不错
> 
> rss支持cron

没看到哪里设置呢
