### ISSUE TITLE
标题中带 Season 的资源检索失败

### ISSUE THREAD

**Issue by yongman** [NAStool/nas-tools#4562]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.0
>
> 环境: Synology
>

## 你遇到什么问题了？

> 无法完成搜索 ”漫长的季节“，提示没有检索的资源，通过看日志 indexer 把 `The long season` 识别为 `The long`，搜索失败。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 能够正常检索

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by whkwkxsyf1991** [comment]
顶，同样的问题

**Comment by LAN-Cliv** [comment]
![QQ截图20230427093350](https://user-images.githubusercontent.com/18377783/234737396-ab26d6cb-c43b-465c-9f94-128e5b3428a2.png)
要不就看看wiki呗~

**Comment by zjjxwhh** [comment]
看 PR #4508 ，已经有大佬修了，等更新就好了
