### ISSUE TITLE
请教个关于程序打包题外话

### ISSUE THREAD

**Issue by 276562578** [NAStool/nas-tools#4571]
请教下作者使用的什么打包程序呀？这么大的python程序和依赖最后打包的体积却这么小

**Comment by ZXiangQAQ** [comment]
直接查看 github workflow 不就清楚了么 。。。 
pyinstaller + upx

**Comment by 276562578** [comment]
感谢，才知道有这么个功能
但很疑惑，自己打包的时候一个小功能，加上几个依赖就上百兆了，作者这么多依赖才几十兆
