### ISSUE TITLE
monika提示未登录，需要修改登录状态判断

### ISSUE THREAD

**Issue by AisukaYuki** [NAStool/nas-tools#4575]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.1
>
> 环境: docker or windows or Synology
>源码运行

## 你遇到什么问题了？

> monika提示未登录cookies失效，实际未失效。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 需要修改登录状态判断

修改 \app\helper\site_helper.py
logout_or_usercp
增加//form[contains(@action, "logout")]
或user_info_div增加//a[contains(@href, "users")]
![image](https://user-images.githubusercontent.com/17586327/235114029-41187303-06de-4a60-adb3-095ec2a7199c.png)

以上我自己随便改改的。
具体判断，麻烦再确认一下。

## 给出程序界面截图、后台运行日志或配置文件
![image](https://user-images.githubusercontent.com/17586327/235113204-329023ef-4100-4cac-8b8c-d38d70ecfe2a.png)
![image](https://user-images.githubusercontent.com/17586327/235113281-bbe174d7-44f7-4fa7-9f6e-de416f90ece0.png)
![image](https://user-images.githubusercontent.com/17586327/235114298-d59cfb81-f290-4825-ac37-1e8f0a167ca9.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by lightolly** [comment]
感谢告知，应该是站点最近有升级
