### ISSUE TITLE
无法正常加载首页我的媒体库

### ISSUE THREAD

**Issue by FISH-Z** [NAStool/nas-tools#4581]
> NAStool 版本:   v3.2.1 f4efbf2
>
> 环境: docker
>

## 你遇到什么问题了？

更新后无法加载首页我的媒体库

<img width="1509" alt="image" src="https://user-images.githubusercontent.com/56290047/235155577-b614f320-a924-41e5-9907-a9519e705b4e.png">
docker 日志：（感觉是这个报错，不太确定）
<img width="877" alt="image" src="https://user-images.githubusercontent.com/56290047/235170921-e2eca6ab-1430-45b5-8a58-8cf902da854c.png">

**Comment by FISH-Z** [comment]
我使用的是PLEX ，更新前此功能显示完好

**Comment by Sowevo** [comment]
> 我使用的是PLEX ，更新前此功能显示完好

谢谢反馈
确实有问题
修了

**Comment by torch132** [comment]
这个媒体库功能能设置哪些显示和哪些不显示么，还有哪些库不显示正在观看
