### ISSUE TITLE
运行插件报错

### ISSUE THREAD

**Issue by qcwolf** [NAStool/nas-tools#4583]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: [v3.2.1 f4efbf2](https://github.com/NAStool/nas-tools)
>
> 环境: docker 
>

## 你遇到什么问题了？
间歇性运行插件报错

Wrong number of fields; got 6, expected 5

![屏幕截图 2023-04-29 001830](https://user-images.githubusercontent.com/22956195/235201057-9598db1a-9545-45c6-a078-357e0cba4503.png)

**Comment by qcwolf** [comment]
豆瓣可以正常使用，签到和刮削报错

**Comment by qcwolf** [comment]
实时日志里面没有报错内容。
<html>
<body>


00:15:22 | Plugin | 站点自动签到 - 签到服务启动，立即运行一次
-- | -- | --
00:15:22 | Plugin | 站点自动签到 - 定时签到服务启动，周期：0 15 06 ? * *
00:16:08 | Plugin | 站点自动签到 - 定时签到服务启动，周期：0 15 06 ? * *
00:17:10 | Plugin | 媒体库刮削 - 刮削服务启动，周期：0 15 03 ? * *
00:22:41 | Plugin | 媒体库刮削 - 刮削服务启动，周期：0 15 03 ? * *
00:22:53 | Plugin | 豆瓣同步 - 订阅服务启动，周期：12 小时，类型：['wish']，用户：['qcwolf']
00:22:53 | Plugin | 豆瓣同步 - 同步服务启动，立即运行一次


</body>
</html>

**Comment by Sowevo** [comment]
你的表达式貌似不对?多了一位?
[使用这个工具测试一下](https://tool.lu/crontab/)
选择Linux这个类型测试一下试试

**Comment by qcwolf** [comment]
> 

感谢大神，好了！
