### ISSUE TITLE
nastool里面的海报图都是闪一下就消失了，只剩下文字

### ISSUE THREAD

**Issue by fanceq821** [NAStool/nas-tools#4584]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
> v3.2.1 f4efbf2
> 环境: docker or windows or Synology
> unraid docker

## 你遇到什么问题了？

> nastool里面的海报图都是闪一下就消失了，只剩下文字

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

>没有找到，有没有交流群可以咨询

**Comment by Sowevo** [comment]
能不能具体描述下
首页`我的媒体库`的问题么,用什么媒体库呢?
