### ISSUE TITLE
升级到3.2.1 版本后，刷流任务消失了

### ISSUE THREAD

**Issue by zjuht** [NAStool/nas-tools#4595]
## 你使用的 NAStool 是什么版本，什么环境？
3.2.1  群辉DS220+

> NAStool 版本: v3.2.1
>
> 环境: Synology
>

## 你遇到什么问题了？

> 升级到3.2.1 版本后，刷流任务消失了

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

重新有这个选项

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
![1682741246167](https://user-images.githubusercontent.com/12762280/235282749-6a3ffa64-c260-43bd-8002-c1e3fa6f7954.png)

**Comment by xiachf** [comment]
要pt站注册满一个月以后才会显示

**Comment by dim-HAOS** [comment]
> 

请问是作为认证的站点要注册满一个月吗？

**Comment by zjuht** [comment]
请问下刷流的网址是多少，比如http://*:3003/web#？  最后的单词是什么

**Comment by dick86114** [comment]
> 请问下刷流的网址是多少，比如http://*:3003/web#？ 最后的单词是什么

brushtask
