### ISSUE TITLE
请求适配莫妮卡，ggpt

### ISSUE THREAD

**Issue by xiele88787** [NAStool/nas-tools#4603]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.1
>
> 环境: docker or windows or synology
synology
## 你想要新增或者改进什么功能？
请求适配莫妮卡，ggpt
ggpt为https://www.gamegamept.com/
> 你想要新增或者改进什么功能？

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by jxxghp** [comment]
我去注册了，但一直收不到注册邮件，也无法重新注册。。。。

**Comment by jxxghp** [comment]
下个版本支持
