### ISSUE TITLE
签到队列注解

### ISSUE THREAD

**Issue by git-0101** [NAStool/nas-tools#4604]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.1
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 能否增加签到队列注解。不知设置多少最优。

**Comment by thsrite** [comment]
那就默认10
你也可以设置高一点，如果签到一次失败太多再调低

**Comment by git-0101** [comment]
> 那就默认10 你也可以设置高一点，如果签到一次失败太多再调低

好的，感谢大佬！我去给群友解惑。
