### ISSUE TITLE
签到失败不会继续签到吗？要到第二天吗？求大佬指点一下怎么配置。

### ISSUE THREAD

**Issue by Mrxlei** [NAStool/nas-tools#4605]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>
> 环境: docker or windows or Synology
>

## 你遇到什么问题了？

> 请问怎么让失败的继续签到，等到第二天不就没意义了吗？不是失败了就自动多久重试吗？
【自动签到任务完成】
本次签到数量: 6
命中重试数量: 2
强制签到数量: 0
下次签到数量: 2
下次签到时间: 2023-05-01 08:01:00
详见签到消息
2023-04-30 09:53:27

**Comment by thsrite** [comment]
百度下cron五位表达式

**Comment by Mrxlei** [comment]
> 百度下cron五位表达式

你的意思我设置每几个小时一次，不应该是检测失败自动的吗？如果一直有失败的，第二天是失败的签到，还是全签呢？

**Comment by Mrxlei** [comment]
签到列队是什么意思？

**Comment by thsrite** [comment]
> > 百度下cron五位表达式
> 
> 你的意思我设置每几个小时一次，不应该是检测失败自动的吗？如果一直有失败的，第二天是失败的签到，还是全签呢？

每天签到多次，第一次全签，后续只签到命中重试关键字的
自己试试不很清晰吗？

**Comment by Amexcent** [comment]
簽到變插件後，執行後沒反應啊，怎麼愈改愈倒退

**Comment by thsrite** [comment]
> 簽到變插件後，執行後沒反應啊，怎麼愈改愈倒退

插件设置截图？
签到周期设置了吗？
开启签到了吗？

**Comment by Amexcent** [comment]
> > 簽到變插件後，執行後沒反應啊，怎麼愈改愈倒退
> 
> 插件设置截图？ 签到周期设置了吗？ 开启签到了吗？

https://imgur.com/D2EoXck.jpg
https://imgur.com/K56qYNS.jpg

早上6:01就會執行了，可是我看20個站都無簽到
昨天都正常，其實本來好好的又簡單無腦，怎麼突然要改的這麼複雜啊

**Comment by git-0101** [comment]
你这个cron设置错了。注意空格 位数。改为插件后统一配置，还可以自定义队列，签到成功率已经非常高了。开始还想回到模拟登录方式，现在才完美。还有更新没推送，更新后签到时间和之前一样有四种配置方式。

**Comment by Amexcent** [comment]
> 你这个cron设置错了。注意空格 位数。改为插件后统一配置，还可以自定义队列，签到成功率已经非常高了。开始还想回到模拟登录方式，现在才完美。还有更新没推送，更新后签到时间和之前一样有四种配置方式。

解決了，謝謝。
要是島也能自動簽到，就真的強大了
