### ISSUE TITLE
还是提示no matching manifest for linux/arm/v8 in the manifest list entries

### ISSUE THREAD

**Issue by icezxf** [NAStool/nas-tools#4606]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>NAStool 3.2.1最新版本
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？
no matching manifest for linux/arm/v8 in the manifest list entries
> 描述一下你遇到的问题
设备是N1 coreelec9.2.2
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是的，看到issues之前有提过相同的问题，说是已经解决了，但是我这里还是报同样的错误
> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果
如果不支持N1的arm64，我就死心了

## 给出程序界面截图、后台运行日志或配置文件
![image](https://user-images.githubusercontent.com/122969420/235351870-4513d150-357f-4ee6-ba83-e84706b2faac.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by DDSDerek** [comment]
docker pull --platform=linux/arm64/v8 jxxghp/nas-tools:latest

试试看用这个命令

**Comment by icezxf** [comment]
> 

<img width="477" alt="image" src="https://user-images.githubusercontent.com/122969420/235358269-cfa67853-7601-47f0-83d5-9667739e8a28.png">

还是不行啊

**Comment by jxxghp** [comment]
N1还是放弃吧，就算能跑起来，估计也卡的不行。

**Comment by icezxf** [comment]
> N1还是放弃吧，就算能跑起来，估计也卡的不行。

之前的都能能用 跑过 这个跑起来应该不用多少资源吧
