### ISSUE TITLE
签到失败后无法再次运行签到

### ISSUE THREAD

**Issue by andy-sherlock** [NAStool/nas-tools#4610]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.1
>
> 环境: docker 
>

## 你遇到什么问题了？

> **签到失败后再次运行签到，插件提示已经执行过签到命令，然后直接结束，我猜测是不是现在签到的判断标准是以是否执行作为判断标准而不是执行结果呢？另外我还找到了更新版本之前的签到命令作为对比！而且好像我设置了失败后重新签到的命令也没有效果。从截图中可以看到，图一为旧版本签到，每一次签到都是独立单独执行一次命令，而后面几张图中，明显签到失败，但是系统检测到已经执行过签到，所以再次签到就直接跳过不执行了**作为对比，我放出昨天的签到截图，证明相同版本下，我并没有修改任何配置，是正常可以签到的，图二是五月1日签到截图
![photo_2023-05-01_10-05-25](https://user-images.githubusercontent.com/66240002/235391505-2b19f05a-c8a9-46fe-98e9-7a9e1f83aba0.jpg)
![photo_2023-05-01_10-05-31](https://user-images.githubusercontent.com/66240002/235391539-65b948de-cbda-43ff-b9a0-ef631d7994d4.jpg)
![photo_2023-05-01_10-05-35](https://user-images.githubusercontent.com/66240002/235391541-c0c14582-5a64-448d-85bc-ece0a2ab7eac.jpg)
![QQ截图20230501100602](https://user-images.githubusercontent.com/66240002/235391542-f0cb23ce-5804-42a1-b7f0-2c87675b5207.png)
![QQ截图20230501101606](https://user-images.githubusercontent.com/66240002/235392044-e3025417-2330-40d8-8c2c-cd63a57be324.png)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已浏览，未解决

## 你期望的结果

> 每次签到都单独再次执行一遍，而不是检测到之前执行过就不执行

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
#4605
