### ISSUE TITLE
更新3.2.1後套的刷流任務功能好像失效了

### ISSUE THREAD

**Issue by Amexcent** [NAStool/nas-tools#4612]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>3.2.1
> 环境: docker or windows or Synology
>docker, synology

## 你遇到什么问题了？

> 描述一下你遇到的问题
原本是3.2.0在套的刷流任務都正常，遇到五大官組都會正常rss下來刷流
幾前天docker自動更新到3.2.1後，到今天為址，都沒有再自動下載符合正則式的來刷流，
跑去網站看，種子有些都有符合資格，看日誌有顯示正常rss，但是沒有下載符合的

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是
> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果
是否可請作者check一下

> 描述以下你期望的结果
希望能針對套修正一下刷流
## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by sn066** [comment]
看情况像是因为下载器问题，因为我发现经常性提示无法获取下载器数据
