### ISSUE TITLE
请求增加自定义站点的自定义刮削

### ISSUE THREAD

**Issue by oynt** [NAStool/nas-tools#4613]
之前完电影站群的时候，可以自定义要采集的目标站点，并采集对方站点的电影数据，包括播放地址等信息。

那么，NAStool能不能在刮削插件上增加自定义刮削的功能呢？
操作和采集电影数据类似，只是将列表页改为了搜索页。
在搜索页列表里获取总页数，每页数量，本页中的所有电影名称和详情页链接

再在详情页中刮削电影详细数据，如播放地址或下载地址（部分电影站还需要在播放页面中读取到电影的实际地址）

实际上刮削搜索下载站，下载地址（如磁力链）可能直接在搜索列表或详情页中出现，比采集电影应该要简单。
求适配。

**Comment by Wenjungang** [comment]
这个基本没有通用方案。需要爬虫基础的，自行调试适配
