### ISSUE TITLE
刷流设置的建议

### ISSUE THREAD

**Issue by youyifentian** [NAStool/nas-tools#4619]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.1
>
> 环境: docker on synology

## 4、其实如果能够给予足够的风险提示，搭配一些适合大部分站点的风险最低的配置参数作为默认参数，可能对新手会更友好一些，毕竟有了刷流，过站点考核会更方便一些，只要明确告知当他们开始使用刷流的时候，就得有风险自负的觉悟，这对任何人都是一样，一点拙见，希望大佬可以考虑下，感谢！

**Comment by aicenluo** [comment]
你的这个建议好是好，但是可操作性比较低。现在市面上站点多如牛毛，作者不可能根据每个网站的规则进行适配的，而且个性化功能没办法普遍使用。

**Comment by taoletsgo** [comment]
其实可以每个站点单独出一个配置教程，通配的教程往往误导小白，但这工作量嘛~就看哪位大佬愿意出图文或者视频教程了。或者说nastool本来就是要有上手门槛的，一上来无脑刷流导致号废了的，说明门槛还没摸到:p

**Comment by Wangsc1** [comment]
建议的很好，下次别建议了
