### ISSUE TITLE
电影名字里面带有：的下载完成rclone移动在：号前面会有一个引号

### ISSUE THREAD

**Issue by xx-super** [NAStool/nas-tools#4631]
![9AB9469C-4639-4E92-9BA7-0B067C211E46](https://user-images.githubusercontent.com/73808426/236126817-83ad8982-a4ad-48a1-8024-2abe564a639c.jpeg)
![A170B679-84C6-4B19-AA55-3E7F8A4343D5](https://user-images.githubusercontent.com/73808426/236126835-8b0f0e7f-0d08-4a2a-b49c-d226d212525c.jpeg)
![E459BEE0-5183-4AEC-B164-EBB78F86E614](https://user-images.githubusercontent.com/73808426/236126841-1c969cbf-bfc8-4e26-a1cd-00de250b7061.jpeg)
sftp里面没有那个引号，但是od客户端里面有，这会导致emby播放不了

**Comment by xx-super** [comment]
![7E66EE09-F478-4F8F-BE45-89E4091E6C9A](https://user-images.githubusercontent.com/73808426/236127754-ff05001d-4c16-4df7-8d48-8139b8a4bb7e.jpeg)

**Comment by yubanmeiqin9048** [comment]
https://rclone.org/overview/#encoding
这不关nastool的事，自行阅读rclone文档

**Comment by xx-super** [comment]
我在rclone配置里面加入了encoding = None
![1E2C68F2-2C50-4774-8783-6A4B3B02C6C3](https://user-images.githubusercontent.com/73808426/236167247-7a330a59-5dfa-4e6e-b7dd-05545025ad1e.jpeg)
然后就是分成两个文件了，电影对的，刮肖数据又不对，能帮我解决一下吗
