### ISSUE TITLE
PT站点未适配 https://hdtime.org/

### ISSUE THREAD

**Issue by yuguansu** [NAStool/nas-tools#4632]
## 你使用的 NAStool 是什么版本，什么环境？
> NAStool 版本: v3.2.1
> 环境: docker

## 你想要新增或者改进什么功能？
> PT站点未适配 https://hdtime.org

**Comment by jxxghp** [comment]
怎么会：
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/51039935/236142150-ff54973d-a07a-4894-8ab2-9e3a841ebf94.png">
