### ISSUE TITLE
升级完成之后，我的站点签到不会签到了

### ISSUE THREAD

**Issue by xiaojie-jack** [NAStool/nas-tools#4636]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.1
>
> 环境: docker 
>

## 你遇到什么问题了？

> 升级完成之后，我的站点签到不会签到了

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 无

## 你期望的结果

> 可以正常签到

## 给出程序界面截图、后台运行日志或配置文件
![图片1](https://user-images.githubusercontent.com/87162069/236198519-82bfa65c-f113-4125-87f2-b106cf2b1d01.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by xiaojie-jack** [comment]
<html>
<body>


19:50:09 | Plugin | 站点自动签到 - 签到服务启动，立即运行一次
-- | -- | --
19:50:11 | Plugin | 站点自动签到 - 定时签到服务启动，周期：04:00
19:51:50 | Plugin | 站点自动签到 - 签到服务启动，立即运行一次
19:51:51 | Plugin | 站点自动签到 - 定时签到服务启动，周期：04:00
19:52:16 | Plugin | 站点自动签到 - 定时签到服务启动，周期：04:00
19:52:19 | Plugin | 站点自动签到 - 签到服务启动，立即运行一次
19:52:19 | Plugin | 站点自动签到 - 定时签到服务启动，周期：04:00
20:15:00 | Plugin | 站点自动签到 - 签到服务启动，立即运行一次
20:15:00 | Plugin | 站点自动签到 - 定时签到服务启动，周期：0 4 * * ?


</body>
</html>

**Comment by torch132** [comment]
我也是，我立即运行一次签到插件后，日志都没反应，完全没触发。

**Comment by leonedit** [comment]
我也是，11个站没一个能签到的

**Comment by 7161457** [comment]
![1683248620867(1)](https://user-images.githubusercontent.com/113887555/236359430-b3bd52f9-1410-4116-a04b-90c9d132f466.jpg)
![1683248675024](https://user-images.githubusercontent.com/113887555/236359435-8d2f4361-3168-40e5-b52f-047f2ba2604b.jpg)
我的也是 更新后 第一次签到全部失败，后期重新设置直接没反应了，进度条一直跑不到头，设置的没有反应。

**Comment by thsrite** [comment]
插件配置截图发下？就这怎么帮你们排查问题？

**Comment by 7161457** [comment]
> 插件配置截图发下？就这怎么帮你们排查问题？

![1683248930470](https://user-images.githubusercontent.com/113887555/236359730-42567f69-e2c6-4ad5-8f6f-cf950003977a.jpg)

**Comment by 7161457** [comment]
> > > 插件配置截图发下？就这怎么帮你们排查问题？
> > 
> > 
> > ![1683248930470](https://user-images.githubusercontent.com/113887555/236359730-42567f69-e2c6-4ad5-8f6f-cf950003977a.jpg)
> 
> 左下角版本是多少

![1683249538388](https://user-images.githubusercontent.com/113887555/236360439-e821ca5c-03b9-4c82-aa5b-b59d9b958fbe.jpg)

**Comment by xiaojie-jack** [comment]
> 19：50：09	插件	站点自动签到 - 签到服务启动，立即运行一次
> 十九点五十分十一秒	插件	站点自动签到 - 定时签到服务启动，周期：04:00
> 十九点五十一分五十秒	插件	站点自动签到 - 签到服务启动，立即运行一次
> 十九点五十一分五十一秒	插件	站点自动签到 - 定时签到服务启动，周期：04:00
> 十九点五十二分十六秒	插件	站点自动签到 - 定时签到服务启动，周期：04:00
> 十九点五十二分十九秒	插件	站点自动签到 - 签到服务启动，立即运行一次
> 十九点五十二分十九秒	插件	站点自动签到 - 定时签到服务启动，周期：04:00
> 20点15分	插件	站点自动签到 - 签到服务启动，立即运行一次
> 20点15分	插件	站点自动签到 - 定时签到服务启动，周期：0 4 * * ?

![image](https://user-images.githubusercontent.com/87162069/236360468-9358f826-037f-4a97-9d2b-225ef4545b65.png)

**Comment by thsrite** [comment]
40 9 * * *
cron设置1分钟后看看日志运行不
最前面的40自己调整改成当前时间+1

**Comment by 7161457** [comment]
> 40 9 * * * cron设置1分钟后看看日志运行不 最前面的40自己调整改成当前时间+1

![Screenshot_20230505_095403_com android chrome](https://user-images.githubusercontent.com/113887555/236363324-c4d73b49-4696-4f4b-a66d-85776c894d20.jpg)
![Screenshot_20230505_095200_com android chrome](https://user-images.githubusercontent.com/113887555/236363344-f61ab58f-adfd-4861-a7d9-9723927a20e3.jpg)
确定设置后 进度条还是一直跑不到头，然后刷新页面，查看日志就是刷新中 没有反应。

**Comment by torch132** [comment]
Same problem as you

**Comment by iSoShow** [comment]
![Uploading image.png…]()
我也一样,升级到最新版本后就不行了.

**Comment by thsrite** [comment]
> v3.2.1 [f4efbf2](https://github.com/NAStool/nas-tools/commit/f4efbf20a017f2ebed436b82c56e8f0d1c93857a) 我也一样,升级后就不自动签到了. ![微信截图_20230505223650](https://user-images.githubusercontent.com/132684061/236488786-f1d8de4c-bab9-43ae-b1b0-cd1470492de4.png) ![微信截图_20230505223711](https://user-images.githubusercontent.com/132684061/236488812-c7dba2cb-f7f5-4a68-82b4-e01899641424.png)

五位cron  改成
0 8,16,23 * * *
试试

**Comment by iSoShow** [comment]
> > v3.2.1 [f4efbf2](https://github.com/NAStool/nas-tools/commit/f4efbf20a017f2ebed436b82c56e8f0d1c93857a)我也一样，升级后就不会自动签到了。![微信截图_20230505223650](https://user-images.githubusercontent.com/132684061/236488786-f1d8de4c-bab9-43ae-b1b0-cd1470492de4.png) ![微信截图_20230505223711](https://user-images.githubusercontent.com/132684061/236488812-c7dba2cb-f7f5-4a68-82b4-e01899641424.png)
> 
> 五位cron改成 0 8,16,23 * * * 试试

哇棒~可以了.谢谢谢谢~

**Comment by iSoShow** [comment]
> > v3.2.1 [f4efbf2](https://github.com/NAStool/nas-tools/commit/f4efbf20a017f2ebed436b82c56e8f0d1c93857a)我也一样，升级后就不会自动签到了。![微信截图_20230505223650](https://user-images.githubusercontent.com/132684061/236488786-f1d8de4c-bab9-43ae-b1b0-cd1470492de4.png) ![微信截图_20230505223711](https://user-images.githubusercontent.com/132684061/236488812-c7dba2cb-f7f5-4a68-82b4-e01899641424.png)
> 
> 五位cron修改 0 8,16,23 * * * 试试


哇.可以啦可以啦.谢谢

**Comment by 7161457** [comment]
> 0 8,16,23 * * *

0 8,16,23 * * * 分别代表什么意思？我想和以前一样 设置早上7点到7点半随机 应该怎么写？

**Comment by thsrite** [comment]
> > 0 8,16,23 * * *
> 
> 0 8,16,23 * * * 分别代表什么意思？我想和以前一样 设置早上7点到7点半随机 应该怎么写？

目前不支持随机，等更新

**Comment by 7161457** [comment]
> > > 0 8,16,23 * * *
> > 
> > 
> > 0 8,16,23 * * * 分别代表什么意思？我想和以前一样 设置早上7点到7点半随机 应该怎么写？
> 
> 目前不支持随机，等更新

那 早上7点 应该怎么写？

**Comment by thsrite** [comment]
> > > > 0 8,16,23 * * *
> > > 
> > > 
> > > 0 8,16,23 * * * 分别代表什么意思？我想和以前一样 设置早上7点到7点半随机 应该怎么写？
> > 
> > 
> > 目前不支持随机，等更新
> 
> 那 早上7点 应该怎么写？

0 7 * * *
建议百度下cron五位表达式

**Comment by iSoShow** [comment]
> > 0 8,16,23 * * *
> 
> 0 8,16,23 * * * 分别代表什么意思？我想和以前一样 设置早上7点到7点半随机 应该怎么写？

24小时制,每天8点,16点,23点执行一次签到命令.我有几个小站,有的时候会签到失败,就设置了一天执行三次.

**Comment by xiaojie-jack** [comment]
[](url)

> > > 0 8，16，23 * * *
> > 
> > 
> > 0 8,16,23 * * * 分别代表什么意思？我想和以前一样 设置早上7点到7点半随机 应该怎么写？
> 
> 24小时制,每天8点,16点,23点执行一次签到命令.我有几个小站,有的时候会签到失败,就设置了一天执行三次.

新版本是不是用那个失败重签就可以了

**Comment by 7161457** [comment]
> > > > > 0 8,16,23 * * *
> > > > 
> > > > 
> > > > 0 8,16,23 * * * 分别代表什么意思？我想和以前一样 设置早上7点到7点半随机 应该怎么写？
> > > 
> > > 
> > > 目前不支持随机，等更新
> > 
> > 
> > 那 早上7点 应该怎么写？
> 
> 0 7 * * * 建议百度下cron五位表达式

![1683359331610](https://user-images.githubusercontent.com/113887555/236611021-1f5a01f5-1f72-4d3d-8d36-603ed12b32c7.jpg)
我这边还是不行，确定后 进度条跑不到头，进实时日志 显示刷新中。从新 安装卸载都是卡着的状态，卸载后 插件页 还是显示存在。

**Comment by 7161457** [comment]
> > > > > > 0 8,16,23 * * *
> > > > > 
> > > > > 
> > > > > 0 8,16,23 * * * 分别代表什么意思？我想和以前一样 设置早上7点到7点半随机 应该怎么写？
> > > > 
> > > > 
> > > > 目前不支持随机，等更新
> > > 
> > > 
> > > 那 早上7点 应该怎么写？
> > 
> > 
> > 0 7 * * * 建议百度下cron五位表达式
> 
> ![1683359331610](https://user-images.githubusercontent.com/113887555/236611021-1f5a01f5-1f72-4d3d-8d36-603ed12b32c7.jpg) 我这边还是不行，确定后 进度条跑不到头，进实时日志 显示刷新中。从新 安装卸载都是卡着的状态，卸载后 插件页 还是显示存在。

![1683359626596](https://user-images.githubusercontent.com/113887555/236611374-fba2be53-48e2-404d-aaff-9d14a03ff30d.jpg)

**Comment by thsrite** [comment]
> > > > > > 0 8,16,23 * * *
> > > > > 
> > > > > 
> > > > > 0 8,16,23 * * * 分别代表什么意思？我想和以前一样 设置早上7点到7点半随机 应该怎么写？
> > > > 
> > > > 
> > > > 目前不支持随机，等更新
> > > 
> > > 
> > > 那 早上7点 应该怎么写？
> > 
> > 
> > 0 7 * * * 建议百度下cron五位表达式
> 
> ![1683359331610](https://user-images.githubusercontent.com/113887555/236611021-1f5a01f5-1f72-4d3d-8d36-603ed12b32c7.jpg) 我这边还是不行，确定后 进度条跑不到头，进实时日志 显示刷新中。从新 安装卸载都是卡着的状态，卸载后 插件页 还是显示存在。

重启下
