### ISSUE TITLE
torrentleech站点刷流失败

### ISSUE THREAD

**Issue by likd2002** [NAStool/nas-tools#4645]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.1
>
> 环境: docker
>

## 你遇到什么问题了？

> 添加torrentleech后测试成功但是无法获取资源，站点资源获取为空。

**Comment by jxxghp** [comment]
这个站是要开仿真的，是动态页面。

<img width="1313" alt="image" src="https://user-images.githubusercontent.com/51039935/236615110-63de779a-4600-4293-9a77-344c6fde6534.png">
