### ISSUE TITLE
IYUU辅种插件能否增加https选项

### ISSUE THREAD

**Issue by Boice522** [NAStool/nas-tools#4651]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本:  v3.2.1 f4efbf2
>
> 环境: docker 威联通
>

## 你遇到什么问题了？

IYUU插件没有https选项，导致馒头，观众等站点默认为tracher地址为http连接不上。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 新增https选项。

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
<img width="644" alt="image" src="https://user-images.githubusercontent.com/26293844/236591761-592435d7-2c6f-4325-853a-f2f130532486.png">

**Comment by jxxghp** [comment]
下个版本更新
