### ISSUE TITLE
能不能对硬链接失败后需要手动识别的视频种，增加一个重新识别

### ISSUE THREAD

**Issue by adaisanhao** [NAStool/nas-tools#4655]
你好，就是我前几天硬链接很多电视剧，有个晚上网络出现问题，到时刮削的时候tmdb全部连不上，早上起来后又3000多个视频没识别，需要手动识别或者重新识别，但是手动识别界面里一次只能选择30个重新识别，有点麻烦。能否加个按钮，能让这些没识别的视频，重新再总体识别一次，非常感谢

**Comment by adaisanhao** [comment]
![272f45516c41afb1daaea68f53193d5](https://user-images.githubusercontent.com/132738498/236608194-858b796a-d001-4b9d-b2b5-57814462e14b.png)

**Comment by thsrite** [comment]
服务--目录同步，重新同步下试试
