### ISSUE TITLE
对于同时存在原名和英文名的标题无法识别

### ISSUE THREAD

**Issue by Mashiro69** [NAStool/nas-tools#4662]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.1
>
> 环境: docker
>

## 你遇到什么问题了？

> 对于同时存在原名和英文名的标题无法识别，会忽略所有分隔符，识别成整体
![image](https://user-images.githubusercontent.com/132663330/236670041-d0115e10-aa28-463d-81d5-248a62af6cf1.png)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

>是

## 你期望的结果

> 对于同时存在原名和英文名的标题正常识别，或能自定义分隔符

## 给出程序界面截图、后台运行日志或配置文件

> 只存在一种名字的时候正常识别
![image](https://user-images.githubusercontent.com/132663330/236670257-5e4e71de-00b6-4fe9-ae56-95d5e8101eab.png)
![image](https://user-images.githubusercontent.com/132663330/236670274-1b8688d3-cded-4f12-bec4-fce6d60e571b.png)

**Comment by Mashiro69** [comment]
对于原标题名存在多个空格的情况下也无法识别
![image](https://user-images.githubusercontent.com/132663330/236672672-920bea93-1370-411e-865b-eb9350ee4665.png)
![image](https://user-images.githubusercontent.com/132663330/236672675-496f88cc-1f91-4d45-97fe-efa174c92264.png)
![image](https://user-images.githubusercontent.com/132663330/236672686-b6cafa99-1cfc-415f-be61-4e9426173fb1.png)

**Comment by jxxghp** [comment]
命名的乱七八糟没法支持
