### ISSUE TITLE
电影信息显示不全

### ISSUE THREAD

**Issue by aiwu12** [NAStool/nas-tools#4669]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.2
>
> 环境: docker or windows or Synology
>

## 你遇到什么问题了？
![image](https://user-images.githubusercontent.com/61082200/236800305-dbc35d6e-de59-4100-9f52-fef3e8ef933e.png)
无法向上滑动
> 描述一下你遇到的问题

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by cyclc77** [comment]
![未命名1683541759](https://user-images.githubusercontent.com/35233448/236801889-971da6c6-2308-4376-a816-016782f0d534.png)
同样的问题

**Comment by jxxghp** [comment]
修复了
