### ISSUE TITLE
站点添加天雪但站点索引不显示

### ISSUE THREAD

**Issue by Mashiro69** [NAStool/nas-tools#4678]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.2
>
> 环境: docker 
>

## 你遇到什么问题了？

> 站点添加了天雪但是站点索引和站点资源内没有

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 站点索引内出现天雪

## 给出程序界面截图、后台运行日志或配置文件

> 
![IMG_20230509_065926](https://user-images.githubusercontent.com/132663330/236955636-80a5325d-d8ad-4591-a7b4-4539f8ea2a28.jpg)
![image](https://user-images.githubusercontent.com/132663330/236955802-782615ef-1ba3-4b46-9364-32bdc1aff706.png)

**Comment by jxxghp** [comment]
<img width="1208" alt="image" src="https://user-images.githubusercontent.com/51039935/237017170-abd098d4-552e-49a6-aea1-ad3574ea1e1c.png">
<img width="122" alt="image" src="https://user-images.githubusercontent.com/51039935/237017301-db321f2d-1081-4e3c-bafe-857e604c3e64.png">

**Comment by Mashiro69** [comment]
问题是由于天雪有两个地址导致的
skyeysnow.com可以正常识别
www.skyey2.com无法识别
