### ISSUE TITLE
剧集第一集识别偶发故障

### ISSUE THREAD

**Issue by zhouyh1899** [NAStool/nas-tools#4683]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.1 - 3.2.2
>
> 环境: Synology
>

## 你遇到什么问题了？

> 刮削剧集时经常出现无法第一集识别，但是手动识别时文件名识别完全没问题，出现概率大概10%。
> 此前还出现过第一集和后面集命名不同，比如后缀比其他多一个-TLF之类的。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是的

## 你期望的结果

> 第一集正常识别，并和后面集数保持一致格式

> 2023-05-09 11:16:28,088	WARNING: 【Rmt】Black.Mirror.S05E01.2019.1080p.WEB-DL.x265.10bit.AC3￡cXcY@FRDS.mkv 无法识别媒体信息！
> 2023-05-09 11:16:31,395	WARNING: 【Rmt】Black.Mirror.S05E01.2019.1080p.WEB-DL.x265.10bit.AC3￡cXcY@FRDS.mkv 按原文件名转移到未识别目录：/volume1/pt/downloads/unrecognized

**Comment by jxxghp** [comment]
检查与TMDB的网络连接是否稳定
