### ISSUE TITLE
搜索结果丰富

### ISSUE THREAD

**Issue by xxzj990** [NAStool/nas-tools#4692]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.2
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 是否有可能在搜索结果里面展示Plex或者Emby媒体库的结果？

## 这个功能有什么可以参考的资料吗？

> 这个功能的使用场景是：每次想看一部电影，去搜索，然后下载，下载完后发现原来Plex里面已经有了。
> 现在的操作是每次搜电影前先去Plex APP里搜，没有再去Nas-Tools里面搜索下载，感觉操作稍微有些繁琐。

**Comment by Shurelol** [comment]
![Screenshot_20230509_203545_Chrome.jpg](https://github.com/NAStool/nas-tools/assets/16237201/871fbbef-3edd-4b1c-9b54-e7e36d106818)

**Comment by xxzj990** [comment]
@Shurelol 感谢回复，现在是不是不支持Plex？


Nas-tools截图：

![e1938337d25d859f3e2755e6d9e5fa5](https://github.com/NAStool/nas-tools/assets/5134154/9345cbae-3ba6-4c66-8da1-0492d34ce580)

Plex截图：

![b1f380f83b0b411b792734490a017e0](https://github.com/NAStool/nas-tools/assets/5134154/dd05a9ae-3d4a-474d-bc72-c950fc262706)

**Comment by xxzj990** [comment]
@Shurelol Plex token已经配置好了，首页可以看到Plex的播放记录。

![b8bf08209654826609425f79dde8ac2](https://github.com/NAStool/nas-tools/assets/5134154/aeaf56b7-db2b-4ed2-a1cf-2fbb115b6157)
