### ISSUE TITLE
榜单能不能请开发者默认为首播时间

### ISSUE THREAD

**Issue by naoki66** [NAStool/nas-tools#4693]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
> v3.2.2 7ecbe70

> 环境: docker or windows or synology
> docker 

## 你想要新增或者改进什么功能？

> 探索里的榜单能不能请开发者默认为首播时间（或者在设置里加个开关选择），否则霸榜的永远是那几部高分的。不便于展示最新的热播剧，很多时候反而靠刷抖音看到剧名才通过nastool搜索下载。非常感谢！

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.
如截图所示
默认
![image](https://github.com/NAStool/nas-tools/assets/22931306/afbbbb19-8665-4d19-883c-efdbdf512959)

首播时间
![image](https://github.com/NAStool/nas-tools/assets/22931306/298383b0-62bc-4187-9497-392f266f399d)

**Comment by jxxghp** [comment]
缺点也很明显，就是很多没海报的
