### ISSUE TITLE
下载器限速插件无法正常运行

### ISSUE THREAD

**Issue by ZmmLAOBiao** [NAStool/nas-tools#4696]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 3.2.2
>
> 环境: docker 
>

## 你遇到什么问题了？

nastools下载器限速插件无法正常使用，plex已正确设置webhooks，nt日志可以显示播放、暂停消息，但是一直没有限速启动、停止的日志，重启过nt、重启过plex、重启过nas，关闭https，更改web端口都无法解决。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

已经浏览过

## 你期望的结果

是否为bug希望解决。

## 给出程序界面截图、后台运行日志或配置文件
![微信截图_20230510122626](https://github.com/NAStool/nas-tools/assets/131415589/6bb3b3a0-a6fa-43b4-be1c-3470766a63d2)
![微信截图_20230510122640](https://github.com/NAStool/nas-tools/assets/131415589/fe384e8a-3395-4eab-8193-dfec2f880999)
![微信截图_20230510122552](https://github.com/NAStool/nas-tools/assets/131415589/3931f955-1849-409c-8557-ec5bc7b649ed)
![微信截图_20230510123141](https://github.com/NAStool/nas-tools/assets/131415589/f25fee23-7a1e-4394-8208-dd9f52d8ed0b)
![微信截图_20230510122953](https://github.com/NAStool/nas-tools/assets/131415589/118acfa7-f6e0-4223-83f0-233c1e1b1ac8)
![微信截图_20230510122537](https://github.com/NAStool/nas-tools/assets/131415589/a9cecba7-eb33-4814-abb0-943565ac515e)

**Comment by ZmmLAOBiao** [comment]
![微信截图_20230510125003](https://github.com/NAStool/nas-tools/assets/131415589/6010babb-aac6-4e1b-a3a2-d741fbbf1271)

**Comment by Shurelol** [comment]
![image](https://github.com/NAStool/nas-tools/assets/16237201/bea8ea57-0f65-4060-bcc3-143fef055102)

**Comment by ZmmLAOBiao** [comment]
我这里内网段是192.168.2.0的，没有设置错啊？我在外网用ipv6进行的播放。没有限速提示。不是在内网播放的。

**Comment by ZmmLAOBiao** [comment]
我这里内网段是192.168.2.0的，没有设置错啊？我在外网用ipv6进行的播放。没有限速提示。不是在内网播放的。

**Comment by ZmmLAOBiao** [comment]
已解决，忘记配置限制IPV6的地址段了。谢谢
