### ISSUE TITLE
签到任务可能未按时触发和签到通知的问题

### ISSUE THREAD

**Issue by cng10001** [NAStool/nas-tools#4698]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本:  v3.2.2 7ecbe70
>
> 环境: docker synology
>

## 你遇到什么问题了？

> 1，签到任务包括其他系统任务（比如自定义订阅任务）有时候可能会没有按时启动，因为没启动，日志里也没有相关消息，无法复现，不知道是否因为群晖系统运行问题。
**2、另一个应该比较明确和简单，自动签到运行通知按钮不管打开还是没打开，实际都会推送通知。
这个亲测，比如手动运行签到，通知按钮没打开肯定也会推送通知的。**

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果     小问题，请作者看看，顺带可以优化优化☺

## 给出程序界面截图、后台运行日志或配置文件
![签到 拷贝](https://github.com/NAStool/nas-tools/assets/115156545/83479e63-06e2-4657-9067-85ba6275533d)
_这个在关闭状态，匜会推送通知_
> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by thsrite** [comment]
#4704

**Comment by cng10001** [comment]
> #4704
不知道我有没有理解对，这条是不是说插件没有运行，我是运行通知开关按钮关闭了还是会推送通知

**Comment by thsrite** [comment]
> > #4704
> > 不知道我有没有理解对，这条是不是说插件没有运行，我是运行通知开关按钮关闭了还是会推送通知

#4701
